{type:'open', pts:9,
 q: String.raw`<strong>Exercice 1 — Stationnarité : définitions et classification.</strong><br>
<strong>(a)</strong> Énoncer la définition de la <strong>stationnarité faible</strong> (au second ordre) et de la <strong>stationnarité stricte</strong> d'un processus $\{X_t\}_{t\in\mathbb{Z}}$. (3 pts)<br>
<strong>(b)</strong> Soit $Y_t\overset{\text{iid}}{\sim}\mathcal{N}(0,\sigma_Y^2)$ et $a,b,c$ des constantes. Pour chacun des processus, dire s'il est faiblement et/ou strictement stationnaire, et donner sa moyenne et son ACVS : (i) $X_t=a+bY_t+cY_{t-1}$ ; (ii) $X_t=Y_0\cos(ct)$. (4 pts)<br>
<strong>(c)</strong> Donner un processus <strong>strictement</strong> stationnaire mais <strong>non faiblement</strong> stationnaire, et justifier. (2 pts)`,
 answer: String.raw`<div class="step"><strong>(a)</strong> $\{X_t\}$ est <strong>faiblement (second-ordre) stationnaire</strong> si les moments d'ordre 1 et 2 existent, sont finis et invariants par décalage : $\mathbb{E}[X_t]=\mu$ (constante), $\operatorname{Var}(X_t)=\sigma^2<\infty$ (constante), et $\operatorname{Cov}(X_t,X_{t+\tau})$ ne dépend que du décalage $\tau$ (pas de $t$). Elle est <strong>strictement stationnaire</strong> si, pour tout $n$ et tous $t_1,\dots,t_n$, la loi jointe de $(X_{t_1},\dots,X_{t_n})$ est égale à celle de $(X_{t_1+\tau},\dots,X_{t_n+\tau})$ pour tout $\tau$.</div>
<div class="step"><strong>(b)(i)</strong> $\mathbb{E}[X_t]=a$. Par indépendance des $Y_t$, $$\gamma_\tau=\begin{cases}(b^2+c^2)\sigma_Y^2,&\tau=0\\ bc\,\sigma_Y^2,&\tau=\pm 1\\ 0,&|\tau|\ge 2.\end{cases}$$ Ne dépend que de $\tau$ et est finie $\Rightarrow$ <strong>faiblement stationnaire</strong> ; combinaison linéaire de gaussiennes $\Rightarrow$ processus gaussien $\Rightarrow$ <strong>aussi strictement</strong> stationnaire.</div>
<div class="step"><strong>(b)(ii)</strong> $\mathbb{E}[X_t]=0$, mais $\operatorname{Cov}(X_t,X_{t+\tau})=\sigma_Y^2\cos(ct)\cos\big(c(t+\tau)\big)$ <strong>dépend de $t$</strong> $\Rightarrow$ <strong>non stationnaire</strong> (ni faiblement, ni strictement). (Contraste avec $Y_1\cos(ct)+Y_2\sin(ct)$, lui stationnaire d'ACVS $\sigma_Y^2\cos(c\tau)$.)</div>
<div class="step"><strong>(c)</strong> Une suite i.i.d. de Cauchy (Student-$t$ à $1$ degré de liberté) : i.i.d. donc <strong>strictement</strong> stationnaire, mais espérance et variance <strong>non définies</strong> $\Rightarrow$ la condition de variance finie de la stationnarité faible échoue. Donc strict $\not\Rightarrow$ faible.</div>`},

{type:'open', pts:8,
 q: String.raw`<strong>Exercice 2 — Calcul d'autocovariance.</strong> Soit $\{\varepsilon_t\}$ un bruit blanc (white noise) centré de variance $\sigma^2$.<br>
<strong>(a)</strong> Soit $\{X_t\}$ stationnaire d'ACVS $\gamma_\tau$, <strong>indépendant</strong> de $\{\varepsilon_t\}$. Déterminer l'ACVS de $Z_t=X_t+\varepsilon_t$. (3 pts)<br>
<strong>(b)</strong> Soit $W_t=\theta_1\varepsilon_t+\theta_2\varepsilon_{t-1}$. Calculer son ACVS $\gamma_\tau^{W}$, puis son autocorrélation $\rho_1$, et montrer que $\lvert\rho_1\rvert\le \tfrac12$. (5 pts)`,
 answer: String.raw`<div class="step"><strong>(a)</strong> L'indépendance annule toutes les covariances croisées $\operatorname{Cov}(X_s,\varepsilon_u)=0$, et $\{\varepsilon_t\}$ étant un bruit blanc n'ajoute de la variance qu'au décalage $0$ : $$\gamma^{Z}_\tau=\gamma_\tau+\sigma^2\,\mathbf{1}_{\{\tau=0\}}.$$ (Ajouter un bruit blanc indépendant ne change que la variance, $\tau=0$.)</div>
<div class="step"><strong>(b)</strong> Par bilinéarité et $\operatorname{Cov}(\varepsilon_s,\varepsilon_u)=\sigma^2\mathbf{1}_{\{s=u\}}$, seuls les indices de bruit qui coïncident survivent : $$\gamma^{W}_\tau=\begin{cases}(\theta_1^2+\theta_2^2)\sigma^2,&\tau=0\\ \theta_1\theta_2\,\sigma^2,&\tau=\pm 1\\ 0,&|\tau|\ge 2.\end{cases}$$</div>
<div class="step">D'où $\rho_1=\dfrac{\gamma^{W}_1}{\gamma^{W}_0}=\dfrac{\theta_1\theta_2}{\theta_1^2+\theta_2^2}$. Par l'inégalité arithmético-géométrique $\lvert\theta_1\theta_2\rvert\le\tfrac12(\theta_1^2+\theta_2^2)$, donc $\lvert\rho_1\rvert\le\tfrac12$, avec égalité ssi $\lvert\theta_1\rvert=\lvert\theta_2\rvert$. (Aucun processus de ce type ne peut avoir $\lvert\rho_1\rvert>\tfrac12$ — un bon test de cohérence.)</div>`},

{type:'open', pts:8,
 q: String.raw`<strong>Exercice 3 — Propriétés de l'ACVS.</strong><br>
<strong>(a)</strong> Montrer que la suite d'autocovariance $\{\gamma_\tau\}$ d'un processus stationnaire est <strong>semi-définie positive</strong> : pour tout $n$ et tous $a_1,\dots,a_n\in\mathbb{R}$, $\sum_{j=1}^n\sum_{k=1}^n a_j a_k\,\gamma_{j-k}\ge 0$. (4 pts)<br>
<strong>(b)</strong> En déduire la symétrie $\gamma_{-\tau}=\gamma_\tau$ et la borne $\lvert\gamma_\tau\rvert\le\gamma_0$. (2 pts)<br>
<strong>(c)</strong> La suite $\gamma_0=1,\ \gamma_{\pm1}=0{,}8,\ \gamma_\tau=0\ (|\tau|\ge2)$ est-elle une ACVS valide ? Justifier. (2 pts)`,
 answer: String.raw`<div class="step"><strong>(a)</strong> Poser $W=\sum_{j=1}^n a_j X_j$. Comme une variance est positive, $$0\le\operatorname{Var}(W)=\sum_{j=1}^n\sum_{k=1}^n a_j a_k\operatorname{Cov}(X_j,X_k)=\sum_{j=1}^n\sum_{k=1}^n a_j a_k\,\gamma_{j-k}.$$</div>
<div class="step"><strong>(b)</strong> Symétrie : $\gamma_{-\tau}=\operatorname{Cov}(X_t,X_{t-\tau})=\operatorname{Cov}(X_{t-\tau},X_t)=\gamma_\tau$ (cas réel). Borne : par Cauchy–Schwarz, $\lvert\gamma_\tau\rvert=\lvert\operatorname{Cov}(X_t,X_{t+\tau})\rvert\le\sqrt{\operatorname{Var}(X_t)\operatorname{Var}(X_{t+\tau})}=\gamma_0$.</div>
<div class="step"><strong>(c)</strong> <strong>Non.</strong> Une ACVS valide doit être semi-définie positive, ce qui équivaut à une densité spectrale $\ge 0$. Ici $$S(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}=1+1{,}6\cos(2\pi f),$$ qui vaut $1-1{,}6=-0{,}6<0$ en $f=\tfrac12$. La densité devient négative $\Rightarrow$ suite non semi-définie positive $\Rightarrow$ ce n'est <strong>pas</strong> une ACVS valide. (Noter que $\lvert\rho_1\rvert=0{,}8>\tfrac12$ : déjà impossible pour un MA(1).)</div>`},

{type:'open', pts:9,
 q: String.raw`<strong>Exercice 4 — Estimation et ergodicité.</strong><br>
<strong>(a)</strong> Écrire les deux estimateurs de l'ACVS (versions $\tfrac{1}{n-|\tau|}$ et $\tfrac1n$). Lequel est biaisé ? Lequel est semi-défini positif ? (3 pts)<br>
<strong>(b)</strong> Pour un bruit blanc gaussien (moyenne connue) on a, pour $\tau\ne0$, $\operatorname{Var}(\hat\gamma_\tau)=\tfrac{n-|\tau|}{n^2}\sigma^4$ et $\operatorname{Var}(\tilde\gamma_\tau)=\tfrac{1}{n-|\tau|}\sigma^4$. Lequel a la plus petite EQM (MSE) et pourquoi ? (3 pts)<br>
<strong>(c)</strong> Montrer que si $\sum_\tau\lvert\gamma_\tau\rvert<\infty$ alors $\operatorname{Var}(\bar X)\to0$, donc $\bar X$ est un estimateur consistant de $\mu$ (ergodicité en moyenne). (3 pts)`,
 answer: String.raw`<div class="step"><strong>(a)</strong> Pour $|\tau|\le n-1$ (et $0$ sinon) : $$\tilde\gamma_\tau=\frac{1}{n-|\tau|}\sum_{t=1}^{n-|\tau|}(X_t-\bar X)(X_{t+|\tau|}-\bar X),\qquad \hat\gamma_\tau=\frac{1}{n}\sum_{t=1}^{n-|\tau|}(X_t-\bar X)(X_{t+|\tau|}-\bar X).$$ $\tilde\gamma_\tau$ est <strong>non biaisé</strong> (moyenne connue) mais pas toujours semi-défini positif ; $\hat\gamma_\tau$ est <strong>biaisé</strong> ($\mathbb{E}[\hat\gamma_\tau]=\tfrac{n-|\tau|}{n}\gamma_\tau$) mais <strong>semi-défini positif</strong> — c'est pourquoi on l'utilise par défaut.</div>
<div class="step"><strong>(b)</strong> Pour un bruit blanc les deux sont non biaisés, donc $\mathrm{EQM}=\operatorname{Var}$. Or $$\operatorname{Var}(\hat\gamma_\tau)=\frac{n-|\tau|}{n^2}\sigma^4=\Big(\frac{n-|\tau|}{n}\Big)^2\frac{\sigma^4}{n-|\tau|}=\Big(\frac{n-|\tau|}{n}\Big)^2\operatorname{Var}(\tilde\gamma_\tau)\le\operatorname{Var}(\tilde\gamma_\tau).$$ Donc l'estimateur <strong>biaisé</strong> $\hat\gamma_\tau$ a la <strong>plus petite</strong> EQM. Leçon : l'objectif n'est pas l'absence de biais mais une faible EQM (et la semi-définie positivité).</div>
<div class="step"><strong>(c)</strong> $\mathbb{E}[\bar X]=\mu$. En regroupant par décalage, $$\operatorname{Var}(\bar X)=\frac{1}{n^2}\sum_{i,j=1}^n\gamma_{j-i}=\frac1n\sum_{\tau=-(n-1)}^{n-1}\Big(1-\frac{|\tau|}{n}\Big)\gamma_\tau.$$ Par le théorème de Cesàro, $\sum_{\tau}\big(1-\tfrac{|\tau|}{n}\big)\gamma_\tau\to\sum_{\tau=-\infty}^{\infty}\gamma_\tau=:C(\gamma)$, fini car $\sum_\tau|\gamma_\tau|<\infty$. Donc $n\operatorname{Var}(\bar X)\to C(\gamma)$, soit $\operatorname{Var}(\bar X)=O(1/n)\to0$. Ainsi $\bar X\to\mu$ en moyenne quadratique, donc en probabilité : $\bar X$ est consistant (le processus est ergodique en moyenne).</div>`},
