{
  n: 8,
  title: String.raw`Estimation spectrale : périodogramme & tapering`,
  intro: String.raw`Le périodogramme (periodogram) estime la densité spectrale, mais il est biaisé (noyau de Fejér) et surtout non consistant ; le tapering attaque le biais, le multitaper attaque la variance.`,
  sections: [
    {h: String.raw`Le périodogramme : un estimateur plug-in de la densité spectrale`, body: String.raw`<p>On observe une série $X_1,\dots,X_n$ ($T=\{1,\dots,n\}$, intervalle d'échantillonnage $\Delta=1$) et on veut estimer la <strong>densité spectrale</strong> (spectral density function, SDF) $S(f)=\sum_{\tau\in\mathbb{Z}}\gamma_\tau\,e^{-2\pi i f\tau}$. L'idée la plus naturelle : remplacer l'ACVS théorique $\gamma_\tau$ par son estimateur empirique. C'est exactement le <strong>périodogramme</strong>.</p>
<p>Définition (estimateur « plug-in ») :</p>
$$\hat S^{(p)}(f)=\sum_{\tau\in\mathbb{Z}}\hat\gamma_\tau\,e^{-2\pi i f\tau},\qquad \hat\gamma_\tau=\frac1n\sum_{t=1}^{n-\lvert\tau\rvert}(X_t-\bar X)(X_{t+\lvert\tau\rvert}-\bar X).$$
<p>De façon <strong>équivalente</strong>, c'est le module au carré de la transformée de Fourier finie des données centrées :</p>
$$\hat S^{(p)}(f)=\lvert J(f)\rvert^2\ge 0,\qquad J(f)=\sqrt{\tfrac1n}\sum_{t\in T}(X_t-\bar X)\,e^{-2\pi i t f}.$$
<p><strong>Intuition.</strong> Cette deuxième écriture est précieuse : (i) elle montre que le périodogramme est <strong>toujours positif ou nul</strong>, comme doit l'être une densité spectrale ; (ii) $J(f)$ se calcule par <strong>FFT</strong> (Fast Fourier Transform) en $O(n\log n)$ au lieu de $O(n^2)$ ; (iii) on peut même retrouver l'ACVS empirique en transformant à l'envers le périodogramme. On évalue typiquement $\hat S^{(p)}$ aux <strong>fréquences de Fourier</strong> $f_k=k/n$, là où les ordonnées sont (approximativement) décorrélées.</p>`},
    {h: String.raw`Biais : l'espérance est un flou par le noyau de Fejér`, body: String.raw`<p>Le périodogramme n'est pas exactement sans biais. Comme $\mathbb{E}[\hat\gamma_\tau]=\big(1-\tfrac{\lvert\tau\rvert}{n}\big)\gamma_\tau$ pour $\lvert\tau\rvert<n$, on obtient (processus centré) une ACVS <em>pondérée par un triangle</em> :</p>
$$\mathbb{E}\big[\hat S^{(p)}(f)\big]=\sum_{\tau\in\mathbb{Z}} w_\tau\,\gamma_\tau\,e^{-2\pi i\tau f},\qquad w_\tau=\Big(1-\tfrac{\lvert\tau\rvert}{n}\Big)\mathbf{1}_{[-n,n]}(\tau).$$
<p>Multiplier par $w_\tau$ dans le domaine temporel revient à <strong>convoluer</strong> dans le domaine fréquentiel. L'espérance est donc une version floutée (blurring) de la vraie densité :</p>
$$\mathbb{E}\big[\hat S^{(p)}(f)\big]=\int_{-1/2}^{1/2} S(f')\,\mathcal{F}_n(f-f')\,df',\qquad \mathcal{F}_n(f)=\frac1n\,\frac{\sin^2(n\pi f)}{\sin^2(\pi f)},$$
<p>avec $\mathcal{F}_n(0)=n$ : c'est le <strong>noyau de Fejér</strong> (Fejér kernel), qui est l'autocorrélation de la fenêtre rectangulaire (transformée du poids triangulaire $w_\tau$).</p>
<p><strong>Intuition (pourquoi ça floute).</strong> Observer une fenêtre finie de données, c'est multiplier le signal par une fenêtre rectangulaire ; en fréquence, « multiplication $=$ convolution », donc le vrai spectre est convolué avec $\mathcal{F}_n$. Or $\mathcal{F}_n$ a des <strong>lobes latéraux</strong> (side lobes) larges qui décroissent lentement : un pic spectral net est étalé et sa puissance « déborde » sur les fréquences voisines (fuite spectrale, leakage). Plus le pic est marqué, plus c'est visible (cf. l'AR(4) du cours). <strong>Bonne nouvelle :</strong> quand $n\to\infty$, $\mathcal{F}_n$ se concentre en $0$ — le périodogramme est <strong>asymptotiquement sans biais</strong>.</p>`},
    {h: String.raw`Variance : l'estimateur n'est PAS consistant`, body: String.raw`<p>Le vrai problème n'est pas le biais (qui disparaît) mais la <strong>variance</strong> (qui ne disparaît jamais). Pour $f\ne0\bmod\tfrac12$,</p>
$$\operatorname{Var}\big(\hat S^{(p)}(f)\big)\xrightarrow[n\to\infty]{} S(f)^2\;>\;0,$$
<p>et aux fréquences de Fourier distinctes les ordonnées sont asymptotiquement décorrélées.</p>
<p><strong>Idée du résultat.</strong> Pour un processus gaussien, $J(f)$ est asymptotiquement gaussien complexe, donc $\hat S^{(p)}(f)=\lvert J(f)\rvert^2$ se comporte comme $\tfrac12 S(f)\,\chi^2_2$, c'est-à-dire $S(f)\cdot\mathrm{Exp}(1)$. Une loi du khi-deux à $2$ degrés de liberté a une variance qui vaut le carré de l'échelle : on retrouve $\operatorname{Var}\approx S(f)^2$.</p>
<p><strong>Intuition (plus de données n'aide PAS).</strong> À $f$ fixé, doubler $n$ ne divise <em>pas</em> la variance par deux : elle reste $\approx S(f)^2$. Ce qu'on gagne en ajoutant des données, c'est de la <strong>résolution</strong> (plus d'ordonnées de Fourier $f_k=k/n$), pas de la précision par ordonnée. « Ça devient plus bruité quand j'ajoute des données » est donc normal, pas un bug. <strong>Conclusion :</strong> le périodogramme n'est pas consistant ; pour réduire la variance, il faut <strong>moyenner</strong> (multitaper, ou lisser des ordonnées voisines).</p>`},
    {h: String.raw`Tapering : remplacer le noyau de Fejér par un meilleur noyau`, body: String.raw`<p>On voudrait limiter l'influence des grands lags, mal estimés. Tronquer brutalement l'ACVS est dangereux : le « spectre » obtenu peut devenir négatif (on casse la non-négativité-définie ; cf. la troncature de l'exercice). La voie propre est de <strong>façonner une fenêtre sur les données</strong> : c'est le <strong>taper</strong> (data taper).</p>
<p>Un taper est une suite $\{h_t\}_{t\in T}$ normalisée par $\lVert h\rVert_2^2=\sum_t h_t^2=1$. On pondère les données avant la transformée :</p>
$$J_h(f)=\sum_{t\in T} h_t\,(X_t-\bar X)\,e^{-2\pi i t f},\qquad \hat S^{(p)}_h(f)=\lvert J_h(f)\rvert^2.$$
<p>Le choix constant $h_t=\sqrt{1/n}$ redonne le périodogramme ordinaire. L'effet du taper se lit sur l'espérance, où le noyau de Fejér est remplacé par $\lvert H\rvert^2$ ($H$ = transformée de Fourier de $h$) :</p>
$$\mathbb{E}\big[\hat S^{(p)}_h(f)\big]=\int_{-1/2}^{1/2} S(f')\,\lvert H(f-f')\rvert^2\,df'.$$
<p><strong>Intuition.</strong> Un bon taper (par ex. les tapers <em>dpss</em> / Slepian) rend $\lvert H\rvert^2$ bien plus concentré près de $0$, avec des lobes latéraux beaucoup plus faibles que $\mathcal{F}_n$ : <strong>moins de fuite, donc moins de biais</strong>. La normalisation $\lVert h\rVert_2^2=1$ n'est pas cosmétique : c'est exactement elle qui garantit que le taper reste <strong>sans biais sur un bruit blanc</strong> (white noise), car par Parseval $\int_{-1/2}^{1/2}\lvert H(f')\rvert^2\,df'=\sum_t h_t^2=\lVert h\rVert_2^2=1$.</p>`},
    {h: String.raw`Multitaper : moyenner pour restaurer la consistance`, body: String.raw`<p>Le tapering corrige le biais mais pas la variance (un seul périodogramme tapéré reste de variance $\approx S(f)^2$). Pour la variance, il faut moyenner des estimateurs <em>quasi indépendants</em>. C'est le <strong>multitaper</strong> : on prend $K$ tapers <strong>orthonormés</strong> ($\sum_t h_{t,k}h_{t,k'}=\delta_{k,k'}$) et on moyenne leurs périodogrammes tapérés :</p>
$$\hat S^{(mt)}(f)=\frac1K\sum_{k=1}^{K}\hat S^{(p)}_{h_k}(f).$$
<p>Asymptotiquement, l'orthogonalité rend les $K$ périodogrammes décorrélés, chacun de variance $S(f)^2$, donc moyenner $K$ termes décorrélés divise la variance par $K$ :</p>
$$\operatorname{Var}\big(\hat S^{(mt)}(f)\big)\approx\frac{S(f)^2}{K}.$$
<p>Son espérance est une convolution avec le <strong>noyau moyen</strong> $\overline H(f)=\tfrac1K\sum_{k=1}^K\lvert H_k(f)\rvert^2$.</p>
<p><strong>Intuition / slogan.</strong> En laissant $K\to\infty$ (lentement) avec $n$, la variance tend vers $0$ : <strong>le multitaper restaure la consistance</strong>, au prix d'un léger biais supplémentaire. Le résumé de toute la semaine tient en une ligne : le périodogramme brut a un biais tolérable (qui disparaît) mais une variance têtue (qui ne disparaît pas) ; <strong>taper $\Rightarrow$ biais, multitaper $\Rightarrow$ variance</strong>.</p>`}
  ],
  checks: [
    {q: String.raw`Pourquoi le périodogramme $\hat S^{(p)}(f)=\lvert J(f)\rvert^2$ est-il toujours $\ge 0$, et pourquoi est-ce souhaitable ?`, a: String.raw`Parce que c'est un module au carré. C'est souhaitable car une densité spectrale est par nature réelle, paire et non-négative ; un estimateur qui peut devenir négatif (comme une ACVS tronquée) ne serait pas une SDF valide.`},
    {q: String.raw`Quel est le noyau qui apparaît dans l'espérance du périodogramme, et que provoque-t-il ?`, a: String.raw`Le noyau de Fejér $\mathcal{F}_n(f)=\frac1n\frac{\sin^2(n\pi f)}{\sin^2(\pi f)}$. Ses lobes latéraux décroissent lentement : il floute (blurring) la vraie densité et fait fuir la puissance des pics vers les fréquences voisines (biais).`},
    {q: String.raw`Vrai ou faux : doubler $n$ divise par deux la variance de $\hat S^{(p)}(f)$ à $f$ fixé ?`, a: String.raw`Faux. La variance tend vers $S(f)^2>0$ et ne décroît pas avec $n$ : le périodogramme n'est pas consistant. Plus de données donne plus de résolution (plus d'ordonnées de Fourier), pas plus de précision par ordonnée.`},
    {q: String.raw`Que change le tapering par rapport au périodogramme ordinaire, et que change le multitaper ?`, a: String.raw`Le tapering remplace le noyau de Fejér $\mathcal{F}_n$ par $\lvert H\rvert^2$, plus concentré (moins de biais / fuite). Le multitaper moyenne $K$ tapers orthonormés, ce qui donne $\operatorname{Var}\approx S(f)^2/K$ (moins de variance, consistance restaurée).`},
    {q: String.raw`Pourquoi impose-t-on $\lVert h\rVert_2^2=1$ pour un taper ?`, a: String.raw`Pour que le périodogramme tapéré reste exactement sans biais sur un bruit blanc : par Parseval $\int_{-1/2}^{1/2}\lvert H(f')\rvert^2\,df'=\sum_t h_t^2=\lVert h\rVert_2^2$, donc $\mathbb{E}[\hat S^{(p)}_h(f)]=\sigma^2\lVert h\rVert_2^2=\sigma^2$ ssi $\lVert h\rVert_2^2=1$.`}
  ],
  test: [
    {type:'open', q: String.raw`Soit $X_1,\dots,X_n$ observés sur $T=\{1,\dots,n\}$ ($\Delta=1$). On définit le périodogramme par $\hat S^{(p)}(f)=\sum_{\tau\in\mathbb{Z}}\hat\gamma_\tau e^{-2\pi i f\tau}$ avec $\hat\gamma_\tau=\frac1n\sum_{t=1}^{n-\lvert\tau\rvert}(X_t-\bar X)(X_{t+\lvert\tau\rvert}-\bar X)$. Montrer que $\hat S^{(p)}(f)=\lvert J(f)\rvert^2$, où $J(f)=\sqrt{1/n}\sum_{t\in T}(X_t-\bar X)e^{-2\pi i t f}$.`,
     answer: String.raw`<div class="step"><strong>Notation.</strong> Posons $Y_t=X_t-\bar X$. Seuls les lags $\lvert\tau\rvert\le n-1$ contribuent, donc $\hat S^{(p)}(f)=\sum_{\tau=-n+1}^{n-1}\frac1n\sum_{t=1}^{n-\lvert\tau\rvert} Y_t Y_{t+\lvert\tau\rvert}\,e^{-2\pi i\tau f}.$</div>
<div class="step"><strong>Réindexation en double somme libre.</strong> Pour chaque $\tau$, posons $s=t+\lvert\tau\rvert$ (resp. $s=t-\lvert\tau\rvert$ pour $\tau<0$) ; lorsque $\tau$ parcourt $\{-(n-1),\dots,n-1\}$ et $t$ son domaine, le couple $(t,s)$ parcourt exactement tout le carré $\{1,\dots,n\}^2$ avec $\tau=t-s$. Ainsi $$\hat S^{(p)}(f)=\frac1n\sum_{t=1}^{n}\sum_{s=1}^{n} Y_t Y_s\,e^{-2\pi i (t-s) f}.$$</div>
<div class="step"><strong>Factorisation.</strong> On sépare l'exponentielle : $e^{-2\pi i(t-s)f}=e^{2\pi i t f}\,e^{-2\pi i s f}$, ce qui découple les sommes en $t$ et en $s$ : $$\hat S^{(p)}(f)=\Big(\sqrt{\tfrac1n}\sum_{t=1}^{n} Y_t e^{2\pi i t f}\Big)\Big(\sqrt{\tfrac1n}\sum_{s=1}^{n} Y_s e^{-2\pi i s f}\Big).$$</div>
<div class="step"><strong>Conclusion.</strong> La seconde parenthèse est $J(f)$ ; comme les $Y_t$ sont réels, la première est son conjugué $\overline{J(f)}$. Donc $\hat S^{(p)}(f)=\overline{J(f)}\,J(f)=\lvert J(f)\rvert^2$. En passant, cela prouve $\hat S^{(p)}(f)\ge0$ et donne le calcul par FFT en $O(n\log n)$.</div>`, pts: 4},
    {type:'open', q: String.raw`Énoncer précisément (avec hypothèses) le résultat sur l'espérance du périodogramme. Donner la forme « ACVS pondérée », la forme « convolution » avec le noyau de Fejér, et expliquer en quoi cela quantifie le biais et son comportement quand $n\to\infty$.`,
     answer: String.raw`<div class="step"><strong>Hypothèse.</strong> Soit $\{X_t\}$ stationnaire au second ordre, <em>centré</em> ($\mu=0$), d'ACVS sommable $\{\gamma_\tau\}\in\ell^1$ et de SDF $S(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}$, observé sur $T=\{1,\dots,n\}$.</div>
<div class="step"><strong>Forme ACVS pondérée.</strong> Comme $\mathbb{E}[\hat\gamma_\tau]=\big(1-\tfrac{\lvert\tau\rvert}{n}\big)\gamma_\tau$ pour $\lvert\tau\rvert<n$, on transforme terme à terme : $$\mathbb{E}\big[\hat S^{(p)}(f)\big]=\sum_{\tau\in\mathbb{Z}} w_\tau\,\gamma_\tau\,e^{-2\pi i\tau f},\qquad w_\tau=\Big(1-\tfrac{\lvert\tau\rvert}{n}\Big)\mathbf{1}_{[-n,n]}(\tau).$$ Le poids triangulaire $w_\tau$ est l'autocorrélation (normalisée) de la fenêtre rectangulaire.</div>
<div class="step"><strong>Forme convolution.</strong> Multiplier par $w_\tau$ en temps équivaut à convoluer en fréquence (théorème de convolution). La transformée de $w$ est $\mathcal{F}_n=\lvert\mathcal{D}_T\rvert^2/n$ (module au carré du noyau de Dirichlet), d'où $$\mathbb{E}\big[\hat S^{(p)}(f)\big]=\int_{-1/2}^{1/2} S(f')\,\mathcal{F}_n(f-f')\,df',\qquad \mathcal{F}_n(f)=\frac1n\frac{\sin^2(n\pi f)}{\sin^2(\pi f)}\ (f\ne0),\quad \mathcal{F}_n(0)=n.$$</div>
<div class="step"><strong>Lecture du biais.</strong> L'espérance est donc une version <em>floutée</em> de $S$ (convolution par $\mathcal{F}_n$). Le noyau de Fejér a des lobes latéraux qui décroissent lentement : la puissance d'un pic spectral « fuit » vers les fréquences voisines (leakage), d'où un biais d'autant plus marqué que le spectre est piqué.</div>
<div class="step"><strong>Asymptotique.</strong> Quand $n\to\infty$, $\mathcal{F}_n$ se concentre en $0$ (sa masse $\int_{-1/2}^{1/2}\mathcal{F}_n=1$ se resserre, $\mathcal{F}_n(0)=n\to\infty$), donc $\mathbb{E}[\hat S^{(p)}(f)]\to S(f)$ : le périodogramme est <strong>asymptotiquement sans biais</strong>.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit un AR(1) $X_t=\phi X_{t-1}+\varepsilon_t$, $\lvert\phi\rvert<1$, $\{\varepsilon_t\}$ bruit blanc de variance $\sigma^2$. Sachant que son ACVS est $\gamma_\tau=\frac{\sigma^2}{1-\phi^2}\phi^{\lvert\tau\rvert}$, dériver sa densité spectrale $S(f)$ via la somme géométrique, puis la confirmer par la fonction de transfert. Décrire la forme du spectre selon le signe de $\phi$.`,
     answer: String.raw`<div class="step"><strong>Mise en place.</strong> $$S(f)=\sum_{\tau\in\mathbb{Z}}\gamma_\tau e^{-2\pi i f\tau}=\frac{\sigma^2}{1-\phi^2}\sum_{\tau\in\mathbb{Z}}\phi^{\lvert\tau\rvert}e^{-2\pi i f\tau}.$$ On sépare $\tau=0$ et les deux queues $\tau\ge1$ et $\tau\le-1$.</div>
<div class="step"><strong>Sommes géométriques.</strong> Posons $z=e^{-2\pi i f}$ (donc $\lvert\phi z\rvert=\lvert\phi\rvert<1$). $$\sum_{\tau\ge1}\phi^\tau e^{-2\pi i f\tau}=\frac{\phi z}{1-\phi z},\qquad \sum_{\tau\ge1}\phi^\tau e^{2\pi i f\tau}=\frac{\phi\bar z}{1-\phi\bar z}.$$ D'où $\sum_{\tau\in\mathbb{Z}}\phi^{\lvert\tau\rvert}e^{-2\pi i f\tau}=1+\frac{\phi z}{1-\phi z}+\frac{\phi\bar z}{1-\phi\bar z}.$</div>
<div class="step"><strong>Réduction au même dénominateur.</strong> Le dénominateur commun est $\lvert 1-\phi z\rvert^2=(1-\phi z)(1-\phi\bar z)=1-\phi(z+\bar z)+\phi^2=1-2\phi\cos(2\pi f)+\phi^2$. Le numérateur se simplifie : $(1-\phi z)(1-\phi\bar z)+\phi z(1-\phi\bar z)+\phi\bar z(1-\phi z)=1-\phi^2.$ Donc $$\sum_{\tau\in\mathbb{Z}}\phi^{\lvert\tau\rvert}e^{-2\pi i f\tau}=\frac{1-\phi^2}{1-2\phi\cos(2\pi f)+\phi^2}.$$</div>
<div class="step"><strong>Résultat.</strong> $$S(f)=\frac{\sigma^2}{1-\phi^2}\cdot\frac{1-\phi^2}{1-2\phi\cos(2\pi f)+\phi^2}=\frac{\sigma^2}{1-2\phi\cos(2\pi f)+\phi^2}.$$</div>
<div class="step"><strong>Confirmation par la fonction de transfert.</strong> Pour un AR(1), $\Phi(z)=1-\phi z$ et $S(f)=\sigma^2/\lvert\Phi(e^{-2\pi i f})\rvert^2=\sigma^2/\lvert 1-\phi e^{-2\pi i f}\rvert^2=\sigma^2/(1-2\phi\cos(2\pi f)+\phi^2)$ — identique.</div>
<div class="step"><strong>Forme du spectre.</strong> Pour $\phi>0$, le dénominateur est minimal en $f=0$ : $S$ pique à basse fréquence (spectre « rouge », variation lente). Pour $\phi<0$, il est minimal en $f=\tfrac12$ : $S$ pique à haute fréquence (spectre « bleu », alternance rapide). Quand $\phi\to1$, le pic en $0$ explose (proche d'une racine unité).</div>`, pts: 4},
    {type:'open', q: String.raw`On propose la suite $\gamma_0=1$, $\gamma_{\pm1}=\rho$, $\gamma_\tau=0$ pour $\lvert\tau\rvert\ge2$, avec $\rho\in\mathbb{R}$. Pour quelles valeurs de $\rho$ est-ce une ACVS valide ? Justifier par le critère spectral et tester aux fréquences pertinentes.`,
     answer: String.raw`<div class="step"><strong>Critère.</strong> Une suite symétrique sommable est une ACVS valide si et seulement si elle est non-négative définie, ce qui équivaut à $S(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}\ge0$ pour tout $f$.</div>
<div class="step"><strong>Calcul de la SDF.</strong> Seuls $\tau\in\{-1,0,1\}$ contribuent : $$S(f)=\gamma_0+\gamma_1(e^{-2\pi i f}+e^{2\pi i f})=1+2\rho\cos(2\pi f).$$ (C'est la forme d'un MA(1).) Elle est bien réelle et paire.</div>
<div class="step"><strong>Minimum sur $f$.</strong> Comme $\cos(2\pi f)\in[-1,1]$, $S(f)$ varie dans $[\,1-2\lvert\rho\rvert,\ 1+2\lvert\rho\rvert\,]$. Le minimum $1-2\lvert\rho\rvert$ est atteint en $f=\tfrac12$ si $\rho>0$ (alors $\cos=-1$) et en $f=0$ si $\rho<0$ (alors $\cos=+1$ avec $\rho<0$).</div>
<div class="step"><strong>Condition de validité.</strong> $S(f)\ge0$ pour tout $f$ équivaut à $1-2\lvert\rho\rvert\ge0$, soit $$\boxed{\ \lvert\rho\rvert\le\tfrac12\ }.$$</div>
<div class="step"><strong>Conclusion.</strong> Pour $\lvert\rho\rvert\le\tfrac12$, la suite est une ACVS valide. Pour $\lvert\rho\rvert>\tfrac12$, la SDF devient négative (au point de minimum) et la suite n'est pas une ACVS. C'est cohérent avec le fait qu'un MA(1) ne peut avoir $\lvert\rho_1\rvert>\tfrac12$.</div>`, pts: 3},
    {type:'open', q: String.raw`On définit le périodogramme tapéré $\hat S^{(p)}_h(f)=\lvert J_h(f)\rvert^2$ avec $J_h(f)=\sum_{t\in T} h_t (X_t-\mu)e^{-2\pi i t f}$ (en remplaçant $\bar X$ par $\mu$ et $h_t=0$ hors de $T$). Montrer que $\mathbb{E}[\hat S^{(p)}_h(f)]=\int_{-1/2}^{1/2} S(f')\lvert H(f-f')\rvert^2 df'$, où $H$ est la transformée de Fourier de $h$. En déduire que si $\{X_t\}$ est un bruit blanc de variance $\sigma^2$, alors $\hat S^{(p)}_h$ est sans biais pour tout $n$ dès que $\lVert h\rVert_2^2=1$.`,
     answer: String.raw`<div class="step"><strong>Développement du module au carré.</strong> Avec $Y_t=X_t-\mu$, $$\hat S^{(p)}_h(f)=\Big\lvert\sum_{t} h_t Y_t e^{-2\pi i f t}\Big\rvert^2=\sum_{t}\sum_{s} h_t h_s\,Y_t Y_s\,e^{-2\pi i f(t-s)}.$$</div>
<div class="step"><strong>Espérance et regroupement par lag.</strong> Comme $\mathbb{E}[Y_tY_s]=\gamma_{t-s}$, en posant $\tau=t-s$ : $$\mathbb{E}\big[\hat S^{(p)}_h(f)\big]=\sum_{\tau\in\mathbb{Z}} w_\tau\,\gamma_\tau\,e^{-2\pi i f\tau},\qquad w_\tau=\sum_{t\in\mathbb{Z}} h_t h_{t+\tau}.$$</div>
<div class="step"><strong>Théorème de convolution (1).</strong> Comme $w_\tau\gamma_\tau$ est un produit en temps, sa transformée est une convolution : $\mathbb{E}[\hat S^{(p)}_h(f)]=\int_{-1/2}^{1/2} S(f')\,W(f-f')\,df'$, où $W$ est la transformée de $w$.</div>
<div class="step"><strong>Théorème de convolution (2).</strong> Posons $\tilde h_t=h_{-t}$ et $\bar h_t=h_t$. Alors $w_\tau=\sum_t h_t h_{t+\tau}=(\tilde h * \bar h)_\tau$ (autocorrélation du taper). Donc $W(f)=\tilde H(f)\,\bar H(f)=\overline{H(f)}\,H(f)=\lvert H(f)\rvert^2$. D'où $$\mathbb{E}\big[\hat S^{(p)}_h(f)\big]=\int_{-1/2}^{1/2} S(f')\,\lvert H(f-f')\rvert^2\,df'.$$</div>
<div class="step"><strong>Cas du bruit blanc.</strong> Pour un bruit blanc, $S\equiv\sigma^2$. Par périodicité et changement de variable, $$\mathbb{E}\big[\hat S^{(p)}_h(f)\big]=\sigma^2\int_{-1/2}^{1/2}\lvert H(f')\rvert^2\,df'.$$</div>
<div class="step"><strong>Parseval.</strong> En développant $\lvert H(f')\rvert^2=\sum_t\sum_s h_t h_s e^{-2\pi i(t-s)f'}$ et en utilisant $\int_{-1/2}^{1/2} e^{-2\pi i\tau f'}df'=\mathbf{1}_{\{\tau=0\}}$, seul $t=s$ survit : $\int_{-1/2}^{1/2}\lvert H(f')\rvert^2 df'=\sum_t h_t^2=\lVert h\rVert_2^2$. Donc $\mathbb{E}[\hat S^{(p)}_h(f)]=\sigma^2\lVert h\rVert_2^2$, qui vaut $\sigma^2=S(f)$ <strong>exactement</strong> dès que $\lVert h\rVert_2^2=1$, pour tout $n$ et tout $f$.</div>`, pts: 5},
    {type:'open', q: String.raw`Avec $K$ tapers orthonormés $h_1,\dots,h_K$ ($\sum_t h_{t,k}h_{t,k'}=\delta_{k,k'}$), on pose l'estimateur multitaper $\hat S^{(mt)}(f)=\frac1K\sum_{k=1}^K \hat S^{(p)}_{h_k}(f)$. En admettant qu'asymptotiquement $\operatorname{Cov}(\hat S^{(p)}_{h_k}(f),\hat S^{(p)}_{h_{k'}}(f))\to S(f)^2\delta_{k,k'}$, calculer la variance de $\hat S^{(mt)}(f)$ et expliquer pourquoi le multitaper restaure la consistance, contrairement au périodogramme brut.`,
     answer: String.raw`<div class="step"><strong>Variance d'une moyenne.</strong> Par bilinéarité de la covariance, $$\operatorname{Var}\big(\hat S^{(mt)}(f)\big)=\frac{1}{K^2}\sum_{k=1}^{K}\sum_{k'=1}^{K}\operatorname{Cov}\big(\hat S^{(p)}_{h_k}(f),\hat S^{(p)}_{h_{k'}}(f)\big).$$</div>
<div class="step"><strong>Décorrélation asymptotique.</strong> En injectant $\operatorname{Cov}\to S(f)^2\delta_{k,k'}$, seuls les termes diagonaux $k=k'$ survivent : $$\operatorname{Var}\big(\hat S^{(mt)}(f)\big)\approx\frac{1}{K^2}\sum_{k=1}^{K} S(f)^2=\frac{1}{K^2}\cdot K\,S(f)^2=\frac{S(f)^2}{K}.$$</div>
<div class="step"><strong>Comparaison au périodogramme brut.</strong> Le périodogramme correspond à $K=1$ : sa variance reste $\approx S(f)^2$, indépendante de $n$ — il n'est pas consistant (le biais disparaît, pas la variance).</div>
<div class="step"><strong>Restauration de la consistance.</strong> Avec le multitaper, en laissant $K\to\infty$ (lentement, par ex. $K=K(n)\to\infty$ avec $K/n\to0$ pour ne pas trop dégrader le biais), on obtient $\operatorname{Var}(\hat S^{(mt)}(f))\approx S(f)^2/K\to 0$. Comme le biais reste contrôlé (espérance = convolution avec le noyau moyen $\overline H=\tfrac1K\sum_k\lvert H_k\rvert^2$), biais et variance tendent vers $0$ : l'estimateur est consistant. Slogan : <strong>taper réduit le biais, multitaper réduit la variance.</strong></div>`, pts: 4}
  ]
},
