{
  n: 13,
  title: String.raw`Filtres linéaires invariants (LTI)`,
  intro: String.raw`Un filtre LTI agit comme une convolution par sa réponse impulsionnelle $h$ (vue temporelle) et multiplie le spectre par $\lvert H(f)\rvert^2$ (vue fréquentielle) ; c'est le moteur de la densité spectrale d'un ARMA.`,
  sections: [
    {h: String.raw`Filtre LTI : « pareil à chaque instant + superposition »`, body: String.raw`<p>Un <strong>filtre numérique (digital filter)</strong> transforme une suite en une autre, $\{Y_t\}=\mathcal{L}[\{X_t\}]$ avec $t\in\mathbb{Z}$. On note l'élément de sortie au temps $u$ par $Y_u=\mathcal{L}[\{X_t\}]_u$ : ici $t$ est muet, c'est $u\in\mathbb{Z}$ qui a un sens (le temps de sortie). On autorise des séries à valeurs <strong>complexes</strong> ; le conjugué tombe alors sur le <em>second</em> facteur de l'autocovariance, $\gamma^{(X)}_\tau=\operatorname{Cov}(X_{t+\tau},X_t)=\mathbb{E}[(X_{t+\tau}-\mu)\overline{(X_t-\mu)}]$.</p>
<p>Les filtres utiles pour les séries temporelles sont les <strong>linéaires invariants dans le temps</strong> (linear time-invariant, LTI). $\mathcal{L}$ est LTI si, pour toutes suites et tout $\alpha\in\mathbb{C}$ :</p>
<ul>
<li><strong>Linéarité :</strong> $\mathcal{L}[\{\alpha X_t+Y_t\}]=\alpha\,\mathcal{L}[\{X_t\}]+\mathcal{L}[\{Y_t\}]$ ;</li>
<li><strong>Invariance temporelle :</strong> $\mathcal{L}[B[\{X_t\}]]=B[\mathcal{L}[\{X_t\}]]$, c.-à-d. $\mathcal{L}$ <em>commute avec le retard</em> (backshift) $B$.</li>
</ul>
<p>La condition pour un seul décalage suffit : elle entraîne $\mathcal{L}[B^u\{X_t\}]=B^u\mathcal{L}[\{X_t\}]$ pour tout $u\in\mathbb{Z}$. <strong>Intuition :</strong> la linéarité = on peut filtrer chaque morceau séparément puis additionner ; l'invariance = décaler puis filtrer donne la même chose que filtrer puis décaler. Le retard $B$ lui-même est le filtre LTI prototypique.</p>
<p><strong>Stabilité de la famille.</strong> Toute combinaison linéaire $\alpha\mathcal{L}_1+\mathcal{L}_2$ et toute mise en <strong>cascade</strong> $\mathcal{L}_1\mathcal{L}_2$ (définie par $\mathcal{L}[\{X_t\}]=\mathcal{L}_1[\mathcal{L}_2[\{X_t\}]]$) de filtres LTI est LTI. Les filtres LTI forment donc un espace vectoriel clos par composition : en particulier tout polynôme ou série en $B$, comme $\Phi(B)=\sum_j\phi_j B^j$, est LTI.</p>`},
    {h: String.raw`Réponse impulsionnelle, transfert, et les deux visions d'une série`, body: String.raw`<p>On sonde un filtre LTI avec deux entrées-test. <strong>(1) L'impulsion (impulse).</strong> Avec $\delta_{t,m}=1$ si $t=m$, $0$ sinon, la <strong>réponse impulsionnelle (impulse response)</strong> est la suite</p>
$$h_m=\mathcal{L}[\{\delta_{t,-m}\}]_0,\qquad m\in\mathbb{Z}$$
<p>(le $0$ est l'indice de temps de sortie) : c'est la réponse, lue en $t=0$, à un choc unité placé en $-m$. Condition de régularité usuelle : $h\in\ell^1$ (alors $\lVert h\rVert_\infty\le\lVert h\rVert_1<\infty$).</p>
<p><strong>(2) L'onde complexe (complex wave)</strong> $\xi_{t,f}=e^{2\pi i f t}$. La <strong>fonction de transfert (transfer function)</strong> est</p>
$$H(f)=\mathcal{L}[\{\xi_{t,f}\}]_0,\qquad f\in\mathbb{R},$$
<p>elle décrit comment chaque fréquence pure est ré-amplifiée et déphasée.</p>
<p><strong>Théorème (LTI $\Leftrightarrow$ convolution).</strong> Sous hypothèses de convergence ($h\in\ell^1$), un filtre LTI <em>est</em> une convolution par $h$, et réciproquement toute convolution par $h\in\ell^1$ est LTI :</p>
$$\mathcal{L}[\{X_t\}]_u\;=\;\sum_{m\in\mathbb{Z}}h_{u-m}X_m,\qquad u\in\mathbb{Z}.$$
<p>Idée de preuve : décomposer l'entrée en impulsions, puis linéarité (somme finie) + invariance temporelle $\mathcal{L}[\{\delta_{t,m}\}]_u=\mathcal{L}[\{\delta_{t,m-u}\}]_0=h_{u-m}$, l'absolue convergence passant à la limite. <strong>Lecture directe :</strong> dans $\mathcal{L}[\{X_t\}]_u=\sum_k h_k X_{u-k}$, le coefficient de $X_{u-k}$ <em>est</em> $h_k$.</p>
<p><strong>Deux visions de la même série.</strong> $X_t=\sum_m X_m\delta_{m,t}$ (somme d'impulsions) ou $X_t=\mu+\int_{-1/2}^{1/2}e^{2\pi i f t}\,dZ(f)$ (somme d'ondes). Filtrer agit simplement sur chaque brique : pondérer les impulsions par $h$ (convolution) ou les ondes par $H(f)$ (multiplication). Le théorème « $H=\hat h$ » dit que ce sont les deux faces d'une même pièce.</p>`},
    {h: String.raw`Ondes propres et $H$ = transformée de Fourier de $h$`, body: String.raw`<p><strong>Théorème (les ondes sont des vecteurs propres).</strong> Pour tout $f$, l'onde $\{\xi_{t,f}\}$ est une <em>eigensequence</em> de $\mathcal{L}$ :</p>
$$\mathcal{L}[\{\xi_{t,f}\}]=H(f)\,\{\xi_{t,f}\}.$$
<p>Le filtre ne change que l'amplitude et la phase, jamais la fréquence : $H(f)$ est la valeur propre. C'est ce qui <strong>diagonalise</strong> tout filtre LTI dans la base des fréquences. Preuve : comme $B^{-u}[\{\xi_{t,f}\}]=e^{2\pi i u f}\{\xi_{t,f}\}$, l'invariance + la linéarité donnent $\mathcal{L}[\{\xi_{t,f}\}]_u=e^{2\pi i f u}\mathcal{L}[\{\xi_{t,f}\}]_0=\xi_{u,f}H(f)$.</p>
<p><strong>Théorème ($H$ = transformée de Fourier de $h$).</strong> Si $h\in\ell^1$,</p>
$$H(f)=\sum_{m\in\mathbb{Z}}h_m\,e^{-2\pi i f m},\qquad f\in\mathbb{R},$$
<p>et inversement $h_m=\int_{-1/2}^{1/2}H(f)e^{2\pi i f m}\,df$ (les poids sont les coefficients de Fourier de $H$). <strong>Cas polynomial (Lemme).</strong> Pour $\mathcal{L}=\Phi(B)$ avec $\Phi(z)=\sum_{j=0}^p\phi_j z^j$, la réponse impulsionnelle est $h_m=\phi_m$ pour $0\le m\le p$ (et $0$ sinon), donc directement</p>
$$H(f)=\Phi\big(e^{-2\pi i f}\big).$$
<p><strong>Cascades en fréquence.</strong> Filtrer = multiplier par $H$ sur chaque fréquence, donc une cascade $\mathcal{L}=\mathcal{L}_1\mathcal{L}_2$ a pour transfert le <em>produit</em> $H(f)=H_1(f)H_2(f)$ (et $\lvert H\rvert^2=\lvert H_1\rvert^2\lvert H_2\rvert^2$) ; en temps, la convolution des $h$ correspond au produit des $H$.</p>`},
    {h: String.raw`Spectre de sortie : $S_Y=\lvert H\rvert^2 S_X$`, body: String.raw`<p><strong>Théorème (filtrage et stationnarité).</strong> Si $\{X_t\}$ est stationnaire et $\mathcal{L}$ est LTI avec $h\in\ell^1$, alors $\{Y_t\}=\mathcal{L}[\{X_t\}]$ est stationnaire : par la convolution $Y_t=\sum_m h_m X_{t-m}$, sa moyenne $\mu_X\sum_m h_m$ ne dépend pas de $t$, et $\gamma^{(Y)}_\tau=\sum_{m,s}h_m\overline{h_s}\,\gamma^{(X)}_{\tau-m+s}$ non plus. C'est ce qui autorise à parler de $S_Y$.</p>
<p><strong>Théorème (spectre de sortie — LE résultat clé).</strong> Si de plus $\gamma^{(X)}\in\ell^1$, alors</p>
$$S_Y(f)=\lvert H(f)\rvert^2\,S_X(f),\qquad f\in\mathbb{R}.$$
<p>Le gain est $\lvert H(f)\rvert^2$ (réel, $\ge 0$) — <strong>pas</strong> $H(f)$ ni $H(f)^2$. Idée : $\gamma^{(Y)}=w*\gamma^{(X)}$ avec $w=h*\tilde h$ et $\tilde h_t=\overline{h_{-t}}$ ; le théorème de convolution donne $W(f)=H(f)\overline{H(f)}=\lvert H(f)\rvert^2$. Toute question de filtrage devient « par quel gain $\lvert H(f)\rvert^2$ multiplie-t-on ? ».</p>
<p><strong>Exemple (différenciation $Y_t=X_t-X_{t-1}$).</strong> $\mathcal{L}=I-B$ : $h_0=1,\,h_1=-1$, donc $H(f)=1-e^{-2\pi i f}$ et, avec l'identité utile $\lvert 1-e^{-2\pi i f}\rvert^2=2-2\cos(2\pi f)=4\sin^2(\pi f)$,</p>
$$S_Y(f)=\lvert 1-e^{-2\pi i f}\rvert^2 S_X(f)=4\sin^2(\pi f)\,S_X(f).$$
<p>$H(0)=0$ : la différenciation <em>tue</em> $f=0$ et amplifie les hautes fréquences — un filtre passe-haut (high-pass).</p>`},
    {h: String.raw`Densité spectrale d'un ARMA : MA en haut, AR en bas`, body: String.raw`<p><strong>Théorème (densité spectrale d'un ARMA$(p,q)$).</strong> Pour un processus stationnaire $\Phi(B)X_t=\Theta(B)\varepsilon_t$, avec $\varepsilon_t$ bruit blanc (white noise) de variance $\sigma^2$ :</p>
$$S_X(f)=\sigma^2\,\frac{\lvert\Theta(e^{-2\pi i f})\rvert^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2}=\sigma^2\left\lvert\frac{\sum_{j=0}^q\theta_j e^{-2\pi i j f}}{\sum_{j=0}^p\phi_j e^{-2\pi i j f}}\right\rvert^2.$$
<p><strong>Preuve.</strong> On lit l'égalité de processus $\Phi(B)[\{X_t\}]=\Theta(B)[\{\varepsilon_t\}]$ ; le spectre de sortie appliqué aux deux côtés, plus le lemme polynomial, donne $\lvert\Phi(e^{-2\pi i f})\rvert^2 S_X(f)=\lvert\Theta(e^{-2\pi i f})\rvert^2\sigma^2$. On divise — légal car la condition de stationnarité interdit à $\Phi$ d'avoir un zéro sur le cercle unité, donc $\Phi(e^{-2\pi i f})\neq 0$.</p>
<p><strong>Intuition (MA en haut, AR en bas).</strong> Appliquer $\Theta(B)$ au bruit met $\lvert\Theta\rvert^2$ au numérateur ; « inverser » $\Phi(B)$ met $\lvert\Phi\rvert^2$ au dénominateur. L'ARMA n'a <em>pas</em> de forme close pour l'ACVS, mais une forme close très propre pour la densité spectrale — la façon pratique de lire son contenu fréquentiel.</p>
<p><strong>Réflexe AR(1)</strong> $X_t=\phi X_{t-1}+\varepsilon_t$ ($\lvert\phi\rvert<1$) : $S_X(f)=\sigma^2/\lvert 1-\phi e^{-2\pi i f}\rvert^2=\sigma^2/(1+\phi^2-2\phi\cos 2\pi f)$. Pic en $f=0$ si $\phi>0$ (série persistante), en $f=\tfrac12$ si $\phi<0$ (oscillante).</p>`}
  ],
  checks: [
    {q: String.raw`Que signifient concrètement les deux axiomes d'un filtre LTI ?`, a: String.raw`Linéarité = filtrer une combinaison = combiner les filtrés (superposition). Invariance temporelle = $\mathcal{L}$ commute avec le retard $B$ : décaler puis filtrer = filtrer puis décaler. Conséquence : « faire la même chose à chaque instant ».`},
    {q: String.raw`Comment lit-on la réponse impulsionnelle $h$ sur un filtre écrit comme convolution ?`, a: String.raw`Dans $\mathcal{L}[\{X_t\}]_u=\sum_k h_k X_{u-k}$, le coefficient de $X_{u-k}$ est exactement $h_k$. Ex. $Y_u=X_u+\phi X_{u-1}$ donne $h_0=1,\ h_1=\phi$.`},
    {q: String.raw`Pourquoi le spectre se multiplie-t-il par $\lvert H(f)\rvert^2$ et non par $H(f)$ ?`, a: String.raw`Chaque onde est un vecteur propre rescalé par $H(f)$ ; le spectre est une puissance ($\propto$ amplitude au carré), donc il se multiplie par le module au carré $\lvert H(f)\rvert^2$ — réel et $\ge 0$, comme doit l'être une densité spectrale.`},
    {q: String.raw`Quelle est la fonction de transfert d'un filtre polynomial $\Phi(B)$, et celle d'une cascade ?`, a: String.raw`Pour $\Phi(B)$ : $H(f)=\Phi(e^{-2\pi i f})$. Pour une cascade $\mathcal{L}_1\mathcal{L}_2$ : $H=H_1 H_2$, donc $\lvert H\rvert^2=\lvert H_1\rvert^2\lvert H_2\rvert^2$ (les gains se multiplient).`},
    {q: String.raw`Pourquoi peut-on diviser par $\lvert\Phi(e^{-2\pi i f})\rvert^2$ dans la densité spectrale ARMA ?`, a: String.raw`Parce que la condition de stationnarité impose que $\Phi$ n'ait aucun zéro sur le cercle unité, donc $\Phi(e^{-2\pi i f})\neq 0$ pour tout $f$ : la division est licite.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer le théorème du spectre de sortie d'un filtre LTI, avec TOUTES ses hypothèses, puis en déduire (en l'énonçant aussi) le théorème de la densité spectrale d'un ARMA$(p,q)$ $\Phi(B)X_t=\Theta(B)\varepsilon_t$.`,
     answer: String.raw`<div class="step"><strong>Hypothèses.</strong> Soit $\{X_t\}_{t\in\mathbb{Z}}$ stationnaire avec autocovariance $\gamma^{(X)}\in\ell^1$. Soit $\mathcal{L}$ un filtre LTI de réponse impulsionnelle $h\in\ell^1$ et de fonction de transfert $H(f)=\sum_m h_m e^{-2\pi i f m}$. Posons $\{Y_t\}=\mathcal{L}[\{X_t\}]$.</div>
<div class="step"><strong>Énoncé.</strong> Alors $\{Y_t\}$ est stationnaire (le filtrage préserve la stationnarité quand $h\in\ell^1$) et sa densité spectrale vérifie $$S_Y(f)=\lvert H(f)\rvert^2\,S_X(f),\qquad f\in\mathbb{R}.$$ Le gain est le module au carré $\lvert H(f)\rvert^2\ge 0$.</div>
<div class="step"><strong>Application à l'ARMA.</strong> Un ARMA stationnaire s'écrit comme l'égalité de deux séries filtrées : $\Phi(B)[\{X_t\}]=\Theta(B)[\{\varepsilon_t\}]$, avec $\varepsilon_t$ bruit blanc de variance $\sigma^2$ (donc $S_\varepsilon(f)=\sigma^2$). Les filtres $\Phi(B)$ et $\Theta(B)$ sont polynomiaux donc LTI, de transferts $\Phi(e^{-2\pi i f})$ et $\Theta(e^{-2\pi i f})$ (lemme du filtre polynomial).</div>
<div class="step">Le théorème du spectre de sortie sur chaque côté donne $\lvert\Phi(e^{-2\pi i f})\rvert^2 S_X(f)=\lvert\Theta(e^{-2\pi i f})\rvert^2\sigma^2$.</div>
<div class="step"><strong>Conclusion.</strong> La condition de stationnarité interdit à $\Phi$ tout zéro sur le cercle unité, donc $\Phi(e^{-2\pi i f})\neq 0$ et l'on peut diviser : $$S_X(f)=\sigma^2\,\frac{\lvert\Theta(e^{-2\pi i f})\rvert^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2}.$$</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $\{X_t\}$ stationnaire et $\{Y_t\}=(I-B)[\{X_t\}]$, c.-à-d. $Y_t=X_t-X_{t-1}$. (a) $\{Y_t\}$ est-elle stationnaire ? (b) Donner $h$ et $H(f)$. (c) Exprimer $S_Y$ en fonction de $S_X$ sous forme réelle simplifiée. (d) Quel type de filtre est-ce ?`,
     answer: String.raw`<div class="step"><strong>(a)</strong> $I-B$ est un filtre LTI de réponse impulsionnelle finie $h_0=1,\ h_1=-1$ (autres nuls), donc $h\in\ell^1$. Le filtrage par un tel $h$ préserve la stationnarité : $\{Y_t\}$ est stationnaire.</div>
<div class="step"><strong>(b)</strong> $H(f)=\sum_m h_m e^{-2\pi i f m}=h_0+h_1 e^{-2\pi i f}=1-e^{-2\pi i f}$.</div>
<div class="step"><strong>(c)</strong> $S_Y(f)=\lvert H(f)\rvert^2 S_X(f)=\lvert 1-e^{-2\pi i f}\rvert^2 S_X(f)$. On simplifie le gain : $\lvert 1-e^{-2\pi i f}\rvert^2=(1-\cos 2\pi f)^2+\sin^2 2\pi f=1-2\cos 2\pi f+\cos^2 2\pi f+\sin^2 2\pi f=2-2\cos(2\pi f)=4\sin^2(\pi f)$. Donc $$S_Y(f)=4\sin^2(\pi f)\,S_X(f).$$</div>
<div class="step"><strong>(d)</strong> $H(0)=1-1=0$ : la composante $f=0$ (la moyenne / tendance lente) est annulée, et le gain $4\sin^2(\pi f)$ croît vers $f=\tfrac12$. C'est un <strong>filtre passe-haut</strong> (high-pass).</div>`, pts: 3},
    {type:'open', q: String.raw`Soit le bruit blanc $\varepsilon_t$ de variance $\sigma^2$ et $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ (un MA(1)). (a) Via la machinerie LTI, calculer $S_X(f)$ sous forme réelle. (b) Vérifier le résultat en passant par l'ACVS et $S_X(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}$.`,
     answer: String.raw`<div class="step"><strong>(a)</strong> $X_t=\Theta(B)\varepsilon_t$ avec $\Theta(z)=1-\theta z$ : filtre LTI de réponse impulsionnelle $h_0=1,\ h_1=-\theta$, donc $H(f)=1-\theta e^{-2\pi i f}$.</div>
<div class="step">Spectre de sortie : $S_X(f)=\lvert H(f)\rvert^2 S_\varepsilon(f)=\sigma^2\lvert 1-\theta e^{-2\pi i f}\rvert^2$.</div>
<div class="step">Développement du module : $\lvert 1-\theta e^{-2\pi i f}\rvert^2=(1-\theta e^{-2\pi i f})(1-\theta e^{2\pi i f})=1-\theta(e^{-2\pi i f}+e^{2\pi i f})+\theta^2=1+\theta^2-2\theta\cos(2\pi f)$. D'où $$S_X(f)=\sigma^2\big(1+\theta^2-2\theta\cos(2\pi f)\big).$$</div>
<div class="step"><strong>(b) Vérification par l'ACVS.</strong> Pour ce MA(1) : $\gamma_0=(1+\theta^2)\sigma^2$, $\gamma_{\pm 1}=-\theta\sigma^2$, $\gamma_\tau=0$ sinon. Alors $S_X(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}=(1+\theta^2)\sigma^2-\theta\sigma^2(e^{-2\pi i f}+e^{2\pi i f})=\sigma^2(1+\theta^2-2\theta\cos 2\pi f)$ — identique à (a).</div>`, pts: 3},
    {type:'open', q: String.raw`Considérer la moyenne mobile centrée $\mathcal{L}[\{X_t\}]_u=\tfrac13(X_{u-1}+X_u+X_{u+1})$. (a) Donner la réponse impulsionnelle $h$. (b) Calculer $H(f)$ et le gain $\lvert H(f)\rvert^2$. (c) Effet en $f=0$ et en $f=\tfrac13$ ; nature du filtre ?`,
     answer: String.raw`<div class="step"><strong>(a)</strong> On écrit $\mathcal{L}[\{X_t\}]_u=\sum_k h_k X_{u-k}$. Les coefficients de $X_{u-1},X_u,X_{u+1}$ sont $h_1,h_0,h_{-1}$, donc $h_{-1}=h_0=h_1=\tfrac13$ (autres nuls).</div>
<div class="step"><strong>(b)</strong> $H(f)=\sum_m h_m e^{-2\pi i f m}=\tfrac13(e^{2\pi i f}+1+e^{-2\pi i f})=\tfrac13(1+2\cos(2\pi f))$. Le filtre est symétrique donc $H$ est réel (phase nulle), d'où $$\lvert H(f)\rvert^2=\tfrac19\big(1+2\cos(2\pi f)\big)^2.$$</div>
<div class="step"><strong>(c)</strong> En $f=0$ : $H(0)=\tfrac13(1+2)=1$, gain $1$ — la composante continue (moyenne) passe intacte. En $f=\tfrac13$ : $\cos(2\pi/3)=-\tfrac12$, donc $H=\tfrac13(1-1)=0$ — cette fréquence est annihilée.</div>
<div class="step"><strong>Nature :</strong> un lisseur <strong>passe-bas</strong> (low-pass smoother) avec un zéro (null) en $f=\tfrac13$.</div>`, pts: 3},
    {type:'open', q: String.raw`Une série est d'abord différenciée, $\{V_t\}=(I-B)[\{X_t\}]$, puis passée dans la moyenne 3 points $\mathcal{L}_2$ de la question précédente : $\{Y_t\}=\mathcal{L}_2[\{V_t\}]$. Donner $S_Y$ en fonction de $S_X$ et interpréter.`,
     answer: String.raw`<div class="step">L'ensemble est la cascade $\mathcal{L}=\mathcal{L}_2(I-B)$, qui est LTI. Sa fonction de transfert est le <strong>produit</strong> des transferts : $$H(f)=\underbrace{(1-e^{-2\pi i f})}_{\text{différence}}\cdot\underbrace{\tfrac13(1+2\cos 2\pi f)}_{\text{moyenne 3 points}}.$$</div>
<div class="step">Les gains au carré se multiplient. Avec $\lvert 1-e^{-2\pi i f}\rvert^2=4\sin^2(\pi f)$ et $\lvert\tfrac13(1+2\cos 2\pi f)\rvert^2=\tfrac19(1+2\cos 2\pi f)^2$ : $$\lvert H(f)\rvert^2=4\sin^2(\pi f)\cdot\tfrac19\big(1+2\cos 2\pi f\big)^2.$$</div>
<div class="step">Par le théorème du spectre de sortie (deux filtrages successifs LTI, $h\in\ell^1$) : $$S_Y(f)=4\sin^2(\pi f)\cdot\tfrac19\big(1+2\cos 2\pi f\big)^2\,S_X(f).$$</div>
<div class="step"><strong>Interprétation :</strong> la différence retire la composante $f=0$ ($H=0$ en $0$) et la moyenne annule $f=\tfrac13$ — une combinaison qui supprime deux bandes (band-suppressing).</div>`, pts: 4},
    {type:'open', q: String.raw`On affirme que les AR($p$) sont réversibles dans le temps : si $X_t=\sum_{j=1}^p\phi_j X_{t-j}+\varepsilon_t$ ($\varepsilon$ gaussien centré, variance $\sigma_\varepsilon^2$) et $Y_t=X_{-t}$, alors $\{Y_t\}$ est un AR($p$) de mêmes paramètres. Le prouver en utilisant la densité spectrale.`,
     answer: String.raw`<div class="step">Posons $\phi_0=-1$ et $\tilde\nu_t=\sum_{j=0}^p\phi_j Y_{t-j}=\Phi(B)[\{Y_t\}]_t$. Cela revient à $Y_t=\sum_{j=1}^p\phi_j Y_{t-j}-\tilde\nu_t$ ; il suffit donc de montrer que $\{\tilde\nu_t\}$ est un bruit blanc gaussien centré de variance $\sigma_\varepsilon^2$ (le signe est sans importance pour un bruit). Il est gaussien (combinaison linéaire de gaussiennes) et centré car $\mathbb{E}[X_t]=0$.</div>
<div class="step"><strong>Égalité des spectres.</strong> Pour tout $\tau$ : $\gamma^{(Y)}_\tau=\mathbb{E}[Y_t Y_{t+\tau}]=\mathbb{E}[X_{-t}X_{-t-\tau}]=\gamma^{(X)}_{-\tau}=\gamma^{(X)}_\tau$ (symétrie de l'ACVS réelle). Donc $S_Y(f)=S_X(f)$ pour tout $f$.</div>
<div class="step"><strong>Spectre de $\tilde\nu$.</strong> $\{\tilde\nu_t\}=\Phi(B)[\{Y_t\}]$ est un filtrage LTI ; par le lemme polynomial et le spectre de sortie, $S_{\tilde\nu}(f)=\lvert\Phi(e^{-2\pi i f})\rvert^2 S_Y(f)=\lvert\Phi(e^{-2\pi i f})\rvert^2 S_X(f)$.</div>
<div class="step">Or la densité d'un AR (cas $q=0$) donne $S_X(f)=\sigma_\varepsilon^2/\lvert\Phi(e^{-2\pi i f})\rvert^2$, d'où $$S_{\tilde\nu}(f)=\lvert\Phi(e^{-2\pi i f})\rvert^2\cdot\frac{\sigma_\varepsilon^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2}=\sigma_\varepsilon^2.$$</div>
<div class="step">Une densité spectrale constante $\equiv\sigma_\varepsilon^2$ caractérise un <strong>bruit blanc</strong> de variance $\sigma_\varepsilon^2$ ; gaussien et centré, $\{\tilde\nu_t\}$ a la même loi que $\{\varepsilon_t\}$. Donc $\{Y_t\}$ est un AR($p$) de coefficients identiques. $\square$</div>`, pts: 4}
  ]
},
