{
  n: 10,
  title: String.raw`Prévision`,
  intro: String.raw`Le meilleur prédicteur est l'espérance conditionnelle ; pour un ARMA causal on prévoit via les poids $\psi$ (on met à zéro les innovations futures) et l'erreur quadratique croît avec l'horizon.`,
  sections: [
    {h: String.raw`Le problème de prévision et la MSE`, body: String.raw`<p>Le but de l'analyse de séries temporelles est souvent de <strong>prévoir</strong> (forecast) le futur à partir des données. Recette en trois temps : (1) choisir la forme du modèle ; (2) estimer ses paramètres ; (3) prédire. Cette semaine on suppose le modèle et les paramètres <strong>connus</strong> et on prédit $h$ pas en avant : on veut $X_{n+h}$ à partir de $X_1,\dots,X_n$. L'entier $h>0$ est l'<strong>horizon</strong> (lead), $n$ est l'<strong>origine</strong>.</p>
<p>Pour un prédicteur $g(X_1,\dots,X_n)$ de $X_{n+h}$, on mesure sa qualité par l'<strong>erreur quadratique de prévision</strong> (prediction mean square error) :</p>
$$P^{\,n}_{n+h}:=\mathbb{E}\big[(X_{n+h}-g(X_1,\dots,X_n))^2\big].$$
<p>Plus $P^{\,n}_{n+h}$ est petit, meilleure est la prévision : minimiser cette quantité sur une classe de prédicteurs définit le « meilleur » prédicteur de cette classe.</p>
<p><strong>Trois sources d'incertitude.</strong> (1) le modèle (sa forme peut être fausse) ; (2) l'estimation (paramètres estimés, pas connus) ; (3) l'innovation (l'aléa intrinsèque des futurs $\varepsilon_{n+1},\dots,\varepsilon_{n+h}$). En supposant le modèle connu et les paramètres exacts, il ne reste que l'<strong>incertitude d'innovation</strong>.</p>`},
    {h: String.raw`Meilleur prédicteur : espérance conditionnelle et projection linéaire`, body: String.raw`<p><strong>Lemme (étalon-or).</strong> Parmi <em>toutes</em> les fonctions des données, le meilleur prédicteur (au sens de la MSE) est l'espérance conditionnelle $g=\mathbb{E}[X_{n+h}\mid X_1,\dots,X_n]$. Idée : pour toute variable $Y$ de moyenne $\mu$ et toute constante $c$, $\mathbb{E}[(Y-c)^2]=\operatorname{Var}(Y)+(\mu-c)^2$ est minimal en $c=\mu$ ; on applique cela conditionnellement aux données puis on prend l'espérance (propriété de la tour).</p>
<p>En général l'espérance conditionnelle est <strong>non linéaire</strong> en les données. Pour la rendre calculable on se restreint au <strong>meilleur prédicteur linéaire</strong> (best linear predictor) : la combinaison</p>
$$X^{\,n}_{n+h}=P_{X_1,\dots,X_n}(X_{n+h})=\sum_{j=1}^{n}\beta_j X_j$$
<p>qui minimise la MSE parmi toutes les combinaisons linéaires des données. C'est la <strong>projection orthogonale</strong> de $X_{n+h}$ sur $\operatorname{vect}\{X_1,\dots,X_n\}$, et elle n'a besoin que de la covariance.</p>
<p><strong>Cas gaussien.</strong> Si le processus est gaussien, l'espérance conditionnelle est <em>déjà</em> linéaire en les données : meilleur prédicteur linéaire $=$ meilleur prédicteur tout court.</p>
<p>L'<strong>erreur de prévision à $h$ pas</strong> $e_n(h):=X_{n+h}-X^{\,n}_{n+h}$ est sans biais ($\mathbb{E}[e_n(h)]=0$) et sa variance vaut la MSE : $\operatorname{Var}(e_n(h))=P^{\,n}_{n+h}$.</p>`},
    {h: String.raw`Équations de prévision (forme covariance)`, body: String.raw`<p><strong>Théorème.</strong> Pour un processus stationnaire centré, les coefficients $\beta_j$ du meilleur prédicteur linéaire résolvent les <strong>équations de prévision</strong> (prediction equations) :</p>
$$\mathbb{E}\big[(X_{n+h}-X^{\,n}_{n+h})\,X_k\big]=0,\qquad k=1,\dots,n,$$
<p>c'est-à-dire l'erreur de prévision est <strong>orthogonale</strong> à chaque observation. De façon équivalente, en forme matricielle $\Gamma_n\beta=\gamma_{[h]}$ où $\Gamma_n=[\gamma_{i-j}]_{i,j=1}^n$ est de Toeplitz et $\gamma_{[h]}=(\gamma_{n+h-1},\gamma_{n+h-2},\dots,\gamma_h)^{\top}$.</p>
<p>Si $\Gamma_n$ est inversible, on a la forme fermée</p>
$$X^{\,n}_{n+h}=\gamma_{[h]}^{\top}\,\Gamma_n^{-1}\,X,\qquad P^{\,n}_{n+h}=\gamma_0-\gamma_{[h]}^{\top}\,\Gamma_n^{-1}\,\gamma_{[h]}.$$
<p>Valable pour <em>tout</em> processus stationnaire : la prévision optimale n'utilise que la covariance. <strong>Moyenne non nulle</strong> $\mu$ : on centre, $X^{\,n}_{n+h}=\mu+\gamma_{[h]}^{\top}\Gamma_n^{-1}(X-\mu\mathbf{1}_n)$, et la MSE est <strong>inchangée</strong> (le décalage constant n'affecte pas la variance de l'erreur).</p>
<p><strong>Raccourci AR($p$).</strong> Pour un AR($p$) avec $n\ge p$, la prévision à un pas est simplement $X^{\,n}_{n+1}=\sum_{i=1}^{p}\phi_i X_{n+1-i}$ — aucune inversion de matrice. Raison : $X_{n+1}-\sum_i\phi_i X_{n+1-i}=\varepsilon_{n+1}$ est orthogonal au passé, donc le candidat satisfait déjà les équations de prévision.</p>`},
    {h: String.raw`Prévision ARMA causal par les poids $\psi$`, body: String.raw`<p><strong>Théorème.</strong> Si $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$ (représentation $MA(\infty)$ d'un ARMA causal), alors le meilleur prédicteur linéaire et sa MSE valent</p>
$$X^{\,n}_{n+h}=\sum_{j=h}^{\infty}\psi_j\,\varepsilon_{n+h-j}=\psi_h\varepsilon_n+\psi_{h+1}\varepsilon_{n-1}+\cdots,\qquad P^{\,n}_{n+h}=\sigma^2\sum_{j=0}^{h-1}\psi_j^2.$$
<p><strong>En pratique :</strong> écrire $X_{n+h}=\sum_j\psi_j\varepsilon_{n+h-j}$ puis <strong>mettre à zéro les innovations futures</strong> $\varepsilon_{n+1},\dots,\varepsilon_{n+h}$ (elles sont décorrélées du passé), garder les résidus passés et les observations. C'est le moteur de toute prévision ARMA.</p>
<p><strong>Deux théorèmes, une seule projection.</strong> Les équations de prévision projettent sur $\operatorname{vect}\{X_1,\dots,X_n\}$ via la covariance ; la formule en $\psi$ projette sur l'espace des <em>innovations</em> $\{\varepsilon_s:s\le n\}$. Pour un ARMA inversible ces deux espaces coïncident — même réponse, mais la vue « innovations » est bien plus rapide.</p>
<p><strong>Intervalle de prévision gaussien.</strong> Si le processus est gaussien, $e_n(h)\sim\mathcal{N}(0,\operatorname{Var}(e_n(h)))$, d'où l'intervalle à $(1-\alpha)$ :</p>
$$X^{\,n}_{n+h}\;\pm\;z_{1-\alpha/2}\,\sqrt{\operatorname{Var}(e_n(h))}\qquad(z_{0.975}\approx1.96\text{ pour }95\%).$$`},
    {h: String.raw`Comportement limite : ARMA vs ARIMA`, body: String.raw`<p><strong>ARMA causal — retour à la moyenne.</strong> Les poids décroissent exponentiellement, $\psi_j\to0$, donc</p>
$$X^{\,n}_{n+h}\to\mu,\qquad \operatorname{Var}(e_n(h))=\sigma^2\sum_{j=0}^{h-1}\psi_j^2\ \uparrow\ \gamma_0\quad(h\to\infty).$$
<p>Prévoir très loin revient à donner « moyenne $\pm$ écart-type marginal » : l'intervalle <strong>sature</strong>. Exemples : AR(1) $X^{\,n}_{n+h}=\phi^h X_n\to0$ ; MA($q$) la mémoire dure $q$ pas, donc dès $h>q$ la prévision <em>vaut</em> exactement $\mu$.</p>
<p><strong>ARIMA$(p,d,q)$.</strong> On prévoit la série différenciée $Z_t=\nabla^{\,d}X_t$ (un ARMA) puis on <strong>ré-intègre</strong>. Comme la différenciation est un filtre linéaire fixe, elle commute avec la projection : $\nabla^{\,d}X^{\,n}_{n+h}=Z^{\,n}_{n+h}$. Pour $d=1$,</p>
$$X^{\,n}_{n+h}=X_n+\sum_{j=0}^{h-1}Z^{\,n}_{n+h-j},\qquad h\ge1.$$
<p>Ici la MSE <strong>diverge</strong> : $P^{\,n}_{n+h}\to\infty$ (pas de retour à la moyenne). Si $Z_t$ a une moyenne $\alpha\ne0$, $X^{\,n}_{n+h}\approx X_n+\alpha h$ (droite de dérive).</p>
<p><strong>Piège.</strong> En développant un ARIMA$(p,1,q)$ on obtient une équation qui <em>ressemble</em> à un AR($p{+}1$), mais ses coefficients ne satisfont pas la condition de causalité (racine unité) : ce n'est <strong>pas</strong> un ARMA stationnaire — d'où la divergence de la MSE.</p>
<p><strong>Recette tronquée (à la main).</strong> (1) isoler $y_t$ à gauche, tout le reste à droite ; (2) remplacer $t$ par $n+h$ ; (3) substituer : observations futures $\to$ leurs prévisions, erreurs futures $\to 0$, erreurs passées $\to$ résidus $\hat\varepsilon_s$. On déroule $h=1,2,3,\dots$, chaque prévision nourrit la suivante.</p>`}
  ],
  checks: [
    {q: String.raw`Quel est le meilleur prédicteur de $X_{n+h}$ au sens de la MSE, et quand est-il linéaire ?`, a: String.raw`C'est l'espérance conditionnelle $\mathbb{E}[X_{n+h}\mid X_1,\dots,X_n]$. Elle est linéaire (donc égale au meilleur prédicteur linéaire) lorsque le processus est gaussien.`},
    {q: String.raw`Que disent les équations de prévision et que vaut la prévision en forme fermée ?`, a: String.raw`L'erreur est orthogonale aux données : $\mathbb{E}[(X_{n+h}-X^{\,n}_{n+h})X_k]=0$, soit $\Gamma_n\beta=\gamma_{[h]}$. Si $\Gamma_n$ est inversible, $X^{\,n}_{n+h}=\gamma_{[h]}^{\top}\Gamma_n^{-1}X$ et $P^{\,n}_{n+h}=\gamma_0-\gamma_{[h]}^{\top}\Gamma_n^{-1}\gamma_{[h]}$.`},
    {q: String.raw`Comment prévoit-on un ARMA causal rapidement, et que vaut la MSE ?`, a: String.raw`On écrit $X_{n+h}=\sum_j\psi_j\varepsilon_{n+h-j}$ et on met à zéro les innovations futures $\varepsilon_{n+1},\dots,\varepsilon_{n+h}$. La MSE vaut $P^{\,n}_{n+h}=\sigma^2\sum_{j=0}^{h-1}\psi_j^2$.`},
    {q: String.raw`Pourquoi l'intervalle de prévision d'un ARMA stationnaire sature alors que celui d'un ARIMA explose ?`, a: String.raw`ARMA : $\psi_j\to0$ donc $\operatorname{Var}(e_n(h))\uparrow\gamma_0$ (variance marginale, bornée). ARIMA : racine unité, pas de retour à la moyenne, donc $P^{\,n}_{n+h}\to\infty$.`},
    {q: String.raw`Pour un AR($p$) avec $n\ge p$, quelle est la prévision à un pas et pourquoi ?`, a: String.raw`$X^{\,n}_{n+1}=\sum_{i=1}^{p}\phi_i X_{n+1-i}$, sans inversion de matrice, car $X_{n+1}-\sum_i\phi_iX_{n+1-i}=\varepsilon_{n+1}$ est orthogonal au passé : le candidat satisfait déjà les équations de prévision.`}
  ],
  test: [
    {type:'open', q: String.raw`Soit $\varepsilon_t$ un bruit blanc (white noise) et $X_t=\phi_1X_{t-1}+\phi_2X_{t-2}+\varepsilon_t$ un AR(2) causal. Montrer que les meilleurs prédicteurs linéaires à un pas fondés sur une observation $X_1$, puis sur deux observations $X_1,X_2$, sont $X^{\,1}_2=\dfrac{\gamma_1}{\gamma_0}X_1=\rho_1 X_1$ et $X^{\,2}_3=\phi_1X_2+\phi_2X_1$.`,
     answer: String.raw`<div class="step"><strong>Fondé sur $X_1$ ($n=1$, $h=1$).</strong> L'équation de prévision $\Gamma_1\beta=\gamma_{[1]}$ est scalaire : $\gamma_0\beta_1=\gamma_1$, donc $\beta_1=\gamma_1/\gamma_0=\rho_1$.</div>
<div class="step">D'où $X^{\,1}_2=\beta_1 X_1=\dfrac{\gamma_1}{\gamma_0}X_1=\rho_1 X_1$.</div>
<div class="step"><strong>Fondé sur $X_1,X_2$ ($n=2$, $h=1$).</strong> Plutôt que de construire et inverser $\Gamma_2$, on utilise le modèle : $X_3=\phi_1X_2+\phi_2X_1+\varepsilon_3$, donc $X_3-(\phi_1X_2+\phi_2X_1)=\varepsilon_3$.</div>
<div class="step">Comme $\varepsilon_3$ (bruit blanc, futur) est décorrélé de $X_1$ et $X_2$ : $\mathbb{E}[(X_3-\phi_1X_2-\phi_2X_1)X_1]=\mathbb{E}[\varepsilon_3 X_1]=0$ et $\mathbb{E}[(X_3-\phi_1X_2-\phi_2X_1)X_2]=\mathbb{E}[\varepsilon_3 X_2]=0$.</div>
<div class="step">Le candidat $\phi_1X_2+\phi_2X_1$ a donc une erreur orthogonale aux deux observations : par le théorème des équations de prévision, c'est le meilleur prédicteur linéaire, $X^{\,2}_3=\phi_1X_2+\phi_2X_1$. (Fait général : pour un AR($p$) avec $n\ge p$, la prévision à un pas est $\sum_{i=1}^p\phi_iX_{n+1-i}$.)</div>`, pts: 4},
    {type:'open', q: String.raw`Énoncer (hypothèses comprises) le théorème de prévision d'un ARMA causal par les poids $\psi$, puis le démontrer : pour $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$, montrer que $X^{\,n}_{n+h}=\sum_{j=h}^{\infty}\psi_j\varepsilon_{n+h-j}$ et $P^{\,n}_{n+h}=\sigma^2\sum_{j=0}^{h-1}\psi_j^2$.`,
     answer: String.raw`<div class="step"><strong>Hypothèses.</strong> $\{X_t\}$ est un ARMA causal de représentation linéaire $X_t=\sum_{j=0}^{\infty}\psi_j\varepsilon_{t-j}$ avec $\varepsilon_t$ bruit blanc de variance $\sigma^2$, $\psi_0=1$. On prédit $X_{n+h}$ par le meilleur prédicteur linéaire fondé sur $X_1,\dots,X_n$.</div>
<div class="step"><strong>Toute prévision linéaire démarre en $\varepsilon_n$.</strong> Écrivons $X^{\,n}_{n+h}=\sum_{i=1}^n\beta_i X_i=\sum_{i=1}^n\beta_i\sum_{j=0}^{\infty}\psi_j\varepsilon_{i-j}=\sum_{j=0}^{\infty}c_j\,\varepsilon_{n-j}$ pour certains coefficients $c_j$ : c'est une combinaison des innovations jusqu'au temps $n$.</div>
<div class="step"><strong>Décomposition de la MSE.</strong> Avec $X_{n+h}=\sum_{j=0}^{\infty}\psi_j\varepsilon_{n+h-j}$ et en isolant les innovations futures (indices $j=0,\dots,h-1$, soit $\varepsilon_{n+1},\dots,\varepsilon_{n+h}$) : $$\mathbb{E}\big[(X_{n+h}-X^{\,n}_{n+h})^2\big]=\sigma^2\Big(\sum_{j=0}^{h-1}\psi_j^2+\sum_{j=h}^{\infty}(\psi_j-c_{j-h})^2\Big),$$ les termes croisés s'annulant car les $\varepsilon$ sont décorrélés.</div>
<div class="step"><strong>Minimisation.</strong> La première somme est fixe (aucun prédicteur fondé sur le passé ne peut atteindre les innovations futures). La seconde, positive, est annulée par $c_{j-h}=\psi_j$, c'est-à-dire $c_j=\psi_{j+h}$.</div>
<div class="step"><strong>Conclusion.</strong> $X^{\,n}_{n+h}=\sum_{j=0}^{\infty}\psi_{j+h}\varepsilon_{n-j}=\sum_{j=h}^{\infty}\psi_j\varepsilon_{n+h-j}$. Le résidu est $X_{n+h}-X^{\,n}_{n+h}=\sum_{j=0}^{h-1}\psi_j\varepsilon_{n+h-j}$, d'où $P^{\,n}_{n+h}=\sigma^2\sum_{j=0}^{h-1}\psi_j^2$.</div>`, pts: 5},
    {type:'open', q: String.raw`Soit l'AR(1) gaussien $X_t=\phi X_{t-1}+\varepsilon_t$, $|\phi|<1$, $\varepsilon_t\stackrel{iid}{\sim}\mathcal{N}(0,\sigma^2)$. Calculer $X^{\,n}_{n+1}$ et $X^{\,n}_{n+2}$, leurs variances d'erreur de prévision, vérifier que $\operatorname{Var}(e_n(h))\to\gamma_0$ quand $h\to\infty$, et donner un intervalle à $95\%$ pour $X_{n+2}$.`,
     answer: String.raw`<div class="step"><strong>Poids $\psi$.</strong> Un AR(1) causal a pour représentation $MA(\infty)$ $\psi_j=\phi^j$ (de $1/(1-\phi B)=\sum_j\phi^j B^j$).</div>
<div class="step"><strong>Prévisions ponctuelles.</strong> On met à zéro les innovations futures : $X^{\,n}_{n+1}=\phi X_n$ et $X^{\,n}_{n+2}=\phi^2 X_n$ (et plus généralement $X^{\,n}_{n+h}=\phi^h X_n$, gaussien donc $=\mathbb{E}[X_{n+h}\mid$ passé$]$).</div>
<div class="step"><strong>Variances d'erreur.</strong> $\operatorname{Var}(e_n(1))=\sigma^2\psi_0^2=\sigma^2$ ; $\operatorname{Var}(e_n(2))=\sigma^2(\psi_0^2+\psi_1^2)=\sigma^2(1+\phi^2)$.</div>
<div class="step"><strong>Limite.</strong> En général $\operatorname{Var}(e_n(h))=\sigma^2\sum_{j=0}^{h-1}\phi^{2j}=\sigma^2\dfrac{1-\phi^{2h}}{1-\phi^2}\xrightarrow[h\to\infty]{}\dfrac{\sigma^2}{1-\phi^2}=\gamma_0$, la variance marginale de l'AR(1). La variance d'erreur sature donc à $\gamma_0$.</div>
<div class="step"><strong>Intervalle à $95\%$ pour $X_{n+2}$.</strong> Gaussien : $\phi^2 X_n\pm 1.96\,\sigma\sqrt{1+\phi^2}$.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit le MA(2) inversible centré $X_t=\varepsilon_t-\theta_1\varepsilon_{t-1}-\theta_2\varepsilon_{t-2}$, $\varepsilon_t\stackrel{iid}{\sim}\mathcal{N}(0,\sigma^2)$. Donner $X^{\,n}_{n+1}$, $X^{\,n}_{n+2}$, $X^{\,n}_{n+3}$, leurs variances d'erreur, et un intervalle à $95\%$ pour $X_{n+2}$.`,
     answer: String.raw`<div class="step"><strong>Poids $\psi$.</strong> La forme $MA(\infty)$ est finie : $\psi_0=1$, $\psi_1=-\theta_1$, $\psi_2=-\theta_2$, et $\psi_j=0$ pour $j\ge3$.</div>
<div class="step"><strong>Prévisions.</strong> On écrit $X_{n+h}=\varepsilon_{n+h}-\theta_1\varepsilon_{n+h-1}-\theta_2\varepsilon_{n+h-2}$ et on met à zéro les innovations futures : $X^{\,n}_{n+1}=-\theta_1\hat\varepsilon_n-\theta_2\hat\varepsilon_{n-1}$ ; $X^{\,n}_{n+2}=-\theta_2\hat\varepsilon_n$ ; $X^{\,n}_{n+3}=0=\mu$ (un MA(2) se prévoit par la moyenne dès $h>2$, mémoire de longueur $2$).</div>
<div class="step"><strong>Variances d'erreur</strong> ($\operatorname{Var}(e_n(h))=\sigma^2\sum_{j=0}^{h-1}\psi_j^2$) : $\operatorname{Var}(e_n(1))=\sigma^2$ ; $\operatorname{Var}(e_n(2))=\sigma^2(1+\theta_1^2)$ ; $\operatorname{Var}(e_n(3))=\sigma^2(1+\theta_1^2+\theta_2^2)=\gamma_0$.</div>
<div class="step">Pour $h\ge3$ la variance sature à $\gamma_0=\sigma^2(1+\theta_1^2+\theta_2^2)$, la variance marginale du MA(2), comme attendu.</div>
<div class="step"><strong>Intervalle à $95\%$ pour $X_{n+2}$.</strong> $-\theta_2\hat\varepsilon_n\pm 1.96\,\sigma\sqrt{1+\theta_1^2}$.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $X_t$ une ARIMA$(0,1,0)$ avec dérive : $Z_t=X_t-X_{t-1}=\alpha+\varepsilon_t$, $\varepsilon_t\stackrel{iid}{\sim}\mathcal{N}(0,\sigma^2)$. Trouver $X^{\,n}_{n+h}$ et $\operatorname{Var}(e_n(h))$, et montrer que la MSE diverge.`,
     answer: String.raw`<div class="step"><strong>Prévision de la série différenciée.</strong> $Z_t=\alpha+\varepsilon_t$ est un bruit blanc décalé d'une constante, donc $Z^{\,n}_{n+h}=\mathbb{E}[Z_{n+h}\mid$ passé$]=\alpha$ pour tout $h$ (les $\varepsilon$ futurs sont décorrélés du passé).</div>
<div class="step"><strong>Ré-intégration</strong> ($d=1$) : $X^{\,n}_{n+h}=X_n+\sum_{j=0}^{h-1}Z^{\,n}_{n+h-j}=X_n+\sum_{j=0}^{h-1}\alpha=X_n+\alpha h$. C'est une droite de dérive partant de la dernière observation.</div>
<div class="step"><strong>Erreur de prévision.</strong> En télescopant $X_{n+h}=X_n+\sum_{j=1}^{h}Z_{n+j}=X_n+\alpha h+\sum_{j=1}^{h}\varepsilon_{n+j}$, donc $e_n(h)=X_{n+h}-X^{\,n}_{n+h}=\sum_{j=1}^{h}\varepsilon_{n+j}$ (les innovations futures accumulées).</div>
<div class="step"><strong>Variance.</strong> Les $\varepsilon_{n+j}$ étant décorrélés, $\operatorname{Var}(e_n(h))=h\,\sigma^2$.</div>
<div class="step"><strong>Divergence.</strong> $P^{\,n}_{n+h}=h\sigma^2\to\infty$ quand $h\to\infty$ : l'intervalle $X_n+\alpha h\pm 1.96\,\sigma\sqrt{h}$ s'évase sans borne — marque d'un processus intégré (pas de retour à la moyenne).</div>`, pts: 4},
    {type:'open', q: String.raw`Pour le modèle ajusté ARIMA$(3,1,1)$ $(1-\phi_1B-\phi_2B^2-\phi_3B^3)(1-B)y_t=(1+\theta_1B)\varepsilon_t$, dériver la prévision tronquée à un pas $y^{\,n}_{n+1}$ et la récurrence générale $y^{\,n}_{n+h}$ ($h>1$). (Convention $\Theta(B)=1+\theta_1B$.)`,
     answer: String.raw`<div class="step"><strong>Étape 1 — isoler $y_t$.</strong> Développer $(1-\phi_1B-\phi_2B^2-\phi_3B^3)(1-B)=1-(1+\phi_1)B+(\phi_1-\phi_2)B^2+(\phi_2-\phi_3)B^3+\phi_3B^4$.</div>
<div class="step">Le modèle s'écrit alors $y_t-(1+\phi_1)y_{t-1}+(\phi_1-\phi_2)y_{t-2}+(\phi_2-\phi_3)y_{t-3}+\phi_3y_{t-4}=\varepsilon_t+\theta_1\varepsilon_{t-1}$, soit $$y_t=(1+\phi_1)y_{t-1}-(\phi_1-\phi_2)y_{t-2}-(\phi_2-\phi_3)y_{t-3}-\phi_3y_{t-4}+\varepsilon_t+\theta_1\varepsilon_{t-1}.$$</div>
<div class="step"><strong>Étapes 2-3 — décaler en $n+1$ et substituer ($h=1$).</strong> Les seuls termes d'erreur sont $\varepsilon_{n+1}\to0$ (futur) et $\varepsilon_n\to\hat\varepsilon_n$ (dernier résidu). D'où $$y^{\,n}_{n+1}=(1+\phi_1)y_n-(\phi_1-\phi_2)y_{n-1}-(\phi_2-\phi_3)y_{n-2}-\phi_3y_{n-3}+\theta_1\hat\varepsilon_n.$$</div>
<div class="step"><strong>Cas $h>1$.</strong> Tous les termes d'erreur sont futurs ($\to0$) et les observations futures sont remplacées par leurs prévisions : $$y^{\,n}_{n+h}=(1+\phi_1)y^{\,n}_{n+h-1}-(\phi_1-\phi_2)y^{\,n}_{n+h-2}-(\phi_2-\phi_3)y^{\,n}_{n+h-3}-\phi_3y^{\,n}_{n+h-4},$$ avec la convention $y^{\,n}_s=y_s$ pour $s\le n$.</div>
<div class="step"><strong>Remarque.</strong> Bien que l'équation développée ressemble à un AR(4), elle a une racine unité (facteur $1-B$) : ce n'est pas un ARMA stationnaire, et la MSE croît sans borne quand $h$ augmente ($d=1$).</div>`, pts: 5}
  ]
},
