{
  n: 1,
  title: String.raw`Stationnarité, autocovariance & ergodicité`,
  intro: String.raw`Quand on n'observe qu'une seule trajectoire d'un processus dépendant, c'est la stationnarité qui permet de remplacer une moyenne sur plusieurs réalisations par une moyenne dans le temps — et toute l'analyse repose alors sur les deux premiers moments et la fonction d'autocovariance.`,
  sections: [
    {h: String.raw`Le problème : données dépendantes, une seule trajectoire`, body: String.raw`<p>Une <strong>série temporelle (time series)</strong> $\{X_t\}$ désigne à la fois les données enregistrées dans l'ordre du temps <em>et</em> le processus stochastique $\{X_t : t\in T\}$ dont elles sont une réalisation. Ici $T=\mathbb{Z}$ et le pas d'échantillonnage $\Delta=1$.</p>
<p>La différence avec la statistique classique : les observations sont <strong>dépendantes</strong>. « Il y a beaucoup plus de façons d'être dépendant que d'être indépendant ». Et le défi central : on n'observe en général qu'<em>une seule</em> trajectoire de taille $n$, mais on veut quand même estimer des quantités « de population » (moyenne, variance).</p>
<p><strong>Intuition.</strong> Si la structure du processus ne change pas au cours du temps — c'est la <strong>stationnarité</strong> — alors une <em>moyenne dans le temps</em> peut jouer le rôle d'une moyenne sur plusieurs réalisations. C'est cette idée qui rend l'estimation possible à partir d'un seul échantillon.</p>
<p><strong>Théorème d'existence (Kolmogorov).</strong> Une famille de lois fini-dimensionnelles $\{F_{\mathbf{t}}\}$ est celle d'un processus stochastique <em>si et seulement si</em> elle est <strong>cohérente</strong> (consistent) : marginaliser une coordonnée redonne la loi des autres, $\lim_{x_i\to\infty} F_{\mathbf{t}}(\mathbf{x}) = F_{\mathbf{t}(i)}(\mathbf{x}(i))$. Cela garantit qu'un processus à index infini $\{X_t\}_{t\in\mathbb{Z}}$ existe vraiment à partir de ses seules marginales finies — ce qui légitime de modéliser tout l'axe du temps alors qu'on n'observe que $n$ points.</p>`},
    {h: String.raw`Stationnarité faible et forte`, body: String.raw`<p><strong>Stationnarité faible (weak / second-order / covariance stationarity).</strong> $\{X_t\}$ est faiblement stationnaire si tous les moments d'ordre $1$ et $2$ existent, sont finis, et sont invariants par décalage. Concrètement, pour tout $t,s,\tau$ :</p>
$$\text{(i)}\ \mathbb{E}[X_t]=\mu;\qquad \text{(ii)}\ \operatorname{Var}(X_t)=\sigma^2<\infty;\qquad \text{(iii)}\ \mathbb{E}[X_tX_{t+\tau}]=\mathbb{E}[X_sX_{s+\tau}].$$
<p>La condition (iii) force $\mathbb{E}[X_tX_{t+\tau}]$ à ne dépendre que du décalage (lag) $\tau$, pas de $t$.</p>
<p><strong>Stationnarité forte (strict stationarity).</strong> $\{X_t\}$ est strictement stationnaire si, pour tout $n$ et tous $t_1,\dots,t_n$, la loi jointe de $(X_{t_1},\dots,X_{t_n})$ est identique à celle de $(X_{t_1+\tau},\dots,X_{t_n+\tau})$ : <em>toute</em> la distribution est invariante par décalage, pas seulement les deux premiers moments.</p>
<p><strong>Intuition — aucune n'implique l'autre.</strong> <strong>Forte $\not\Rightarrow$ faible</strong> : un bruit i.i.d. Student-$t$ à $1$ degré de liberté (loi de Cauchy) est strictement stationnaire mais n'a pas de moments finis, donc (ii) échoue. <strong>Faible $\not\Rightarrow$ forte</strong> : la stationnarité faible ne dit rien sur les moments d'ordre $\ge 3$. Les deux <strong>coïncident pour un processus gaussien</strong> (Gaussian process), car toute loi jointe y est multinormale, donc entièrement déterminée par moyenne et covariance.</p>
<p><strong>Méthode (tester la stationnarité faible).</strong> Vérifier les trois conditions dans l'ordre, et s'arrêter au premier échec : (1) $\mathbb{E}[X_t]$ constante ? (2) $\operatorname{Var}(X_t)$ finie et constante ? (3) $\operatorname{Cov}(X_t,X_{t+\tau})$ ne dépend que de $\tau$ ? Piège classique : une covariance qui garde un $t$, du type $\cos(ct)\cos(c(t+\tau))$.</p>`},
    {h: String.raw`Autocovariance (ACVS) et autocorrélation (ACF)`, body: String.raw`<p>Pour $\{X_t\}$ faiblement stationnaire, la <strong>fonction d'autocovariance (ACVS)</strong> et la <strong>fonction d'autocorrélation (ACF)</strong> sont</p>
$$\gamma_\tau=\operatorname{Cov}(X_t,X_{t+\tau}),\qquad \rho_\tau=\frac{\gamma_\tau}{\gamma_0}=\operatorname{Corr}(X_t,X_{t+\tau}),\qquad \tau\in\mathbb{Z}.$$
<p><strong>Propriétés.</strong> $\gamma_0=\operatorname{Var}(X_t)\ge 0$ ; symétrie $\gamma_{-\tau}=\gamma_\tau$ ; $\rho_0=1$ et $\lvert\rho_\tau\rvert\le 1$. L'ACVS est, pour une série, l'analogue de la matrice de covariance d'un vecteur.</p>
<p><strong>L'ACVS est semi-définie positive (s.d.p.).</strong> Pour tout $n$, tous $t_1,\dots,t_n\in\mathbb{Z}$ et tous $a_1,\dots,a_n\in\mathbb{R}$ :</p>
$$\sum_{j=1}^n\sum_{k=1}^n a_j a_k\,\gamma_{j-k}\ge 0.$$
<p>L'idée de preuve est simple : poser $W=\sum_j a_j X_j$ ; alors $0\le\operatorname{Var}(W)=\sum_{j,k} a_j a_k\operatorname{Cov}(X_j,X_k)=\sum_{j,k} a_j a_k\gamma_{j-k}$. C'est la propriété <strong>caractéristique</strong> d'une vraie autocovariance : une suite qui n'est pas s.d.p. ne peut pas être une ACVS.</p>
<p><strong>Technique-clé — ACVS d'un filtre fini de bruit blanc.</strong> Pour $X_t=\sum_k\theta_k\varepsilon_{t-k}$ avec $\varepsilon$ bruit blanc (white noise) de variance $\sigma^2$ (donc $\operatorname{Cov}(\varepsilon_s,\varepsilon_u)=\sigma^2\mathbf{1}_{\{s=u\}}$), par bilinéarité :</p>
$$\gamma_\tau=\operatorname{Cov}\!\Big(\sum_k\theta_k\varepsilon_{t+\tau-k},\ \sum_j\theta_j\varepsilon_{t-j}\Big)=\sigma^2\sum_j\theta_j\,\theta_{j+\lvert\tau\rvert}.$$
<p>Seuls survivent les termes dont les indices de bruit coïncident — ce seul réflexe gère <em>tous</em> les calculs de covariance des moyennes mobiles (MA).</p>`},
    {h: String.raw`Estimer l'ACVS : biais, s.d.p. et MSE`, body: String.raw`<p>Avec $X_1,\dots,X_n$ de moyenne empirique $\bar X$, on dispose de deux estimateurs de $\gamma_\tau$ pour $\lvert\tau\rvert\le n-1$ (nuls sinon) :</p>
$$\tilde\gamma_\tau=\frac{1}{n-\lvert\tau\rvert}\sum_{t=1}^{n-\lvert\tau\rvert}(X_t-\bar X)(X_{t+\lvert\tau\rvert}-\bar X),\qquad \hat\gamma_\tau=\frac{1}{n}\sum_{t=1}^{n-\lvert\tau\rvert}(X_t-\bar X)(X_{t+\lvert\tau\rvert}-\bar X).$$
<p><strong>Diviseur $n-\lvert\tau\rvert$ (estimateur $\tilde\gamma_\tau$)</strong> : <em>sans biais</em> à moyenne connue, mais pas toujours semi-défini positif.</p>
<p><strong>Diviseur $n$ (estimateur $\hat\gamma_\tau$)</strong> : <em>biaisé</em>, avec $\mathbb{E}[\hat\gamma_\tau]=\tfrac{n-\lvert\tau\rvert}{n}\gamma_\tau$, mais <strong>semi-défini positif</strong> — c'est le choix par défaut. L'ACF estimée est le plug-in $\hat\rho_\tau=\hat\gamma_\tau/\hat\gamma_0$.</p>
<p><strong>Intuition — l'absence de biais n'est pas le but, le faible MSE l'est.</strong> Pour un bruit blanc gaussien, les deux estimateurs sont sans biais et l'on montre (via le théorème d'Isserlis pour les moments d'ordre $4$) que, pour $\tau\ne 0$,</p>
$$\operatorname{Var}(\hat\gamma_\tau)=\frac{n-\lvert\tau\rvert}{n^2}\sigma_X^4,\qquad \operatorname{Var}(\tilde\gamma_\tau)=\frac{1}{n-\lvert\tau\rvert}\sigma_X^4,\qquad \operatorname{Var}(\hat\gamma_\tau)=\Big(\tfrac{n-\lvert\tau\rvert}{n}\Big)^{2}\operatorname{Var}(\tilde\gamma_\tau)\le\operatorname{Var}(\tilde\gamma_\tau).$$
<p>Le diviseur $n$, pourtant biaisé, a le <strong>plus petit MSE</strong>.</p>`},
    {h: String.raw`Ergodicité et variance de la moyenne empirique`, body: String.raw`<p><strong>Ergodicité en moyenne (mean ergodicity).</strong> $\{X_t\}$ est ergodique en moyenne si ses deux premiers moments sont finis et $\bar X\xrightarrow{\ \mathbb{P}\ }\mathbb{E}[X_t]$ quand $n\to\infty$ : « les moyennes temporelles $=$ les moyennes de population ». Ergodicité et stationnarité ne sont <em>pas</em> équivalentes.</p>
<p><strong>Variance de $\bar X$ et consistance.</strong> Si $\sum_\tau\lvert\gamma_\tau\rvert<\infty$, alors $\bar X$ est sans biais et</p>
$$\operatorname{Var}(\bar X)=\frac{1}{n^2}\sum_{i,j=1}^{n}\gamma_{j-i}=\frac{1}{n}\sum_{\tau=-(n-1)}^{n-1}\Big(1-\tfrac{\lvert\tau\rvert}{n}\Big)\gamma_\tau,\qquad n\,\operatorname{Var}(\bar X)\xrightarrow[n\to\infty]{}\sum_{\tau=-\infty}^{\infty}\gamma_\tau.$$
<p>On regroupe la double somme par lag $\tau$, puis on applique le <strong>théorème de sommabilité de Cesàro</strong> pour remplacer $\sum(1-\tfrac{\lvert\tau\rvert}{n})\gamma_\tau$ par $\sum\gamma_\tau$. Comme cette somme est finie, $\operatorname{Var}(\bar X)\to 0$ et donc $\bar X\xrightarrow{\ \mathbb{P}\ }\mu$ (consistance).</p>
<p><strong>Intuition — la dépendance, pas seulement $n$, pilote la précision.</strong> Puisque $n\,\operatorname{Var}(\bar X)\to\sum_\tau\gamma_\tau$, c'est la <em>somme de toutes les corrélations</em> qui compte. Une forte corrélation positive (ex. AR(1) avec $\phi\to 1$) gonfle $\operatorname{Var}(\bar X)$ : on a beaucoup d'observations, mais peu d'« information indépendante ».</p>
<p><strong>Intuition — stationnaire $\ne$ ergodique.</strong> La stationnarité dit que la <em>structure</em> ne bouge pas dans le temps ; l'ergodicité dit qu'<em>une seule</em> trajectoire suffit pour retrouver la moyenne de population. Contre-exemple type : $X_t=Y$ avec $Y$ aléatoire fixe — parfaitement stationnaire, mais $\bar X\to Y$ (une variable aléatoire, pas une constante), donc <strong>non</strong> ergodique.</p>`}
  ],
  checks: [
    {q: String.raw`Quelles sont les trois conditions de la stationnarité faible, et dans quel ordre les tester ?`, a: String.raw`(i) $\mathbb{E}[X_t]=\mu$ constante ; (ii) $\operatorname{Var}(X_t)=\sigma^2<\infty$ constante ; (iii) $\operatorname{Cov}(X_t,X_{t+\tau})$ ne dépend que du lag $\tau$. On les teste dans cet ordre et on s'arrête au premier échec.`},
    {q: String.raw`Stationnarité forte et faible : laquelle implique l'autre ?`, a: String.raw`En général aucune n'implique l'autre (Cauchy i.i.d. : forte mais pas faible ; faible ne contraint pas les moments d'ordre $\ge 3$). Elles coïncident pour un processus gaussien.`},
    {q: String.raw`Pourquoi préfère-t-on l'estimateur $\hat\gamma_\tau$ (diviseur $n$) bien qu'il soit biaisé ?`, a: String.raw`Parce qu'il est semi-défini positif (donc une vraie ACVS) et a un MSE plus faible que l'estimateur sans biais $\tilde\gamma_\tau$. L'absence de biais n'est pas le but, le faible MSE l'est.`},
    {q: String.raw`Quelle propriété algébrique caractérise une vraie autocovariance, et comment la prouve-t-on ?`, a: String.raw`La semi-définie positivité : $\sum_{j,k} a_j a_k\gamma_{j-k}\ge 0$. Preuve : poser $W=\sum_j a_j X_j$, alors $0\le\operatorname{Var}(W)=\sum_{j,k} a_j a_k\gamma_{j-k}$. Une suite non s.d.p. ne peut pas être une ACVS.`},
    {q: String.raw`Donner un processus stationnaire mais non ergodique en moyenne.`, a: String.raw`$X_t=Y$ avec $Y$ aléatoire (fixé une fois pour toutes) : stationnaire, mais $\bar X\to Y$, qui reste aléatoire, donc non ergodique en moyenne.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer précisément la définition de la stationnarité faible (second-order), avec ses trois conditions et toutes leurs hypothèses, puis expliquer pourquoi un bruit i.i.d. de loi de Student à $1$ degré de liberté (Cauchy) n'est pas faiblement stationnaire alors qu'il est strictement stationnaire.`,
     answer: String.raw`<div class="step"><strong>Définition.</strong> $\{X_t\}$ est faiblement stationnaire si tous les moments joints d'ordre $1$ et $2$ existent, sont finis, et sont invariants par décalage : pour tous $t,s\in T$ et tout décalage admissible $\tau$, (i) $\mathbb{E}[X_t]=\mu$ (indépendant de $t$) ; (ii) $\operatorname{Var}(X_t)=\sigma^2<\infty$ (fini et indépendant de $t$) ; (iii) $\mathbb{E}[X_tX_{t+\tau}]=\mathbb{E}[X_sX_{s+\tau}]$.</div>
<div class="step"><strong>Conséquence de (iii).</strong> Le moment d'ordre $2$ croisé $\mathbb{E}[X_tX_{t+\tau}]$, et donc $\operatorname{Cov}(X_t,X_{t+\tau})=\gamma_\tau$, ne dépendent que du lag $\tau$ et pas de l'instant $t$.</div>
<div class="step"><strong>Le cas Cauchy.</strong> Une loi de Student à $1$ degré de liberté est une loi de Cauchy standard. Son espérance et sa variance sont <em>indéfinies</em> (l'intégrale ne converge pas).</div>
<div class="step"><strong>Conclusion.</strong> La condition (ii) (variance finie) n'est pas satisfaite — en fait même (i) échoue —, donc $\{X_t\}$ n'est <strong>pas</strong> faiblement stationnaire. En revanche, comme les $X_t$ sont i.i.d., toute loi jointe est invariante par décalage : le processus est <strong>strictement</strong> stationnaire. C'est l'illustration nette que forte $\not\Rightarrow$ faible.</div>`, pts: 3},
    {type:'open', q: String.raw`Soit $Y_t$ i.i.d. $\mathcal{N}(0,\sigma_Y^2)$ et $a,b,c$ des constantes. Pour chacun des processus suivants, dire s'il est faiblement et/ou fortement stationnaire et, le cas échéant, donner sa moyenne et son ACVS : (1) $X_t=a+bY_t+cY_{t-1}$ ; (2) $X_t=a+bY_0$ ; (3) $X_t=Y_1\cos(ct)+Y_2\sin(ct)$ ; (4) $X_t=Y_0\cos(ct)$.`,
     answer: String.raw`<div class="step"><strong>(1) MA(1).</strong> $\mathbb{E}[X_t]=a+b\,\mathbb{E}[Y_t]+c\,\mathbb{E}[Y_{t-1}]=a$. Par indépendance des $Y$, $\operatorname{Cov}(X_t,X_{t+\tau})$ vaut $b^2\sigma_Y^2$ au lag $0$ via $Y_t$ et $c^2\sigma_Y^2$ via $Y_{t-1}$, soit $\gamma_0=(b^2+c^2)\sigma_Y^2$ ; au lag $\pm 1$ seul le terme croisé $bc\,\operatorname{Cov}(Y_t,Y_t)$ survit, soit $\gamma_{\pm1}=bc\,\sigma_Y^2$ ; et $0$ sinon. Dépend de $\tau$ seul et fini $\Rightarrow$ <strong>faiblement stationnaire</strong> ; combinaison linéaire de gaussiennes $\Rightarrow$ gaussien $\Rightarrow$ aussi <strong>fortement stationnaire</strong>.</div>
<div class="step"><strong>(2)</strong> $\mathbb{E}[X_t]=a$, et $\operatorname{Cov}(X_t,X_{t+\tau})=\operatorname{Cov}(bY_0,bY_0)=b^2\sigma_Y^2$ pour <em>tout</em> $\tau$ (le hasard est figé à travers le temps). Dépend de $\tau$ seul (constant), fini, gaussien $\Rightarrow$ <strong>faiblement et fortement stationnaire</strong>.</div>
<div class="step"><strong>(3)</strong> $\mathbb{E}[X_t]=0$. Avec $\cos\alpha\cos\beta+\sin\alpha\sin\beta=\cos(\alpha-\beta)$ et l'indépendance de $Y_1,Y_2$ : $\operatorname{Cov}(X_t,X_{t+\tau})=\sigma_Y^2[\cos(ct)\cos(c(t+\tau))+\sin(ct)\sin(c(t+\tau))]=\sigma_Y^2\cos(c\tau)$. Fonction de $\tau$ seul $\Rightarrow$ <strong>faiblement</strong> (et, gaussien, <strong>fortement</strong>) <strong>stationnaire</strong>.</div>
<div class="step"><strong>(4)</strong> $\mathbb{E}[X_t]=0$, mais $\operatorname{Cov}(X_t,X_{t+\tau})=\sigma_Y^2\cos(ct)\cos(c(t+\tau))$ <em>dépend de $t$</em> $\Rightarrow$ <strong>non stationnaire</strong> (donc ni faiblement ni fortement). Le contraste (3) vs (4) est le piège classique : deux coefficients aléatoires restaurent la stationnarité qu'un seul détruit.</div>`, pts: 5},
    {type:'open', q: String.raw`Soit $\varepsilon_t$ un bruit blanc de moyenne nulle et de variance $\sigma^2$, et $X_t=\theta_1\varepsilon_t+\theta_2\varepsilon_{t-1}$ (un MA(1)). Calculer l'ACVS $\gamma_\tau$ et l'ACF $\rho_\tau$, puis déterminer pour quels $\theta_1,\theta_2$ la corrélation au lag $1$ est maximale en module, et donner cette valeur maximale.`,
     answer: String.raw`<div class="step"><strong>Technique du filtre.</strong> $\gamma_\tau=\operatorname{Cov}(\theta_1\varepsilon_{t+\tau}+\theta_2\varepsilon_{t+\tau-1},\ \theta_1\varepsilon_t+\theta_2\varepsilon_{t-1})$. Seuls survivent les termes dont les indices de bruit coïncident, avec $\operatorname{Cov}(\varepsilon_s,\varepsilon_u)=\sigma^2\mathbf{1}_{\{s=u\}}$.</div>
<div class="step"><strong>Lag $0$.</strong> Les couplages $\varepsilon_{t}$–$\varepsilon_{t}$ et $\varepsilon_{t-1}$–$\varepsilon_{t-1}$ donnent $\gamma_0=(\theta_1^2+\theta_2^2)\sigma^2$.</div>
<div class="step"><strong>Lag $\pm 1$.</strong> Seul $\varepsilon_{t-1}$ (issu de $X_t$) coïncide avec $\varepsilon_{t-1}$ (issu de $X_{t-1}$, c.-à-d. le terme $\theta_1$ décalé), donnant $\gamma_{\pm1}=\theta_1\theta_2\sigma^2$. Pour $\lvert\tau\rvert\ge 2$, aucun indice ne coïncide : $\gamma_\tau=0$.</div>
<div class="step"><strong>ACF.</strong> $\rho_1=\dfrac{\gamma_1}{\gamma_0}=\dfrac{\theta_1\theta_2}{\theta_1^2+\theta_2^2}$, et $\rho_\tau=0$ pour $\lvert\tau\rvert\ge 2$, $\rho_0=1$.</div>
<div class="step"><strong>Borne (AM–GM).</strong> Comme $\lvert\theta_1\theta_2\rvert\le\tfrac12(\theta_1^2+\theta_2^2)$, on a $\lvert\rho_1\rvert\le\tfrac12$, avec égalité si et seulement si $\lvert\theta_1\rvert=\lvert\theta_2\rvert$. <strong>Aucun MA(1) ne peut avoir $\lvert\rho_1\rvert>\tfrac12$</strong> — un test de cohérence utile : la valeur maximale est $\tfrac12$, atteinte pour $\lvert\theta_1\rvert=\lvert\theta_2\rvert$ (le signe de $\rho_1$ suit celui de $\theta_1\theta_2$).</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $\{X_t\}$ faiblement stationnaire d'ACVS $\gamma_\tau$, et $\varepsilon_t$ un bruit blanc i.i.d. de variance $\sigma^2$, indépendant de $\{X_t\}$. Déterminer l'ACVS de $Z_t=X_t+\varepsilon_t$ et interpréter le résultat.`,
     answer: String.raw`<div class="step"><strong>Bilinéarité.</strong> $\operatorname{Cov}(Z_t,Z_{t+\tau})=\operatorname{Cov}(X_t,X_{t+\tau})+\operatorname{Cov}(X_t,\varepsilon_{t+\tau})+\operatorname{Cov}(\varepsilon_t,X_{t+\tau})+\operatorname{Cov}(\varepsilon_t,\varepsilon_{t+\tau})$.</div>
<div class="step"><strong>Croisés nuls.</strong> Par indépendance de $\{X_t\}$ et $\{\varepsilon_t\}$, les deux termes croisés s'annulent : $\operatorname{Cov}(X_t,\varepsilon_{t+\tau})=\operatorname{Cov}(\varepsilon_t,X_{t+\tau})=0$.</div>
<div class="step"><strong>Termes restants.</strong> $\operatorname{Cov}(X_t,X_{t+\tau})=\gamma_\tau$ et, le bruit étant blanc, $\operatorname{Cov}(\varepsilon_t,\varepsilon_{t+\tau})=\sigma^2\mathbf{1}_{\{\tau=0\}}$.</div>
<div class="step"><strong>Résultat.</strong> $\gamma_Z(\tau)=\gamma_\tau+\sigma^2\mathbf{1}_{\{\tau=0\}}$, c.-à-d. $\gamma_Z(0)=\gamma_0+\sigma^2$ et $\gamma_Z(\tau)=\gamma_\tau$ pour $\tau\ne 0$.</div>
<div class="step"><strong>Interprétation.</strong> Ajouter un bruit blanc indépendant ne gonfle que la variance (la « pépite » au lag $0$) et laisse tous les autres lags inchangés.</div>`, pts: 3},
    {type:'open', q: String.raw`Pour $\{X_t\}$ faiblement stationnaire vérifiant $\sum_{\tau}\lvert\gamma_\tau\rvert<\infty$, montrer que $\operatorname{Var}(\bar X)=\frac{1}{n}\sum_{\tau=-(n-1)}^{n-1}\big(1-\tfrac{\lvert\tau\rvert}{n}\big)\gamma_\tau$, déterminer la limite de $n\,\operatorname{Var}(\bar X)$, et en déduire la consistance de $\bar X$. Commenter l'effet de la dépendance.`,
     answer: String.raw`<div class="step"><strong>Sans biais.</strong> $\mathbb{E}[\bar X]=\tfrac1n\sum_{i=1}^n\mathbb{E}[X_i]=\mu$.</div>
<div class="step"><strong>Variance, double somme.</strong> $\operatorname{Var}(\bar X)=\mathbb{E}[(\bar X-\mu)^2]=\frac{1}{n^2}\sum_{i=1}^{n}\sum_{j=1}^{n}\mathbb{E}[(X_i-\mu)(X_j-\mu)]=\frac{1}{n^2}\sum_{i,j=1}^{n}\gamma_{j-i}$.</div>
<div class="step"><strong>Regroupement par lag.</strong> Pour un lag fixé $\tau=j-i$ avec $\lvert\tau\rvert\le n-1$, il y a exactement $n-\lvert\tau\rvert$ couples $(i,j)$. Donc $\operatorname{Var}(\bar X)=\frac{1}{n^2}\sum_{\tau=-(n-1)}^{n-1}(n-\lvert\tau\rvert)\gamma_\tau=\frac{1}{n}\sum_{\tau=-(n-1)}^{n-1}\big(1-\tfrac{\lvert\tau\rvert}{n}\big)\gamma_\tau$.</div>
<div class="step"><strong>Limite (Cesàro).</strong> Comme $\sum_\tau\lvert\gamma_\tau\rvert<\infty$, le théorème de sommabilité de Cesàro permet de remplacer le poids $\big(1-\tfrac{\lvert\tau\rvert}{n}\big)$ par $1$ à la limite : $n\,\operatorname{Var}(\bar X)=\sum_{\tau=-(n-1)}^{n-1}\big(1-\tfrac{\lvert\tau\rvert}{n}\big)\gamma_\tau\xrightarrow[n\to\infty]{}\sum_{\tau=-\infty}^{\infty}\gamma_\tau<\infty$.</div>
<div class="step"><strong>Consistance.</strong> Donc $\operatorname{Var}(\bar X)=O(1/n)\to 0$. Comme $\bar X$ est sans biais et $\operatorname{Var}(\bar X)\to 0$, on a la convergence en moyenne quadratique, donc en probabilité : $\bar X\xrightarrow{\ \mathbb{P}\ }\mu$.</div>
<div class="step"><strong>Effet de la dépendance.</strong> La précision asymptotique est pilotée par $\sum_\tau\gamma_\tau$, et non par $n$ seul. De fortes corrélations positives (ex. AR(1) avec $\phi\to 1$) gonflent $\sum_\tau\gamma_\tau$ et donc $\operatorname{Var}(\bar X)$ : beaucoup de points, mais peu d'information indépendante.</div>`, pts: 5},
    {type:'open', q: String.raw`Soit $X_t$ un bruit blanc gaussien i.i.d. de variance $\sigma_X^2$ (moyenne connue, remplacée dans $\bar X$). Pour $\tau\ne 0$, on admet $\operatorname{Var}(\hat\gamma_\tau)=\frac{n-\lvert\tau\rvert}{n^2}\sigma_X^4$ et $\operatorname{Var}(\tilde\gamma_\tau)=\frac{1}{n-\lvert\tau\rvert}\sigma_X^4$, où $\hat\gamma_\tau$ a le diviseur $n$ et $\tilde\gamma_\tau$ le diviseur $n-\lvert\tau\rvert$. Comparer biais, variance et MSE des deux estimateurs et conclure lequel l'emporte.`,
     answer: String.raw`<div class="step"><strong>Biais.</strong> Pour un bruit blanc, $\gamma_\tau=0$ ($\tau\ne 0$). À moyenne connue, $\mathbb{E}[\tilde\gamma_\tau]=\gamma_\tau=0$ et $\mathbb{E}[\hat\gamma_\tau]=\tfrac{n-\lvert\tau\rvert}{n}\gamma_\tau=0$ : les deux estimateurs sont <em>sans biais</em> dans ce cas particulier. (En général $\hat\gamma_\tau$ est biaisé, $\tilde\gamma_\tau$ ne l'est pas.)</div>
<div class="step"><strong>MSE = variance.</strong> Comme le biais est nul ici, $\operatorname{MSE}=\text{biais}^2+\operatorname{Var}=\operatorname{Var}$ pour chacun.</div>
<div class="step"><strong>Comparaison.</strong> $\operatorname{Var}(\hat\gamma_\tau)=\frac{n-\lvert\tau\rvert}{n^2}\sigma_X^4=\Big(\frac{n-\lvert\tau\rvert}{n}\Big)^{2}\cdot\frac{1}{n-\lvert\tau\rvert}\sigma_X^4=\Big(\frac{n-\lvert\tau\rvert}{n}\Big)^{2}\operatorname{Var}(\tilde\gamma_\tau)$.</div>
<div class="step"><strong>Conclusion.</strong> Le facteur $\big(\tfrac{n-\lvert\tau\rvert}{n}\big)^2\le 1$ donne $\operatorname{Var}(\hat\gamma_\tau)\le\operatorname{Var}(\tilde\gamma_\tau)$, donc $\operatorname{MSE}(\hat\gamma_\tau)\le\operatorname{MSE}(\tilde\gamma_\tau)$. L'estimateur à diviseur $n$ ($\hat\gamma_\tau$), bien que biaisé en général, a le plus petit MSE — et il est en plus semi-défini positif. Leçon récurrente : l'absence de biais n'est pas le but, le faible MSE l'est.</div>`, pts: 4}
  ]
},
