{
  n: 7,
  title: String.raw`Densité spectrale & représentation spectrale`,
  intro: String.raw`La densité spectrale $S(f)$ est la transformée de Fourier de l'autocovariance : elle répartit la variance d'un processus stationnaire fréquence par fréquence (Herglotz, représentation spectrale).`,
  sections: [
    {h: String.raw`La densité spectrale (spectral density function, SDF)`, body: String.raw`<p>Jusqu'ici on décrivait un processus stationnaire dans le <em>domaine temporel</em> par son ACVS $\{\gamma_\tau\}$. Cette semaine on passe dans le <em>domaine fréquentiel</em> : la même information de second ordre se lit comme une répartition de la variance selon les fréquences — c'est la « deuxième face » d'un processus stationnaire. On fixe le pas d'échantillonnage $\Delta=1$ et on travaille avec la fréquence ordinaire $f$ (et non angulaire $\omega=2\pi f$).</p>
<p><strong>Définition.</strong> Pour un processus stationnaire $\{X_t\}_{t\in\mathbb{Z}}$ d'ACVS <strong>sommable</strong> ($\{\gamma_\tau\}\in\ell^1$), la densité spectrale (spectral density function, SDF) est la transformée de Fourier en temps discret de l'ACVS :</p>
$$S(f)=\sum_{\tau\in\mathbb{Z}}\gamma_\tau\,e^{-2\pi i f\tau},\qquad f\in\mathbb{R}.$$
<p>On l'inverse par $\gamma_\tau=\int_{-1/2}^{1/2}S(f)\,e^{2\pi i f\tau}\,df$ ; en particulier, à $\tau=0$,</p>
$$\gamma_0=\operatorname{Var}(X_t)=\int_{-1/2}^{1/2}S(f)\,df.$$
<p>Une SDF valide est <strong>réelle</strong>, <strong>paire</strong> ($S(-f)=S(f)$, car $\gamma_{-\tau}=\gamma_\tau$), <strong>positive</strong> ($S\ge0$) et <strong>$1$-périodique</strong>.</p>
<p><strong>Intuition.</strong> $S(f)\,df$ = quantité de variance (« puissance ») apportée par les composantes de fréquence proche de $f$. La SDF découpe la variance totale $\gamma_0$ fréquence par fréquence. Un spectre <em>plat</em> = bruit blanc (white noise) : toutes les fréquences sont également présentes, d'où le qualificatif « blanc » ; un spectre <em>piqué</em> signale une oscillation marquée à cette fréquence. En pairant $\tau$ et $-\tau$ ($e^{-2\pi i f\tau}+e^{2\pi i f\tau}=2\cos(2\pi f\tau)$) on obtient la forme réelle commode</p>
$$S(f)=\gamma_0+2\sum_{\tau\ge1}\gamma_\tau\cos(2\pi f\tau).$$`},
    {h: String.raw`Calculer une SDF : filtres linéaires, MA et ARMA`, body: String.raw`<p>Le réflexe de base : ou bien on transforme l'ACVS, ou bien — bien plus rapide pour un filtre — on passe par la <strong>fonction de transfert</strong>. Si $X_t=\sum_j\psi_j\varepsilon_{t-j}$ avec $\{\varepsilon_t\}$ bruit blanc de variance $\sigma^2$, alors</p>
$$S(f)=\sigma^2\Big|\sum_j\psi_j\,e^{-2\pi i j f}\Big|^2,\qquad\text{(ARMA) }S(f)=\sigma^2\,\frac{\lvert\Theta(e^{-2\pi i f})\rvert^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2}.$$
<p>La SDF est un carré de module, donc <strong>automatiquement $\ge0$</strong> : c'est la garantie de validité.</p>
<ul>
<li><strong>Bruit blanc :</strong> seul $\gamma_0=\sigma_\varepsilon^2$ survit, donc $S(f)=\sigma_\varepsilon^2$ pour tout $f$ — spectre <em>plat</em>.</li>
<li><strong>MA($q$)</strong> $X_t=\sum_{j=0}^q\theta_j\varepsilon_{t-j}$ : $S(f)=\sigma_\varepsilon^2\,\lvert\Theta(e^{-2\pi i f})\rvert^2$, le carré du module de la fonction de transfert.</li>
<li><strong>MA(1)</strong> $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ : $S(f)=\sigma^2(1+\theta^2-2\theta\cos(2\pi f))$. Pour $\theta>0$ : min en $f=0$ ($\sigma^2(1-\theta)^2$), max en $f=\tfrac12$ ($\sigma^2(1+\theta)^2$).</li>
<li><strong>AR(1)</strong> $X_t=\phi X_{t-1}+\varepsilon_t$, $\lvert\phi\rvert<1$ : à partir de $\gamma_\tau=\frac{\sigma^2}{1-\phi^2}\phi^{\lvert\tau\rvert}$ et de la somme géométrique on trouve $S(f)=\dfrac{\sigma^2}{1-2\phi\cos(2\pi f)+\phi^2}$. Pour $\phi>0$ : pic en $f=0$ (spectre « rouge », lent) ; pour $\phi<0$ : pic en $f=\tfrac12$ (spectre « bleu », rapidement alternant).</li>
</ul>
<p><strong>Tests de cohérence.</strong> $S$ doit être réelle, paire, $\ge0$ et $\int_{-1/2}^{1/2}S=\gamma_0$.</p>`},
    {h: String.raw`Tester si une suite est une ACVS valide`, body: String.raw`<p>$\{\gamma_\tau\}$ est une ACVS valide <em>si et seulement si</em> elle est non-négative définie ; dans le cas sommable cela équivaut à</p>
$$S(f)=\sum_\tau\gamma_\tau\,e^{-2\pi i f\tau}\ \ge 0\quad\text{pour tout }f.$$
<p><strong>Méthode.</strong> (i) vérifier $\gamma_{-\tau}=\gamma_\tau$ et $\gamma_0\ge\lvert\gamma_\tau\rvert$ (nécessaire) ; (ii) calculer $S(f)$ ; (iii) <em>chercher une fréquence où $S<0$</em> — souvent aux bords : $f=0$ donne $\sum_\tau\gamma_\tau$, et $f=\tfrac12$ donne $\sum_\tau(-1)^\tau\gamma_\tau$ (car $\cos(\pi\tau)=(-1)^\tau$). <strong>Une seule valeur négative disqualifie la suite.</strong></p>
<p><strong>Pourquoi c'est subtil.</strong> Tronquer brutalement une ACVS casse en général la validité : on tape le <em>spectre</em>, pas l'ACVS. Exemple : $\gamma_\tau=1$ pour $\lvert\tau\rvert\le K$ et $0$ sinon donne le noyau de Dirichlet $S(f)=\frac{\sin((2K+1)\pi f)}{\sin(\pi f)}$, et $S(\tfrac12)=(-1)^K<0$ dès que $K$ est impair — donc ce n'est pas une ACVS. La bonne façon de « tronquer » est de tapérer le spectre, pas l'ACVS.</p>`},
    {h: String.raw`Aliasing, fréquence de Nyquist et processus harmonique`, body: String.raw`<p><strong>Aliasing.</strong> Échantillonner à pas $\Delta=1$ <em>replie</em> le spectre continu : $S(f)=\sum_{k\in\mathbb{Z}}\mathcal{S}(f+k)$. Au-delà de la <strong>fréquence de Nyquist</strong> $1/2$, le contenu est irrécupérable : deux sinusoïdes de fréquences $f$ et $f+k$ deviennent indistinguables (effet « roue de chariot »). Bon accord si le spectre continu est négligeable au-delà de $1/2$ ; sinon le spectre discret est corrompu. Remède : échantillonner plus fin (petit $\Delta$, Nyquist plus grand).</p>
<p><strong>Processus harmonique (harmonic process).</strong> Avec $A>0$ et $\Theta\sim\mathrm{Unif}(-\pi,\pi)$ indépendants, $X_t=A\cos(\nu t+\Theta)$. Alors $\mathbb{E}[X_t]=0$ et $\operatorname{Cov}(X_{t+\tau},X_t)=\tfrac12\,\mathbb{E}[A^2]\cos(\nu\tau)$. Il est stationnaire mais son ACVS <strong>ne décroît pas</strong> : $\{\gamma_\tau\}\notin\ell^1$, donc <strong>pas de SDF ordinaire</strong>. Son spectre est une <em>paire de raies</em> (sauts) en $\pm\nu/(2\pi)$.</p>
<p><strong>Pourquoi on a besoin de plus que la SDF.</strong> La SDF suppose $\{\gamma_\tau\}\in\ell^1$. Le processus harmonique montre qu'un processus stationnaire parfaitement légitime peut violer cette hypothèse. Il faut donc un objet plus général qui existe <em>toujours</em> : le spectre intégré.</p>`},
    {h: String.raw`Spectre intégré, Herglotz, Lebesgue et représentation spectrale`, body: String.raw`<p><strong>Spectre intégré (integrated spectrum) $S^{(I)}$.</strong> Fonction sur $[-\tfrac12,\tfrac12]$, continue à droite, bornée, <strong>croissante</strong>, avec $S^{(I)}(-\tfrac12)=0$ et $S^{(I)}(\tfrac12)=\sigma^2=\gamma_0$. Elle se comporte comme une fonction de répartition (à un facteur près) en fréquence et représente l'ACVS par</p>
$$\gamma_\tau=\int_{-1/2}^{1/2} e^{2\pi i\tau f}\,dS^{(I)}(f).$$
<p>Quand $\{\gamma_\tau\}\in\ell^1$, $S^{(I)}$ admet une densité, qui est exactement la SDF : $S=dS^{(I)}/df$.</p>
<p><strong>Théorème (Herglotz).</strong> Une suite $\{g_t\}_{t\in\mathbb{Z}}$ est <strong>non-négative définie</strong> si et seulement s'il existe $G^{(I)}$ continue à droite, bornée, croissante, $G^{(I)}(-\tfrac12)=0$, telle que $g_t=\int_{-1/2}^{1/2} e^{2\pi i t f}\,dG^{(I)}(f)$. <em>Conséquence centrale :</em> toute ACVS étant non-négative définie, <strong>tout processus stationnaire possède un spectre intégré $S^{(I)}$</strong> — même ceux, comme l'harmonique, sans SDF ordinaire. La SDF n'est que le cas particulier $dS^{(I)}=S\,df$.</p>
<p><strong>Théorème (décomposition de Lebesgue).</strong> Tout spectre intégré se décompose de façon unique en $S^{(I)}=S^{(I)}_1+S^{(I)}_2+S^{(I)}_3$, où $S^{(I)}_1$ est <strong>absolument continu</strong> (sa dérivée est la SDF $S$, ACVS qui <em>s'amortit</em> $\gamma_\tau\to0$ — type ARMA), $S^{(I)}_2$ est une <strong>fonction en escalier</strong> (sauts = raies de sinusoïdes pures, <em>line spectrum</em> : ACVS qui <em>ne s'amortit pas</em> — type harmonique) et $S^{(I)}_3$ est singulier continu (pathologique, sans intérêt pratique). Un signal périodique noyé dans un bruit coloré donne un spectre <em>mixte</em>.</p>
<p><strong>Théorème (représentation spectrale).</strong> Pour $\{X_t\}$ réel, stationnaire, de moyenne $\mu$, il existe un <strong>processus à accroissements orthogonaux</strong> $\{Z(f)\}$ sur $[-\tfrac12,\tfrac12]$ tel que, au sens de la moyenne quadratique,</p>
$$X_t=\mu+\int_{-1/2}^{1/2} e^{2\pi i f t}\,dZ(f),$$
<p>avec, pour $f\ne f'$, $\mathbb{E}[dZ(f)]=0$, $\operatorname{Var}(dZ(f))=dS^{(I)}(f)$ et $\operatorname{Cov}(dZ(f),dZ(f'))=0$. <strong>Le slogan à graver :</strong> tout processus stationnaire est une superposition de sinusoïdes aléatoires <em>décorrélées</em> $e^{2\pi i f t}\,dZ(f)$, la « quantité de variance » à la fréquence $f$ valant $dS^{(I)}(f)$. Herglotz garantit que ce spectre <em>existe</em> ; la représentation spectrale dit comment le processus <em>est fait</em> à partir de lui ; la SDF est la densité de cette puissance, quand elle existe.</p>`}
  ],
  checks: [
    {q: String.raw`Que représente concrètement $S(f)\,df$ ?`, a: String.raw`La quantité de variance (« puissance ») apportée par les composantes de fréquence proche de $f$. La SDF découpe la variance totale $\gamma_0=\int_{-1/2}^{1/2}S(f)\,df$ fréquence par fréquence.`},
    {q: String.raw`Quelles quatre propriétés caractérisent une SDF valide ?`, a: String.raw`Réelle, paire ($S(-f)=S(f)$), positive ($S\ge0$) et $1$-périodique. Si l'une manque, ce n'est pas une SDF (et l'ACVS sous-jacente n'est pas valide).`},
    {q: String.raw`Comment teste-t-on rapidement si $\{\gamma_\tau\}$ est une ACVS valide ?`, a: String.raw`On calcule $S(f)$ et on vérifie $S(f)\ge0$ partout (équivalent à non-négative définie dans le cas sommable). On regarde surtout les bords : $f=0$ donne $\sum_\tau\gamma_\tau$, $f=\tfrac12$ donne $\sum_\tau(-1)^\tau\gamma_\tau$. Une seule valeur négative disqualifie la suite.`},
    {q: String.raw`Pourquoi le processus harmonique $X_t=A\cos(\nu t+\Theta)$ n'a-t-il pas de SDF ordinaire, et que garantit Herglotz dans ce cas ?`, a: String.raw`Son ACVS $\tfrac12\mathbb{E}[A^2]\cos(\nu\tau)$ ne décroît pas, donc $\{\gamma_\tau\}\notin\ell^1$ : pas de SDF. Mais Herglotz garantit qu'il possède quand même un spectre intégré $S^{(I)}$ (ici une paire de raies en $\pm\nu/(2\pi)$).`},
    {q: String.raw`Énoncez la représentation spectrale en une phrase, avec la propriété clé de $\{Z(f)\}$.`, a: String.raw`$X_t=\mu+\int_{-1/2}^{1/2}e^{2\pi i f t}\,dZ(f)$ avec $\{Z(f)\}$ à accroissements orthogonaux : $\operatorname{Var}(dZ(f))=dS^{(I)}(f)$ et $\operatorname{Cov}(dZ(f),dZ(f'))=0$ pour $f\ne f'$. Tout processus stationnaire est une superposition de sinusoïdes aléatoires décorrélées.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncez le théorème de Herglotz avec toutes ses hypothèses, et expliquez pourquoi il entraîne que tout processus stationnaire possède un spectre intégré.`,
     answer: String.raw`<div class="step"><strong>Énoncé.</strong> Une suite complexe $\{g_t\}_{t\in\mathbb{Z}}$ est non-négative définie si et seulement s'il existe une fonction $G^{(I)}$ <em>continue à droite, bornée, croissante</em>, avec $G^{(I)}(-\tfrac12)=0$, telle que $$g_t=\int_{-1/2}^{1/2} e^{2\pi i t f}\,dG^{(I)}(f),\qquad t\in\mathbb{Z}.$$ Les propriétés de $G^{(I)}$ sont essentiellement celles d'une fonction de répartition.</div>
<div class="step"><strong>Sens $(\Leftarrow)$.</strong> Toute intégrale de cette forme avec $G^{(I)}$ croissante produit une suite non-négative définie : pour des scalaires $a_1,\dots,a_m$, $\sum_{j,k}a_j\bar a_k\,g_{t_j-t_k}=\int_{-1/2}^{1/2}\big|\sum_j a_j e^{2\pi i t_j f}\big|^2\,dG^{(I)}(f)\ge0$ car l'intégrande est $\ge0$ et $dG^{(I)}\ge0$.</div>
<div class="step"><strong>Sens $(\Rightarrow)$.</strong> On construit $G^{(I)}$ comme limite faible des moyennes de Cesàro / Fejér (non-négatives) des sommes partielles $\sum_{\lvert t\rvert\le N}g_t e^{-2\pi i t f}$, qui forment une famille tendue de mesures.</div>
<div class="step"><strong>Conséquence.</strong> L'ACVS $\{\gamma_\tau\}$ de tout processus stationnaire est non-négative définie (propriété fondamentale). En appliquant Herglotz à $g_t=\gamma_t$, on obtient $\gamma_\tau=\int_{-1/2}^{1/2} e^{2\pi i\tau f}\,dS^{(I)}(f)$ avec $S^{(I)}(-\tfrac12)=0$, $S^{(I)}(\tfrac12)=\sigma^2=\gamma_0$, $S^{(I)}$ croissante. Donc <strong>tout</strong> processus stationnaire admet un spectre intégré $S^{(I)}$ — même ceux sans SDF ordinaire (comme l'harmonique). La SDF est le cas particulier absolument continu où $dS^{(I)}=S\,df$.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $\{\varepsilon_t\}$ un bruit blanc de variance $\sigma_\varepsilon^2$. Déterminez sa densité spectrale, puis celle d'un MA($q$) $X_t=\sum_{j=0}^q\theta_j\varepsilon_{t-j}$. Commentez le signe.`,
     answer: String.raw`<div class="step"><strong>Bruit blanc.</strong> L'ACVS est $\gamma_\tau=\sigma_\varepsilon^2$ si $\tau=0$ et $0$ sinon. Seul le terme $\tau=0$ survit dans la somme : $$S(f)=\sum_{\tau\in\mathbb{Z}}\gamma_\tau\,e^{-2\pi i f\tau}=\sigma_\varepsilon^2\quad\text{pour tout }f.$$ Le spectre est <strong>plat</strong> : puissance égale à toutes les fréquences — d'où « blanc ».</div>
<div class="step"><strong>MA($q$) : ACVS.</strong> $\gamma_\tau=\sigma_\varepsilon^2\sum_{j=0}^q\theta_j\theta_{j+\lvert\tau\rvert}$ pour $\lvert\tau\rvert\le q$ (et $0$ sinon, avec $\theta_0=1$). On l'écrit comme double somme : $\gamma_\tau=\sigma_\varepsilon^2\sum_{j=0}^q\sum_{k=0}^q\theta_j\theta_k\,\mathbf{1}_{\{\tau=k-j\}}$.</div>
<div class="step"><strong>MA($q$) : transformée.</strong> Comme $\gamma\in\ell^1$, la SDF existe : $$S(f)=\sigma_\varepsilon^2\sum_{j=0}^q\sum_{k=0}^q\theta_j\theta_k\sum_\tau\mathbf{1}_{\{\tau=k-j\}}e^{-2\pi i\tau f}=\sigma_\varepsilon^2\sum_{j=0}^q\sum_{k=0}^q\theta_j\theta_k\,e^{-2\pi i(k-j)f}.$$ La double somme se factorise : $$S(f)=\sigma_\varepsilon^2\Big(\sum_{j=0}^q\theta_j e^{-2\pi i j f}\Big)\overline{\Big(\sum_{k=0}^q\theta_k e^{-2\pi i k f}\Big)}=\sigma_\varepsilon^2\,\big\lvert\Theta(e^{-2\pi i f})\big\rvert^2.$$</div>
<div class="step"><strong>Signe.</strong> La SDF est le carré du module de la fonction de transfert, donc <strong>automatiquement $\ge0$</strong>, comme toute SDF doit l'être. (Le bruit blanc est le cas $q=0$ : $S(f)=\sigma_\varepsilon^2$.)</div>`, pts: 4},
    {type:'open', q: String.raw`On considère la suite $\gamma_\tau=1$ pour $\lvert\tau\rvert\le K$ et $\gamma_\tau=0$ pour $\lvert\tau\rvert>K$, $K$ entier positif. Est-ce une ACVS d'un processus stationnaire ? Que vaudrait sa SDF ?`,
     answer: String.raw`<div class="step"><strong>Conditions nécessaires.</strong> $\{\gamma_\tau\}$ est sommable et symétrique ($\gamma_{-\tau}=\gamma_\tau$), donc on peut former sa transformée de Fourier.</div>
<div class="step"><strong>Calcul de la SDF.</strong> $$S(f)=\sum_{\tau=-K}^{K}e^{-2\pi i\tau f}=1+2\sum_{\tau=1}^K\cos(2\pi\tau f)=\frac{\sin\big((2K+1)\pi f\big)}{\sin(\pi f)}$$ (noyau de Dirichlet).</div>
<div class="step"><strong>Test de positivité au bord $f=\tfrac12$.</strong> Avec $\cos(\pi\tau)=(-1)^\tau$ : $$S(\tfrac12)=1+2\sum_{\tau=1}^K(-1)^\tau=(-1)^K.$$ Donc $S(\tfrac12)=-1<0$ dès que $K$ est <strong>impair</strong> (poser $K=2q+1$).</div>
<div class="step"><strong>Conclusion.</strong> Comme la SDF devient négative, $\{\gamma_\tau\}$ n'est <strong>pas</strong> non-négative définie, donc ce n'est <strong>pas</strong> une ACVS valide (au moins pour $K$ impair). Morale : tronquer brutalement une ACVS casse en général la non-négativité-définie ; on tape le spectre, pas l'ACVS.</div>`, pts: 4},
    {type:'open', q: String.raw`Déterminez l'autocovariance $\gamma_\tau$ du processus $\{X_t\}$ de spectre $S(f)=\dfrac{\sigma^2}{\pi}(1-2\lvert f\rvert)\,\mathbf{1}_{\{\lvert f\rvert\le 1/2\}}$.`,
     answer: String.raw`<div class="step"><strong>Mise en place.</strong> Par inversion, $\gamma_\tau=\int_{-1/2}^{1/2}e^{2\pi i f\tau}S(f)\,df$. Comme $S$ est paire, la partie en $\sin$ (impaire) s'annule : pour $\tau\ne0$, $$\gamma_\tau=\frac{2\sigma^2}{\pi}\int_0^{1/2}\cos(2\pi f\tau)(1-2f)\,df=\frac{2\sigma^2}{\pi}\big(I_1-2I_2\big).$$</div>
<div class="step"><strong>Intégrales de base.</strong> $$I_1=\int_0^{1/2}\cos(2\pi f\tau)\,df=\frac{\sin(\pi\tau)}{2\pi\tau},\qquad I_2=\int_0^{1/2}f\cos(2\pi f\tau)\,df=\frac{\sin(\pi\tau)}{4\pi\tau}+\frac{\cos(\pi\tau)-1}{4\pi^2\tau^2}.$$</div>
<div class="step"><strong>Combinaison.</strong> $I_1-2I_2=-\dfrac{\cos(\pi\tau)-1}{2\pi^2\tau^2}=\dfrac{1-\cos(\pi\tau)}{2\pi^2\tau^2}$, d'où $$\gamma_\tau=\frac{\sigma^2}{\pi^3}\,\frac{1-\cos(\pi\tau)}{\tau^2}\qquad(\tau\ne0).$$</div>
<div class="step"><strong>Cas $\tau=0$.</strong> $\gamma_0=\dfrac{2\sigma^2}{\pi}\int_0^{1/2}(1-2f)\,df=\dfrac{2\sigma^2}{\pi}\cdot\tfrac14=\dfrac{\sigma^2}{2\pi}$.</div>
<div class="step"><strong>Lecture.</strong> Comme $1-\cos(\pi\tau)=0$ pour $\tau$ pair et $=2$ pour $\tau$ impair, l'ACVS est portée par les retards impairs et $\tau=0$ : $\gamma_0=\sigma^2/(2\pi)$, $\gamma_1=2\sigma^2/\pi^3$, $\gamma_2=0$, $\gamma_3=2\sigma^2/(9\pi^3)$, etc.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit l'AR(1) $X_t=\phi X_{t-1}+\varepsilon_t$ avec $\lvert\phi\rvert<1$ et $\{\varepsilon_t\}$ bruit blanc de variance $\sigma^2$. Dérivez sa densité spectrale à partir de l'ACVS, confirmez-la via la fonction de transfert, et décrivez sa forme selon le signe de $\phi$.`,
     answer: String.raw`<div class="step"><strong>ACVS.</strong> Pour un AR(1) causal, $\gamma_\tau=\dfrac{\sigma^2}{1-\phi^2}\,\phi^{\lvert\tau\rvert}$.</div>
<div class="step"><strong>SDF par sommes géométriques.</strong> $$S(f)=\frac{\sigma^2}{1-\phi^2}\sum_{\tau\in\mathbb{Z}}\phi^{\lvert\tau\rvert}e^{-2\pi i f\tau}=\frac{\sigma^2}{1-\phi^2}\Big(1+\sum_{\tau\ge1}\phi^\tau\big(e^{-2\pi i f\tau}+e^{2\pi i f\tau}\big)\Big).$$ Avec $\sum_{\tau\ge1}\phi^\tau e^{-2\pi i f\tau}=\dfrac{\phi e^{-2\pi i f}}{1-\phi e^{-2\pi i f}}$ et son conjugué : $$S(f)=\frac{\sigma^2}{1-\phi^2}\Big(1+\frac{\phi e^{-2\pi i f}}{1-\phi e^{-2\pi i f}}+\frac{\phi e^{2\pi i f}}{1-\phi e^{2\pi i f}}\Big)=\frac{\sigma^2}{1-\phi^2}\cdot\frac{1-\phi^2}{1-2\phi\cos(2\pi f)+\phi^2}.$$ D'où $$S(f)=\frac{\sigma^2}{1-2\phi\cos(2\pi f)+\phi^2}.$$</div>
<div class="step"><strong>Vérification par la fonction de transfert.</strong> Ici $\Phi(z)=1-\phi z$, donc $S(f)=\dfrac{\sigma^2}{\lvert1-\phi e^{-2\pi i f}\rvert^2}$. Or $\lvert1-\phi e^{-2\pi i f}\rvert^2=(1-\phi e^{-2\pi i f})(1-\phi e^{2\pi i f})=1-2\phi\cos(2\pi f)+\phi^2$ : identique.</div>
<div class="step"><strong>Forme.</strong> Le dénominateur $1-2\phi\cos(2\pi f)+\phi^2$ est minimal là où $\phi\cos(2\pi f)$ est maximal. Pour $\phi>0$ : minimum en $f=0$, donc $S$ pique en basse fréquence (spectre « rouge », lent) ; pour $\phi<0$ : pic en $f=\tfrac12$ (spectre « bleu », rapidement alternant). Quand $\phi\to1$, le pic en $0$ explose (quasi-racine unité, dépendance à très longue portée).</div>`, pts: 4},
    {type:'open', q: String.raw`Pour quelles valeurs de $\rho\in\mathbb{R}$ la suite $\gamma_0=1$, $\gamma_{\pm1}=\rho$, $\gamma_\tau=0$ pour $\lvert\tau\rvert\ge2$ est-elle une ACVS valide ? Justifiez par la densité spectrale.`,
     answer: String.raw`<div class="step"><strong>Forme.</strong> C'est la forme d'ACVS d'un MA(1). Sa SDF est $$S(f)=\gamma_0+2\gamma_1\cos(2\pi f)=1+2\rho\cos(2\pi f).$$</div>
<div class="step"><strong>Minimum de la SDF.</strong> Comme $\cos(2\pi f)\in[-1,1]$, le minimum de $S$ vaut $1-2\lvert\rho\rvert$, atteint en $f=\tfrac12$ si $\rho>0$ et en $f=0$ si $\rho<0$.</div>
<div class="step"><strong>Condition de validité.</strong> $S(f)\ge0$ pour tout $f$ équivaut à $1-2\lvert\rho\rvert\ge0$, soit $$\boxed{\lvert\rho\rvert\le\tfrac12.}$$</div>
<div class="step"><strong>Conclusion.</strong> Pour $\lvert\rho\rvert\le\tfrac12$, c'est une ACVS valide ; pour $\lvert\rho\rvert>\tfrac12$, la SDF passe sous zéro, donc ce n'est pas une ACVS. C'est cohérent avec le fait qu'un MA(1) ne peut avoir $\lvert\rho_1\rvert>\tfrac12$.</div>`, pts: 4}
  ]
},
