{
  n: 12,
  title: String.raw`Séries non linéaires : ARCH & GARCH`,
  intro: String.raw`Pour la volatilité changeante des rendements financiers (volatility clustering), on modélise la variance conditionnelle : ARCH/GARCH sont non corrélés mais dépendants.`,
  sections: [
    {h: String.raw`Le problème : rendements financiers et clusters de volatilité`, body: String.raw`<p>Les modèles linéaires (AR, MA, ARMA) décrivent la <strong>moyenne conditionnelle</strong> et supposent une variance d'innovation <strong>constante</strong>. Les rendements logarithmiques (log-returns) financiers violent cela. Pour un prix $\{X_t\}$ on étudie</p>
$$r_t=\log\!\Big(\frac{X_t}{X_{t-1}}\Big)=\log X_t-\log X_{t-1},$$
<p>la variation relative du prix. Empiriquement, les $r_t$ sont quasi <strong>non corrélés</strong> (l'ACF/PACF de $r_t$ ressemble à du bruit blanc, donc un modèle linéaire de la moyenne est presque inutile), mais leurs <strong>carrés</strong> $r_t^2$ sont fortement dépendants (ACF/PACF qui décroît lentement). On observe :</p>
<ul>
<li><strong>groupement de volatilité</strong> (volatility clustering) : grands chocs suivis de grands chocs, périodes calmes suivies de calme ;</li>
<li><strong>queues épaisses</strong> (fat tails) : kurtosis $>3$, visible comme un écart sur un QQ-plot contre $\mathcal N(0,1)$.</li>
</ul>
<p><strong>Idée centrale.</strong> Garder la série centrée et non corrélée, mais laisser la <strong>variance conditionnelle</strong> $\sigma_t^2$ évoluer dans le temps. On note $\mathcal F_t$ l'information jusqu'à $t$ inclus, et $\{\varepsilon_t\}$ un bruit blanc (white noise) de moyenne $0$, variance $1$, <strong>indépendant</strong> de $\mathcal F_{t-1}$.</p>`},
    {h: String.raw`Définitions : ARCH(p) et GARCH(p,q)`, body: String.raw`<p><strong>ARCH(1).</strong> $\{r_t\}$ est un modèle <em>AutoRegressive Conditionally Heteroscedastic</em> d'ordre $1$ si</p>
$$r_t=\sigma_t\varepsilon_t,\qquad \sigma_t^2=\alpha_0+\alpha_1 r_{t-1}^2,\qquad \alpha_0>0,\ \alpha_1\ge0.$$
<p>La volatilité $\sigma_t$ est $\mathcal F_{t-1}$-mesurable (connue un pas à l'avance), donc $\mathbb{E}[r_t\mid\mathcal F_{t-1}]=0$ et $\operatorname{Var}(r_t\mid\mathcal F_{t-1})=\sigma_t^2$. Plus généralement <strong>ARCH$(p)$</strong> : $\sigma_t^2=\alpha_0+\sum_{j=1}^{p}\alpha_j r_{t-j}^2$ (avec $\alpha_0,\alpha_p>0$, $\alpha_j\ge0$).</p>
<p><strong>GARCH$(p,q)$.</strong> On réinjecte en plus les <strong>variances</strong> passées :</p>
$$\sigma_t^2=\alpha_0+\sum_{j=1}^{p}\alpha_j r_{t-j}^2+\sum_{j=1}^{q}\beta_j\sigma_{t-j}^2,$$
<p>avec $\alpha_0,\alpha_p,\beta_q>0$ et les autres coefficients $\ge0$. Cas particulier : GARCH$(p,0)=$ ARCH$(p)$. En pratique on utilise souvent <strong>GARCH$(1,1)$</strong>, parcimonieux et performant.</p>
<p><strong>Pourquoi réinjecter $\sigma_{t-1}^2$ ?</strong> Dans ARCH$(1)$, $\sigma_t^2$ ne dépend que du <em>seul</em> carré le plus récent : un jour calme fait instantanément retomber $\sigma_t^2$ vers $\alpha_0$, donc le modèle ne peut pas tenir de longs régimes de forte volatilité. GARCH ajoute le terme lisse $\beta_1\sigma_{t-1}^2$ : l'estimation de variance d'hier est reportée, la volatilité devient <strong>collante</strong>. En finance, les GARCH$(1,1)$ ajustés ont $\alpha_1+\beta_1$ proche de $1$ (volatilité très persistante).</p>`},
    {h: String.raw`Bruit blanc mais dépendant : moyenne, variance, corrélation`, body: String.raw`<p><strong>Réflexe de calcul.</strong> Conditionner sur $\mathcal F_{t-1}$, sortir les facteurs $\mathcal F_{t-1}$-mesurables ($\sigma_t$), utiliser $\mathbb{E}[\varepsilon_t]=0$, $\mathbb{E}[\varepsilon_t^2]=1$, puis espérance itérée (tour) $+$ stationnarité.</p>
<p><strong>Moments d'un ARCH(1)</strong> (si $\alpha_1<1$) : $\mathbb{E}[r_t]=0$ et</p>
$$\operatorname{Var}(r_t)=\frac{\alpha_0}{1-\alpha_1}.$$
<p><em>Idée :</em> $\operatorname{Var}(r_t)=\mathbb{E}[\sigma_t^2]=\alpha_0+\alpha_1\operatorname{Var}(r_{t-1})$ ; par stationnarité $\operatorname{Var}(r_t)=\operatorname{Var}(r_{t-1})$, on résout. La condition $\alpha_1<1$ est <strong>nécessaire et suffisante</strong> pour la stationnarité faible d'un ARCH$(1)$.</p>
<p><strong>ARCH/GARCH = bruit blanc.</strong> Tout ARCH$(p)$ ou GARCH$(p,q)$ vérifie $\mathbb{E}[r_t]=0$ et, pour $\tau\ne0$, $\operatorname{Cov}(r_{t+\tau},r_t)=0$. <em>Idée :</em> pour $\tau>0$, conditionner sur $\mathcal F_{t+\tau-1}$ (qui contient $r_t$ et $\sigma_{t+\tau}$) ; il reste $\mathbb{E}[r_t\,\sigma_{t+\tau}\,\mathbb{E}[\varepsilon_{t+\tau}\mid\mathcal F_{t+\tau-1}]]=0$.</p>
<p>C'est le fait central : la structure de corrélation <strong>linéaire</strong> reste plate, mais toute la dépendance est <strong>non linéaire</strong> (dans les carrés). « Bruit blanc » $\ne$ « sans structure » : on a $\operatorname{Corr}(r_{t+\tau},r_t)=0$ pourtant $\operatorname{Corr}(r_{t+\tau}^2,r_t^2)\ne0$. Les problèmes de moyenne conditionnelle (ARMA) et de variance conditionnelle (GARCH) se <strong>découplent</strong>.</p>`},
    {h: String.raw`Queues épaisses et ACF des carrés (ARCH(1))`, body: String.raw`<p><strong>Isserlis (formule de Wick).</strong> Pour un vecteur gaussien centré et $N=4$ : $\mathbb{E}[X_1X_2X_3X_4]=\mathbb{E}[X_1X_2]\mathbb{E}[X_3X_4]+\mathbb{E}[X_1X_3]\mathbb{E}[X_2X_4]+\mathbb{E}[X_1X_4]\mathbb{E}[X_2X_3]$. En particulier $\mathbb{E}[\varepsilon_t^4]=3$ pour un $\varepsilon_t$ gaussien standard.</p>
<p><strong>Kurtosis d'un ARCH(1)</strong> (innovations gaussiennes). Le $4^{\text e}$ moment est fini <strong>ssi</strong> $\alpha_1^2<\tfrac13$, et alors</p>
$$\kappa=\frac{\mathbb{E}[r_t^4]}{\operatorname{Var}(r_t)^2}=\frac{3(1-\alpha_1^2)}{1-3\alpha_1^2}\ >\ 3\quad(\alpha_1>0).$$
<p>ARCH <strong>génère</strong> donc de l'excès de kurtosis tout seul, même avec un $\varepsilon_t$ gaussien.</p>
<p><strong>Deux seuils à ne pas confondre.</strong> $\alpha_1<1$ donne une <em>variance</em> finie ; le seuil strictement plus serré $\alpha_1^2<\tfrac13$ (soit $\alpha_1<1/\sqrt3\approx0{,}577$) donne un <em>$4^{\text e}$ moment</em> fini. Quand $\alpha_1\uparrow1/\sqrt3$, $\kappa\to\infty$ : plus d'effet ARCH $=$ queues plus lourdes.</p>
<p><strong>ACF des carrés.</strong> Pour $0<\alpha_1<1/\sqrt3$,</p>
$$\operatorname{Corr}(r_{t+\tau}^2,r_t^2)=\alpha_1^{\lvert\tau\rvert}:$$
<p>décroissance <strong>géométrique</strong>. <em>Idée :</em> conditionner sur $\mathcal F_{t+\tau-1}$ donne la récursion $C_\tau=\alpha_1 C_{\tau-1}$ (les constantes s'annulent via $\mathbb{E}[r_t^2]=\alpha_0/(1-\alpha_1)$). Souvent trop rapide pour les données réelles $\Rightarrow$ GARCH.</p>`},
    {h: String.raw`GARCH : stationnarité, ARCH(∞), MLE et diagnostics`, body: String.raw`<p><strong>Stationnarité & variance d'un GARCH$(p,q)$.</strong> Solution faiblement stationnaire <strong>ssi</strong></p>
$$\sum_{j=1}^{p}\alpha_j+\sum_{j=1}^{q}\beta_j<1,\qquad\text{et alors}\qquad \operatorname{Var}(r_t)=\frac{\alpha_0}{1-\sum_j\alpha_j-\sum_j\beta_j}.$$
<p><em>Idée :</em> prendre l'espérance inconditionnelle de la récursion, remplacer $\mathbb{E}[r_{t-j}^2]=\mathbb{E}[\sigma_{t-j}^2]=\operatorname{Var}(r_t)$ par stationnarité, et résoudre. Pour GARCH$(1,1)$ gaussien, le $4^{\text e}$ moment existe ssi $3\alpha_1^2+2\alpha_1\beta_1+\beta_1^2<1$.</p>
<p><strong>GARCH(1,1) $\approx$ ARCH$(\infty)$.</strong> En itérant $\sigma_t^2=\alpha_0+\alpha_1 r_{t-1}^2+\beta_1\sigma_{t-1}^2$ (pour $0\le\beta_1<1$) :</p>
$$\sigma_t^2=\frac{\alpha_0}{1-\beta_1}+\alpha_1\sum_{k=0}^{\infty}\beta_1^{k}\,r_{t-1-k}^2.$$
<p>C'est un ARCH$(\infty)$ à coefficients $\alpha_1\beta_1^{k}$ qui décroissent géométriquement : $\beta_1$ fixe la persistance, $\alpha_1$ l'impact immédiat du choc, le tout avec seulement <strong>trois</strong> paramètres.</p>
<p><strong>Estimation (MLE gaussien conditionnel).</strong> Sous innovations gaussiennes, $r_t\mid\mathcal F_{t-1}\sim\mathcal N(0,\sigma_t^2)$. En conditionnant sur les premières observations, on maximise (à constantes près)</p>
$$\log L_c=-\tfrac12\sum_{t}\Big[\log\sigma_t^2+\frac{r_t^2}{\sigma_t^2}\Big],$$
<p>où $\sigma_t^2$ est donné par la récursion du modèle. La vraisemblance arbitre entre « ne pas gonfler $\sigma_t^2$ inutilement » (pénalité $\log\sigma_t^2$) et « expliquer un gros $r_t^2$ par un gros $\sigma_t^2$ » : c'est exactement du <strong>suivi de volatilité</strong>. Maximisation numérique sous $\alpha_0>0$ et $\sum\alpha+\sum\beta<1$.</p>
<p><strong>Diagnostics.</strong> Résidus standardisés $\tilde e_t=r_t/\hat\sigma_t$ : si le modèle est correct, $\tilde e_t$ <em>et</em> $\tilde e_t^2$ doivent ressembler à du bruit blanc (ACF/PACF plates) et le QQ-plot doit être à peu près droit ; on superpose les bandes $\pm1{,}96\,\hat\sigma_t$ sur $r_t$. <strong>ARMA–GARCH :</strong> comme un GARCH est lui-même un bruit blanc, il peut servir d'innovation à un ARMA, $X_t=\sum_{j}\phi_j X_{t-j}-\sum_{k}\theta_k r_{t-k}$ ($\theta_0=-1$). <strong>Limites :</strong> chocs positifs et négatifs traités symétriquement (pas d'effet de levier) ; dépendance qui décroît seulement géométriquement (extensions EGARCH, GJR-GARCH hors programme).</p>`}
  ],
  checks: [
    {q: String.raw`Quelle est l'idée centrale d'ARCH/GARCH face aux rendements financiers ?`, a: String.raw`Garder $r_t$ centré et non corrélé (bruit blanc), mais laisser la variance conditionnelle $\sigma_t^2$ varier dans le temps en fonction des carrés passés (et, pour GARCH, des variances passées). Cela reproduit le volatility clustering et les queues épaisses.`},
    {q: String.raw`ARCH/GARCH sont « bruit blanc mais dépendants » : qu'est-ce que cela signifie exactement ?`, a: String.raw`Non corrélés : $\operatorname{Corr}(r_{t+\tau},r_t)=0$ pour $\tau\ne0$ (corrélation linéaire plate). Mais pas indépendants : $\operatorname{Corr}(r_{t+\tau}^2,r_t^2)\ne0$ (forte dépendance non linéaire dans les carrés). « Bruit blanc » $\ne$ « sans structure ».`},
    {q: String.raw`Quels sont les deux seuils à ne pas confondre pour un ARCH(1) ?`, a: String.raw`Variance finie (stationnarité faible) : $\alpha_1<1$. $4^{\text e}$ moment fini (kurtosis, ACF des carrés bien définie) : $\alpha_1^2<\tfrac13$, soit $\alpha_1<1/\sqrt3\approx0{,}577$, strictement plus serré.`},
    {q: String.raw`Pourquoi préférer GARCH(1,1) à ARCH(p) en finance ?`, a: String.raw`En réinjectant $\beta_1\sigma_{t-1}^2$, GARCH(1,1) équivaut à un ARCH$(\infty)$ à coefficients $\alpha_1\beta_1^k$ : il encode toute une queue géométrique de dépendance avec seulement trois paramètres, donnant une volatilité persistante (souvent $\alpha_1+\beta_1\approx1$) de façon parcimonieuse.`},
    {q: String.raw`Comment ajuste-t-on et diagnostique-t-on un (G)ARCH ?`, a: String.raw`Ajustement : MLE gaussien conditionnel, $\log L_c=-\tfrac12\sum_t[\log\sigma_t^2+r_t^2/\sigma_t^2]$, maximisé sous $\alpha_0>0$ et $\sum\alpha+\sum\beta<1$. Diagnostic : résidus standardisés $\tilde e_t=r_t/\hat\sigma_t$ ; $\tilde e_t$ et $\tilde e_t^2$ doivent être du bruit blanc et le QQ-plot droit.`}
  ],
  test: [
    {type:'open', q: String.raw`Soit $r_t=\sigma_t\varepsilon_t$ avec $\sigma_t^2=\beta_0+\beta_1 r_{t-1}^2+\beta_2 r_{t-2}^2$ un ARCH(2), les $\beta_j\ge0$, et $\varepsilon_t$ de moyenne nulle et variance $1$, indépendant de $\mathcal F_{t-1}$. (a) Calculer $\mathbb{E}[r_t]$ par espérance itérée. (b) En supposant la stationnarité, trouver la variance marginale $\operatorname{Var}(r_t)$. (c) Donner les conditions nécessaires de stationnarité en termes des $\beta_j$.`,
     answer: String.raw`<div class="step"><strong>(a) Moyenne.</strong> $\sigma_t$ est $\mathcal F_{t-1}$-mesurable et $\varepsilon_t$ est indépendant de $\mathcal F_{t-1}$ avec $\mathbb{E}[\varepsilon_t]=0$, donc $\mathbb{E}[r_t\mid\mathcal F_{t-1}]=\sigma_t\,\mathbb{E}[\varepsilon_t]=0$. Par espérance itérée (tour) : $\mathbb{E}[r_t]=\mathbb{E}\big[\mathbb{E}[r_t\mid\mathcal F_{t-1}]\big]=0$.</div>
<div class="step"><strong>(b) Variance conditionnelle.</strong> Par la loi de la variance totale, avec $\operatorname{Var}(\varepsilon_t)=1$ : $\operatorname{Var}(r_t\mid\mathcal F_{t-1})=\sigma_t^2\operatorname{Var}(\varepsilon_t)=\beta_0+\beta_1 r_{t-1}^2+\beta_2 r_{t-2}^2$.</div>
<div class="step">Comme $\mathbb{E}[r_t\mid\mathcal F_{t-1}]=0$ (variance nulle), $\operatorname{Var}(r_t)=\mathbb{E}[\operatorname{Var}(r_t\mid\mathcal F_{t-1})]+\operatorname{Var}(\mathbb{E}[r_t\mid\mathcal F_{t-1}])=\mathbb{E}[\beta_0+\beta_1 r_{t-1}^2+\beta_2 r_{t-2}^2]+0$.</div>
<div class="step">Avec $\mathbb{E}[r_{t-j}^2]=\operatorname{Var}(r_{t-j})$ (moyenne nulle) et la stationnarité $\operatorname{Var}(r_t)=\operatorname{Var}(r_{t-1})=\operatorname{Var}(r_{t-2})=:v$ : $v=\beta_0+\beta_1 v+\beta_2 v$, d'où $(1-\beta_1-\beta_2)v=\beta_0$ et $$\operatorname{Var}(r_t)=\frac{\beta_0}{1-\beta_1-\beta_2}\quad(\beta_1+\beta_2<1).$$</div>
<div class="step"><strong>(c) Conditions.</strong> Pour une variance positive et finie : $\beta_0>0$ et $\beta_1+\beta_2<1$ (avec $\beta_1,\beta_2\ge0$). C'est le cas $p=2,q=0$ de la condition générale $\sum\alpha+\sum\beta<1$.</div>`, pts: 4},
    {type:'open', q: String.raw`Pour un GARCH$(m,r)$ à bruit gaussien, $\sigma_t^2=\alpha_0+\sum_{j=1}^{m}\alpha_j r_{t-j}^2+\sum_{j=1}^{r}\beta_j\sigma_{t-j}^2$ avec $\alpha_j,\beta_j\ge0$, démontrer que $\mathbb{E}[r_t]=0$ et $\operatorname{Corr}(r_{t+\tau},r_t)=0$ pour $\tau\ne0$ (le processus est un bruit blanc).`,
     answer: String.raw`<div class="step"><strong>Moyenne nulle.</strong> $\sigma_t$ est déterminé par le passé, donc $\mathcal F_{t-1}$-mesurable, et $\varepsilon_t$ est indépendant de $\mathcal F_{t-1}$ avec $\mathbb{E}[\varepsilon_t]=0$ : $$\mathbb{E}[r_t]=\mathbb{E}\big[\mathbb{E}[\sigma_t\varepsilon_t\mid\mathcal F_{t-1}]\big]=\mathbb{E}\big[\sigma_t\,\mathbb{E}[\varepsilon_t\mid\mathcal F_{t-1}]\big]=\mathbb{E}[\sigma_t\cdot0]=0.$$</div>
<div class="step"><strong>Non corrélation.</strong> Soit $\tau>0$. Comme $\mathbb{E}[r_t]=0$, $\operatorname{Cov}(r_{t+\tau},r_t)=\mathbb{E}[r_{t+\tau}r_t]$. Les facteurs $r_t$ et $\sigma_{t+\tau}$ sont tous deux $\mathcal F_{t+\tau-1}$-mesurables.</div>
<div class="step">Par espérance itérée, en conditionnant sur $\mathcal F_{t+\tau-1}$ et en sortant les facteurs mesurables : $$\mathbb{E}[r_{t+\tau}r_t]=\mathbb{E}\big[\mathbb{E}[\sigma_{t+\tau}\varepsilon_{t+\tau}r_t\mid\mathcal F_{t+\tau-1}]\big]=\mathbb{E}\big[r_t\,\sigma_{t+\tau}\,\mathbb{E}[\varepsilon_{t+\tau}\mid\mathcal F_{t+\tau-1}]\big]=\mathbb{E}[r_t\sigma_{t+\tau}\cdot0]=0.$$</div>
<div class="step">Par symétrie de l'autocovariance le résultat vaut aussi pour $\tau<0$. Donc $\operatorname{Cov}(r_{t+\tau},r_t)=0$ et $\operatorname{Corr}(r_{t+\tau},r_t)=0$ pour tout $\tau\ne0$ : GARCH est un bruit blanc (mais la dépendance subsiste dans les carrés).</div>`, pts: 4},
    {type:'open', q: String.raw`Pour un ARCH(1) avec $0<\alpha_0$ et $0<\alpha_1<1/\sqrt3$, montrer que $\operatorname{Corr}(r_{t+\tau}^2,r_t^2)=\alpha_1^{\lvert\tau\rvert}$ (décroissance géométrique de l'ACF des carrés).`,
     answer: String.raw`<div class="step"><strong>Covariance de départ.</strong> Soit $\tau>0$. Par stationnarité $\mathbb{E}[r_{t+\tau}^2]=\mathbb{E}[r_t^2]$, donc $$\operatorname{Cov}(r_{t+\tau}^2,r_t^2)=\mathbb{E}[r_{t+\tau}^2 r_t^2]-\big(\mathbb{E}[r_t^2]\big)^2.$$</div>
<div class="step"><strong>Conditionner sur $\mathcal F_{t+\tau-1}$.</strong> Les facteurs $r_t^2$ et $\sigma_{t+\tau}^2=\alpha_0+\alpha_1 r_{t+\tau-1}^2$ y sont mesurables, et $\mathbb{E}[\varepsilon_{t+\tau}^2\mid\mathcal F_{t+\tau-1}]=1$ : $$\mathbb{E}[r_{t+\tau}^2 r_t^2\mid\mathcal F_{t+\tau-1}]=r_t^2\,\sigma_{t+\tau}^2=r_t^2(\alpha_0+\alpha_1 r_{t+\tau-1}^2).$$</div>
<div class="step">En prenant l'espérance : $\mathbb{E}[r_{t+\tau}^2 r_t^2]=\alpha_0\,\mathbb{E}[r_t^2]+\alpha_1\,\mathbb{E}[r_{t+\tau-1}^2 r_t^2]$. Avec $C_\tau:=\operatorname{Cov}(r_{t+\tau}^2,r_t^2)$ et $\mathbb{E}[r_{t+\tau-1}^2 r_t^2]=C_{\tau-1}+(\mathbb{E}[r_t^2])^2$ : $$C_\tau=\alpha_1 C_{\tau-1}+\underbrace{\alpha_0\mathbb{E}[r_t^2]+\alpha_1(\mathbb{E}[r_t^2])^2-(\mathbb{E}[r_t^2])^2}_{=:R}.$$</div>
<div class="step"><strong>Le terme constant s'annule.</strong> Substituer $\mathbb{E}[r_t^2]=\operatorname{Var}(r_t)=\alpha_0/(1-\alpha_1)$ : $$R=\alpha_0\frac{\alpha_0}{1-\alpha_1}-(1-\alpha_1)\Big(\frac{\alpha_0}{1-\alpha_1}\Big)^2=\frac{\alpha_0^2}{1-\alpha_1}-\frac{\alpha_0^2}{1-\alpha_1}=0.$$</div>
<div class="step"><strong>Récursion et conclusion.</strong> Donc $C_\tau=\alpha_1 C_{\tau-1}$ ; en itérant $\tau$ fois depuis $C_0=\operatorname{Var}(r_t^2)$ : $C_\tau=\alpha_1^{\tau}\operatorname{Var}(r_t^2)$. D'où $\operatorname{Corr}(r_{t+\tau}^2,r_t^2)=C_\tau/\operatorname{Var}(r_t^2)=\alpha_1^{\tau}$, et par symétrie $\operatorname{Corr}(r_{t+\tau}^2,r_t^2)=\alpha_1^{\lvert\tau\rvert}$. (La condition $\alpha_1^2<1/3$ assure $\operatorname{Var}(r_t^2)<\infty$, donc la corrélation est bien définie.)</div>`, pts: 5},
    {type:'open', q: String.raw`Un GARCH$(1,1)$ ajusté aux log-returns du S&P 500 donne $\alpha_0=3{,}686\times10^{-6}$, $\alpha_1=0{,}1713$, $\beta_1=0{,}7897$. (a) Vérifier la stationnarité et calculer la variance et l'écart-type inconditionnels (volatilité journalière). (b) Le $4^{\text e}$ moment existe-t-il ? (c) Commenter la persistance $\alpha_1+\beta_1$.`,
     answer: String.raw`<div class="step"><strong>(a) Stationnarité.</strong> $\alpha_1+\beta_1=0{,}1713+0{,}7897=0{,}9610<1$ : le processus est faiblement stationnaire. Variance inconditionnelle : $$\operatorname{Var}(r_t)=\frac{\alpha_0}{1-\alpha_1-\beta_1}=\frac{3{,}686\times10^{-6}}{1-0{,}9610}=\frac{3{,}686\times10^{-6}}{0{,}0390}\approx9{,}45\times10^{-5}.$$</div>
<div class="step">Volatilité journalière implicite : $\sqrt{9{,}45\times10^{-5}}\approx9{,}72\times10^{-3}$, soit environ $0{,}97\%$ par jour — une valeur plausible pour des actions.</div>
<div class="step"><strong>(b) $4^{\text e}$ moment.</strong> Critère GARCH$(1,1)$ gaussien : $3\alpha_1^2+2\alpha_1\beta_1+\beta_1^2<1$. $$3(0{,}1713)^2+2(0{,}1713)(0{,}7897)+(0{,}7897)^2=0{,}0880+0{,}2706+0{,}6236=0{,}9822<1.$$ Le $4^{\text e}$ moment existe donc — mais de justesse : la proximité de $1$ signale des queues très lourdes.</div>
<div class="step"><strong>(c) Persistance.</strong> $\alpha_1+\beta_1=0{,}961$ est proche de $1$, la signature des ajustements GARCH financiers : les chocs de volatilité sont très persistants (décroissance géométrique lente de l'ACF des carrés), reproduisant de longs régimes calmes/turbulents, tout en restant stationnaire car la somme est strictement $<1$.</div>`, pts: 4},
    {type:'open', q: String.raw`Un ARCH(1) à innovations gaussiennes présente une kurtosis $\kappa=9$. (a) Trouver $\alpha_1$. (b) Quelle est la plus grande kurtosis qu'un ARCH(1) peut atteindre tout en gardant un $4^{\text e}$ moment fini ?`,
     answer: String.raw`<div class="step"><strong>(a) Équation de la kurtosis.</strong> On utilise $\kappa=\dfrac{3(1-\alpha_1^2)}{1-3\alpha_1^2}$ et on pose $\kappa=9$ : $$9(1-3\alpha_1^2)=3(1-\alpha_1^2)\;\Rightarrow\;9-27\alpha_1^2=3-3\alpha_1^2\;\Rightarrow\;6=24\alpha_1^2\;\Rightarrow\;\alpha_1^2=\tfrac14.$$</div>
<div class="step">On prend la racine positive : $\alpha_1=\tfrac12$. Vérification : $\alpha_1^2=1/4<1/3$, donc le $4^{\text e}$ moment est bien fini et la formule s'applique.</div>
<div class="step"><strong>(b) Borne supérieure.</strong> Quand $\alpha_1^2\uparrow1/3$ (soit $\alpha_1\uparrow1/\sqrt3$), le dénominateur $1-3\alpha_1^2\downarrow0^+$ tandis que le numérateur reste positif, donc $\kappa\to+\infty$. Il n'y a <strong>aucune</strong> borne supérieure finie sur la kurtosis tant qu'on garde un $4^{\text e}$ moment fini.</div>
<div class="step">À l'inverse, $\kappa\to3$ quand $\alpha_1\to0$ (retour à la variance constante), ce qui confirme $\kappa>3$ pour tout $\alpha_1>0$ : ARCH génère toujours de l'excès de kurtosis.</div>`, pts: 4},
    {type:'open', q: String.raw`Pour un ARCH(1) avec $\alpha_0=0{,}0001$, $\alpha_1=0{,}4$, le dernier rendement est $r_t=0{,}03$. (a) Donner $\sigma_{t+1}^2$ et un intervalle de prévision à $95\%$ pour $r_{t+1}$ (innovations gaussiennes). (b) Comparer à la bande inconditionnelle. (c) Le modèle est-il stationnaire au $4^{\text e}$ moment, et quelle est sa kurtosis ?`,
     answer: String.raw`<div class="step"><strong>(a) Prévision de variance à un pas.</strong> $\sigma_{t+1}^2=\alpha_0+\alpha_1 r_t^2=0{,}0001+0{,}4(0{,}03)^2=0{,}0001+0{,}4(0{,}0009)=0{,}0001+0{,}00036=0{,}00046$. Donc $\sigma_{t+1}=\sqrt{0{,}00046}\approx0{,}02145$.</div>
<div class="step">Comme $r_{t+1}\mid\mathcal F_t\sim\mathcal N(0,\sigma_{t+1}^2)$, l'intervalle conditionnel à $95\%$ est $0\pm1{,}96\,\sigma_{t+1}=\pm1{,}96(0{,}02145)\approx\pm0{,}0421$.</div>
<div class="step"><strong>(b) Bande inconditionnelle.</strong> $\operatorname{Var}(r_t)=\alpha_0/(1-\alpha_1)=0{,}0001/0{,}6\approx1{,}667\times10^{-4}$, donc $\sigma\approx0{,}01291$ et la bande inconditionnelle est $\pm1{,}96(0{,}01291)\approx\pm0{,}0253$. Après le gros choc $r_t=0{,}03$, la bande conditionnelle ($\pm0{,}042$) est nettement <strong>plus large</strong> que l'inconditionnelle ($\pm0{,}025$) : le modèle a relevé sa prévision de volatilité — c'est exactement le clustering.</div>
<div class="step"><strong>(c) Stationnarité au $4^{\text e}$ moment.</strong> Variance : $\alpha_1=0{,}4<1$ (ok). $4^{\text e}$ moment : $\alpha_1^2=0{,}16<1/3\approx0{,}333$ (ok), donc la kurtosis est finie : $$\kappa=\frac{3(1-\alpha_1^2)}{1-3\alpha_1^2}=\frac{3(1-0{,}16)}{1-0{,}48}=\frac{3(0{,}84)}{0{,}52}=\frac{2{,}52}{0{,}52}\approx4{,}85>3.$$</div>`, pts: 4}
  ]
},
