{
  n: 9,
  title: String.raw`Séries multivariées & VAR`,
  intro: String.raw`On passe du scalaire au vecteur : matrice d'autocovariance (attention, le décalage est dans le PREMIER argument !), spectre matriciel et cohérence, puis le modèle VAR avec son astuce reine — « tout VAR($p$) est un VAR(1) » via la forme compagnon.`,
  sections: [
    {h: String.raw`Du scalaire au vecteur : ACVS matricielle`, body: String.raw`<p>On observe désormais plusieurs séries à la fois (un panier d'actions Apple / Nasdaq-100 / S&P 500, ou la position et la température d'une bouée dérivante). Chaque $X_t=(X_t^{(1)},\dots,X_t^{(d)})^{\top}\in\mathbb{R}^d$ est un <strong>vecteur</strong>. Le processus est <strong>stationnaire d'ordre 2</strong> (<em>second-order stationary</em>) si la moyenne est constante, $\operatorname{tr}(\operatorname{Var}(X_t))<\infty$, et $\operatorname{Cov}(X_{t+\tau},X_t)$ ne dépend que de $\tau$. De façon équivalente : chaque marginale est stationnaire <em>et</em> chaque paire a une covariance croisée invariante par décalage.</p>
<p>La structure d'ordre 2 devient <strong>matricielle</strong>. La <strong>matrice d'autocovariance</strong> (<em>matrix ACVS</em>) est</p>
$$\Gamma_\tau=\operatorname{Cov}(X_{t+\tau},X_t),\qquad \gamma_\tau^{(j,k)}=\operatorname{Cov}\!\big(X_{t+\tau}^{(j)},X_t^{(k)}\big).$$
<p><strong>Le décalage $\tau$ est dans le PREMIER argument.</strong> Sur la diagonale ($j=k$) on retrouve l'ACVS usuelle de la marginale. Hors diagonale ($j\ne k$) c'est la <strong>covariance croisée</strong> (<em>cross-covariance</em>, CCS), qui encode les relations d'avance/retard entre canaux. La <strong>corrélation croisée</strong> (<em>cross-correlation</em>) est $\rho_\tau^{(j,k)}=\gamma_\tau^{(j,k)}/\sqrt{\gamma_0^{(j,j)}\gamma_0^{(k,k)}}$.</p>
<p><strong>Symétrie clé.</strong> En scalaire $\gamma_\tau=\gamma_{-\tau}$ (paire) et l'ordre des arguments est sans importance. En multivarié il devient crucial :</p>
$$\gamma_\tau^{(j,k)}=\gamma_{-\tau}^{(k,j)}\ \Longleftrightarrow\ \Gamma_{-\tau}=\Gamma_\tau^{\top}.$$
<p>La diagonale reste paire, mais une covariance croisée n'a aucune raison d'égaler $\gamma_{-\tau}^{(j,k)}$ : c'est cette asymétrie qui code les relations avance-retard. <strong>Erreur classique :</strong> oublier d'échanger les indices $(j,k)\to(k,j)$ en retournant le signe de $\tau$. La suite $\{\Gamma_\tau\}$ est aussi semi-définie positive : $\sum_{j,k} a_j^{\top}\Gamma_{k-j}a_k\ge0$ (c'est $\operatorname{Var}(\sum_j a_j^{\top}X_{t_j})\ge0$).</p>`},
    {h: String.raw`Bruit blanc multivarié, spectre matriciel et cohérence`, body: String.raw`<p><strong>Bruit blanc multivarié</strong> (<em>multivariate white noise</em>) : $\{\varepsilon_t\}\sim\mathrm{WN}(0,\Sigma)$ ssi stationnaire, de moyenne nulle, avec $\Gamma_\tau^{(\varepsilon)}=\Sigma$ si $\tau=0$ et $0$ sinon. Les composantes sont décorrélées <strong>dans le temps</strong>, mais peuvent être corrélées <strong>au même instant</strong> (termes hors diagonale de $\Sigma$). On suppose parfois $\Sigma$ diagonale — c'est une hypothèse <em>en plus</em>, pas la définition.</p>
<p>Si toutes les covariances croisées sont sommables ($\ell^1$), la <strong>matrice de densité spectrale</strong> (<em>spectral density matrix</em>) est</p>
$$S(f)=\sum_{\tau\in\mathbb{Z}}\Gamma_\tau\,e^{-2\pi i\tau f},\qquad \Gamma_\tau=\int_{-1/2}^{1/2}S(f)\,e^{2\pi if\tau}\,df.$$
<p>Sur la diagonale : la densité spectrale usuelle $S_{j,j}(f)\in\mathbb{R}$. Hors diagonale : le <strong>spectre croisé</strong> (<em>cross-spectrum</em>) $S_{j,k}(f)\in\mathbb{C}$, complexe en général. La symétrie de l'ACVS donne $S(f)=S(f)^{H}$ (hermitienne), $S(f)=S(-f)^{\top}$, et $S(f)\succeq0$ pour tout $f$.</p>
<p>La <strong>cohérence</strong> (<em>coherence</em>) est la « corrélation » fréquence par fréquence entre canaux :</p>
$$r_{j,k}(f)=\frac{S_{j,k}(f)}{\sqrt{S_{j,j}(f)\,S_{k,k}(f)}}\in\mathbb{C}.$$
<p>On regarde son <strong>module</strong> $\lvert r_{j,k}(f)\rvert$ (force de l'association, $\lvert r\rvert^2\in[0,1]$) et sa <strong>phase</strong> $\arg r_{j,k}(f)$ (le « signe » / l'angle d'avance-retard). Le <strong>théorème de représentation spectrale multivariée</strong> (analogue vectoriel de Cramér) écrit $X_t=\mu+\int_{-1/2}^{1/2}e^{2\pi ift}\,dZ(f)$ avec $\operatorname{Var}(dZ(f))=S(f)\,df$ et $\operatorname{Cov}(dZ(f),dZ(f'))=0$ pour $f\ne f'$ : la cohérence est littéralement la corrélation des incréments $dZ_j(f),dZ_k(f)$.</p>`},
    {h: String.raw`Signatures : bruit commun et retard pur`, body: String.raw`<p>Deux mécanismes reviennent sans cesse dans les exercices.</p>
<p><strong>Bruit commun (corrélation contemporaine).</strong> Si on ajoute le <em>même</em> bruit scalaire $\phi_t$ (variance $\sigma_\phi^2$) aux deux canaux, $Y_t=X_t+\phi_t\mathbf{1}$ avec $\mathbf{1}=(1,1)^{\top}$, alors</p>
$$\Gamma_\tau^{(Y)}=\Gamma_\tau^{(X)}+\sigma_\phi^2\,\delta_{\tau,0}\,\mathbf{1}\mathbf{1}^{\top},\qquad \mathbf{1}\mathbf{1}^{\top}=\begin{pmatrix}1&1\\1&1\end{pmatrix}.$$
<p>L'indépendance tue les termes croisés $X$–$\phi$ et $\operatorname{Cov}(\phi_{t+\tau},\phi_t)=\sigma_\phi^2\delta_{\tau,0}$ s'ajoute à <em>chaque</em> entrée. Un choc commun crée donc de la corrélation au <strong>lag $0$ seulement</strong>, indépendamment de la structure de $X$. C'est le mécanisme du « tout bouge ensemble ».</p>
<p><strong>Retard pur (phase linéaire).</strong> Si $X_t=(Y_t,Y_{t-\nu})^{\top}$ pour $\{Y_t\}$ stationnaire, alors $\gamma_\tau^{(1,2)}=\operatorname{Cov}(Y_{t+\tau},Y_{t-\nu})=\gamma_{\tau+\nu}^{(Y)}$, donc</p>
$$S_{1,1}(f)=S_{2,2}(f)=S_Y(f),\qquad S_{1,2}(f)=S_Y(f)\,e^{2\pi if\nu},\qquad r_{1,2}(f)=e^{2\pi if\nu}.$$
<p>Cohérence de module $1$ et phase $2\pi\nu f$, <strong>linéaire en $f$</strong>. L'intuition (mnémonique) : un décalage de $\nu$ échantillons dans le temps $=$ un facteur $e^{\pm2\pi i\nu f}$ dans le spectre $=$ une phase linéaire $\pm2\pi\nu f$. Une cohérence de module $1$ avec phase qui croît proportionnellement à $f$ est la signature manuel d'une avance/retard de $\nu$ entre canaux.</p>`},
    {h: String.raw`Le modèle VAR($p$) et la forme compagnon`, body: String.raw`<p>Avec $\{\varepsilon_t\}\sim\mathrm{WN}(0,\Sigma)$, le <strong>vecteur autorégressif</strong> (<em>vector autoregression</em>) d'ordre $p$ s'écrit</p>
$$X_t=\Phi_1 X_{t-1}+\cdots+\Phi_p X_{t-p}+\varepsilon_t,\qquad \Phi(B)X_t=\varepsilon_t,$$
<p>où $\Phi(z)=I_d-\sum_{j=1}^p\Phi_j z^j$ et $\Phi_j\in\mathbb{R}^{d\times d}$, $\Phi_p\ne0$. Les <strong>mêmes régresseurs</strong> (les passés du vecteur entier) apparaissent dans chaque équation composante ; les entrées hors diagonale des $\Phi_j$ sont exactement la dynamique inter-canaux.</p>
<p><strong>Tout est un VAR(1).</strong> En empilant $Y_t=(X_t^{\top},\dots,X_{t-p+1}^{\top})^{\top}\in\mathbb{R}^{dp}$, le VAR($p$) devient un VAR(1) $Y_t=F\,Y_{t-1}+U_t$ avec la matrice compagnon (<em>companion form</em>)</p>
$$F=\begin{pmatrix}\Phi_1 & \Phi_2 & \cdots & \Phi_{p-1} & \Phi_p\\ I_d & 0 & \cdots & 0 & 0\\ 0 & I_d & & & \vdots\\ \vdots & & \ddots & & \vdots\\ 0 & \cdots & & I_d & 0\end{pmatrix},\qquad U_t=\begin{pmatrix}\varepsilon_t\\0\\\vdots\\0\end{pmatrix}.$$
<p>La ligne du haut porte la vraie équation VAR($p$) ; les blocs $I_d$ du bas ne font que décaler la pile. On récupère $X_t=G\,Y_t$ avec $G=(I_d\ 0\ \cdots\ 0)$. On prouve donc <em>une seule fois</em> la théorie VAR(1) (stabilité, MA($\infty$), covariances) puis on la ré-applique pour tout $p$.</p>
<p><strong>Stabilité.</strong> Le VAR est <strong>stable</strong> ssi les racines de $\det(I_d-\Phi_1 z-\cdots-\Phi_p z^p)=0$ sont toutes <em>hors</em> du cercle unité ($\lvert z\rvert>1$) ; de façon équivalente ssi $F$ a toutes ses valeurs propres $\lvert\lambda\rvert<1$. Stabilité $\Rightarrow$ stationnarité (pas la réciproque). <strong>Raccourci VAR(1) :</strong> $\det(I_d-\Phi_1 z)=0\iff z=1/\lambda_i(\Phi_1)$, il suffit de $\lvert\lambda_i(\Phi_1)\rvert<1$ (rayon spectral $<1$) ; pour $\Phi_1$ triangulaire, ce sont les éléments diagonaux. Sanity-check : $\det(\cdot)\rvert_{z=0}=\det I_d=1$ toujours.</p>`},
    {h: String.raw`MA($\infty$), covariances et Yule–Walker`, body: String.raw`<p>Si le VAR(1) $X_t=\Phi_1 X_{t-1}+\varepsilon_t$ est stable, la substitution répétée ($\Phi_1^j\to0$) donne la <strong>MA($\infty$)</strong> causale (filtre géométrique matriciel du bruit)</p>
$$X_t=\sum_{j\ge0}\Phi_1^{\,j}\,\varepsilon_{t-j}.$$
<p>En injectant dans $\operatorname{Cov}(X_{t+\tau},X_t)$, seuls survivent les couples de temps de bruit égaux ($j=k+\tau$), d'où pour $\tau\ge0$</p>
$$\Gamma_\tau=\sum_{k\ge0}\Phi_1^{\,k+\tau}\,\Sigma\,(\Phi_1^{\,k})^{\top}.$$
<p>En $\tau=0$ : $\Gamma_0=\Phi_1\Gamma_0\Phi_1^{\top}+\Sigma$, l'<strong>équation de Lyapunov</strong> (vectorisable : $\operatorname{vec}\Gamma_0=(I-\Phi_1\otimes\Phi_1)^{-1}\operatorname{vec}\Sigma$). Si $\Phi_1$ et $\Sigma$ sont diagonales, tout se découple en $d$ AR(1) scalaires : $\Gamma_0^{(j,j)}=\sigma_j^2/(1-\phi_j^2)$, spectre croisé nul, cohérence nulle partout. Pour un VAR($p$) : même formule avec $F,\Sigma_U$, puis projection $\Gamma_\tau^{(X)}=G(\sum_k F^{k+\tau}\Sigma_U (F^k)^{\top})G^{\top}$.</p>
<p><strong>Équations de Yule–Walker (VAR).</strong> En multipliant l'équation VAR par $X_t^{\top}$ et en prenant l'espérance, le terme de bruit n'apparaît qu'en $\tau=0$ (car $X_t$ ne dépend que de $\varepsilon_s$, $s\le t$, donc $\operatorname{Cov}(\varepsilon_{t+\tau},X_t)=0$ pour $\tau>0$). Pour $\tau\ge0$ :</p>
$$\Gamma_\tau=\Phi_1\Gamma_{\tau-1}+\cdots+\Phi_p\Gamma_{\tau-p}+\delta_{\tau,0}\,\Sigma.$$
<p>On résout les $p+1$ premières pour $\Gamma_0,\dots,\Gamma_p$, puis la récursion donne tout $\Gamma_\tau$. <strong>Attention au transpose :</strong> un terme $\Phi_i\Gamma_{-s}$ signifie $\Phi_i\Gamma_s^{\top}$. À l'envers, ces équations estiment les $\Phi_j$ à partir des covariances empiriques (ajustement d'un VAR).</p>`}
  ],
  checks: [
    {q: String.raw`Pourquoi le décalage $\tau$ doit-il être placé dans le premier argument de $\operatorname{Cov}$ ?`, a: String.raw`En scalaire $\gamma_\tau=\gamma_{-\tau}$, l'ordre est sans importance. En multivarié c'est lui qui fixe la convention $\Gamma_{-\tau}=\Gamma_\tau^{\top}$ et $\gamma_\tau^{(j,k)}=\gamma_{-\tau}^{(k,j)}$ : il faut toujours échanger les indices $(j,k)$ en retournant le signe de $\tau$.`},
    {q: String.raw`Dans un bruit blanc $\mathrm{WN}(0,\Sigma)$, les composantes peuvent-elles être corrélées ?`, a: String.raw`Oui, mais seulement <strong>au même instant</strong> ($\tau=0$, via les termes hors diagonale de $\Sigma$). À travers le temps ($\tau\ne0$) elles sont décorrélées : $\Gamma_\tau^{(\varepsilon)}=0$. $\Sigma$ diagonale est une hypothèse en plus.`},
    {q: String.raw`Quelle est la signature spectrale d'un retard pur de $\nu$ échantillons entre deux canaux ?`, a: String.raw`Cohérence de module $1$ et phase linéaire $2\pi\nu f$ : $r_{1,2}(f)=e^{2\pi if\nu}$. Un décalage temporel de $\nu$ $=$ un facteur $e^{2\pi if\nu}$ dans le spectre croisé.`},
    {q: String.raw`Comment teste-t-on la stabilité d'un VAR(1) sans calculer de racines de polynôme ?`, a: String.raw`On regarde directement les valeurs propres de $\Phi_1$ : stable ssi $\lvert\lambda_i(\Phi_1)\rvert<1$ (rayon spectral $<1$). Pour $\Phi_1$ triangulaire ce sont les éléments diagonaux. C'est équivalent à « racines de $\det(I_d-\Phi_1 z)$ hors du cercle unité ».`},
    {q: String.raw`Dans la dérivation de Yule–Walker, pourquoi le terme $\Sigma$ n'apparaît-il qu'en $\tau=0$ ?`, a: String.raw`$X_t$ est bâti sur $\varepsilon_t,\varepsilon_{t-1},\dots$ Pour $\tau>0$, $\varepsilon_{t+\tau}$ est dans le futur de $X_t$, donc $\operatorname{Cov}(\varepsilon_{t+\tau},X_t)=0$. Seul $\tau=0$ donne $\operatorname{Cov}(\varepsilon_t,X_t)=\Sigma$.`}
  ],
  test: [
    {type:'open', q: String.raw`Soit $Y_t=(Y_t^{(1)},Y_t^{(2)})^{\top}$ avec $Y_t^{(j)}=X_t^{(j)}+\varepsilon_t$ ($j=1,2$), où $X^{(1)},X^{(2)},\varepsilon$ sont mutuellement indépendants et $\{\varepsilon_t\}$ est un bruit blanc scalaire. On pose $\sigma_j^2=\operatorname{Var}(X_t^{(j)})$, $\sigma_\varepsilon^2=\operatorname{Var}(\varepsilon_t)$ et $\tilde\gamma_\tau^{(1,2)}=\operatorname{Cov}(X_{t+\tau}^{(1)},X_t^{(2)})$. Calculez la corrélation croisée $\rho_\tau^{(1,2)}$ entre $\{Y^{(1)}\}$ et $\{Y^{(2)}\}$ à tous les décalages.`,
     answer: String.raw`<div class="step"><strong>Covariance croisée.</strong> Le <em>même</em> bruit $\varepsilon_t$ est ajouté aux deux canaux. On développe par bilinéarité : $\gamma_\tau^{(1,2)}=\operatorname{Cov}(Y_{t+\tau}^{(1)},Y_t^{(2)})=\operatorname{Cov}(X_{t+\tau}^{(1)},X_t^{(2)})+\operatorname{Cov}(X_{t+\tau}^{(1)},\varepsilon_t)+\operatorname{Cov}(\varepsilon_{t+\tau},X_t^{(2)})+\operatorname{Cov}(\varepsilon_{t+\tau},\varepsilon_t)$.</div>
<div class="step"><strong>On tue les termes croisés.</strong> Par indépendance de $X$ et $\varepsilon$, les deux termes du milieu sont nuls. Et $\operatorname{Cov}(\varepsilon_{t+\tau},\varepsilon_t)=\sigma_\varepsilon^2\delta_{\tau,0}$. Donc $\gamma_\tau^{(1,2)}=\tilde\gamma_0^{(1,2)}+\sigma_\varepsilon^2$ si $\tau=0$, et $\gamma_\tau^{(1,2)}=\tilde\gamma_\tau^{(1,2)}$ si $\tau\ne0$.</div>
<div class="step"><strong>Variances marginales.</strong> $\gamma_0^{(1,1)}=\operatorname{Var}(X_t^{(1)})+\operatorname{Var}(\varepsilon_t)=\sigma_1^2+\sigma_\varepsilon^2$ et de même $\gamma_0^{(2,2)}=\sigma_2^2+\sigma_\varepsilon^2$.</div>
<div class="step"><strong>Corrélation croisée.</strong> $$\rho_\tau^{(1,2)}=\frac{\gamma_\tau^{(1,2)}}{\sqrt{(\sigma_1^2+\sigma_\varepsilon^2)(\sigma_2^2+\sigma_\varepsilon^2)}}=\begin{cases}\dfrac{\tilde\gamma_0^{(1,2)}+\sigma_\varepsilon^2}{\sqrt{(\sigma_1^2+\sigma_\varepsilon^2)(\sigma_2^2+\sigma_\varepsilon^2)}} & \tau=0,\\[8pt] \dfrac{\tilde\gamma_\tau^{(1,2)}}{\sqrt{(\sigma_1^2+\sigma_\varepsilon^2)(\sigma_2^2+\sigma_\varepsilon^2)}} & \tau\ne0.\end{cases}$$ Le bruit partagé injecte une corrélation supplémentaire ($+\sigma_\varepsilon^2$) <strong>uniquement au lag $0$</strong> : mécanisme de la corrélation contemporaine.</div>`, pts: 3},
    {type:'open', q: String.raw`Processus de retard : pour $\alpha>0$, $\nu\in\mathbb{Z}$, on a $X_t^{(1)}=\alpha X_{t-\nu}^{(2)}+\varepsilon_t$ où $\{\varepsilon_t\}$ est un bruit blanc (variance $\sigma_\varepsilon^2$) et $\{X_t^{(2)}\}$ est stationnaire et décorrélé de $\{\varepsilon_t\}$ à tous les lags. (a) Calculez la corrélation croisée entre $\{X^{(1)}\}$ et $\{X^{(2)}\}$ à tous les lags. (b) Calculez le spectre croisé $S_{1,2}(f)$ et donnez son amplitude et sa phase.`,
     answer: String.raw`<div class="step"><strong>(a) Covariance croisée.</strong> Par indépendance de $X^{(2)}$ et $\varepsilon$ : $\gamma_\tau^{(1,2)}=\operatorname{Cov}(X_{t+\tau}^{(1)},X_t^{(2)})=\alpha\operatorname{Cov}(X_{t+\tau-\nu}^{(2)},X_t^{(2)})+\operatorname{Cov}(\varepsilon_{t+\tau},X_t^{(2)})=\alpha\,\gamma_{\tau-\nu}^{(2,2)}$ (le second terme est nul).</div>
<div class="step"><strong>Variances marginales.</strong> $\gamma_0^{(2,2)}=\sigma_2^2$ et $\gamma_0^{(1,1)}=\operatorname{Var}(\alpha X_{t-\nu}^{(2)}+\varepsilon_t)=\alpha^2\sigma_2^2+\sigma_\varepsilon^2$.</div>
<div class="step"><strong>Corrélation croisée.</strong> $$\rho_\tau^{(1,2)}=\frac{\alpha\,\gamma_{\tau-\nu}^{(2,2)}}{\sqrt{\alpha^2\sigma_2^2+\sigma_\varepsilon^2}\,\sqrt{\sigma_2^2}}=\frac{\rho_{\tau-\nu}^{(2,2)}}{\sqrt{1+\sigma_\varepsilon^2/(\alpha\sigma_2)^2}}.$$ C'est l'autocorrélation de $X^{(2)}$ décalée de $\nu$ et atténuée par le bruit.</div>
<div class="step"><strong>(b) Spectre croisé.</strong> On Fourier-transforme et on réindexe la somme ($\tau\to\tau+\nu$) pour sortir le facteur de phase : $$S_{1,2}(f)=\sum_{\tau}\gamma_\tau^{(1,2)}e^{-2\pi if\tau}=\alpha\sum_{\tau}\gamma_{\tau-\nu}^{(2,2)}e^{-2\pi if\tau}=\alpha e^{-2\pi if\nu}\sum_{\tau}\gamma_\tau^{(2,2)}e^{-2\pi if\tau}=\alpha\,S_{2,2}(f)\,e^{-2\pi if\nu}.$$</div>
<div class="step"><strong>Amplitude et phase.</strong> Comme $S_{2,2}(f)\ge0$ est réel (densité spectrale de $X^{(2)}$), l'amplitude est $\lvert S_{1,2}(f)\rvert=\alpha\,S_{2,2}(f)$ (le spectre de $X^{(2)}$ multiplié par $\alpha$) et la phase est $\arg S_{1,2}(f)=-2\pi\nu f$, linéaire en $f$ de pente $-2\pi\nu$ : la signature du retard.</div>`, pts: 4},
    {type:'open', q: String.raw`Énoncez le critère de stabilité d'un VAR($p$) avec ses deux formulations équivalentes, puis appliquez-le au VAR(2) bivarié $X_t=\Phi_1 X_{t-1}+\Phi_2 X_{t-2}+\varepsilon_t$ avec $\Phi_1=\begin{pmatrix}0.5&0.1\\0.4&0.5\end{pmatrix}$, $\Phi_2=\begin{pmatrix}0&0\\0.25&0\end{pmatrix}$ : formez le polynôme caractéristique inverse, donnez ses racines (et leurs modules) et concluez.`,
     answer: String.raw`<div class="step"><strong>Critère.</strong> Un VAR($p$) est stable ssi les racines de $\det(I_d-\Phi_1 z-\cdots-\Phi_p z^p)=0$ sont toutes strictement hors du cercle unité ($\lvert z\rvert>1$) ; de façon équivalente ssi la matrice compagnon $F$ a toutes ses valeurs propres de module $<1$. Stabilité $\Rightarrow$ stationnarité.</div>
<div class="step"><strong>Matrice $M(z)=I_2-\Phi_1 z-\Phi_2 z^2$.</strong> $$M(z)=\begin{pmatrix}1-0.5z & -0.1z\\ -0.4z-0.25z^2 & 1-0.5z\end{pmatrix}.$$</div>
<div class="step"><strong>Déterminant.</strong> $\det M(z)=(1-0.5z)^2-(-0.1z)(-0.4z-0.25z^2)=(1-z+0.25z^2)-(0.04z^2+0.025z^3)=1-z+0.21z^2-0.025z^3$. Sanity-check : $\det M(0)=1=\det I_2$.</div>
<div class="step"><strong>Racines.</strong> Les racines de $1-z+0.21z^2-0.025z^3=0$ sont $z_1=1.3$, $z_2=3.55+4.26i$, $z_3=3.55-4.26i$.</div>
<div class="step"><strong>Modules et conclusion.</strong> $\lvert z_1\rvert=1.3>1$ et $\lvert z_2\rvert=\lvert z_3\rvert=\sqrt{3.55^2+4.26^2}=\sqrt{12.60+18.15}=\sqrt{30.75}\approx5.545>1$. Les trois racines sont strictement hors du cercle unité : le VAR(2) est <strong>stable</strong> (donc stationnaire).</div>`, pts: 4},
    {type:'open', q: String.raw`VAR(1) trivarié triangulaire : $X_t=\Phi_1 X_{t-1}+\varepsilon_t$ avec $\Phi_1=\begin{pmatrix}0.5&0&0\\0.1&0.1&0.3\\0&0.2&0.3\end{pmatrix}$. Factorisez le polynôme caractéristique inverse et décidez de la stabilité (utilisez aussi le raccourci par valeurs propres).`,
     answer: String.raw`<div class="step"><strong>Mise en place.</strong> $$I_3-\Phi_1 z=\begin{pmatrix}1-0.5z & 0 & 0\\ -0.1z & 1-0.1z & -0.3z\\ 0 & -0.2z & 1-0.3z\end{pmatrix}.$$ La première ligne n'a qu'une entrée non nulle, on développe le long de cette ligne.</div>
<div class="step"><strong>Développement.</strong> $\det(I_3-\Phi_1 z)=(1-0.5z)\det\begin{pmatrix}1-0.1z & -0.3z\\ -0.2z & 1-0.3z\end{pmatrix}=(1-0.5z)\big[(1-0.1z)(1-0.3z)-0.06z^2\big]$.</div>
<div class="step"><strong>Facteur quadratique.</strong> $(1-0.1z)(1-0.3z)=1-0.4z+0.03z^2$, donc $[\cdots]=1-0.4z+0.03z^2-0.06z^2=1-0.4z-0.03z^2$. Ainsi $\det(I_3-\Phi_1 z)=(1-0.5z)(1-0.4z-0.03z^2)$.</div>
<div class="step"><strong>Racines.</strong> Premier facteur : $z_1=2$. Quadratique $0.03z^2+0.4z-1=0$ : $z=\dfrac{-0.4\pm\sqrt{0.16+0.12}}{0.06}=\dfrac{-0.4\pm\sqrt{0.28}}{0.06}$, soit $z_2\approx2.153$ et $z_3\approx-15.486$. Tous vérifient $\lvert z\rvert>1$.</div>
<div class="step"><strong>Conclusion + raccourci.</strong> Le VAR(1) est <strong>stable</strong>. Équivalent : $\Phi_1$ est bloc triangulaire inférieur, de valeurs propres $0.5$ et celles de $\begin{pmatrix}0.1&0.3\\0.2&0.3\end{pmatrix}$ (trace $0.4$, déterminant $0.03-0.06=-0.03$), soit $\approx0.465$ et $\approx-0.065$ ; tous de module $<1$.</div>`, pts: 4},
    {type:'open', q: String.raw`VAR(1) diagonal : $X_t=\Phi_1 X_{t-1}+\varepsilon_t$ avec $\Phi_1=\begin{pmatrix}0.5&0\\0&0.3\end{pmatrix}$ et $\{\varepsilon_t\}\sim\mathrm{WN}(0,I_2)$. (a) Écrivez la forme MA($\infty$). (b) Calculez la covariance stationnaire $\Gamma_0$ et la matrice de lag $1$, $\Gamma_1$. (c) Quelle est la cohérence entre les deux canaux ?`,
     answer: String.raw`<div class="step"><strong>(a) MA($\infty$).</strong> $\Phi_1=\operatorname{diag}(0.5,0.3)$ a un rayon spectral $0.5<1$ : le VAR est stable et $X_t=\sum_{j\ge0}\Phi_1^j\varepsilon_{t-j}$ avec $\Phi_1^j=\operatorname{diag}(0.5^j,0.3^j)$.</div>
<div class="step"><strong>(b) $\Gamma_0$ par la formule de covariance.</strong> Avec $\Sigma=I_2$ : $\Gamma_0=\sum_{k\ge0}\Phi_1^k(\Phi_1^k)^{\top}=\sum_{k\ge0}\operatorname{diag}(0.25^k,0.09^k)$. Sommes géométriques : $\sum 0.25^k=\frac{1}{1-0.25}=\frac{4}{3}$, $\sum 0.09^k=\frac{1}{1-0.09}=\frac{100}{91}$. Donc $\Gamma_0=\operatorname{diag}(\tfrac{4}{3},\tfrac{100}{91})\approx\operatorname{diag}(1.333,1.099)$.</div>
<div class="step"><strong>Vérification Lyapunov.</strong> $\Gamma_0=\Phi_1\Gamma_0\Phi_1^{\top}+I_2$ donne composante par composante $g_{jj}=\phi_j^2 g_{jj}+1$, soit $g_{jj}=1/(1-\phi_j^2)$ : on retrouve $4/3$ et $100/91$.</div>
<div class="step"><strong>$\Gamma_1$ par Yule–Walker.</strong> $\Gamma_1=\Phi_1\Gamma_0=\operatorname{diag}(0.5,0.3)\operatorname{diag}(\tfrac{4}{3},\tfrac{100}{91})=\operatorname{diag}(\tfrac{2}{3},\tfrac{30}{91})\approx\operatorname{diag}(0.667,0.330)$.</div>
<div class="step"><strong>(c) Cohérence.</strong> $\Phi_1$ et $\Sigma$ étant diagonales, toutes les entrées hors diagonale de $\Gamma_\tau$ sont nulles pour tout $\tau$ : les deux canaux sont des AR(1) indépendants. Donc $S_{1,2}(f)\equiv0$ et la cohérence $r_{1,2}(f)=0$ à toutes les fréquences (canaux complètement découplés).</div>`, pts: 4},
    {type:'open', q: String.raw`VAR(1) bivarié $X_t=\Phi_1 X_{t-1}+\varepsilon_t$ avec $\Phi_1=\begin{pmatrix}0.6&0.2\\0.1&0.5\end{pmatrix}$, $\{\varepsilon_t\}\sim\mathrm{WN}(0,I_2)$. (a) Vérifiez la stabilité via le polynôme caractéristique inverse. (b) Exprimez $\Gamma_2$ en fonction de $\Gamma_0$ via Yule–Walker (donnez $\Phi_1^2$ explicitement). (c) Donnez $\Gamma_{-1}$ en fonction de $\Gamma_1$ et expliquez pourquoi $\Gamma_{-1}\ne\Gamma_1$ en général.`,
     answer: String.raw`<div class="step"><strong>(a) Polynôme inverse.</strong> $\det(I_2-\Phi_1 z)=(1-0.6z)(1-0.5z)-(0.2z)(0.1z)=1-1.1z+0.30z^2-0.02z^2=1-1.1z+0.28z^2$.</div>
<div class="step"><strong>Racines.</strong> $0.28z^2-1.1z+1=0$ : $z=\dfrac{1.1\pm\sqrt{1.21-1.12}}{0.56}=\dfrac{1.1\pm0.3}{0.56}$, soit $z_1=\tfrac{1.4}{0.56}=2.5$ et $z_2=\tfrac{0.8}{0.56}=\tfrac{10}{7}\approx1.43$. Les deux ont un module $>1$ : <strong>stable</strong>. (Équivalent : $\Phi_1$ a trace $1.1$, déterminant $0.28$, valeurs propres $0.7$ et $0.4$, toutes dans le cercle unité.)</div>
<div class="step"><strong>(b) Yule–Walker.</strong> Pour un VAR(1), $\Gamma_\tau=\Phi_1\Gamma_{\tau-1}$ pour $\tau\ge1$. En itérant : $\Gamma_1=\Phi_1\Gamma_0$, $\Gamma_2=\Phi_1\Gamma_1=\Phi_1^2\Gamma_0$.</div>
<div class="step"><strong>$\Phi_1^2$.</strong> $\Phi_1^2=\begin{pmatrix}0.6\cdot0.6+0.2\cdot0.1 & 0.6\cdot0.2+0.2\cdot0.5\\ 0.1\cdot0.6+0.5\cdot0.1 & 0.1\cdot0.2+0.5\cdot0.5\end{pmatrix}=\begin{pmatrix}0.38&0.22\\0.11&0.27\end{pmatrix}$, donc $\Gamma_2=\begin{pmatrix}0.38&0.22\\0.11&0.27\end{pmatrix}\Gamma_0$.</div>
<div class="step"><strong>(c) $\Gamma_{-1}$.</strong> Par la symétrie transpose $\Gamma_{-\tau}=\Gamma_\tau^{\top}$ : $\Gamma_{-1}=\Gamma_1^{\top}=(\Phi_1\Gamma_0)^{\top}=\Gamma_0\Phi_1^{\top}$ (avec $\Gamma_0=\Gamma_0^{\top}$). Comme $\Phi_1$ n'est pas symétrique, $\Gamma_1\ne\Gamma_1^{\top}$, donc $\Gamma_{-1}\ne\Gamma_1$ : l'ACVS multivariée n'est pas paire en $\tau$.</div>`, pts: 4}
  ]
},
