{
  n: 2,
  title: String.raw`Modèles ARMA et autocorrélation partielle (PACF)`,
  intro: String.raw`Trois briques (bruit blanc, MA, AR) se combinent en ARMA ; l'ACF et la PACF sont les signatures qui permettent de les reconnaître.`,
  sections: [
    {h: String.raw`Bruit blanc, MA et AR : les briques de base`, body: String.raw`<p>Le <strong>bruit blanc (white noise)</strong>, ou processus purement aléatoire, est l'atome de tous les modèles. $\{X_t\}$ est un bruit blanc si les $X_t$ sont <em>non corrélés</em>, centrés, de variance finie : pour tout $t\in\mathbb{Z}$, $\mathbb{E}[X_t]=0$, $\operatorname{Var}(X_t)=\sigma^2<\infty$, et $\operatorname{Cov}(X_s,X_t)=0$ pour $s\ne t$. Sa structure d'ordre 2 est donc $\gamma_\tau=\sigma^2$ si $\tau=0$, $0$ sinon, soit $\rho_\tau=\mathbf{1}_{\{\tau=0\}}$. On note $\varepsilon_t$ un bruit blanc centré de variance $\sigma_\varepsilon^2$.</p>
<p><strong>Intuition.</strong> « Non corrélé » est plus faible qu'« indépendant » : le bruit blanc ne contraint que les deux premiers moments, il n'est pas forcément i.i.d. ni gaussien. Le mot « blanc » renvoie à sa densité spectrale (spectral density) plate (même puissance à toutes les fréquences), miroir de son ACF plate.</p>
<p>Une <strong>moyenne mobile MA($q$) (moving average)</strong> est un filtre linéaire fini du bruit : $$X_t=\mu-\sum_{j=0}^{q}\theta_j\,\varepsilon_{t-j},\qquad \theta_0=-1,\ \theta_q\ne0.$$ La convention $\theta_0=-1$ rend le terme dominant $-\theta_0\varepsilon_t=\varepsilon_t$. Une MA($q$) est <strong>toujours stationnaire</strong> (seule condition : $\lvert\theta_j\rvert<\infty$). Exemple simple, MA(1) centrée : $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$.</p>
<p>Un <strong>autorégressif AR($p$) (autoregressive)</strong> s'écrit $$X_t=\sum_{j=1}^{p}\phi_j X_{t-j}+\varepsilon_t,\qquad \phi_p\ne0.$$ Contrairement à la MA, des <strong>conditions sur les $\phi_j$</strong> sont requises pour la stationnarité (racines du polynôme AR hors du cercle unité), et il n'y a pas de forme close simple de l'ACVS en général.</p>`},
    {h: String.raw`ARMA, causalité et inversibilité (les racines)`, body: String.raw`<p>On combine AR et MA en un <strong>ARMA($p,q$)</strong> : $$X_t=\sum_{j=1}^{p}\phi_j X_{t-j}-\sum_{k=0}^{q}\theta_k\varepsilon_{t-k},\quad\text{soit}\quad \Phi(B)X_t=\Theta(B)\varepsilon_t,$$ avec $\Phi(z)=1-\sum_{j=1}^{p}\phi_j z^{j}$, $\Theta(z)=-\sum_{k=0}^{q}\theta_k z^{k}$ et l'opérateur de retard $B^jX_t=X_{t-j}$.</p>
<p>Le processus est <strong>causal</strong> s'il s'écrit $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$ avec $\sum_j\lvert\psi_j\rvert<\infty$ : il ne dépend que du <em>présent et du passé</em> du bruit (représentation MA($\infty$), de poids $\psi_j$, les $\psi$-poids).</p>
<p><strong>Où regarder les racines.</strong> La <strong>causalité / stationnarité</strong> exige que toutes les racines de $\Phi(z)$ soient <em>hors</em> du cercle unité ($\lvert z\rvert>1$) ; l'<strong>inversibilité</strong> exige la même chose pour $\Theta(z)$. Pour AR(1), $\Phi(z)=1-\phi z$ a pour racine $z=1/\phi$, donc $\lvert z\rvert>1\iff\lvert\phi\rvert<1$. Pour AR(2) ($\Phi(z)=1-\phi_1 z-\phi_2 z^2$), le triangle de stationnarité est $\phi_1+\phi_2<1$, $\phi_2-\phi_1<1$, $\lvert\phi_2\rvert<1$. Une MA($q$) centrée est <em>toujours</em> causale.</p>
<p><strong>Pourquoi imposer l'inversibilité.</strong> Deux MA(1) « jumelles », $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ et $Y_t=\eta_t-\tfrac1\theta\eta_{t-1}$ (avec $\operatorname{Var}\eta_t=\sigma_\varepsilon^2\theta^2$), ont <em>exactement la même</em> ACVS : on ne peut pas les distinguer par la structure d'ordre 2. Choisir la représentation inversible (racine de $\Theta$ hors du cercle, soit $\lvert\theta\rvert<1$) fixe un modèle unique. C'est aussi la raison de la convention $\theta_0=-1$ : sans elle, l'échelle du coefficient dominant n'est pas identifiable.</p>`},
    {h: String.raw`ACVS d'une MA et développement causal de l'AR(1)`, body: String.raw`<p><strong>L'ACVS d'une MA($q$) coupe après le retard $q$.</strong> Avec $\theta_j:=0$ pour $j>q$, $$\gamma_\tau=\operatorname{Cov}(X_{t+\tau},X_t)=\begin{cases}\sigma_\varepsilon^2\sum_{j=0}^{q}\theta_j\theta_{j+\lvert\tau\rvert} & \lvert\tau\rvert\le q,\\ 0 & \lvert\tau\rvert>q.\end{cases}$$ Donc l'<strong>ACF d'une MA($q$) est nulle pour $\lvert\tau\rvert>q$</strong> : c'est la signature qui se lit directement sur l'ACF. <em>Idée</em> : par bilinéarité de la covariance et $\operatorname{Cov}(\varepsilon_s,\varepsilon_u)=\sigma_\varepsilon^2\mathbf{1}_{\{s=u\}}$, seuls survivent les indices de bruit identiques ; pour $\lvert\tau\rvert>q$ aucune paire de coefficients ne se chevauche.</p>
<p><strong>Développement causal de l'AR(1).</strong> Pour $X_t=\phi X_{t-1}+\varepsilon_t$ avec $\lvert\phi\rvert<1$, l'itération donne la forme MA($\infty$) $X_t=\sum_{k\ge0}\phi^k\varepsilon_{t-k}$ ($\psi_k=\phi^k$), d'où, par la somme géométrique $\sum_{k\ge0}\phi^{2k}=1/(1-\phi^2)$, $$\gamma_\tau=\frac{\sigma_\varepsilon^2}{1-\phi^2}\,\phi^{\lvert\tau\rvert},\qquad \rho_\tau=\phi^{\lvert\tau\rvert}.$$ L'ACF <strong>décroît (tails off)</strong> sans jamais valoir exactement $0$ : c'est ce qui motive la PACF.</p>
<p><strong>Technique générale ($\psi$-poids).</strong> On obtient la représentation MA($\infty$) en développant $\psi(z)=\Theta(z)/\Phi(z)=\sum_{j\ge0}\psi_j z^j$ en série entière (ou en identifiant les coefficients dans $\Phi(B)\psi(B)=\Theta(B)$), puis $$\gamma_\tau=\sigma_\varepsilon^2\sum_{j\ge0}\psi_j\psi_{j+\lvert\tau\rvert}.$$</p>`},
    {h: String.raw`La PACF : corrélation partielle et signatures`, body: String.raw`<p>Pour $\{X_t\}$ stationnaire centré, la <strong>PACF (partial autocorrelation function)</strong> au retard $\tau$ est la corrélation <em>partielle</em> de $X_t$ et $X_{t+\tau}$ sachant les valeurs intermédiaires $Z=(X_{t+1},\dots,X_{t+\tau-1})$ : on retire de chacun son meilleur prédicteur linéaire (best linear predictor) à partir de $Z$, puis on corrèle les résidus : $$\alpha_\tau=\operatorname{Corr}\big(X_{t+\tau}-\hat X_{t+\tau},\,X_t-\hat X_t\big).$$ De façon équivalente, si $P_{X_0,\dots,X_{\tau-1}}(X_\tau)=\sum_{j=1}^{\tau}\alpha_{\tau,j}X_{\tau-j}$, alors $\alpha_\tau=\alpha_{\tau,\tau}$ (le <em>dernier</em> coefficient de régression) ; on pose $\alpha_1=\rho_1$.</p>
<p><strong>Ce que mesure la PACF.</strong> Elle répond : « combien d'information linéaire <em>nouvelle</em> sur $X_{t+\tau}$ reste-t-il dans $X_t$ une fois tout l'intermédiaire enlevé ? ». Dans un AR(1), $\rho_\tau=\phi^{\lvert\tau\rvert}\ne0$ pour tout $\tau$ alors que $X_t$ ne dépend directement que de $X_{t-1}$ : la corrélation au retard $2$ est entièrement <em>transmise</em> par $X_{t-1}$. La PACF retire ce relais, donc s'annule pour $\tau>1$ et identifie exactement $p=1$.</p>
<p><strong>Relation ACF--PACF (équations de prédiction, type Yule--Walker).</strong> Pour $\tau>0$ et $k\in\{1,\dots,\tau\}$, avec $\hat X_\tau=\sum_{j=1}^{\tau}\alpha_{\tau,j}X_{\tau-j}$, $$\rho_k=\sum_{j=1}^{\tau}\alpha_{\tau,j}\,\rho_{k-j}.$$ <em>Idée</em> : l'erreur de prédiction est orthogonale aux régresseurs ($\operatorname{Cov}(X_\tau-\hat X_\tau,X_k)=0$), ce qui relie l'ACF aux coefficients $\alpha_{\tau,j}$. La <strong>PACF d'un AR($p$) s'annule au-delà de $p$</strong> : $\alpha_\tau=0$ pour $\tau>p$, car par causalité les équations de prédiction sont résolues par $\alpha_{\tau,j}=\phi_j$ ($j\le p$) et $0$ sinon, donc $\alpha_{\tau,\tau}=0$. La PACF estimée aux retards $>p$ est asymptotiquement de moyenne $0$ et variance $1/n$, d'où les bandes $\pm1.96/\sqrt n$.</p>`},
    {h: String.raw`Identification : la table 2x3 et Durbin--Levinson`, body: String.raw`<p><strong>Théorème (signatures ACF et PACF).</strong> Pour un ARMA($p,q$) <em>causal et inversible</em> :</p>
<p>$$\begin{array}{lccc} & \text{AR}(p) & \text{MA}(q) & \text{ARMA}(p,q)\\ \text{ACF} & \text{décroît} & \text{coupe après } q & \text{décroît}\\ \text{PACF} & \text{coupe après } p & \text{décroît} & \text{décroît}\end{array}$$</p>
<p>On lit <strong>$q$ là où l'ACF coupe</strong>, <strong>$p$ là où la PACF coupe</strong> ; si les deux décroissent, c'est un ARMA mixte. <em>Coupe</em> (cuts off) = exactement $0$ au-delà d'un retard ; <em>décroît</em> (tails off) = décroissance géométrique ou sinusoïdale amortie, sans zéro exact (comme $\phi^{\lvert\tau\rvert}$). Sur des données, « $0$ » se juge par rapport à la bande $\pm1.96/\sqrt n$.</p>
<p><strong>Récursion de Durbin--Levinson</strong> (calcule la PACF à partir de l'ACF) : $$\alpha_{1,1}=\rho_1,\qquad \alpha_{\tau,\tau}=\frac{\rho_\tau-\sum_{j=1}^{\tau-1}\alpha_{\tau-1,j}\,\rho_{\tau-j}}{1-\sum_{j=1}^{\tau-1}\alpha_{\tau-1,j}\,\rho_{j}},$$ puis la mise à jour $\alpha_{\tau,j}=\alpha_{\tau-1,j}-\alpha_{\tau,\tau}\,\alpha_{\tau-1,\tau-j}$ pour $j=1,\dots,\tau-1$. Marche avec l'ACF théorique <em>ou</em> empirique ; une coupure nette de $\alpha_{\tau,\tau}$ à $\tau=p+1$ signale un AR($p$).</p>
<p><strong>Démarche de lecture sur graphiques.</strong> (1) vérifier la stationnarité (une ACF qui décroît très lentement, presque linéairement, signale du non-stationnaire $\Rightarrow$ différencier) ; (2) ACF coupe après $q$ et PACF décroît $\Rightarrow$ MA($q$) ; (3) PACF coupe après $p$ et ACF décroît $\Rightarrow$ AR($p$) ; (4) les deux décroissent $\Rightarrow$ ARMA mixte ; (5) rien de significatif $\Rightarrow$ bruit blanc. Le choix n'est jamais unique : il faut un argument défendable.</p>`}
  ],
  checks: [
    {q: String.raw`Quelle est la différence entre « non corrélé » et « indépendant » pour un bruit blanc ?`, a: String.raw`Le bruit blanc ne contraint que les deux premiers moments ($\mathbb{E}[X_t]=0$, $\operatorname{Var}=\sigma^2$, covariances nulles). Il n'est donc pas forcément i.i.d. ni gaussien ; l'indépendance impliquerait des contraintes sur tous les moments.`},
    {q: String.raw`Pour tester la causalité d'un AR($p$), où doivent se trouver les racines de $\Phi(z)$ ?`, a: String.raw`Toutes <em>hors</em> du cercle unité ($\lvert z\rvert>1$). Pour AR(1), $z=1/\phi$, donc cela équivaut à $\lvert\phi\rvert<1$.`},
    {q: String.raw`Sur l'ACF et la PACF, comment reconnaît-on une MA($q$) et un AR($p$) ?`, a: String.raw`MA($q$) : l'ACF <strong>coupe</strong> après le retard $q$ et la PACF décroît. AR($p$) : la PACF <strong>coupe</strong> après le retard $p$ et l'ACF décroît. Si les deux décroissent, c'est un ARMA mixte.`},
    {q: String.raw`Pourquoi la PACF d'un AR(1) vaut-elle $0$ pour $\tau\ge2$ alors que l'ACF ne s'annule jamais ?`, a: String.raw`L'ACF vaut $\rho_\tau=\phi^{\lvert\tau\rvert}\ne0$ car la corrélation à distance $2$ est <em>transmise</em> par $X_{t-1}$. La PACF retire l'effet de l'intermédiaire $X_{t-1}$ : il ne reste aucune information nouvelle, donc $\alpha_\tau=0$ pour $\tau>1$.`},
    {q: String.raw`Pourquoi impose-t-on l'inversibilité d'une MA(1) ?`, a: String.raw`Parce que $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ et sa jumelle de coefficient $1/\theta$ (variance de bruit $\sigma_\varepsilon^2\theta^2$) ont la même ACVS. Imposer $\lvert\theta\rvert<1$ (racine de $\Theta$ hors du cercle) sélectionne une représentation unique.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer le théorème des signatures ACF / PACF des modèles ARMA, en précisant les hypothèses, puis expliquer comment lire $(p,q)$ sur les graphiques.`,
     answer: String.raw`<div class="step"><strong>Hypothèse.</strong> Le processus $\{X_t\}$ est un ARMA($p,q$) <em>causal et inversible</em> (toutes les racines de $\Phi(z)$ et de $\Theta(z)$ hors du cercle unité), stationnaire centré.</div><div class="step"><strong>Énoncé.</strong> L'ACF $\rho_\tau$ et la PACF $\alpha_\tau$ se comportent ainsi : $$\begin{array}{lccc} & \text{AR}(p) & \text{MA}(q) & \text{ARMA}(p,q)\\ \text{ACF} & \text{décroît} & \text{coupe après } q & \text{décroît}\\ \text{PACF} & \text{coupe après } p & \text{décroît} & \text{décroît}\end{array}$$ « Coupe après $m$ » signifie exactement $0$ au-delà du retard $m$ ; « décroît » signifie décroissance géométrique ou sinusoïdale amortie sans zéro exact.</div><div class="step"><strong>Lecture.</strong> On lit $q$ là où l'ACF coupe et $p$ là où la PACF coupe. Si seule l'ACF coupe (après $q$) : MA($q$). Si seule la PACF coupe (après $p$) : AR($p$). Si les deux décroissent : ARMA mixte. Si aucune n'est significative à un retard non nul : bruit blanc.</div><div class="step"><strong>Significativité.</strong> Sur données, « $0$ » se juge par rapport aux bandes $\pm1.96/\sqrt n$ (variance asymptotique $1/n$ de la PACF estimée au-delà de $p$).</div>`, pts: 3},
    {type:'open', q: String.raw`Soit la MA(2) $X_t=\varepsilon_t-\theta_1\varepsilon_{t-1}-\theta_2\varepsilon_{t-2}$ avec bruit blanc de variance $\sigma_\varepsilon^2$. Calculer $\gamma_\tau$ pour tout $\tau$, vérifier que $\gamma_\tau=0$ pour $\lvert\tau\rvert\ge3$, et donner $\rho_1,\rho_2$.`,
     answer: String.raw`<div class="step"><strong>Coefficients du filtre.</strong> Les « taps » sont $(\psi_0,\psi_1,\psi_2)=(1,-\theta_1,-\theta_2)$ et $\psi_j=0$ sinon. On utilise $\gamma_\tau=\sigma_\varepsilon^2\sum_{j}\psi_j\psi_{j+\lvert\tau\rvert}$ (bilinéarité de $\operatorname{Cov}$, $\operatorname{Cov}(\varepsilon_s,\varepsilon_u)=\sigma_\varepsilon^2\mathbf{1}_{\{s=u\}}$).</div><div class="step"><strong>$\tau=0$ :</strong> $\gamma_0=\sigma_\varepsilon^2(1+\theta_1^2+\theta_2^2)$.</div><div class="step"><strong>$\tau=\pm1$ :</strong> $\gamma_1=\sigma_\varepsilon^2\big[(1)(-\theta_1)+(-\theta_1)(-\theta_2)\big]=\sigma_\varepsilon^2(-\theta_1+\theta_1\theta_2)=\sigma_\varepsilon^2\theta_1(\theta_2-1)$.</div><div class="step"><strong>$\tau=\pm2$ :</strong> $\gamma_2=\sigma_\varepsilon^2\big[(1)(-\theta_2)\big]=-\sigma_\varepsilon^2\theta_2$.</div><div class="step"><strong>$\lvert\tau\rvert\ge3$ :</strong> le filtre a longueur $3$, donc aucune paire de taps ne se chevauche et $\gamma_\tau=0$. L'ACF coupe bien après $q=2$.</div><div class="step"><strong>ACF.</strong> $\rho_1=\dfrac{\theta_1(\theta_2-1)}{1+\theta_1^2+\theta_2^2}$, $\rho_2=\dfrac{-\theta_2}{1+\theta_1^2+\theta_2^2}$.</div>`, pts: 4},
    {type:'open', q: String.raw`Pour l'AR(2) $X_t=\phi_1 X_{t-1}+\phi_2 X_{t-2}+\varepsilon_t$ : (a) donner les conditions de causalité sur $(\phi_1,\phi_2)$ ; (b) pour $\phi_1=\tfrac12$, $\phi_2=-\tfrac14$, vérifier la causalité et calculer $\rho_1,\rho_2,\rho_3$ par Yule--Walker ; (c) prédire le motif de la PACF.`,
     answer: String.raw`<div class="step"><strong>(a) Causalité.</strong> Avec $\Phi(z)=1-\phi_1 z-\phi_2 z^2$, on veut les deux racines hors du cercle unité. De façon équivalente, le triangle de stationnarité : $\phi_1+\phi_2<1$, $\ \phi_2-\phi_1<1$, $\ \lvert\phi_2\rvert<1$.</div><div class="step"><strong>(b) Vérification.</strong> $\phi_1+\phi_2=\tfrac14<1$, $\ \phi_2-\phi_1=-\tfrac34<1$, $\ \lvert\phi_2\rvert=\tfrac14<1$ : le processus est causal.</div><div class="step"><strong>Yule--Walker</strong> : $\rho_\tau=\phi_1\rho_{\tau-1}+\phi_2\rho_{\tau-2}$ pour $\tau\ge1$, avec $\rho_0=1$ et $\rho_{-1}=\rho_1$. Pour $\tau=1$ : $\rho_1=\phi_1+\phi_2\rho_1\Rightarrow\rho_1=\dfrac{\phi_1}{1-\phi_2}=\dfrac{1/2}{1+1/4}=\dfrac25$.</div><div class="step"><strong>$\tau=2$ :</strong> $\rho_2=\phi_1\rho_1+\phi_2=\tfrac12\cdot\tfrac25-\tfrac14=\tfrac15-\tfrac14=-\tfrac1{20}$.</div><div class="step"><strong>$\tau=3$ :</strong> $\rho_3=\phi_1\rho_2+\phi_2\rho_1=\tfrac12\cdot(-\tfrac1{20})-\tfrac14\cdot\tfrac25=-\tfrac1{40}-\tfrac1{10}=-\tfrac1{40}-\tfrac4{40}=-\tfrac18$.</div><div class="step"><strong>(c) PACF.</strong> L'ACF décroît (tails off) sans s'annuler ; la PACF d'un AR(2) <strong>coupe après le retard $2$</strong>, donc $\alpha_3=0$ et $\alpha_\tau=0$ pour tout $\tau>2$. Les coefficients diagonaux donnent $\alpha_{2,1}=\phi_1$, $\alpha_{2,2}=\phi_2$.</div>`, pts: 4},
    {type:'open', q: String.raw`Un processus stationnaire a $\rho_1=\tfrac25$, $\rho_2=-\tfrac1{20}$, $\rho_3=-\tfrac18$. Calculer $\alpha_1,\alpha_2,\alpha_3$ par la récursion de Durbin--Levinson et identifier un modèle plausible.`,
     answer: String.raw`<div class="step"><strong>Retard 1.</strong> $\alpha_{1,1}=\rho_1=\dfrac25$.</div><div class="step"><strong>Retard 2.</strong> $\alpha_{2,2}=\dfrac{\rho_2-\alpha_{1,1}\rho_1}{1-\alpha_{1,1}\rho_1}=\dfrac{-\frac1{20}-\frac25\cdot\frac25}{1-\frac25\cdot\frac25}=\dfrac{-\frac1{20}-\frac4{25}}{1-\frac4{25}}$. Numérateur $=-\frac5{100}-\frac{16}{100}=-\frac{21}{100}$ ; dénominateur $=\frac{84}{100}$. Donc $\alpha_{2,2}=-\dfrac{21}{84}=-\dfrac14$.</div><div class="step"><strong>Mise à jour.</strong> $\alpha_{2,1}=\alpha_{1,1}-\alpha_{2,2}\alpha_{1,1}=\tfrac25-(-\tfrac14)\tfrac25=\tfrac25+\tfrac1{10}=\tfrac12$.</div><div class="step"><strong>Retard 3.</strong> $\alpha_{3,3}=\dfrac{\rho_3-\alpha_{2,1}\rho_2-\alpha_{2,2}\rho_1}{1-\alpha_{2,1}\rho_1-\alpha_{2,2}\rho_2}$. Numérateur $=-\tfrac18-\tfrac12(-\tfrac1{20})-(-\tfrac14)\tfrac25=-\tfrac18+\tfrac1{40}+\tfrac1{10}=-\tfrac5{40}+\tfrac1{40}+\tfrac4{40}=0$. Donc $\alpha_{3,3}=0$.</div><div class="step"><strong>Conclusion.</strong> $\alpha_1=\tfrac25$, $\alpha_2=-\tfrac14$, $\alpha_3=0$. La PACF coupe à $\tau=3$ : motif d'un <strong>AR(2)</strong>. En effet $Y_t=\tfrac12 Y_{t-1}-\tfrac14 Y_{t-2}+\varepsilon_t$ a la même ACF, et $\alpha_{2,1}=\tfrac12=\phi_1$, $\alpha_{2,2}=-\tfrac14=\phi_2$ redonnent les coefficients AR.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit l'AR(1) causal $X_t=\phi X_{t-1}+\varepsilon_t$, $\lvert\phi\rvert<1$, bruit blanc de variance $\sigma_\varepsilon^2$. (a) Établir la représentation MA($\infty$) ; (b) en déduire $\gamma_\tau$ et $\rho_\tau$.`,
     answer: String.raw`<div class="step"><strong>(a) Itération.</strong> En remplaçant $X_{t-1}=\phi X_{t-2}+\varepsilon_{t-1}$ de façon répétée : $X_t=\varepsilon_t+\phi\varepsilon_{t-1}+\phi^2\varepsilon_{t-2}+\dots+\phi^{n-1}\varepsilon_{t-n+1}+\phi^n X_{t-n}$. Comme $\lvert\phi\rvert<1$, le reste $\phi^n X_{t-n}\to0$ en moyenne quadratique, d'où $X_t=\sum_{k\ge0}\phi^k\varepsilon_{t-k}$, soit $\psi_k=\phi^k$. On a bien $\sum_k\lvert\psi_k\rvert=\frac1{1-\lvert\phi\rvert}<\infty$ (causal).</div><div class="step"><strong>(b) ACVS.</strong> $\gamma_\tau=\operatorname{Cov}(X_{t+\tau},X_t)=\sigma_\varepsilon^2\sum_{k\ge0}\psi_k\psi_{k+\lvert\tau\rvert}=\sigma_\varepsilon^2\sum_{k\ge0}\phi^k\phi^{k+\lvert\tau\rvert}=\sigma_\varepsilon^2\,\phi^{\lvert\tau\rvert}\sum_{k\ge0}\phi^{2k}$.</div><div class="step"><strong>Somme géométrique.</strong> $\sum_{k\ge0}\phi^{2k}=\dfrac1{1-\phi^2}$ (car $\phi^2<1$), donc $$\gamma_\tau=\frac{\sigma_\varepsilon^2}{1-\phi^2}\,\phi^{\lvert\tau\rvert}.$$</div><div class="step"><strong>ACF.</strong> $\rho_\tau=\gamma_\tau/\gamma_0=\phi^{\lvert\tau\rvert}$. Elle décroît géométriquement sans jamais s'annuler, ce qui motive la PACF (qui, elle, coupe après le retard $1$).</div>`, pts: 4},
    {type:'open', q: String.raw`Toujours pour l'AR(1) causal $X_t=\phi X_{t-1}+\varepsilon_t$ ($\lvert\phi\rvert<1$). Donner le meilleur prédicteur linéaire à un pas $P_{X_1,\dots,X_n}(X_{n+1})$ et son erreur quadratique moyenne, en justifiant par les équations de prédiction.`,
     answer: String.raw`<div class="step"><strong>Équations de prédiction.</strong> Le meilleur prédicteur linéaire est caractérisé par l'orthogonalité de l'erreur aux régresseurs : $\operatorname{Cov}(X_{n+1}-\hat X_{n+1},X_k)=0$ pour tout $k\in\{1,\dots,n\}$.</div><div class="step"><strong>Candidat.</strong> Posons $\hat X_{n+1}=\phi X_n$. L'erreur vaut $X_{n+1}-\phi X_n=\varepsilon_{n+1}$.</div><div class="step"><strong>Vérification.</strong> Par causalité, $X_k$ ne dépend que des $\varepsilon_s$ avec $s\le k\le n<n+1$, donc $\operatorname{Cov}(\varepsilon_{n+1},X_k)=0$ pour tout $k\le n$. Les équations d'orthogonalité sont satisfaites ; par unicité du meilleur prédicteur linéaire, $$P_{X_1,\dots,X_n}(X_{n+1})=\phi X_n.$$</div><div class="step"><strong>Erreur quadratique.</strong> $\operatorname{MSE}=\mathbb{E}\big[(X_{n+1}-\hat X_{n+1})^2\big]=\mathbb{E}[\varepsilon_{n+1}^2]=\sigma_\varepsilon^2$.</div><div class="step"><strong>Interprétation.</strong> Seule la dernière observation compte : c'est une conséquence directe de la PACF nulle au-delà du retard $1$ (les points plus anciens n'apportent aucune information linéaire nouvelle).</div>`, pts: 3},
    {type:'open', q: String.raw`Montrer que les MA(1) $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ ($\operatorname{Var}\varepsilon_t=\sigma_\varepsilon^2$, $\theta\ne0$) et $Y_t=\eta_t-\tfrac1\theta\eta_{t-1}$ ($\operatorname{Var}\eta_t=\sigma_\varepsilon^2\theta^2$) ont la même ACVS. Laquelle est inversible ?`,
     answer: String.raw`<div class="step"><strong>ACVS de $X_t$.</strong> Taps $(1,-\theta)$ : $\gamma_0=\sigma_\varepsilon^2(1+\theta^2)$, $\ \gamma_{\pm1}=-\sigma_\varepsilon^2\theta$, $\ \gamma_\tau=0$ pour $\lvert\tau\rvert\ge2$.</div><div class="step"><strong>ACVS de $Y_t$.</strong> Coefficient $1/\theta$, variance de bruit $\sigma_\eta^2=\sigma_\varepsilon^2\theta^2$. $\tilde\gamma_0=\sigma_\eta^2\big(1+\tfrac1{\theta^2}\big)=\sigma_\varepsilon^2\theta^2\cdot\dfrac{\theta^2+1}{\theta^2}=\sigma_\varepsilon^2(1+\theta^2)$.</div><div class="step"><strong>Retard 1.</strong> $\tilde\gamma_{\pm1}=-\sigma_\eta^2\cdot\tfrac1\theta=-\sigma_\varepsilon^2\theta^2\cdot\tfrac1\theta=-\sigma_\varepsilon^2\theta$, et $\tilde\gamma_\tau=0$ pour $\lvert\tau\rvert\ge2$.</div><div class="step"><strong>Conclusion.</strong> $\tilde\gamma_\tau=\gamma_\tau$ pour tout $\tau$ : les deux MA(1) sont <strong>indistinguables</strong> par la structure d'ordre 2.</div><div class="step"><strong>Inversibilité.</strong> Les polynômes MA ont pour racines $z=1/\theta$ (pour $X_t$) et $z=\theta$ (pour $Y_t$). La représentation inversible est celle dont la racine est hors du cercle unité : si $\lvert\theta\rvert<1$, c'est $X_t$ (racine $1/\theta$, de module $>1$) ; si $\lvert\theta\rvert>1$, c'est $Y_t$.</div>`, pts: 3}
  ]
},
