{
  n: 11,
  title: String.raw`Diagnostics, sélection de modèle & longue mémoire`,
  intro: String.raw`On valide un modèle par ses résidus (test de Ljung--Box), on choisit entre modèles par AIC/AICc/BIC (méthode Box--Jenkins), puis on sort du monde ARMA : la longue mémoire (long memory) décrit des autocovariances à décroissance lente, modélisée par la différenciation fractionnaire $(1-B)^d$.`,
  sections: [
    {h: String.raw`Diagnostics par les résidus : les résidus doivent être le bruit`, body: String.raw`<p>Une fois un modèle ARIMA identifié et estimé, deux questions restent : <strong>est-il valide ?</strong> (diagnostics, fondés sur les résidus) et <strong>est-ce le bon parmi plusieurs ?</strong> (sélection, fondée sur des critères d'information). Pour une valeur ajustée $\hat X_t$, le <strong>résidu</strong> (residual) est $e_t=X_t-\hat X_t$ et le résidu <strong>standardisé</strong> $\tilde e_t = e_t/\sqrt{\operatorname{Var}(e_t)}$.</p>
<p><strong>Intuition centrale.</strong> Un modèle bien spécifié a capté toute la structure <em>prévisible</em> (la dépendance linéaire) de $\{X_t\}$. Ce qui reste, $e_t$, est la part <em>imprévisible</em> : l'innovation $\varepsilon_t$. Donc tout ce qu'on exigeait du bruit blanc (white noise) <em>en entrée</em>, on le <strong>teste</strong> maintenant <em>en sortie</em>. Pour un AR(1) à vrais paramètres, $\hat X_t=\phi X_{t-1}$ donc $e_t = X_t-\phi X_{t-1}=\varepsilon_t$ exactement : c'est le gabarit de tout diagnostic.</p>
<p><strong>Les quatre questions</strong> (chaque échec pointe un défaut précis) :</p>
<ul><li>Moyenne nulle constante ? (sinon tendance résiduelle) — tracé $\{(t,\tilde e_t)\}$, pas de tendance.</li>
<li>Variance constante (homoscédasticité) ? (sinon grappes de volatilité) — même tracé, dispersion constante.</li>
<li>Décorrélés en $t$ ? (sinon terme AR/MA oublié) — corrélogramme + Ljung--Box.</li>
<li>Gaussiens ? (sinon innovations non normales) — <strong>Q--Q plot</strong> : points alignés si normaux ; queues lourdes $\Rightarrow$ courbure aux extrémités. Le Q--Q plot ne teste que la gaussianité <em>marginale</em>.</li></ul>
<p>Le <strong>corrélogramme des résidus</strong> trace l'autocorrélation empirique $\hat r_\tau=\dfrac{\sum_{t=1}^{n-\tau}(e_{t+\tau}-\bar e)(e_t-\bar e)}{\sum_{t=1}^{n}(e_t-\bar e)^2}$ contre $\tau$. Sous l'hypothèse « bruit blanc », $\hat r_\tau\approx\mathcal N(0,1/n)$, donc on compare chaque valeur ponctuellement à la bande $\left(-1.96/\sqrt n,\ 1.96/\sqrt n\right)$.</p>`},
    {h: String.raw`Test portmanteau de Ljung--Box`, body: String.raw`<p>Plutôt que d'inspecter le corrélogramme retard par retard (problème de tests multiples), on teste d'un coup <strong>$H_0:\rho_1=\rho_2=\cdots=\rho_m=0$</strong> (résidus blancs jusqu'au retard $m$) contre « au moins un $\rho_\tau\neq0$ ». La statistique <strong>Box--Pierce</strong> est $Q_m=n\sum_{\tau=1}^{m}\hat r_\tau^{\,2}$, et sa version corrigée pour petits échantillons, la statistique <strong>Ljung--Box</strong>, est</p>
$$Q_m = n(n+2)\sum_{\tau=1}^{m}\frac{\hat r_\tau^{\,2}}{n-\tau}\ \overset{H_0}{\sim}\ \chi^2_{m-p-q}\quad\text{pour un ARMA}(p,q).$$
<p><strong>Idée de preuve.</strong> Sous bruit blanc, $\sqrt n\,\hat r_\tau\xrightarrow{d}\mathcal N(0,1)$ et les $\hat r_\tau$ sont asymptotiquement indépendants ; $\sum_\tau(\sqrt n\,\hat r_\tau)^2$ est une somme de carrés de normales centrées réduites. Ajuster $p+q$ paramètres ARMA retire $p+q$ degrés de liberté. Le facteur $\frac{n+2}{n-\tau}>1$ rescale chaque terme pour mieux coller au $\chi^2$ à $n$ fini ; quand $n\to\infty$, $\frac{n(n+2)}{n-\tau}\to n$ et les deux statistiques coïncident. On préfère <strong>Ljung--Box</strong> en pratique car l'approximation $\chi^2$ de Box--Pierce est mauvaise à $n$ réaliste.</p>
<p><strong>Décision.</strong> Valeur critique = quantile supérieur $a$ de $\chi^2_{m-p-q}$ ; rejeter $H_0$ si $Q_m$ la dépasse. <strong>Rejet</strong> $\Rightarrow$ autocorrélation résiduelle $\Rightarrow$ modèle inadéquat. <strong>Non-rejet</strong> $\Rightarrow$ pas de preuve contre la blancheur $\Rightarrow$ modèle adéquat.</p>
<p><strong>Le piège des degrés de liberté.</strong> Les df sont $m-p-q$, <strong>pas</strong> $m$ : on soustrait les paramètres ARMA <em>estimés</em> ($p+q$ ; la variance $\sigma^2$ n'est <em>pas</em> soustraite). Prendre $\mathrm{df}=m$ gonfle la valeur critique et fait rejeter beaucoup trop rarement. Exiger $m>p+q$ pour que df $>0$, et $m$ assez grand pour capter les retards d'intérêt mais pas trop (les $\hat r_\tau$ à grand retard, estimés sur peu de paires, n'ajoutent que du bruit).</p>`},
    {h: String.raw`Sélection de modèle : pourquoi pas le $R^2$, et AIC / AICc / BIC`, body: String.raw`<p>Le <strong>$R^2$</strong> $=1-s_e^2/s_y^2$ mesure la variance « expliquée ». C'est un critère <strong>dangereux</strong> en séries temporelles. Pour un AR(1), $s_y^2=\sigma^2/(1-\phi^2)$ et $s_e^2=\sigma^2$, donc</p>
$$R^2 = 1-\frac{\sigma^2(1-\phi^2)}{\sigma^2}=\phi^2.$$
<p>Même le <em>vrai</em> modèle a un $R^2$ borné ($\phi=0.4\Rightarrow R^2=0.16$, « médiocre » mais optimal) : un processus stochastique n'est pas parfaitement prévisible. De plus ajouter des paramètres ne peut <em>qu'</em>augmenter le $R^2$ en échantillon. On utilise donc des <strong>critères d'information</strong>. Pour un modèle à $k$ paramètres estimés, $n$ observations, vraisemblance maximisée $L$ :</p>
$$\mathrm{AIC} = -2\log L + 2k,\qquad \mathrm{AICc} = -2\log L + 2k\,\frac{n}{n-k-1},\qquad \mathrm{BIC} = -2\log L + k\log n.$$
<p><strong>Plus petit = mieux</strong> pour les trois. Pour un ARMA$(p,q)$ : $k=p+q+1$ ($p$ coeff. AR, $q$ coeff. MA, $+\,\sigma^2$).</p>
<p><strong>AIC vs AICc.</strong> L'écart est toujours positif : $\mathrm{AICc}-\mathrm{AIC}=\dfrac{2k(k+1)}{n-k-1}>0$, et $\to0$ quand $n\to\infty$ ($k$ fixé). AIC tend à <em>surestimer</em> $p$ ; AICc (Hurvich--Tsai, 1989) corrige ce biais petit échantillon et est sûr par défaut (il coïncide avec AIC pour $n$ grand).</p>
<p><strong>AIC vs BIC.</strong> Pénalité par paramètre : $2$ (AIC) contre $\log n$ (BIC). Donc $\log n>2\iff n>e^2\approx7.39$ : dès $n\ge8$, BIC pénalise davantage, est plus parcimonieux et <em>consistant</em> (sélectionne le bon ordre avec probabilité $\to1$). <strong>Quand choisir quoi :</strong> AICc si $n$ petit ou $k$ comparable à $n$ ; BIC pour la parcimonie/consistance ; AIC pour la prévision (sur-ajustement léger toléré).</p>`},
    {h: String.raw`Méthode Box--Jenkins et lecture ACF/PACF`, body: String.raw`<p>La méthode <strong>Box--Jenkins</strong> construit un modèle par itérations en quatre étapes :</p>
<ul><li><strong>(1) Identifier</strong> $p,d,q$ : choisir $d$ = plus petit ordre de différenciation qui stabilise la série (tracer les données ; si non stationnaire, tracer les différences) ; choisir $p,q$ en lisant ACF/PACF sur la série différenciée.</li>
<li><strong>(2) Estimer</strong> les paramètres du modèle ARIMA proposé.</li>
<li><strong>(3) Diagnostiquer</strong> les résidus (moyenne / variance / Q--Q / corrélogramme + Ljung--Box) ; si inadéquat, retour à (1).</li>
<li><strong>(4) Utiliser</strong> le modèle validé (prévision ou autre inférence).</li></ul>
<p><strong>Lire ACF/PACF — coupure (cuts off) vs décroissance (tails off),</strong> sur la série correctement différenciée :</p>
<ul><li>AR$(p)$ : ACF décroît, PACF <strong>coupe après le retard $p$</strong>.</li>
<li>MA$(q)$ : ACF <strong>coupe après le retard $q$</strong>, PACF décroît.</li>
<li>ARMA$(p,q)$ : ACF décroît, PACF décroît.</li>
<li>Non stationnaire : ACF décroît <em>très</em> lentement (re-différencier).</li></ul>
<p>« Coupe » = passe dans la bande $\pm1.96/\sqrt n$ au-delà de l'ordre ; « décroît » = décroissance géométrique/sinusoïdale jamais brutale.</p>`},
    {h: String.raw`Longue mémoire : covariance, spectre, FARIMA et mouvement brownien fractionnaire`, body: String.raw`<p>Les ARMA ont des covariances à support fini ($\gamma_\tau=0$ pour $|\tau|>q$) ou à décroissance exponentielle ($\gamma_\tau\sim|\phi|^{\tau}$). Beaucoup de séries réelles décroissent seulement <em>polynomialement</em> : c'est la <strong>longue mémoire</strong> (long-range dependence). $\{X_t\}$ stationnaire au 2e ordre est à longue mémoire si</p>
$$\gamma_\tau \sim L_\gamma(\tau)\,\lvert\tau\rvert^{-\alpha},\quad \lvert\tau\rvert\to\infty,\qquad 0<\alpha<1,$$
<p>($L_\gamma$ à variation lente). De façon équivalente, le spectre (densité spectrale, spectral density) explose à l'origine : $S(f)\sim L_S(f)\,\lvert f\rvert^{\alpha-1}$, $f\to0$, avec $\alpha-1\in(-1,0)$ donc $S(0)=\infty$ (<strong>pôle spectral</strong>). La plage admissible $0<\alpha<2$ donne trois régimes ($\alpha=1$ : dépendance courte, ARMA, $S(0)$ fini non nul ; $1<\alpha<2$ : anti-persistance, $S(0)=0$ et $\sum_k\gamma_k=0$).</p>
<p><strong>Différenciation fractionnaire et FARIMA.</strong> L'opérateur de différenciation fractionnaire est défini pour $d$ réel par $(1-B)^d=\sum_{k\ge0}\binom{d}{k}(-1)^k B^{k}$. La classe <strong>FARIMA</strong> (fractional ARIMA) est la solution stationnaire de</p>
$$(1-B)^d\,\phi(B)\,X_t=\psi(B)\,\varepsilon_t,\qquad d=\frac{1-\alpha}{2}\in\left(-\tfrac12,\tfrac12\right),$$
<p>$\varepsilon_t$ i.i.d. centrées, $\phi,\psi$ de degrés $p,q$ à racines hors du cercle unité. $d$ entier $\Rightarrow$ ARIMA ordinaire ; $d\in(0,\tfrac12)\Rightarrow$ longue mémoire. Son spectre est $S(f)=\sigma_\varepsilon^2\dfrac{\lvert\psi(e^{-2\pi if})\rvert^2}{\lvert\phi(e^{-2\pi if})\rvert^2}\lvert1-e^{-2\pi if}\rvert^{-2d}\overset{f\to0}{\sim}c_f\,\lvert f\rvert^{-2d}$ avec $-2d=\alpha-1$. <strong>Intuition du pôle :</strong> $(1-B)$ a une réponse $1-e^{-2\pi if}$ nulle en $f=0$ (filtre passe-haut qui tue la tendance) ; une puissance fractionnaire négative inverse une fraction de cela, produisant un léger pôle en $0$ — la série est « un peu non stationnaire ».</p>
<p><strong>Conversion des trois paramètres</strong> ($\alpha\leftrightarrow d\leftrightarrow H$) : $d=\dfrac{1-\alpha}{2}$, $H=d+\tfrac12=1-\dfrac{\alpha}{2}$. La <strong>longue mémoire ralentit $\operatorname{Var}(\bar X)$</strong> : pour un spectre absolument continu $\operatorname{Var}(\bar X)\sim S(0)/n$ (taux $1/n$), mais sous longue mémoire $\operatorname{Var}(\bar X)\sim c/n^{\alpha}$ (plus lent), empreinte empirique (Smith, 1938).</p>
<p><strong>Auto-similarité et $B_H$.</strong> $\{Y_t\}$ est auto-similaire (self-similar) d'exposant de Hurst $H$ si $Y_{ct}\overset{d}{=}c^H Y_t$ pour tout $c>0$. Avec accroissements stationnaires, cela impose $\operatorname{Cov}(Y_t,Y_s)=\tfrac{\sigma^2}{2}(\lvert t\rvert^{2H}+\lvert s\rvert^{2H}-\lvert t-s\rvert^{2H})$. Le <strong>mouvement brownien fractionnaire</strong> $B_H(t)$ est le seul processus gaussien auto-similaire de cette covariance ; ses accroissements forment le bruit gaussien fractionnaire. <strong>Estimer $d$ :</strong> $\log I(f_j)\approx \mathrm{cste}-2d\log\lvert f_j\rvert$ près de $0$, d'où une régression log--log du périodogramme (méthode GPH) ; prendre le $\log$ <em>avant</em> l'espérance ($\mathbb{E}\log I\ne\log\mathbb{E}I$).</p>`}
  ],
  checks: [
    {q: String.raw`Pourquoi teste-t-on les résidus, et quelles sont les quatre propriétés vérifiées ?`, a: String.raw`Parce qu'un modèle correct a capté toute la structure prévisible : il ne reste que l'innovation $\varepsilon_t$. On vérifie donc sur $e_t=X_t-\hat X_t$ ce qu'on exigeait du bruit blanc : (1) moyenne nulle constante, (2) variance constante (homoscédasticité), (3) décorrélation en $t$, (4) gaussianité. Pour un AR(1) à vrais paramètres, $e_t=X_t-\phi X_{t-1}=\varepsilon_t$.`},
    {q: String.raw`Quelle est la statistique de Ljung--Box et quel est son nombre de degrés de liberté ?`, a: String.raw`$Q_m=n(n+2)\sum_{\tau=1}^{m}\dfrac{\hat r_\tau^{2}}{n-\tau}\overset{H_0}{\sim}\chi^2_{m-p-q}$ pour un ARMA$(p,q)$. Piège : df $=m-p-q$ (on soustrait les $p+q$ paramètres ARMA estimés, pas $\sigma^2$), et il faut $m>p+q$. Rejet $\Rightarrow$ modèle inadéquat.`},
    {q: String.raw`Pourquoi ne pas sélectionner un modèle par le $R^2$ ? Combien vaut-il pour un AR(1) ?`, a: String.raw`Ajouter des paramètres ne peut qu'augmenter le $R^2$, et même le vrai modèle est borné : pour un AR(1), $R^2=1-\dfrac{\sigma^2(1-\phi^2)}{\sigma^2}=\phi^2$ (ex. $\phi=0.4\Rightarrow R^2=0.16$). On utilise plutôt AIC/AICc/BIC (plus petit = mieux).`},
    {q: String.raw`Quand AIC et BIC pénalisent-ils différemment, et lequel est le plus parcimonieux ?`, a: String.raw`Pénalité par paramètre : $2$ (AIC) vs $\log n$ (BIC). BIC pénalise davantage dès que $\log n>2\iff n>e^2\approx7.4$. BIC est donc plus parcimonieux et consistant ; AIC tend à sur-ajuster $p$. AICc corrige le biais petit échantillon : $\mathrm{AICc}-\mathrm{AIC}=\dfrac{2k(k+1)}{n-k-1}>0$.`},
    {q: String.raw`Qu'est-ce que la longue mémoire, et comment se traduit-elle sur la covariance, le spectre et $\operatorname{Var}(\bar X)$ ? Lien $\alpha,d,H$ ?`, a: String.raw`Covariances polynomiales $\gamma_\tau\sim\lvert\tau\rvert^{-\alpha}$ ($0<\alpha<1$, non sommables), pôle spectral $S(0)=\infty$ ($S(f)\sim\lvert f\rvert^{\alpha-1}$), et $\operatorname{Var}(\bar X)\sim c/n^{\alpha}$ (plus lent que $1/n$). On a $d=\dfrac{1-\alpha}{2}\in(0,\tfrac12)$ et $H=d+\tfrac12=1-\dfrac{\alpha}{2}\in(\tfrac12,1)$ ; modèle = FARIMA.`}
  ],
  test: [
    {type:'open', q: String.raw`Pour $n=150$ observations on ajuste un ARMA$(1,1)$ centré ; les autocorrélations résiduelles aux retards $1$ à $4$ sont $\hat r_1=0.03$, $\hat r_2=-0.09$, $\hat r_3=0.11$, $\hat r_4=-0.05$. (a) Calculer la statistique de Ljung--Box $Q_4$. (b) Tester $H_0:\rho_1=\cdots=\rho_4=0$ au niveau $5\%$ ($\chi^2_2$ à $5\%$ : $5.991$ ; $\chi^2_3$ : $7.815$) : df, valeur critique, conclusion. (c) La conclusion changerait-elle pour un AR$(1)$ ?`,
     answer: String.raw`<div class="step"><strong>(a) Statistique.</strong> $Q_m=n(n+2)\sum_{\tau=1}^m\dfrac{\hat r_\tau^2}{n-\tau}$ avec $n(n+2)=150\cdot152=22800$ et $m=4$ : $$Q_4=22800\left(\frac{0.03^2}{149}+\frac{(-0.09)^2}{148}+\frac{0.11^2}{147}+\frac{(-0.05)^2}{146}\right).$$</div>
<div class="step">Terme par terme : $\dfrac{0.0009}{149}=6.04\times10^{-6}$ ; $\dfrac{0.0081}{148}=5.47\times10^{-5}$ ; $\dfrac{0.0121}{147}=8.23\times10^{-5}$ ; $\dfrac{0.0025}{146}=1.71\times10^{-5}$. Somme $=1.60\times10^{-4}$.</div>
<div class="step">D'où $Q_4\approx 22800\times1.60\times10^{-4}\approx 3.65$.</div>
<div class="step"><strong>(b) Test.</strong> Pour ARMA$(1,1)$, $p=q=1$, donc $\mathrm{df}=m-p-q=4-1-1=2$. Valeur critique à $5\%$ : quantile sup. de $\chi^2_2$ $=5.991$. Comme $Q_4\approx3.65<5.991$, on <strong>ne rejette pas</strong> $H_0$ : pas de preuve d'autocorrélation résiduelle, l'ARMA$(1,1)$ paraît adéquat.</div>
<div class="step"><strong>(c) AR(1).</strong> Alors $p=1,q=0$, donc $\mathrm{df}=4-1-0=3$ et la valeur critique monte à $7.815$. Comme $3.65<7.815$, conclusion inchangée (non-rejet). En général, moins de paramètres ajustés $\Rightarrow$ plus de degrés de liberté $\Rightarrow$ région d'acceptation plus large.</div>`, pts: 4},
    {type:'open', q: String.raw`Pour les mêmes données qu'à la question précédente ($n=150$, $\hat r_{1:4}=0.03,-0.09,0.11,-0.05$, ARMA$(1,1)$), calculer la statistique de <strong>Box--Pierce</strong> $Q_4^{\mathrm{BP}}$ et la comparer à la valeur Ljung--Box $Q_4\approx3.65$. La décision du test change-t-elle ? Pourquoi préfère-t-on Ljung--Box ?`,
     answer: String.raw`<div class="step"><strong>Statistique.</strong> Box--Pierce : $Q_m^{\mathrm{BP}}=n\sum_{\tau=1}^m\hat r_\tau^2$. La somme des carrés est $$\sum_{\tau=1}^4\hat r_\tau^2=0.03^2+0.09^2+0.11^2+0.05^2=0.0009+0.0081+0.0121+0.0025=0.0236.$$</div>
<div class="step">D'où $Q_4^{\mathrm{BP}}=150\times0.0236=3.54$.</div>
<div class="step"><strong>Comparaison.</strong> $3.54$ est légèrement inférieur à la valeur Ljung--Box $3.65$ : Ljung--Box gonfle chaque terme par le facteur $\dfrac{n+2}{n-\tau}>1$.</div>
<div class="step"><strong>Décision.</strong> Les deux utilisent $\mathrm{df}=4-1-1=2$ et la même valeur critique $5.991$. Comme $3.54<5.991$ et $3.65<5.991$, <strong>les deux ne rejettent pas</strong> $H_0$. La décision est identique.</div>
<div class="step"><strong>Pourquoi Ljung--Box.</strong> À $n=150$ les deux coïncident presque ; la différence ne compte qu'à petit $n$, où l'approximation $\chi^2$ de Box--Pierce est peu fiable et où la correction de Ljung--Box rapproche la variance finie de la cible $\chi^2$.</div>`, pts: 3},
    {type:'open', q: String.raw`Soient les critères $\mathrm{AIC}=-2\ln L+2k$ et $\mathrm{AICc}=-2\ln L+2k\,\dfrac{n}{n-k-1}$. (a) Calculer l'écart $\mathrm{AICc}-\mathrm{AIC}$ et montrer qu'il est positif. (b) Sous quelles conditions sur $n$ et $k$ les deux critères deviennent-ils approximativement équivalents ?`,
     answer: String.raw`<div class="step"><strong>(a) Écart.</strong> $$\mathrm{AICc}-\mathrm{AIC}=2k\left(\frac{n}{n-k-1}-1\right)=2k\cdot\frac{n-(n-k-1)}{n-k-1}=2k\cdot\frac{k+1}{n-k-1}=\frac{2k(k+1)}{n-k-1}.$$</div>
<div class="step">Pour $n>k+1$ (cas utile, sinon le critère n'est pas défini), le dénominateur est $>0$ et $2k(k+1)>0$, donc l'écart est <strong>strictement positif</strong> : AICc pénalise toujours davantage la complexité.</div>
<div class="step"><strong>(b) Équivalence.</strong> Les deux critères sont approximativement équivalents exactement quand ce terme de correction $\dfrac{2k(k+1)}{n-k-1}$ est petit.</div>
<div class="step">Si $k$ est <strong>fixé</strong> et $n\to\infty$, alors $\dfrac{2k(k+1)}{n-k-1}\to0$ : AICc $\to$ AIC.</div>
<div class="step">Si $k=k_n$ croît avec $n$, la correction reste petite tant que $n$ est grand devant $k_n^2$, c'est-à-dire $k_n^2/n\to0$. Si $k$ croît trop vite ($k_n^2/n\not\to0$), l'écart ne s'annule pas et AICc reste sensiblement plus conservateur. Conclusion : grands échantillons relativement au nombre de paramètres $\Rightarrow$ équivalence ; petits échantillons ou modèles richement paramétrés $\Rightarrow$ AICc strictement plus prudent.</div>`, pts: 4},
    {type:'open', q: String.raw`Avec $\mathrm{AIC}=-2\log L+2k$ et $\mathrm{BIC}=-2\log L+k\log n$ : (a) montrer que la pénalité BIC dépasse la pénalité AIC si et seulement si $n>e^2\approx7.4$. (b) Pour un $\log L$ fixé, un modèle à $k=3$ paramètres concurrence un modèle à $k=2$ paramètres, avec $n=50$. Quel critère est le plus enclin à choisir le plus gros modèle ? Justifier par les pénalités.`,
     answer: String.raw`<div class="step"><strong>(a)</strong> La pénalité par paramètre est $2$ pour AIC et $\log n$ pour BIC. La pénalité BIC est la plus grande ssi $$\log n>2\iff n>e^2\approx7.39.$$ Pour tout $n\ge8$ réaliste, BIC pénalise plus par paramètre, donc favorise des modèles plus parcimonieux.</div>
<div class="step"><strong>(b)</strong> Passer de $k=2$ à $k=3$ ajoute un paramètre. La pénalité supplémentaire vaut $2\times1=2$ pour AIC et $\log(50)\approx3.91$ pour BIC.</div>
<div class="step">Le plus gros modèle est retenu si la baisse de $-2\log L$ dépasse la pénalité ajoutée. AIC l'exige $>2$ (amélioration de $\log L$ $>1$) ; BIC l'exige $>3.91$ (amélioration de $\log L$ $>1.96$).</div>
<div class="step"><strong>Conclusion.</strong> Le seuil de BIC est plus élevé : <strong>AIC est le plus enclin à choisir le plus gros modèle</strong>, tandis que BIC, plus difficile à satisfaire, protège contre le sur-ajustement.</div>`, pts: 3},
    {type:'open', q: String.raw`Une série stationnaire a une ACVS $\gamma_\tau\sim c\,\lvert\tau\rvert^{-0.4}$ quand $\lvert\tau\rvert\to\infty$. (a) Trouver $\alpha$, le paramètre de différenciation fractionnaire $d$ et l'exposant de Hurst $H$. (b) Classer le régime de dépendance. (c) La somme $\sum_\tau\gamma_\tau$ est-elle finie ? Que fait $S(f)$ près de $f=0$ ? (d) Quel modèle paramétrique génère ce comportement ?`,
     answer: String.raw`<div class="step"><strong>(a)</strong> En identifiant $\gamma_\tau\sim L_\gamma(\tau)\lvert\tau\rvert^{-\alpha}$, on lit $\alpha=0.4$. Puis $d=\dfrac{1-\alpha}{2}=\dfrac{1-0.4}{2}=0.3$ et $H=d+\tfrac12=0.8$ (cohérent avec $H=1-\tfrac{\alpha}{2}=1-0.2=0.8$).</div>
<div class="step"><strong>(b) Régime.</strong> Comme $0<\alpha=0.4<1$ (de façon équivalente $0<d=0.3<\tfrac12$, ou $\tfrac12<H=0.8<1$), le processus est à <strong>longue mémoire / persistance positive</strong>.</div>
<div class="step"><strong>(c) Sommabilité et spectre.</strong> La queue $\lvert\tau\rvert^{-0.4}$ n'est <em>pas</em> sommable ($\sum\lvert\tau\rvert^{-\alpha}$ diverge pour $\alpha\le1$), donc $\sum_\tau\gamma_\tau=\infty$. En conséquence $S(f)\sim L_S(f)\lvert f\rvert^{\alpha-1}=L_S(f)\lvert f\rvert^{-0.6}\to\infty$ quand $f\to0$ : <strong>pôle spectral</strong> à l'origine, signature de la longue mémoire.</div>
<div class="step"><strong>(d) Modèle.</strong> Un FARIMA$(p,d,q)$ avec $d=0.3$, par exemple le processus fractionnairement différencié pur $(1-B)^{0.3}X_t=\varepsilon_t$ ; $d$ s'estime par régression log--log du périodogramme (GPH).</div>`, pts: 4},
    {type:'open', q: String.raw`Pour le mouvement brownien fractionnaire $B_H(t)$ de covariance $\operatorname{Cov}(B_H(t),B_H(s))=\dfrac{\sigma^2}{2}\big(\lvert t\rvert^{2H}+\lvert s\rvert^{2H}-\lvert t-s\rvert^{2H}\big)$ : (a) calculer $\operatorname{Var}(B_H(t))$ ; (b) vérifier au niveau des variances la relation d'auto-similarité $B_H(ct)\overset{d}{=}c^H B_H(t)$ ; (c) pour $H=\tfrac12$, identifier le processus et le régime de dépendance.`,
     answer: String.raw`<div class="step"><strong>(a) Variance.</strong> Poser $s=t$ : $$\operatorname{Var}(B_H(t))=\frac{\sigma^2}{2}\big(\lvert t\rvert^{2H}+\lvert t\rvert^{2H}-0\big)=\sigma^2\lvert t\rvert^{2H}.$$</div>
<div class="step"><strong>(b) Auto-similarité.</strong> $\operatorname{Var}(B_H(ct))=\sigma^2\lvert ct\rvert^{2H}=c^{2H}\sigma^2\lvert t\rvert^{2H}=c^{2H}\operatorname{Var}(B_H(t))=\operatorname{Var}(c^H B_H(t))$, cohérent avec $B_H(ct)\overset{d}{=}c^H B_H(t)$.</div>
<div class="step">Plus généralement, chaque entrée de la covariance se réécrit $\operatorname{Cov}(B_H(ct),B_H(cs))=\dfrac{\sigma^2}{2}(\lvert ct\rvert^{2H}+\lvert cs\rvert^{2H}-\lvert ct-cs\rvert^{2H})=c^{2H}\operatorname{Cov}(B_H(t),B_H(s))$. Pour un processus gaussien centré, l'égalité de toute la structure de covariance (à facteur $c^{2H}$) donne l'égalité en loi.</div>
<div class="step"><strong>(c) Cas $H=\tfrac12$.</strong> $\operatorname{Var}(B_{1/2}(t))=\sigma^2\lvert t\rvert$ et, pour $t,s\ge0$, $\operatorname{Cov}(B_{1/2}(t),B_{1/2}(s))=\dfrac{\sigma^2}{2}(\lvert t\rvert+\lvert s\rvert-\lvert t-s\rvert)=\sigma^2\min(t,s)$ : c'est le <strong>mouvement brownien standard</strong>.</div>
<div class="step">Ses accroissements sont un bruit blanc (décorrélé). $H=\tfrac12$ est la frontière sans mémoire / dépendance courte : $d=0$, $\alpha=1$.</div>`, pts: 4}
  ]
},
