{
  n: 4,
  title: String.raw`Estimation paramétrique : Yule–Walker & moindres carrés`,
  intro: String.raw`On a un modèle ARMA pour $\{X_t\}$ ; il reste à l'ajuster aux données $X_1,\dots,X_n$. Trois voies : la méthode des moments (Yule–Walker), les moindres carrés (forward / backward) et la reconstruction récursive des innovations pour ARMA. Le fait qui débloque tout : la causalité.`,
  sections: [
    {h: String.raw`Le cadre & le fait qui débloque tout : la causalité`, body: String.raw`<p>On suppose $\{X_t\}$ ARMA$(p,q)$ avec $\varepsilon_t \overset{iid}{\sim}\mathcal{N}(0,\sigma_\varepsilon^2)$ bruit blanc gaussien (Gaussian white noise) et la <strong>partie AR causale</strong> (racines de $\Phi(z)$ hors du cercle unité). Estimer signifie trouver les coefficients AR $\phi_1,\dots,\phi_p$, MA $\theta_1,\dots,\theta_q$ et la variance d'innovation $\sigma_\varepsilon^2$ à partir de $X_1,\dots,X_n$.</p>
<p><strong>L'intuition centrale.</strong> Causalité veut dire que $X_{t-k}$ ne dépend que d'innovations <em>strictement antérieures</em> à $\varepsilon_t$. Comme le bruit blanc est non corrélé, le terme croisé s'annule :</p>
$$\mathbb{E}[\varepsilon_t X_{t-k}] = 0 \quad \text{pour } k>0.$$
<p>C'est exactement ce qui transforme l'équation AR en un <strong>système linéaire propre</strong> dans les autocovariances. Sans causalité, le bruit « fuit » dans le passé et Yule–Walker tombe à l'eau. En multipliant au contraire par $X_t$, le terme croisé vaut $\mathbb{E}[\varepsilon_t X_t]=\sigma_\varepsilon^2$, ce qui fournit l'équation de la variance.</p>`},
    {h: String.raw`Yule–Walker : la méthode des moments pour un AR$(p)$`, body: String.raw`<p>Pour un AR$(p)$ causal de moyenne nulle, multiplier $X_t=\sum_{j=1}^p\phi_j X_{t-j}+\varepsilon_t$ par $X_{t-k}$ et prendre l'espérance donne, pour tout $k\ge 1$, les <strong>équations de Yule–Walker</strong> :</p>
$$\gamma_k=\sum_{j=1}^p\phi_j\,\gamma_{k-j},\qquad\text{soit}\qquad \boldsymbol\gamma=\Gamma\boldsymbol\phi,\quad \gamma_0=\sum_{j=1}^p\phi_j\gamma_j+\sigma_\varepsilon^2.$$
<p>Ici $\boldsymbol\gamma=(\gamma_1,\dots,\gamma_p)^{\top}$ et $\Gamma=(\gamma_{i-j})_{i,j=1}^p$ est <strong>symétrique Toeplitz</strong> avec $\gamma_0$ sur la diagonale (on utilise $\gamma_{-\tau}=\gamma_\tau$). On remplace l'ACVS de population par son analogue empirique (autocovariance échantillon, sample autocovariance)</p>
$$\hat\gamma_\tau=\frac1n\sum_{t=1}^{n-\lvert\tau\rvert}X_t X_{t+\lvert\tau\rvert},$$
<p>et on obtient les <strong>estimateurs de Yule–Walker</strong> :</p>
$$\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p,\qquad \hat\sigma_\varepsilon^2=\hat\gamma_0-\sum_{j=1}^p\hat\phi_j\,\hat\gamma_j.$$
<p><strong>Raccourci ACF.</strong> Si on ne donne que les autocorrélations $\hat\rho_\tau$, le même solve marche avec la matrice et le vecteur de corrélations : $\hat{\boldsymbol\phi}_p=\bar\Gamma_p^{-1}\hat{\boldsymbol\rho}_p$ où $\bar\Gamma_p=(\hat\rho_{i-j})$ et $\hat\rho_0=1$ ; le facteur $\hat\gamma_0$ se simplifie. Il ne sert plus que pour $\hat\sigma_\varepsilon^2=\hat\gamma_0\,(1-\sum_j\hat\phi_j\hat\rho_j)$. Cas AR(1) : $\hat\phi=\hat\rho_1=\hat\gamma_1/\hat\gamma_0$.</p>
<p><strong>Deux propriétés clés.</strong> (1) YW = meilleur prédicteur linéaire : les $\phi$ qui minimisent l'erreur quadratique de prévision un pas $\mathbb{E}[(Y_t-\sum_i\phi_i Y_{t-i})^2]$ satisfont <em>exactement</em> les équations de Yule–Walker — d'où l'accord asymptotique avec les moindres carrés. (2) <strong>Levinson–Durbin</strong> résout le système Toeplitz en $O(p^2)$ (au lieu de $O(p^3)$) et fournit gratuitement les autocorrélations partielles $\hat\alpha_k=\hat\phi_{k,k}$.</p>`},
    {h: String.raw`Moindres carrés forward / backward pour un AR$(p)$`, body: String.raw`<p><strong>Forward.</strong> On écrit l'équation AR pour les temps observables $t=p{+}1,\dots,n$ sous forme $\mathbf X_F=F\boldsymbol\phi+\boldsymbol\varepsilon$ et on minimise la somme des erreurs de prévision un pas :</p>
$$\mathrm{SS}_F(\boldsymbol\phi)=\sum_{t=p+1}^n\Big(X_t-\sum_{k=1}^p\phi_k X_{t-k}\Big)^2.$$
<p>C'est une régression linéaire ordinaire (OLS), de solution</p>
$$\hat{\boldsymbol\phi}_F=(F^{\top}F)^{-1}F^{\top}\mathbf X_F,\qquad \hat\sigma_F^2=\frac{\lVert \mathbf X_F-F\hat{\boldsymbol\phi}_F\rVert^2}{\,n-2p\,}.$$
<p>Les $p$ premières observations servent de valeurs de conditionnement. On divise par $n-2p$ car il y a $n-p$ résidus et $p$ coefficients ajustés.</p>
<p><strong>Backward.</strong> Par <strong>réversibilité temporelle</strong> d'un AR gaussien (le processus retourné $Y_t=X_{-t}$ est un AR$(p)$ avec les <em>mêmes</em> coefficients et la même $\sigma_\varepsilon^2$), on régresse chaque point sur ses lags <em>futurs</em> : $\mathbf X_B=B\boldsymbol\phi+\boldsymbol\nu$, en minimisant $\mathrm{SS}_B(\boldsymbol\phi)=\sum_{t=1}^{n-p}(X_t-\sum_k\phi_k X_{t+k})^2$, d'où $\hat{\boldsymbol\phi}_B=(B^{\top}B)^{-1}B^{\top}\mathbf X_B$. <strong>Forward–backward</strong> : on minimise $\mathrm{SS}_F+\mathrm{SS}_B$ (systèmes empilés) — environ deux fois plus de données effectives, donc estimateur plus stable près de la frontière de stationnarité.</p>
<p><strong>Intuition.</strong> Les trois variantes ne diffèrent que par <em>quels</em> $n-p$ résidus un pas elles élèvent au carré : le passé prédit le présent (forward), le futur prédit le présent (backward, licite car un AR gaussien retourné est le même modèle), ou les deux à la fois. <strong>Attention :</strong> les MC ne sont <em>pas</em> contraints à donner un modèle stationnaire — $\hat\Phi(z)$ peut avoir des racines dans le cercle unité (gênant pour la prévision, acceptable pour l'estimation spectrale). Yule–Walker, lui, donne <strong>toujours</strong> un ajustement stationnaire.</p>`},
    {h: String.raw`Moindres carrés pour ARMA : reconstruction récursive des innovations`, body: String.raw`<p>Pour un ARMA$(p,q)$, $\Phi(B)X_t=\Theta(B)\varepsilon_t$, les innovations $\{\varepsilon_t\}$ sont <em>non observées</em>. On ne peut donc plus faire une régression en un coup. On minimise</p>
$$S(\boldsymbol\phi,\boldsymbol\theta)=\sum_t\hat\varepsilon_t^{\,2},$$
<p>où, pour chaque valeur candidate des paramètres, les résidus sont <strong>reconstruits récursivement</strong> à partir de l'équation du modèle résolue pour $\varepsilon_t$, après avoir fixé à zéro les $q$ innovations (et données) pré-échantillon, p.ex. $\varepsilon_0=\varepsilon_{-1}=\dots=0$.</p>
<ul>
<li>MA(1) $X_t=\varepsilon_t-\theta\varepsilon_{t-1}\Rightarrow\varepsilon_t=X_t+\theta\varepsilon_{t-1}$ ;</li>
<li>ARMA(1,1) $X_t=\phi X_{t-1}+\varepsilon_t-\theta\varepsilon_{t-1}\Rightarrow\varepsilon_t=X_t-\phi X_{t-1}+\theta\varepsilon_{t-1}$.</li>
</ul>
<p><strong>Pourquoi ARMA est plus dur que AR.</strong> Le modèle est linéaire en les <em>données</em>, mais les innovations sont <em>latentes</em>. La boucle de rétroaction $\theta\hat\varepsilon_{t-1}$ rend $S$ <em>non quadratique</em> : la minimisation est numérique (pas de forme close), sauf dans le cas AR pur où elle redevient les moindres carrés forward. En déroulant la récurrence d'un MA(1), $\hat\varepsilon_t=\sum_{k=0}^{t-1}\theta^k X_{t-k}$ est un polynôme de degré $t-1$ en $\theta$, donc $S(\theta)$ est de degré $2(n-1)$ — d'où, en général, un solveur numérique.</p>
<p><strong>À retenir / pièges.</strong> Ne pas mettre $\gamma_0$ dans le second membre du système de YW ; diviser $\hat\sigma^2$ par $n-2p$ (pas $n$) ; ne jamais oublier l'initialisation à zéro de la récurrence ARMA. Pour $n$ grand, YW et MC donnent des estimations AR quasi identiques (à l'ordre dominant $\hat\mu\approx\bar Y$ et $\hat\phi\approx\hat\rho_1$).</p>`}
  ],
  checks: [
    {q: String.raw`Quel fait précis sur les innovations rend les équations de Yule–Walker valides, et d'où vient-il ?`,
     a: String.raw`La causalité : $X_{t-k}$ ne dépend que d'innovations antérieures à $\varepsilon_t$, donc $\mathbb{E}[\varepsilon_t X_{t-k}]=0$ pour $k>0$. Le bruit blanc étant non corrélé, le terme croisé disparaît et l'équation AR devient un système linéaire dans les ACVS.`},
    {q: String.raw`Pour un AR(1), à quoi se réduit l'estimateur de Yule–Walker de $\phi$ ?`,
     a: String.raw`À l'autocorrélation empirique au retard 1 : $\hat\phi=\hat\rho_1=\hat\gamma_1/\hat\gamma_0$. La variance vaut $\hat\sigma_\varepsilon^2=\hat\gamma_0-\hat\phi\hat\gamma_1=\hat\gamma_0(1-\hat\phi^2)$.`},
    {q: String.raw`Par combien divise-t-on la somme des carrés des résidus pour estimer $\sigma^2$ en MC forward d'un AR$(p)$, et pourquoi ?`,
     a: String.raw`Par $n-2p$ : il y a $n-p$ résidus (temps $p{+}1,\dots,n$) et $p$ coefficients ajustés, soit $(n-p)-p=n-2p$ degrés de liberté.`},
    {q: String.raw`Pourquoi la régression backward utilise-t-elle les mêmes coefficients $\phi$ que la forward ?`,
     a: String.raw`Par réversibilité temporelle d'un AR gaussien : un gaussien stationnaire est déterminé par son ACVS et $\gamma_{-\tau}=\gamma_\tau$, donc $Y_t=X_{-t}$ est un AR$(p)$ avec les mêmes coefficients et la même $\sigma_\varepsilon^2$.`},
    {q: String.raw`Pourquoi l'estimation MC d'un MA/ARMA n'est-elle pas une simple régression, contrairement à l'AR ?`,
     a: String.raw`Parce que les innovations $\varepsilon_t$ sont latentes. Il faut les reconstruire récursivement (en fixant $\varepsilon_0=0$) avant de les élever au carré ; la rétroaction rend $S$ non quadratique, donc minimisation numérique.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer la proposition des équations de Yule–Walker pour un AR$(p)$ causal de moyenne nulle (avec toutes les hypothèses), puis la démontrer : la récursion $\gamma_k=\sum_{j=1}^p\phi_j\gamma_{k-j}$ pour $k\ge1$ et l'équation de variance $\gamma_0=\sum_{j=1}^p\phi_j\gamma_j+\sigma_\varepsilon^2$.`,
     answer: String.raw`<div class="step"><strong>Hypothèses.</strong> $\{X_t\}$ est un AR$(p)$ de moyenne nulle, $X_t=\sum_{j=1}^p\phi_j X_{t-j}+\varepsilon_t$, avec $\varepsilon_t$ bruit blanc $\mathbb{E}[\varepsilon_t]=0$, $\operatorname{Var}(\varepsilon_t)=\sigma_\varepsilon^2$, et la partie AR <strong>causale</strong> : $X_{t-k}$ est fonction des seules innovations $\varepsilon_{t-k},\varepsilon_{t-k-1},\dots$. Conclusion : pour $k\ge1$, $\gamma_k=\sum_{j=1}^p\phi_j\gamma_{k-j}$ et $\gamma_0=\sum_{j=1}^p\phi_j\gamma_j+\sigma_\varepsilon^2$.</div>
<div class="step"><strong>Récursion ($k\ge1$).</strong> On multiplie l'équation AR par $X_{t-k}$ et on prend l'espérance : $\mathbb{E}[X_t X_{t-k}]=\sum_{j=1}^p\phi_j\,\mathbb{E}[X_{t-j}X_{t-k}]+\mathbb{E}[\varepsilon_t X_{t-k}]$.</div>
<div class="step"><strong>Causalité.</strong> Pour $k>0$, $X_{t-k}$ ne dépend que d'innovations antérieures à $\varepsilon_t$ ; le bruit blanc étant non corrélé, $\mathbb{E}[\varepsilon_t X_{t-k}]=0$. Comme $\{X_t\}$ est de moyenne nulle, $\mathbb{E}[X_{t-j}X_{t-k}]=\gamma_{k-j}$. D'où $\gamma_k=\sum_{j=1}^p\phi_j\gamma_{k-j}$.</div>
<div class="step"><strong>Forme matricielle.</strong> En prenant $k=1,\dots,p$ et en utilisant $\gamma_{-\tau}=\gamma_\tau$, on obtient $\boldsymbol\gamma=\Gamma\boldsymbol\phi$, avec $\boldsymbol\gamma=(\gamma_1,\dots,\gamma_p)^{\top}$ et $\Gamma=(\gamma_{i-j})_{i,j=1}^p$ symétrique Toeplitz.</div>
<div class="step"><strong>Équation de variance ($k=0$).</strong> On multiplie l'équation AR par $X_t$ : $\gamma_0=\sum_{j=1}^p\phi_j\gamma_j+\mathbb{E}[\varepsilon_t X_t]$. Or $\varepsilon_t X_t=\sum_j\phi_j\varepsilon_t X_{t-j}+\varepsilon_t^2$ ; comme $\mathbb{E}[\varepsilon_t X_{t-j}]=0$ pour $j\ge1$, il vient $\mathbb{E}[\varepsilon_t X_t]=\sigma_\varepsilon^2$, donc $\gamma_0=\sum_{j=1}^p\phi_j\gamma_j+\sigma_\varepsilon^2$. $\square$</div>`, pts: 4},
    {type:'open', q: String.raw`Pour la série des taches solaires de Wolfer, les autocovariances échantillon sont $\hat\gamma_0=1382.185$, $\hat\gamma_1=1114.378$, $\hat\gamma_2=591.721$. Ajuster par Yule–Walker le modèle AR(2) $Y_t=\phi_1 Y_{t-1}+\phi_2 Y_{t-2}+\varepsilon_t$ ($Y_t$ centré) : estimer $\hat\phi_1,\hat\phi_2,\hat\sigma_\varepsilon^2$, puis vérifier la causalité du modèle ajusté.`,
     answer: String.raw`<div class="step"><strong>Système YW.</strong> Pour $p=2$, $\hat\Gamma_2\hat{\boldsymbol\phi}=\hat{\boldsymbol\gamma}_2$ s'écrit $\begin{pmatrix}\hat\gamma_0 & \hat\gamma_1\\ \hat\gamma_1 & \hat\gamma_0\end{pmatrix}\begin{pmatrix}\hat\phi_1\\ \hat\phi_2\end{pmatrix}=\begin{pmatrix}\hat\gamma_1\\ \hat\gamma_2\end{pmatrix}$, soit $\begin{pmatrix}1382.185 & 1114.378\\ 1114.378 & 1382.185\end{pmatrix}\begin{pmatrix}\hat\phi_1\\ \hat\phi_2\end{pmatrix}=\begin{pmatrix}1114.378\\ 591.721\end{pmatrix}$.</div>
<div class="step"><strong>Inversion.</strong> Pour $\begin{pmatrix}a&b\\ b&a\end{pmatrix}$, l'inverse est $\frac{1}{a^2-b^2}\begin{pmatrix}a&-b\\ -b&a\end{pmatrix}$. Ici $a=1382.185$, $b=1114.378$, déterminant $a^2-b^2=1.9104\times10^6-1.2418\times10^6=6.686\times10^5$.</div>
<div class="step"><strong>Coefficients.</strong> $\hat{\boldsymbol\phi}=\frac{1}{6.686\times10^5}\begin{pmatrix}1382.185 & -1114.378\\ -1114.378 & 1382.185\end{pmatrix}\begin{pmatrix}1114.378\\ 591.721\end{pmatrix}\approx\begin{pmatrix}1.3175\\ -0.6341\end{pmatrix}$.</div>
<div class="step"><strong>Variance d'innovation.</strong> $\hat\sigma_\varepsilon^2=\hat\gamma_0-\hat\phi_1\hat\gamma_1-\hat\phi_2\hat\gamma_2=1382.185-1.3175(1114.378)-(-0.6341)(591.721)\approx 289.21$.</div>
<div class="step"><strong>Causalité.</strong> $\hat\Phi(z)=1-1.3175z+0.6341z^2$. Discriminant $1.3175^2-4(0.6341)=1.7358-2.5364<0$ : racines complexes conjuguées. Le produit des racines vaut $1/0.6341$, donc $\lvert z\rvert=1/\sqrt{0.6341}\approx 1.256>1$. Toutes les racines sont hors du cercle unité : le modèle ajusté est causal (stationnaire). $\square$</div>`, pts: 4},
    {type:'open', q: String.raw`Démontrer que, pour $\{Y_t\}$ stationnaire de moyenne nulle d'ACVS $\gamma$, les $\phi_1,\dots,\phi_k$ qui minimisent l'erreur quadratique de prévision un pas $\mathbb{E}\big[(Y_t-\sum_{i=1}^k\phi_i Y_{t-i})^2\big]$ satisfont les équations de Yule–Walker $\gamma_j=\sum_{i=1}^k\phi_i\gamma_{j-i}$, $j=1,\dots,k$.`,
     answer: String.raw`<div class="step"><strong>Réduction à une variance.</strong> Posons $W=Y_t-\sum_{i=1}^k\phi_i Y_{t-i}$. Alors $\mathbb{E}[W^2]=\operatorname{Var}(W)+(\mathbb{E}[W])^2$. Par stationnarité $\mathbb{E}[W]=(1-\sum_i\phi_i)\mathbb{E}[Y_t]$, qui s'annule car $\{Y_t\}$ est de moyenne nulle. Donc $\mathbb{E}[W^2]=\operatorname{Var}(W)$.</div>
<div class="step"><strong>Développement bilinéaire.</strong> $\operatorname{Var}(W)=\operatorname{Cov}\big(Y_t-\sum_i\phi_i Y_{t-i},\,Y_t-\sum_j\phi_j Y_{t-j}\big)=\gamma_0-2\sum_{i=1}^k\phi_i\gamma_i+\sum_{i=1}^k\sum_{j=1}^k\phi_i\phi_j\gamma_{i-j}$.</div>
<div class="step"><strong>Forme quadratique.</strong> C'est une forme quadratique positive (semi-définie) en $\boldsymbol\phi$, donc son unique point stationnaire est le minimum global.</div>
<div class="step"><strong>Annulation du gradient.</strong> En dérivant par rapport à $\phi_i$ (et en combinant les deux termes de la double somme via $\gamma_{i-j}=\gamma_{j-i}$) : $\dfrac{\partial\mathbb{E}[W^2]}{\partial\phi_i}=-2\gamma_i+2\sum_{j=1}^k\phi_j\gamma_{i-j}=0$.</div>
<div class="step"><strong>Conclusion.</strong> D'où $\gamma_i=\sum_{j=1}^k\phi_j\gamma_{i-j}$ pour $i=1,\dots,k$ : ce sont exactement les équations de Yule–Walker. YW estime donc les poids du meilleur prédicteur linéaire un pas. $\square$</div>`, pts: 4},
    {type:'open', q: String.raw`Une série de longueur $100$ a pour ACF empirique $\hat\rho_1=0.8$, $\hat\rho_2=0.5$, $\hat\rho_3=0.4$. En supposant un AR(3) de moyenne nulle, estimer $\phi_1,\phi_2,\phi_3$ par Yule–Walker. (Indication : utiliser le raccourci ACF.)`,
     answer: String.raw`<div class="step"><strong>Raccourci ACF.</strong> Diviser le système YW par $\hat\gamma_0$ remplace covariances par corrélations : $\hat{\boldsymbol\phi}=\bar\Gamma_3^{-1}\hat{\boldsymbol\rho}_3$ avec $\bar\Gamma_3=(\hat\rho_{i-j})$ et $\hat\rho_0=1$. La longueur $n=100$ n'entre pas dans le calcul du point estimé.</div>
<div class="step"><strong>Système.</strong> $\begin{pmatrix}1 & 0.8 & 0.5\\ 0.8 & 1 & 0.8\\ 0.5 & 0.8 & 1\end{pmatrix}\begin{pmatrix}\hat\phi_1\\ \hat\phi_2\\ \hat\phi_3\end{pmatrix}=\begin{pmatrix}0.8\\ 0.5\\ 0.4\end{pmatrix}$.</div>
<div class="step"><strong>Résolution.</strong> Par élimination de Gauss on obtient $\hat{\boldsymbol\phi}=(1.30909,\,-0.95455,\,0.50909)^{\top}$.</div>
<div class="step"><strong>Vérification (ligne 1).</strong> $1(1.30909)+0.8(-0.95455)+0.5(0.50909)=1.30909-0.76364+0.25455=0.8$. Conforme.</div>
<div class="step"><strong>Vérification (ligne 3).</strong> $0.5(1.30909)+0.8(-0.95455)+1(0.50909)=0.65455-0.76364+0.50909=0.4$. Conforme. Donc $\hat\phi_1\approx1.309$, $\hat\phi_2\approx-0.955$, $\hat\phi_3\approx0.509$. $\square$</div>`, pts: 3},
    {type:'open', q: String.raw`On observe un MA(1) de moyenne nulle $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ aux valeurs $X_1=0$, $X_2=1$, $X_3=0.5$. Estimer $\theta$ par moindres carrés (reconstruction récursive des innovations) et vérifier l'inversibilité. Expliquer pourquoi ce problème jouet est exactement quadratique alors qu'en général il ne l'est pas.`,
     answer: String.raw`<div class="step"><strong>Résoudre pour l'innovation.</strong> Les $\varepsilon_t$ sont latentes ; on inverse l'équation du modèle : $\varepsilon_t=X_t+\theta\varepsilon_{t-1}$. On prend $t=0$ comme origine et on initialise $\varepsilon_0=0$.</div>
<div class="step"><strong>Récurrence.</strong> $\hat\varepsilon_1=X_1+\theta\varepsilon_0=0$ ; $\hat\varepsilon_2=X_2+\theta\hat\varepsilon_1=1$ ; $\hat\varepsilon_3=X_3+\theta\hat\varepsilon_2=0.5+\theta$.</div>
<div class="step"><strong>Critère.</strong> $S(\theta)=\sum_{t=1}^3\hat\varepsilon_t^2=0^2+1^2+(0.5+\theta)^2=1+(0.5+\theta)^2$.</div>
<div class="step"><strong>Minimisation.</strong> $S$ est minimal quand $(0.5+\theta)^2$ l'est, donc en $\hat\theta=-0.5$. Comme $\lvert\hat\theta\rvert=0.5<1$, le polynôme $\Theta(z)=1-\theta z=1+0.5z$ a sa racine $z=-1/\theta=2$ hors du cercle unité : le modèle est inversible.</div>
<div class="step"><strong>Pourquoi quadratique ici, pas en général.</strong> En déroulant la récurrence, $\hat\varepsilon_t=\sum_{k=0}^{t-1}\theta^k X_{t-k}$ est un polynôme de degré $t-1$ en $\theta$, donc $S(\theta)$ est de degré $2(n-1)$ — généralement plusieurs points stationnaires, d'où un solveur numérique. Ici $X_1=0$ force $\hat\varepsilon_1=0$ et $\hat\varepsilon_2=1$ (sans $\theta$) ; seul $\hat\varepsilon_3=0.5+\theta$ est <em>linéaire</em> en $\theta$, donc $S$ est exactement quadratique : le résultat propre est un artefact de $X_1=0$. $\square$</div>`, pts: 4},
    {type:'open', q: String.raw`Pour un ARMA(1,1) de moyenne nulle $X_t=\phi X_{t-1}+\varepsilon_t-\theta\varepsilon_{t-1}$, écrire la récurrence reconstruisant $\hat\varepsilon_1,\dots,\hat\varepsilon_4$ comme fonctions de $(\phi,\theta)$ à partir de $X_1,X_2,X_3,X_4$, en précisant l'initialisation, puis exhiber l'objectif des moindres carrés et expliquer pourquoi il faut le minimiser numériquement.`,
     answer: String.raw`<div class="step"><strong>Résoudre pour l'innovation courante.</strong> $\varepsilon_t=X_t-\phi X_{t-1}+\theta\varepsilon_{t-1}$.</div>
<div class="step"><strong>Initialisation.</strong> On fixe à zéro la donnée et l'innovation pré-échantillon : $X_0=0$ et $\varepsilon_0=0$ (il y a $q=1$ innovation initiale à annuler).</div>
<div class="step"><strong>Récurrence.</strong> $\hat\varepsilon_1=X_1-\phi X_0+\theta\varepsilon_0=X_1$ ; $\hat\varepsilon_2=X_2-\phi X_1+\theta\hat\varepsilon_1=X_2-\phi X_1+\theta X_1$ ; $\hat\varepsilon_3=X_3-\phi X_2+\theta\hat\varepsilon_2=X_3-\phi X_2+\theta(X_2-\phi X_1+\theta X_1)$ ; $\hat\varepsilon_4=X_4-\phi X_3+\theta\hat\varepsilon_3$.</div>
<div class="step"><strong>Objectif MC.</strong> $S(\phi,\theta)=\sum_{t=1}^4\hat\varepsilon_t^{\,2}=\sum_{t=1}^4\big(X_t-\phi X_{t-1}+\theta\hat\varepsilon_{t-1}\big)^2$.</div>
<div class="step"><strong>Pourquoi numérique.</strong> À cause de la rétroaction $\theta\hat\varepsilon_{t-1}$, chaque $\hat\varepsilon_t$ accumule des puissances croissantes de $\theta$ (degré $t-1$), donc $S$ n'est <em>pas</em> quadratique en $\theta$ : pas de forme close, il faut un optimiseur numérique. C'est la recette ARMA$(p,q)$ générale avec ici $q=1$ innovation pré-échantillon mise à zéro. $\square$</div>`, pts: 4}
  ]
},
