{
  n: 5,
  title: String.raw`Tendances, saisonnalité & SARIMA`,
  intro: String.raw`Une vraie série dérive (tendance) et se répète (saison) : on la rend stationnaire en retirant ces composantes par différenciation, et ARIMA/SARMA encodent tout cela dans des polynômes en $B$.`,
  sections: [
    {h: String.raw`Modèle tendance + bruit et différenciation`, body: String.raw`<p>Une série réelle n'est presque jamais stationnaire. Le modèle de travail est le <strong>signal plus bruit</strong> (signal-plus-noise) $X_t=\mu_t+Y_t$, où $\mu_t$ est une moyenne déterministe dépendant du temps (la <strong>tendance</strong>, trend) et $\{Y_t\}$ est centré et stationnaire à l'ordre 2. Cas typiques : $\mu_t=a+bt$ (linéaire), $\mu_t$ polynôme de degré $q-1$, ou $\mu_t=s_t$ <strong>périodique</strong> de période $s$ ($s_{t+s}=s_t$). Les deux peuvent coexister : $X_t=a+bt+s_t+Y_t$.</p>
<p>Deux façons d'enlever $\mu_t$. <strong>Régresser-et-soustraire</strong> : on estime $a,b$ (ou des harmoniques $\sin/\cos$) par moindres carrés et on analyse les résidus ; c'est interprétable mais suppose connue la forme de la tendance. <strong>Différencier</strong> avec l'opérateur de différence (difference operator) $\nabla=I-B$, où $B$ est le retard (backshift) $BX_t=X_{t-1}$ : c'est sans modèle et robuste.</p>
<p>La différence ordinaire est $\nabla X_t=X_t-X_{t-1}$. Linéaire, sa $d$-ième puissance se développe par le binôme : $$\nabla^{d}=(I-B)^{d}=\sum_{k=0}^{d}\binom{d}{k}(-1)^{k}B^{k},\qquad \nabla^{2}X_t=X_t-2X_{t-1}+X_{t-2}.$$ La différence <strong>saisonnière</strong> (seasonal difference) de période $s$ est $\nabla_{(s)}=I-B^{s}$, soit $\nabla_{(s)}X_t=X_t-X_{t-s}$ : <em>deux</em> termes seulement. Attention, $\nabla_{(s)}$ n'est <strong>pas</strong> $\nabla^{s}=(I-B)^{s}$ : la première tue une saison de période $s$, la seconde un polynôme de degré $s-1$ (erreur d'examen classique).</p>
<p><strong>Intuition.</strong> $\nabla$ abaisse le degré d'un polynôme en $t$ d'exactement un : $\nabla$ tue toute dérive linéaire, $\nabla^{q}$ tout polynôme de degré $q-1$, $\nabla_{(s)}$ toute saison de période $s$, au prix d'une légère déformation du bruit ($\nabla Y_t$ remplace $Y_t$).</p>`},
    {h: String.raw`Retirer tendance et saison : les résultats clés`, body: String.raw`<p><strong>$\nabla$ tue une tendance linéaire.</strong> Si $X_t=a+bt+Y_t$ avec $\{Y_t\}$ stationnaire, alors $$\nabla X_t=X_t-X_{t-1}=b+\nabla Y_t,$$ donc la tendance $a+bt$ se réduit à la constante $b$, et $\nabla Y_t$ (combinaison linéaire finie d'un processus stationnaire) reste stationnaire. Plus généralement, si $\mu_t$ est de degré $q-1$, alors $\nabla^{q}\mu_t\equiv 0$ et $\nabla^{q}X_t=\nabla^{q}Y_t$ : il faut donc $d=q$ différences pour aplatir un trend polynomial de degré $q-1$.</p>
<p><strong>Tendance linéaire + saison mensuelle.</strong> Si $X_t=a+bt+s_t+Y_t$ avec $s_{t+12}=s_t$ et $\{Y_t\}$ centré stationnaire d'ACVS $\gamma_\tau$, on applique d'abord $\nabla_{(12)}$ puis $\nabla$ : $$\nabla\nabla_{(12)}X_t=\nabla\nabla_{(12)}Y_t=Y_t-Y_{t-1}-Y_{t-12}+Y_{t-13}.$$ C'est une combinaison linéaire <em>fixe</em> de $\{Y_t\}$, de moyenne $0$ et de covariance ne dépendant que du décalage $\tau$ : faiblement stationnaire (justification du pré-traitement standard des données mensuelles, type $\mathrm{CO}_2$ de Mauna Loa).</p>
<p><strong>Idée.</strong> $\nabla_{(12)}$ tue $s_t$ et transforme $bt$ en la constante $12b$ ($bt-b(t-12)=12b$) ; puis $\nabla$ tue cette constante. Cas <em>multiplicatif</em> $X_t=(a+bt)s_t+Y_t$ : c'est $\nabla_{(12)}^{2}$ (et non $\nabla\nabla_{(12)}$) qui aplatit, donnant $\nabla_{(12)}^{2}X_t=Y_t-2Y_{t-12}+Y_{t-24}$.</p>
<p><strong>Ordre des opérations.</strong> D'abord $\nabla_{(s)}$ (retirer la saison), puis $\nabla^{d}$ (retirer le trend). On <strong>s'arrête</strong> quand la série différenciée a moyenne stable, variance constante et ACF décroissant vite.</p>`},
    {h: String.raw`Modèles saisonniers : SMA, SAR et SARMA`, body: String.raw`<p>Pour modéliser la saison dans la partie stochastique, on n'agit qu'aux retards multiples de $s$. La <strong>moyenne mobile saisonnière</strong> (seasonal MA) $\mathrm{SMA}(Q)_s$ s'écrit $$X_t=\varepsilon_t-\sum_{j=1}^{Q}\theta^{(s)}_j\varepsilon_{t-js}=\Theta^{(s)}(B)\varepsilon_t,\qquad \Theta^{(s)}(z)=1-\sum_{j=1}^{Q}\theta^{(s)}_j z^{sj}.$$ L'<strong>autorégression saisonnière</strong> (seasonal AR) $\mathrm{SAR}(P)_s$ est $X_t=\varepsilon_t+\sum_{j=1}^{P}\phi^{(s)}_jX_{t-js}$, soit $\Phi^{(s)}(B)X_t=\varepsilon_t$ avec $\Phi^{(s)}(z)=1-\sum_j\phi^{(s)}_j z^{sj}$. Ici $\{\varepsilon_t\}$ est un bruit blanc (white noise) centré de variance $\sigma_\varepsilon^2$.</p>
<p>La <strong>SARMA$(p,q)\times(P,Q)_s$</strong> multiplicative combine une ARMA ordinaire et une ARMA saisonnière : $$\Phi(B)\,\Phi^{(s)}(B)\,X_t=\Theta(B)\,\Theta^{(s)}(B)\,\varepsilon_t.$$ Cas particuliers : $\mathrm{SMA}(Q)_s=\mathrm{SARMA}(0,0)\times(0,Q)_s$ et $\mathrm{SAR}(P)_s=\mathrm{SARMA}(0,0)\times(P,0)_s$. Exemple $\mathrm{SARMA}(0,1)\times(0,1)_{12}$ : $X_t=(1-\theta B)(1-\theta^{(12)}B^{12})\varepsilon_t$.</p>
<p><strong>Empreinte d'une $\mathrm{SMA}(1)_s$ dans le corrélogramme.</strong> Pour $X_t=\varepsilon_t-\theta\varepsilon_{t-s}$, la règle du filtre de bruit blanc $\gamma_\tau=\sigma_\varepsilon^2\sum_j a_j a_{j+\tau}$ (avec $a_0=1,\ a_s=-\theta$) donne $\gamma_0=(1+\theta^2)\sigma_\varepsilon^2$, $\gamma_{\pm s}=-\theta\sigma_\varepsilon^2$, $\gamma_\tau=0$ ailleurs, donc $$\rho_{\pm s}=\frac{-\theta}{1+\theta^{2}},\qquad \rho_\tau=0 \text{ aux autres retards.}$$ Un <em>unique</em> pic d'ACF au retard saisonnier $s$ signale une composante $\mathrm{SMA}(1)_s$.</p>
<p><strong>Développer une SARMA.</strong> Traiter $B$ comme une variable formelle, multiplier les quatre facteurs, lire les retards survivants (le facteur saisonnier ne contribue qu'aux multiples de $s$, les produits croisés donnent des retards $s\pm 1$), puis remplacer $B^{k}X_t=X_{t-k}$ et résoudre pour $X_t$ (récurrence à un pas).</p>`},
    {h: String.raw`ARIMA, SARIMA et la marche aléatoire`, body: String.raw`<p>$\{X_t\}$ est une <strong>ARIMA$(p,d,q)$</strong> (« ARMA intégrée », integrated ARMA) si sa $d$-ième différence est une ARMA$(p,q)$ causale et inversible : $$\Phi(B)\,(1-B)^{d}X_t=\Theta(B)\,\varepsilon_t,\qquad Z_t=\nabla^{d}X_t=\sum_{j=1}^{p}\phi_jZ_{t-j}+\varepsilon_t-\sum_{j=1}^{q}\theta_j\varepsilon_{t-j}.$$ Le « I » = <em>intégrée</em> : on retrouve $X_t$ en sommant ($d$ fois) $Z_t$, l'inverse de différencier. ARMA = cas $d=0$. Le modèle complet <strong>SARIMA$(p,d,q)\times(P,D,Q)_s$</strong> plie devant la SARMA une différence ordinaire d'ordre $d$ <em>et</em> une différence saisonnière d'ordre $D$ : $$\Phi(B)\,\Phi^{(s)}(B)\,(1-B)^{d}(1-B^{s})^{D}\,X_t=\Theta(B)\,\Theta^{(s)}(B)\,\varepsilon_t.$$ Ici $d$ retire un trend polynomial, $D$ un motif saisonnier (éventuellement stochastique), et les quatre polynômes captent le reste de la dépendance.</p>
<p><strong>La marche aléatoire (random walk) est non stationnaire.</strong> Pour $X_t=X_{t-1}+\varepsilon_t=\sum_{j=1}^{t}\varepsilon_j$ ($X_0=0$) : $$\mathbb{E}[X_t]=0,\quad \operatorname{Var}(X_t)=t\,\sigma_\varepsilon^2,\quad \operatorname{Cov}(X_t,X_{t+\tau})=t\,\sigma_\varepsilon^2,$$ tout dépend de $t$. Mais $\nabla X_t=\varepsilon_t$ est un bruit blanc : c'est une ARIMA$(0,1,0)$. C'est l'AR(1) à la frontière $\phi=1$ (racine unité, unit root).</p>
<p><strong>Croissance d'ordre 2 d'une IMA$(1,1)$.</strong> Pour $Y_t=Y_{t-1}+\varepsilon_t-\theta\varepsilon_{t-1}$ (ARIMA$(0,1,1)$, $Y_0=0$), on déroule $Y_t=\varepsilon_t+(1-\theta)\sum_{j=1}^{t-1}\varepsilon_j-\theta\varepsilon_0$, d'où $$\operatorname{Var}(Y_t)=\sigma_\varepsilon^2\bigl[1+(1-\theta)^{2}(t-1)+\theta^{2}\bigr],$$ qui croît <em>linéairement</em> en $t$ (pente $(1-\theta)^2\sigma_\varepsilon^2$), et la corrélation entre instants proches tend vers $1$. Même phénomène pour l'ARI$(1,1)$ : intégrer une AR(1) bien sage recrée la croissance de variance et la corrélation $\to 1$ de la marche aléatoire.</p>`},
    {h: String.raw`Diagnostic : faut-il différencier ? Et le piège de la sur-différenciation`, body: String.raw`<p><strong>Symptômes d'un trend / racine unité résiduelle.</strong> ACF empirique qui décroît <em>lentement</em> et variance qui croît à peu près linéairement avec $t$ (valeurs voisines presque parfaitement corrélées). C'est exactement la signature des résultats IMA$(1,1)$ / ARI$(1,1)$ : il faut alors différencier.</p>
<p><strong>Choisir $d$ et $D$.</strong> Trend de degré $q-1\Rightarrow d=q$ (linéaire $\Rightarrow d=1$, quadratique $\Rightarrow d=2$). Saison fixe de période $s\Rightarrow D=1$ (rarement $2$). On applique $\nabla_{(s)}$ <em>puis</em> $\nabla^{d}$ ; pour du mensuel à dérive linéaire, c'est $\nabla\nabla_{(12)}$.</p>
<p><strong>Ne pas SUR-différencier (over-differencing).</strong> Différencier une série <em>déjà</em> stationnaire injecte un facteur $(1-B)$ dans la partie MA : on crée une MA(1) <strong>non inversible</strong>. À la frontière $\theta=1$, $Y_t=Y_{t-1}+\varepsilon_t-\varepsilon_{t-1}$ télescope en $Y_t=\varepsilon_t-\varepsilon_0$, donc $\nabla Y_t=\varepsilon_t-\varepsilon_{t-1}$ a $\rho_1=-\theta/(1+\theta^2)=-\tfrac12$. Donc : voir $\rho_1\approx-\tfrac12$ après différenciation = signal de différencier <em>une fois de moins</em>.</p>
<p><strong>Poids $\psi_j$ (MA$(\infty)$).</strong> Pour passer de $\Phi(B)X_t=\Theta(B)\varepsilon_t$ à $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$ : inverser l'AR en série géométrique $1/(1-\phi B)=\sum_l\phi^{l}B^{l}$ (valide si $|\phi|<1$), multiplier par le numérateur MA, identifier les puissances de $B$ : $\psi_j=\theta^{(\mathrm{num})}_j+\sum_{i}\phi_i\psi_{j-i}$, $\psi_0=1$. Au-delà du plus haut retard du numérateur, la récurrence pure $\psi_j=\sum_i\phi_i\psi_{j-i}$ prend le relais (raccourci décisif).</p>`}
  ],
  checks: [
    {q: String.raw`Pourquoi $\nabla_{(s)}$ n'est-il pas la même chose que $\nabla^{s}$ ?`, a: String.raw`$\nabla_{(s)}=I-B^{s}$ soustrait la valeur $s$ pas en arrière ($X_t-X_{t-s}$, deux termes) et tue une saison de période $s$. $\nabla^{s}=(I-B)^{s}$ est une combinaison binomiale à $s+1$ termes et tue un polynôme de degré $s-1$. Ils enlèvent des choses différentes.`},
    {q: String.raw`Combien de différences ordinaires pour aplatir un trend quadratique $\mu_t=a+bt+ct^2$ ?`, a: String.raw`Deux : un polynôme de degré $q-1=2$ exige $d=q=2$, car $\nabla$ abaisse le degré d'un polynôme en $t$ d'exactement un, et $\nabla^{2}\mu_t\equiv 0$.`},
    {q: String.raw`Quelle empreinte une $\mathrm{SMA}(1)_s$ laisse-t-elle dans l'ACF ?`, a: String.raw`Un unique pic au retard saisonnier : $\rho_{\pm s}=-\theta/(1+\theta^{2})$ et $\rho_\tau=0$ partout ailleurs. Pour $X_t=\varepsilon_t-\theta\varepsilon_{t-s}$, $\gamma_0=(1+\theta^2)\sigma_\varepsilon^2$ et $\gamma_{\pm s}=-\theta\sigma_\varepsilon^2$.`},
    {q: String.raw`On observe $\rho_1\approx-\tfrac12$ après avoir différencié une fois. Que faut-il en conclure ?`, a: String.raw`On a sur-différencié : différencier une série déjà stationnaire injecte un facteur $(1-B)$ dans la MA, créant une MA(1) non inversible avec $\rho_1=-1/2$. Il faut différencier une fois de moins.`},
    {q: String.raw`En quoi une marche aléatoire est-elle non stationnaire, et que vaut $\nabla X_t$ ?`, a: String.raw`Pour $X_t=\sum_{j=1}^t\varepsilon_j$, $\operatorname{Var}(X_t)=t\sigma_\varepsilon^2$ et $\operatorname{Cov}(X_t,X_{t+\tau})=t\sigma_\varepsilon^2$ dépendent de $t$ : non stationnaire. Mais $\nabla X_t=\varepsilon_t$ est un bruit blanc, donc c'est une ARIMA$(0,1,0)$ (AR(1) à $\phi=1$, racine unité).`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer et démontrer la proposition : si $X_t=a+bt+Y_t$ avec $\{Y_t\}$ stationnaire centré, alors $\nabla X_t$ est stationnaire à une constante additive près. Préciser cette constante, et donner $\nabla^{2}X_t$.`,
     answer: String.raw`<div class="step"><strong>Énoncé.</strong> Soit $X_t=a+bt+Y_t$ avec $\{Y_t\}$ stationnaire à l'ordre 2, centré, et $a,b$ constants, $\nabla=I-B$. Alors $\nabla X_t=b+\nabla Y_t$, processus stationnaire de moyenne $b$ ; et $\nabla^{2}X_t=\nabla^{2}Y_t$, stationnaire centré.</div>
<div class="step"><strong>Calcul de $\nabla X_t$.</strong> Par linéarité de $\nabla$, $$\nabla X_t=X_t-X_{t-1}=\bigl(a+bt+Y_t\bigr)-\bigl(a+b(t-1)+Y_{t-1}\bigr)=b+(Y_t-Y_{t-1})=b+\nabla Y_t.$$ La tendance $a+bt$ est réduite à la constante $b$.</div>
<div class="step"><strong>Stationnarité de $\nabla Y_t$.</strong> $\nabla Y_t=Y_t-Y_{t-1}$ est une combinaison linéaire finie d'un processus stationnaire ; sa moyenne est $0$ et sa covariance $\operatorname{Cov}(\nabla Y_t,\nabla Y_{t-\tau})=2\gamma_\tau-\gamma_{\tau+1}-\gamma_{\tau-1}$ ne dépend que de $\tau$. Donc $\nabla Y_t$ est stationnaire, et $\nabla X_t$ est stationnaire de moyenne constante $b$.</div>
<div class="step"><strong>Seconde différence.</strong> $\nabla^{2}X_t=\nabla(b+\nabla Y_t)=\nabla b+\nabla^{2}Y_t=0+\nabla^{2}Y_t$, car $\nabla$ tue toute constante. Explicitement $\nabla^{2}X_t=Y_t-2Y_{t-1}+Y_{t-2}$, stationnaire et centré : la tendance a complètement disparu.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $X_t=a+bt+s_t+Y_t$ avec $s_{t+4}=s_t$ (saison trimestrielle) et $\{Y_t\}$ centré stationnaire. Calculer explicitement $\nabla\nabla_{(4)}X_t$ et vérifier que c'est une combinaison linéaire fixe de $\{Y_t\}$, de moyenne nulle et faiblement stationnaire.`,
     answer: String.raw`<div class="step"><strong>Étape 1 — différence saisonnière.</strong> On applique d'abord $\nabla_{(4)}=I-B^{4}$ : $$\nabla_{(4)}X_t=X_t-X_{t-4}=\bigl(a+bt+s_t+Y_t\bigr)-\bigl(a+b(t-4)+s_{t-4}+Y_{t-4}\bigr).$$ Comme $s_t=s_{t-4}$, la saison s'annule, et $bt-b(t-4)=4b$ : $$\nabla_{(4)}X_t=4b+(Y_t-Y_{t-4}).$$ Le trend est réduit à la constante $4b$.</div>
<div class="step"><strong>Étape 2 — différence ordinaire.</strong> On applique $\nabla=I-B$ : $$\nabla\nabla_{(4)}X_t=\bigl(4b+Y_t-Y_{t-4}\bigr)-\bigl(4b+Y_{t-1}-Y_{t-5}\bigr)=Y_t-Y_{t-1}-Y_{t-4}+Y_{t-5}.$$ La constante $4b$ disparaît.</div>
<div class="step"><strong>Étape 3 — moyenne nulle.</strong> $\mathbb{E}[\nabla\nabla_{(4)}X_t]=\mathbb{E}[Y_t-Y_{t-1}-Y_{t-4}+Y_{t-5}]=0$ puisque $\{Y_t\}$ est centré.</div>
<div class="step"><strong>Étape 4 — stationnarité faible.</strong> C'est une combinaison linéaire <em>fixe</em> (coefficients $+1,-1,-1,+1$ aux retards $0,1,4,5$) de $\{Y_t\}$ stationnaire. Par bilinéarité de la covariance, $\operatorname{Cov}(\nabla\nabla_{(4)}X_t,\nabla\nabla_{(4)}X_{t-\tau})$ est une somme finie de $\gamma_{\tau+k}$ ne dépendant que de $\tau$. Moyenne constante (nulle) et autocovariance fonction de $\tau$ seul $\Rightarrow$ faiblement stationnaire. (Même forme que le résultat $\nabla\nabla_{(12)}$ avec $12\to4$.)</div>`, pts: 4},
    {type:'open', q: String.raw`Soit le processus saisonnier $(1-0.7B^{2})X_t=(1-0.3B^{2})\varepsilon_t$, $\varepsilon_t$ bruit blanc de variance unité. (a) Justifier la stationnarité par les racines. (b) Donner la représentation MA$(\infty)$ $X_t=\sum_j a_j\varepsilon_{t-j}$. (c) Calculer $\operatorname{Var}(X_t)$ et $\rho_2$.`,
     answer: String.raw`<div class="step"><strong>(a) Racines et stationnarité.</strong> Posons $\phi=0.7$, $\theta=0.3$. Le polynôme AR est $\Phi(z)=1-\phi z^{2}$, de racines $z=\pm\phi^{-1/2}=\pm(0.7)^{-1/2}\approx\pm1.195$. Les deux ont module $>1$ (hors du cercle unité), donc le processus est stationnaire et causal : on peut inverser l'AR. (De même $1-\theta z^2$ a ses racines de module $>1$, le processus est inversible.)</div>
<div class="step"><strong>(b) Développement MA$(\infty)$.</strong> Série géométrique en $B^{2}$ : $$X_t=\frac{1-\theta B^{2}}{1-\phi B^{2}}\varepsilon_t=\sum_{k\ge0}(\phi B^{2})^{k}(1-\theta B^{2})\varepsilon_t.$$ Le coefficient de $B^{2k}$ vaut $\phi^{k}$ et celui de $B^{2k+2}$ vaut $-\phi^{k}\theta$ : seuls les retards <em>pairs</em> survivent. Donc $a_j=0$ pour $j$ impair, $a_0=1$, et pour $j$ pair $\ge2$ : $$a_j=\phi^{\,j/2}-\phi^{\,(j-2)/2}\theta=\phi^{\,(j-2)/2}(\phi-\theta).$$ Par exemple $a_2=\phi-\theta=0.4$, $a_4=\phi(\phi-\theta)=0.28$.</div>
<div class="step"><strong>(c) Variance.</strong> Règle du filtre $\gamma_\tau=\sigma_\varepsilon^2\sum_j a_j a_{j+\tau}$. Avec $a_0=1$ et $a_{2m}=\phi^{m-1}(\phi-\theta)$, $$\operatorname{Var}(X_t)=\gamma_0=\sigma_\varepsilon^2\Bigl(1+(\phi-\theta)^{2}\sum_{m\ge1}\phi^{2(m-1)}\Bigr)=\sigma_\varepsilon^2\Bigl(1+\frac{(\phi-\theta)^{2}}{1-\phi^{2}}\Bigr).$$ Numériquement : $1+\dfrac{0.16}{0.51}\approx1.3137$.</div>
<div class="step"><strong>(c, suite) Autocorrélation $\rho_2$.</strong> Comme les $a_j$ s'annulent aux retards impairs, $\rho_\tau=0$ pour $\tau$ impair. Pour $\tau=2$ : $$\gamma_2=\sigma_\varepsilon^2\Bigl[a_0a_2+\sum_{k\ge1}a_{2k}a_{2k+2}\Bigr]=\sigma_\varepsilon^2\Bigl[(\phi-\theta)\phi^{0}+(\phi-\theta)^{2}\phi\sum_{k\ge1}\phi^{2(k-1)}\Bigr]=\sigma_\varepsilon^2\Bigl[(\phi-\theta)+\frac{(\phi-\theta)^{2}\phi}{1-\phi^{2}}\Bigr].$$ Numériquement $\gamma_2=0.4+\dfrac{0.16\cdot0.7}{0.51}=0.4+0.2196=0.6196$, d'où $\rho_2=\gamma_2/\gamma_0=0.6196/1.3137\approx0.472$. La décroissance est géométrique de raison $\phi$ le long des retards pairs ($\rho_4\approx0.330$, $\rho_6\approx0.231$, …), tous les retards impairs étant nuls.</div>`, pts: 5},
    {type:'open', q: String.raw`Soit la $\mathrm{SARMA}(0,1)\times(1,0)_{12}$ : $(1-\phi^{(12)}B^{12})X_t=(1-\theta B)\varepsilon_t$ (avec $|\phi^{(12)}|<1$, $\varepsilon_t$ bruit blanc de variance $\sigma_\varepsilon^2$). Donner la récurrence à un pas, les poids $\psi_j$ de la MA$(\infty)$, puis l'ACVS aux retards $0,1,11,12,13$.`,
     answer: String.raw`<div class="step"><strong>Récurrence à un pas.</strong> On développe le facteur AR saisonnier et on isole $X_t$ : $$X_t=\phi^{(12)}X_{t-12}+\varepsilon_t-\theta\varepsilon_{t-1}.$$ C'est une AR(1) agissant uniquement au retard saisonnier $12$, alimentée par une entrée MA(1).</div>
<div class="step"><strong>Poids $\psi_j$.</strong> On inverse $1/(1-\phi^{(12)}B^{12})=\sum_{l\ge0}(\phi^{(12)})^{l}B^{12l}$ et on multiplie par $(1-\theta B)$ : $$X_t=\sum_{l\ge0}(\phi^{(12)})^{l}\bigl(\varepsilon_{t-12l}-\theta\varepsilon_{t-12l-1}\bigr),$$ donc $\psi_{12l}=(\phi^{(12)})^{l}$, $\psi_{12l+1}=-\theta(\phi^{(12)})^{l}$, et tous les autres $\psi_j=0$.</div>
<div class="step"><strong>ACVS — règle du filtre.</strong> $\gamma_\tau=\sigma_\varepsilon^2\sum_{j\ge0}\psi_j\psi_{j+\tau}$. Pour $\tau=0$ : $\sum_l[(\phi^{(12)})^{2l}+\theta^{2}(\phi^{(12)})^{2l}]=(1+\theta^2)/(1-(\phi^{(12)})^2)$, donc $$\gamma_0=\sigma_\varepsilon^2\,\frac{1+\theta^{2}}{1-(\phi^{(12)})^{2}}.$$</div>
<div class="step"><strong>Retards $1,11,13$ (lobes latéraux MA(1)).</strong> $\tau=1$ : seuls les couples $(\psi_{12l},\psi_{12l+1})$ contribuent, $\gamma_1=\sigma_\varepsilon^2\sum_l(\phi^{(12)})^{l}\cdot(-\theta)(\phi^{(12)})^{l}=\dfrac{-\theta\,\sigma_\varepsilon^2}{1-(\phi^{(12)})^{2}}$. $\tau=11$ : couples $(\psi_{12l+1},\psi_{12(l+1)})$, $\gamma_{11}=\sigma_\varepsilon^2\sum_l(-\theta)(\phi^{(12)})^{l}\cdot(\phi^{(12)})^{l+1}=\dfrac{-\theta\,\phi^{(12)}\sigma_\varepsilon^2}{1-(\phi^{(12)})^{2}}$. $\tau=13$ : couples $(\psi_{12l},\psi_{12(l+1)+1})$, $\gamma_{13}=\sigma_\varepsilon^2\sum_l(\phi^{(12)})^{l}\cdot(-\theta)(\phi^{(12)})^{l+1}=\gamma_{11}$.</div>
<div class="step"><strong>Retard saisonnier $12$.</strong> Couples $(\psi_{12l},\psi_{12(l+1)})$ et $(\psi_{12l+1},\psi_{12(l+1)+1})$ : $\gamma_{12}=\sigma_\varepsilon^2\sum_l(\phi^{(12)})^{l}(\phi^{(12)})^{l+1}(1+\theta^2)=\phi^{(12)}\gamma_0=\dfrac{\phi^{(12)}(1+\theta^2)\sigma_\varepsilon^2}{1-(\phi^{(12)})^2}$. <strong>Bilan :</strong> la corrélation apparaît en grappes autour des retards saisonniers $0,12,24,\dots$, chacune portant des lobes MA(1) aux $\pm1$, décroissant géométriquement en $\phi^{(12)}$. (Vérification numérique pour $\phi^{(12)}=0.5,\ \theta=0.3,\ \sigma_\varepsilon^2=1$ : $\gamma_0\approx1.453$, $\gamma_1=-0.4$, $\gamma_{11}=\gamma_{13}=-0.2$, $\gamma_{12}\approx0.727$.)</div>`, pts: 5},
    {type:'open', q: String.raw`Pour l'IMA$(1,1)$ $Y_t=Y_{t-1}+\varepsilon_t-\theta\varepsilon_{t-1}$ avec $Y_0=0$ : (a) établir $\operatorname{Var}(Y_t)$ et montrer qu'elle croît linéairement en $t$ pour $\theta\ne1$ ; (b) que se passe-t-il à $\theta=1$, et pourquoi est-ce l'avertissement de sur-différenciation ?`,
     answer: String.raw`<div class="step"><strong>(a) Forme explicite.</strong> En déroulant la récurrence depuis $Y_0=0$ : $Y_1=\varepsilon_1-\theta\varepsilon_0$, $Y_2=\varepsilon_2+(1-\theta)\varepsilon_1-\theta\varepsilon_0$, et par induction $$Y_t=\varepsilon_t+(1-\theta)\sum_{j=1}^{t-1}\varepsilon_j-\theta\varepsilon_0.$$</div>
<div class="step"><strong>(a) Variance.</strong> Les $\varepsilon_j$ étant non corrélés de variance $\sigma_\varepsilon^2$, on somme les carrés des coefficients : un terme $\varepsilon_t$ (coeff $1$), $t-1$ termes (coeff $1-\theta$) et un terme $\varepsilon_0$ (coeff $-\theta$) : $$\operatorname{Var}(Y_t)=\sigma_\varepsilon^2\bigl[\,1+(1-\theta)^{2}(t-1)+\theta^{2}\,\bigr].$$ C'est <em>linéaire</em> en $t$, de pente $(1-\theta)^{2}\sigma_\varepsilon^2>0$ dès que $\theta\ne1$ : la série erre comme une marche aléatoire (amortie), signature d'un processus intégré. La covariance $\operatorname{Cov}(Y_t,Y_{t+\tau})=\sigma_\varepsilon^2[1-\theta+(1-\theta)^2(t-1)+\theta^2]$ partage le terme dominant $(1-\theta)^2(t-1)$, donc $\operatorname{Corr}(Y_t,Y_{t+\tau})\to1$ pour des instants proches.</div>
<div class="step"><strong>(b) Frontière $\theta=1$.</strong> La pente $(1-\theta)^2$ s'annule : $\operatorname{Var}(Y_t)=\sigma_\varepsilon^2[1+0+1]=2\sigma_\varepsilon^2$, <em>bornée</em>. En effet $Y_t=Y_{t-1}+\varepsilon_t-\varepsilon_{t-1}$ télescope en $Y_t=\varepsilon_t-\varepsilon_0$, donc $\nabla Y_t=\varepsilon_t-\varepsilon_{t-1}$ est une MA(1) avec racine unité dans le polynôme MA : <strong>non inversible</strong>.</div>
<div class="step"><strong>(b) Lien sur-différenciation.</strong> Cette MA(1) a $\rho_1=-\theta/(1+\theta^2)=-1/2$. C'est exactement ce qui arrive si l'on différencie une série <em>déjà</em> stationnaire : on injecte un facteur $(1-B)$ dans la MA, créant une MA(1) non inversible de $\rho_1=-\tfrac12$. Voir $\rho_1\approx-\tfrac12$ après différenciation est donc le signal de différencier une fois de moins.</div>`, pts: 4},
    {type:'open', q: String.raw`Soit $\{X_t\}$ une ARIMA$(p,d,q)$ : $\Phi(B)(I-B)^{d}X_t=\Theta(B)\varepsilon_t$, $\varepsilon_t$ bruit blanc. Montrer que $W_t=X_t+A_0+A_1t+\cdots+A_{d-1}t^{d-1}$ (les $A_j$ variables aléatoires indépendantes) satisfait les mêmes équations. Interpréter.`,
     answer: String.raw`<div class="step"><strong>Réduction.</strong> Comme $\Phi(B)$ et $\Theta(B)$ agissent sur ce que produit $(I-B)^{d}$, il suffit de montrer $(I-B)^{d}W_t=(I-B)^{d}X_t$, c'est-à-dire que le polynôme ajouté est annihilé par $(I-B)^{d}$.</div>
<div class="step"><strong>Linéarité.</strong> $\nabla=I-B$ est linéaire et envoie la suite nulle sur la suite nulle. Donc $$(I-B)^{d}W_t=(I-B)^{d}X_t+\sum_{k=1}^{d}A_{k-1}\,(I-B)^{d}t^{\,k-1}.$$ Il reste à prouver $(I-B)^{d}t^{\,k-1}=\mathbf 0$ pour $k=1,\dots,d$ ; il suffit de l'énoncé plus fort $(I-B)^{k}t^{\,k-1}=\mathbf 0$ pour tout $k\in\mathbb{N}$.</div>
<div class="step"><strong>Récurrence — cas de base.</strong> $k=1$ : $(I-B)t^{0}=(I-B)\mathbf 1=\mathbf 1-\mathbf 1=\mathbf 0$ (suite constante un moins elle-même décalée).</div>
<div class="step"><strong>Récurrence — hérédité.</strong> Supposons $(I-B)^{r}t^{\,r-1}=\mathbf 0$ pour tout $r\le k$. Alors $$(I-B)^{k+1}t^{\,k}=(I-B)^{k}\bigl(t^{\,k}-(t-1)^{k}\bigr).$$ Par le binôme, le terme en $t^{k}$ se simplifie : $t^{k}-(t-1)^{k}=-\sum_{r=0}^{k-1}\binom{k}{r}(-1)^{\,k-r}t^{\,r}$, polynôme de degré $k-1$. Par linéarité et l'hypothèse de récurrence (chaque $(I-B)^{r+1}t^{\,r}=\mathbf 0$ pour $r\le k-1$, et une différence de plus de $\mathbf 0$ reste $\mathbf 0$), chaque terme s'annule, donc $(I-B)^{k+1}t^{\,k}=\mathbf 0$.</div>
<div class="step"><strong>Conclusion et interprétation.</strong> Par récurrence, $(I-B)^{d}W_t=(I-B)^{d}X_t$, donc $\{W_t\}$ satisfait les mêmes équations ARIMA. <em>Interprétation :</em> l'intégration $d$-fois d'une ARIMA$(p,d,q)$ laisse les « conditions initiales » polynomiales de degré $d-1$ complètement indéterminées par le modèle — d'où la nécessité de différencier $d$ fois pour retrouver une partie identifiable.</div>`, pts: 5}
  ]
},
