{
  n: 3,
  title: String.raw`Opérateur retard, décomposition de Wold, causalité & inversibilité`,
  intro: String.raw`En notation polynomiale $\Phi(B)X_t=\Theta(B)\varepsilon_t$, la position des racines par rapport au cercle unité décide de la stationnarité (causalité) et de l'inversibilité.`,
  sections: [
    {h: String.raw`Opérateur retard et notation polynomiale`, body: String.raw`<p>L'<strong>opérateur retard</strong> (backshift operator) $B$ décale la série d'un cran vers le passé : $B X_t = X_{t-1}$, et plus généralement $B^k X_t = X_{t-k}$ (avec $B^0=I$). Il est linéaire et, parce que les décalages commutent, on le manipule comme une <em>variable</em> : on peut multiplier, factoriser et inverser des polynômes en $B$.</p>
<p>L'idée de la semaine est de <em>réemballer</em> les modèles AR, MA et ARMA avec $B$. Un $\mathrm{ARMA}(p,q)$ s'écrit alors de façon compacte</p>
$$\Phi(B)X_t=\Theta(B)\varepsilon_t,\qquad \Phi(z)=\sum_{j=0}^{p}\phi_j z^{j},\quad \Theta(z)=\sum_{k=0}^{q}\theta_k z^{k},$$
<p>où $\Phi(z)$ est le <strong>polynôme caractéristique</strong> de la partie autorégressive et $\Theta(z)$ celui de la partie moyenne mobile (moving average). Cas purs : un $\mathrm{AR}(p)$ est $\Phi(B)X_t=\varepsilon_t$, un $\mathrm{MA}(q)$ est $X_t=\Theta(B)\varepsilon_t$. Partout, $\{\varepsilon_t\}$ est un bruit blanc (white noise) centré de variance $\sigma^2$.</p>
<p><strong>Intuition.</strong> $B$ n'est que l'application $X_t\mapsto X_{t-1}$, mais le traiter comme un symbole algébrique $z$ permet de factoriser, inverser et développer les équations du modèle. Tout résultat de cette semaine est, au fond, une affirmation sur le polynôme $\Phi(z)$ ou $\Theta(z)$ obtenu en remplaçant $B$ par la variable complexe $z$.</p>`},
    {h: String.raw`Processus linéaire général et décomposition de Wold`, body: String.raw`<p>Un <strong>processus linéaire général</strong> (general linear process), causal, s'écrit</p>
$$X_t=\sum_{k=0}^{\infty}g_k\,\varepsilon_{t-k},\qquad \lVert g\rVert_2^2=\sum_k g_k^2<\infty,\quad g_0=1.$$
<p>$X_t$ ne dépend que du <em>passé et du présent</em> du bruit : le processus est <strong>causal</strong>. La sommabilité $\lVert g\rVert_2^2<\infty$ rend les moments finis, donc le processus est stationnaire au second ordre. En forme opérateur $X_t=G(B)\varepsilon_t$ avec $G(z)=\sum_{k\ge0}g_k z^k$, la <strong>fonction de transfert</strong> (transfer function) ; pour un ARMA, $G(z)=\Theta(z)/\Phi(z)$.</p>
<p><strong>Théorème (décomposition de Wold).</strong> Tout processus $\{X_t\}$ centré, stationnaire au second ordre, s'écrit</p>
$$X_t = U_t + V_t,\qquad U_t,\ V_t\ \text{décorrélés},$$
<p>où $U_t=\sum_{k=0}^{\infty}g_k\,\varepsilon_{t-k}$ est une $\mathrm{MA}(\infty)$ unilatérale ($g_0=1$, $\lVert g\rVert_2^2<\infty$, $\{\varepsilon_t\}$ bruit blanc décorrélé de $V$, et $\mathbb{E}[\varepsilon_s V_t]=0$ pour tous $s,t$), avec $\{g_k\}$ et $\{\varepsilon_t\}$ <em>uniquement</em> déterminés ; et $V_t$ est <strong>singulier</strong> (déterministe : prévisible sans erreur depuis son propre passé). Idée de preuve : projeter $X_t$ sur l'espace fermé engendré par son propre passé ; les innovations à un pas sont le bruit blanc $\varepsilon_t$ et les $g_k$ sont les coefficients de projection.</p>
<p><strong>Intuition.</strong> La seule information nouvelle qui arrive en $t$ est l'innovation $\varepsilon_t$ ; tout le reste est soit un écho des innovations passées ($U_t$), soit parfaitement prévisible depuis le passé ($V_t$, p. ex. une sinusoïde fixe). Pour les processus du cours $V_t=0$ : il reste la pure forme $\mathrm{MA}(\infty)$, $X_t=G(B)\varepsilon_t$. C'est la justification de tout le programme linéaire : les ARMA sont les approximations <em>finies et rationnelles</em> de cette $\mathrm{MA}(\infty)$.</p>`},
    {h: String.raw`Causalité, inversibilité et critère des racines`, body: String.raw`<p>Deux propriétés à distinguer :</p>
<ul>
<li><strong>Causal (stationnaire)</strong> : $X_t=G(B)\varepsilon_t$ ne fait intervenir que le passé/présent du bruit (forme $\mathrm{MA}(\infty)$).</li>
<li><strong>Inversible</strong> : on peut réécrire $G^{-1}(B)X_t=\varepsilon_t$ (forme $\mathrm{AR}(\infty)$), c.-à-d. récupérer l'innovation $\varepsilon_t$ à partir du passé observé $X_t,X_{t-1},\dots$</li>
</ul>
<p>Le mécanisme : développer $1/G_2(z)$ en série de Laurent ; un pôle $z_j$ <em>hors</em> du cercle contribue par une série en puissances positives de $z$ (passé/présent), un pôle <em>à l'intérieur</em> contribue par des puissances négatives (futur). D'où le résultat analytique : $G$ est <strong>analytique sur et à l'intérieur</strong> du cercle unité, soit $\lvert G(z)\rvert<\infty$ pour $\lvert z\rvert\le1$.</p>
<p><strong>Critère des racines.</strong> Pour $\Phi(B)X_t=\Theta(B)\varepsilon_t$ :</p>
$$\begin{aligned} \mathbf{AR}(p):&\ \text{stationnaire}\iff\text{racines de }\Phi\text{ hors du cercle }(\lvert z\rvert>1);\ \textit{toujours inversible.}\\ \mathbf{MA}(q):&\ \textit{toujours stationnaire};\ \text{inversible}\iff\text{racines de }\Theta\text{ hors }(\lvert z\rvert>1).\\ \mathbf{ARMA}(p,q):&\ \text{stationnaire}\iff\text{racines de }\Phi\text{ hors};\ \text{inversible}\iff\text{racines de }\Theta\text{ hors.} \end{aligned}$$
<p><strong>Intuition.</strong> Stationnarité (causalité) et inversibilité sont <em>le même</em> test (toutes les racines hors du cercle) appliqué à <em>deux</em> polynômes différents : $\Phi$ contrôle si $X_t=G(B)\varepsilon_t$ n'utilise que le bruit passé/présent ; $\Theta$ contrôle si $\varepsilon_t=G^{-1}(B)X_t$ n'utilise que les données passées/présentes. Un AR n'a pas de $\Theta$ qui puisse échouer, donc toujours inversible ; un MA n'a pas de $\Phi$, donc toujours stationnaire.</p>
<p><strong>Attention à la convention.</strong> « Racines hors du cercle » vise les racines de $\Phi(z)=\sum_j\phi_j z^j$, donc $\lvert z\rvert>1$. En termes des racines <em>réciproques</em> $g=1/z$, c'est $\lvert g\rvert<1$ : exactement la condition $\mathrm{AR}(1)$ $\lvert\phi\rvert<1$ (la racine de $1-\phi z$ est $z=1/\phi$). Ne jamais tester à l'intérieur du cercle.</p>`},
    {h: String.raw`Poids $\psi_j$, ACVS et densité spectrale d'un ARMA causal`, body: String.raw`<p>Si $X_t=\sum_{k\ge0}g_k\varepsilon_{t-k}$ avec $\lVert g\rVert_2^2<\infty$, alors</p>
$$\mathbb{E}[X_t]=0,\qquad \gamma_\tau=\sigma^2\sum_{k=0}^{\infty}g_k\,g_{k+\lvert\tau\rvert}.$$
<p>C'est le moteur pour calculer l'ACVS (autocovariance sequence) de tout ARMA causal une fois ses poids $\mathrm{MA}(\infty)$ $\{g_k\}=\{\psi_k\}$ connus. Deux techniques donnent les $\psi_j$ de $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$ :</p>
<ul>
<li><strong>Identification des coefficients</strong> : égaler $\Phi(z)\big(\sum_{j\ge0}\psi_j z^j\big)=\Theta(z)$ et apparier les puissances de $z$, ce qui donne une récurrence sur les $\psi_j$ avec $\psi_0=1$.</li>
<li><strong>Fractions partielles</strong> : développer $G(z)=\Theta(z)/\Phi(z)$ en séries géométriques $\frac{1}{1-z/r_i}=\sum_{j\ge0}(z/r_i)^j$ (convergentes car $\lvert r_i\rvert>1$), puis lire le coefficient de $z^j$.</li>
</ul>
<p>Une troisième route, sans sommer les $\psi$ : multiplier l'équation du modèle par $X_{t-\tau}$ et prendre l'espérance. Pour $\tau$ supérieur à l'ordre MA $q$, le membre de droite s'annule, donnant une <em>récurrence homogène</em> sur $\gamma_\tau$ dont l'équation caractéristique est $\Phi$ ; les petits décalages $\tau=0,\dots,q$ fournissent les conditions initiales via $\mathbb{E}[\varepsilon_{t-k}X_{t-\tau}]=\sigma^2\psi_{k-\tau}$.</p>
<p>Enfin, la <strong>densité spectrale</strong> (spectral density) d'un ARMA causal-inversible se lit directement sur les polynômes :</p>
$$S(f)=\sigma^2\,\frac{\lvert\Theta(e^{-2\pi i f})\rvert^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2},\qquad -\tfrac12\le f\le\tfrac12.$$
<p><strong>Exemple repère ($\mathrm{AR}(1)$).</strong> Pour $(1-\phi B)X_t=\varepsilon_t$ avec $\lvert\phi\rvert<1$ (racine $z=1/\phi$ hors du cercle) : $X_t=\frac{1}{1-\phi B}\varepsilon_t=\sum_{k\ge0}\phi^{k}\varepsilon_{t-k}$, et $\gamma_\tau=\sigma^2\,\dfrac{\phi^{\lvert\tau\rvert}}{1-\phi^2}$. L'inversion géométrique de $1/(1-\phi B)$ <em>exige</em> $\lvert\phi\rvert<1$ : c'est le critère des racines en action.</p>`}
  ],
  checks: [
    {q: String.raw`Que fait l'opérateur retard $B$, et pourquoi le traite-t-on comme une variable ?`, a: String.raw`$B X_t=X_{t-1}$ (et $B^k X_t=X_{t-k}$). Il est linéaire et les décalages commutent, donc les polynômes en $B$ se multiplient, se factorisent et s'inversent comme des polynômes ordinaires en $z$.`},
    {q: String.raw`En une phrase, que dit la décomposition de Wold ?`, a: String.raw`Tout processus stationnaire centré s'écrit $X_t=U_t+V_t$ avec $U_t$ une $\mathrm{MA}(\infty)$ unilatérale de bruit blanc ($g_0=1$, $\lVert g\rVert_2^2<\infty$, $\{g_k\}$ et $\{\varepsilon_t\}$ uniques) et $V_t$ déterministe (singulier). Pour nos modèles $V_t=0$.`},
    {q: String.raw`Causalité et inversibilité : même test ou tests différents ?`, a: String.raw`Le même test (toutes les racines de module $>1$, hors du cercle unité) appliqué à deux polynômes : $\Phi$ pour la stationnarité/causalité, $\Theta$ pour l'inversibilité.`},
    {q: String.raw`Pourquoi un AR est-il toujours inversible et un MA toujours stationnaire ?`, a: String.raw`Un AR n'a pas de polynôme $\Theta$ ($\Theta\equiv1$) qui puisse échouer au test d'inversibilité ; un MA n'a pas de $\Phi$, et $G(z)=\Theta(z)$ étant un polynôme fini est borné partout, donc stationnaire d'office.`},
    {q: String.raw`Une fois les poids $\psi_j$ connus, quelle formule donne l'ACVS d'un ARMA causal ?`, a: String.raw`$\gamma_\tau=\sigma^2\sum_{k\ge0}\psi_k\,\psi_{k+\lvert\tau\rvert}$, avec $\psi_0=1$.`}
  ],
  test: [
    {type:'open', q: String.raw`Énoncer le théorème de décomposition de Wold avec TOUTES ses hypothèses, en précisant la nature de chacun des deux termes et ce qui est unique.`,
     answer: String.raw`<div class="step"><strong>Cadre.</strong> Soit $\{X_t\}$ un processus centré ($\mathbb{E}[X_t]=0$) et stationnaire au second ordre.</div><div class="step"><strong>Énoncé.</strong> On peut écrire $X_t=U_t+V_t$ où $U_t$ et $V_t$ sont décorrélés.</div><div class="step"><strong>Terme régulier $U_t$.</strong> $U_t$ admet une représentation linéaire unilatérale ($\mathrm{MA}(\infty)$) : $U_t=\sum_{k=0}^{\infty}g_k\,\varepsilon_{t-k}$ avec $g_0=1$, $\lVert g\rVert_2^2=\sum_k g_k^2<\infty$, et $\{\varepsilon_t\}$ un bruit blanc centré décorrélé de $V$ : $\mathbb{E}[\varepsilon_s V_t]=0$ pour tous $s,t$.</div><div class="step"><strong>Unicité.</strong> Les suites $\{g_k\}$ et $\{\varepsilon_t\}$ sont uniquement déterminées.</div><div class="step"><strong>Terme singulier $V_t$.</strong> $V_t$ est singulier (déterministe) : il peut être prédit à partir de son propre passé avec une erreur nulle.</div><div class="step"><strong>Lecture.</strong> La seule information nouvelle en $t$ est l'innovation $\varepsilon_t$ ; pour les processus ARMA du cours $V_t=0$, d'où la forme pure $X_t=G(B)\varepsilon_t$.</div>`, pts: 3},
    {type:'open', q: String.raw`Soit l'AR(2) $\frac{15}{16}Y_t=\frac14 Y_{t-1}-\frac{1}{16}Y_{t-2}+\varepsilon_t$, $\varepsilon_t$ gaussien. Écrire le polynôme caractéristique AR. Le processus est-il stationnaire ? Inversible ?`,
     answer: String.raw`<div class="step"><strong>Mise en forme opérateur.</strong> On ramène tous les $Y$ à gauche : $\big(\tfrac{15}{16}-\tfrac14 B+\tfrac{1}{16}B^2\big)Y_t=\varepsilon_t$, donc $\Phi(z)=\tfrac{15}{16}-\tfrac14 z+\tfrac{1}{16}z^2$.</div><div class="step"><strong>Racines.</strong> Résoudre $\tfrac{1}{16}z^2-\tfrac14 z+\tfrac{15}{16}=0$, soit (en multipliant par $16$) $z^2-4z+15=0$. Discriminant $\Delta=16-60=-44$, donc $z=\dfrac{4\pm\sqrt{-44}}{2}=2\pm\sqrt{11}\,i\approx 2\pm 3{,}317\,i$.</div><div class="step"><strong>Modules.</strong> $\lvert z\rvert=\sqrt{2^2+(\sqrt{11})^2}=\sqrt{4+11}=\sqrt{15}\approx 3{,}873>1$.</div><div class="step"><strong>Stationnarité.</strong> Les deux racines sont hors du cercle unité ($\lvert z\rvert>1$), donc le processus est <strong>stationnaire</strong>.</div><div class="step"><strong>Inversibilité.</strong> Un processus AR est <strong>toujours inversible</strong> (pas de polynôme MA à tester, $\Theta\equiv1$).</div>`, pts: 3},
    {type:'open', q: String.raw`Soit l'ARMA(2,1) $Y_t-\frac14 Y_{t-1}+\frac{1}{16}Y_{t-2}=\varepsilon_t-0.5\varepsilon_{t-1}$. Est-il stationnaire ? Inversible ?`,
     answer: String.raw`<div class="step"><strong>Forme opérateur.</strong> $\big(1-\tfrac14 B+\tfrac{1}{16}B^2\big)Y_t=(1-0{,}5B)\varepsilon_t$, donc $\Phi(z)=1-\tfrac14 z+\tfrac{1}{16}z^2$ et $\Theta(z)=1-\tfrac12 z$.</div><div class="step"><strong>Stationnarité (racines de $\Phi$).</strong> $\Phi(z)=0\iff z^2-4z+16=0$ (multiplier par $16$). $\Delta=16-64=-48$, $z=\dfrac{4\pm\sqrt{-48}}{2}=2\pm 2\sqrt{3}\,i$.</div><div class="step">Module : $\lvert z\rvert=\sqrt{2^2+(2\sqrt3)^2}=\sqrt{4+12}=\sqrt{16}=4>1$. Les deux racines sont hors du cercle, donc <strong>stationnaire</strong>.</div><div class="step"><strong>Inversibilité (racine de $\Theta$).</strong> $\Theta(z)=0\iff 1-\tfrac12 z=0\iff z=2$. $\lvert 2\rvert=2>1$, racine hors du cercle, donc <strong>inversible</strong>.</div><div class="step"><strong>Conclusion.</strong> Le processus est à la fois stationnaire et inversible.</div>`, pts: 3},
    {type:'open', q: String.raw`Pour l'ARMA $(1-0.5B+0.04B^2)X_t=(1+0.25B)\varepsilon_t$, trouver les poids $\psi_j$ de la représentation $X_t=\sum_{j\ge0}\psi_j\varepsilon_{t-j}$.`,
     answer: String.raw`<div class="step"><strong>Fonction de transfert.</strong> $X_t=G(B)\varepsilon_t$ avec $G(z)=\dfrac{1+0{,}25z}{1-0{,}5z+0{,}04z^2}$. Le dénominateur $0{,}04z^2-0{,}5z+1=0{,}04(z-2{,}5)(z-10)$ a pour racines $z=2{,}5$ et $z=10$, toutes deux hors du cercle : le processus est causal.</div><div class="step"><strong>Fractions partielles.</strong> $\dfrac{1}{(z-2{,}5)(z-10)}=\dfrac{1}{7{,}5}\Big(\dfrac{-1}{z-2{,}5}+\dfrac{1}{z-10}\Big)$. On développe en séries géométriques (valides pour $\lvert z\rvert<2{,}5$) : $\dfrac{-1}{z-2{,}5}=\dfrac{1}{2{,}5}\sum_{j\ge0}(0{,}4)^j z^j$ et $\dfrac{1}{z-10}=-\dfrac{1}{10}\sum_{j\ge0}(0{,}1)^j z^j$.</div><div class="step"><strong>Regroupement.</strong> Avec le préfacteur $\dfrac{1+0{,}25z}{0{,}04\cdot 7{,}5}=\dfrac{1+0{,}25z}{0{,}3}$ et en collectant les puissances de $z$, on obtient pour $j\ge1$ : $\psi_j=\Big(\tfrac{1}{0{,}75}+\tfrac{1}{1{,}2}\Big)0{,}4^j-\Big(\tfrac{1}{3}+\tfrac{1}{1{,}2}\Big)0{,}1^j=\dfrac{13}{6}(0{,}4)^j-\dfrac{7}{6}(0{,}1)^j$, et $\psi_0=1$.</div><div class="step"><strong>Résultat.</strong> $\psi_0=1$ ; pour $j\ge1$, $\psi_j=\dfrac{13}{6}(0{,}4)^j-\dfrac{7}{6}(0{,}1)^j$.</div><div class="step"><strong>Vérification par récurrence.</strong> Identifier $(1-0{,}5z+0{,}04z^2)\sum_j\psi_j z^j=1+0{,}25z$ donne $\psi_0=1$, $\psi_1-0{,}5\psi_0=0{,}25\Rightarrow\psi_1=0{,}75$, puis $\psi_j=0{,}5\psi_{j-1}-0{,}04\psi_{j-2}$. On obtient $\psi_0,\psi_1,\psi_2,\psi_3=1,\ 0{,}75,\ 0{,}335,\ 0{,}1375$, ce qui coïncide exactement avec $\tfrac{13}{6}0{,}4^j-\tfrac{7}{6}0{,}1^j$.</div>`, pts: 4},
    {type:'open', q: String.raw`Pour l'ARMA(1,1) causal-inversible $(1-0.5B)X_t=(1+0.3B)\varepsilon_t$, calculer les poids $\psi_j$ puis l'ACVS $\gamma_0$ et $\gamma_1$.`,
     answer: String.raw`<div class="step"><strong>Poids $\psi_j$.</strong> Identifier $(1-0{,}5z)\sum_{j\ge0}\psi_j z^j=1+0{,}3z$ : $\psi_0=1$ ; $\psi_1-0{,}5\psi_0=0{,}3\Rightarrow\psi_1=0{,}8$ ; et pour $j\ge2$, $\psi_j-0{,}5\psi_{j-1}=0\Rightarrow\psi_j=0{,}5\psi_{j-1}$. Forme close : $\psi_j=0{,}8\,(0{,}5)^{j-1}$ pour $j\ge1$.</div><div class="step"><strong>Somme des carrés.</strong> $\sum_{j\ge1}\psi_j^2=0{,}8^2\sum_{j\ge1}(0{,}25)^{j-1}=0{,}64\cdot\dfrac{1}{1-0{,}25}=\dfrac{0{,}64}{0{,}75}=\dfrac{64}{75}$.</div><div class="step"><strong>$\gamma_0$.</strong> $\gamma_0=\sigma^2\sum_{j\ge0}\psi_j^2=\sigma^2\Big(1+\tfrac{64}{75}\Big)=\dfrac{139}{75}\sigma^2\approx 1{,}853\,\sigma^2$.</div><div class="step"><strong>$\gamma_1$.</strong> $\sum_{j\ge1}\psi_j\psi_{j+1}=0{,}5\sum_{j\ge1}\psi_j^2=\tfrac12\cdot\tfrac{64}{75}=\tfrac{32}{75}$, donc $\gamma_1=\sigma^2\big(\psi_0\psi_1+\tfrac{32}{75}\big)=\sigma^2\big(0{,}8+\tfrac{32}{75}\big)=\sigma^2\big(\tfrac{60}{75}+\tfrac{32}{75}\big)=\dfrac{92}{75}\sigma^2\approx 1{,}227\,\sigma^2$.</div><div class="step"><strong>Contrôle.</strong> $\rho_1=\gamma_1/\gamma_0=92/139\approx 0{,}662$, valeur raisonnablement grande pour un ARMA(1,1) positivement corrélé.</div>`, pts: 4},
    {type:'open', q: String.raw`Donner la densité spectrale de l'ARMA(1,1) causal-inversible $(1-\phi B)X_t=(1-\theta B)\varepsilon_t$ ($\lvert\phi\rvert<1$, $\lvert\theta\rvert<1$), puis l'utiliser pour retrouver $\gamma_0$ du modèle $(1-0.5B)X_t=(1+0.3B)\varepsilon_t$.`,
     answer: String.raw`<div class="step"><strong>Formule générale.</strong> $S(f)=\sigma^2\dfrac{\lvert\Theta(e^{-2\pi i f})\rvert^2}{\lvert\Phi(e^{-2\pi i f})\rvert^2}=\sigma^2\dfrac{\lvert 1-\theta e^{-2\pi i f}\rvert^2}{\lvert 1-\phi e^{-2\pi i f}\rvert^2}$, soit $S(f)=\sigma^2\dfrac{1+\theta^2-2\theta\cos(2\pi f)}{1+\phi^2-2\phi\cos(2\pi f)}$ pour $-\tfrac12\le f\le\tfrac12$ (on a utilisé $\lvert 1-a e^{-2\pi i f}\rvert^2=1+a^2-2a\cos(2\pi f)$).</div><div class="step"><strong>Variance par intégration.</strong> $\gamma_0=\int_{-1/2}^{1/2}S(f)\,df$. Pour un ARMA(1,1) cela donne la formule standard $\gamma_0=\sigma^2\dfrac{1+\theta^2-2\phi\theta}{1-\phi^2}$ (équivalente à $\sigma^2\sum_j\psi_j^2$ avec $\psi_0=1$, $\psi_j=(\phi-\theta)\phi^{j-1}$).</div><div class="step"><strong>Identification des paramètres.</strong> Le modèle $(1-0{,}5B)X_t=(1+0{,}3B)\varepsilon_t$ correspond à $\phi=0{,}5$ et, dans la convention $(1-\theta B)$, à $\theta=-0{,}3$.</div><div class="step"><strong>Calcul.</strong> Numérateur $=1+(-0{,}3)^2-2(0{,}5)(-0{,}3)=1+0{,}09+0{,}3=1{,}39$. Dénominateur $=1-0{,}5^2=0{,}75$. Donc $\gamma_0=\dfrac{1{,}39}{0{,}75}\sigma^2=\dfrac{139}{75}\sigma^2\approx 1{,}853\,\sigma^2$, ce qui coïncide avec le calcul direct par les $\psi_j$.</div><div class="step"><strong>Lecture.</strong> Comme $\phi>0$ et la racine MA effective est positive, $S$ pique en $f=0$ : signature d'un processus positivement corrélé, dominé par les basses fréquences.</div>`, pts: 4}
  ]
},
