{
  n: 6,
  title: String.raw`Théorie de Fourier`,
  intro: String.raw`La transformée de Fourier (continue, discrète, sur données finies) et le théorème de convolution sont les outils qui font passer du temps aux fréquences ; gare à l'aliasing.`,
  sections: [
    {h: String.raw`Trois transformées : continue, discrète, données finies`, body: String.raw`<p>La transformée de Fourier (Fourier transform) est le <strong>pont</strong> entre le domaine temporel (une fonction ou une suite $g_t$) et le domaine fréquentiel (sa transformée $G(f)$). On la construit en trois temps, et on travaille toujours avec la fréquence ordinaire $f$ (pas la pulsation $\omega=2\pi f$). Convention : la majuscule désigne la transformée, et $g\longleftrightarrow G$ note une <strong>paire de Fourier</strong> (aucune information perdue).</p>
<p><strong>Temps continu (continuous-time FT).</strong> Pour $g:\mathbb{R}\to\mathbb{C}$ avec $g\in L^1$,</p>
$$G(f)=\int_{-\infty}^{\infty} g(t)\,e^{-2\pi i f t}\,dt,\qquad f\in\mathbb{R}.$$
<p>Si de plus $G\in L^1$, l'inverse reconstruit $g$ pour presque tout $t$ : $g(t)=\int_{-\infty}^{\infty} G(f)\,e^{2\pi i f t}\,df$.</p>
<p><strong>Temps discret (discrete-time FT).</strong> Pour une suite $\{g_t\}_{t\in\Delta\mathbb{Z}}\in\ell^1$,</p>
$$G(f)=\Delta\sum_{t\in\Delta\mathbb{Z}} g_t\,e^{-2\pi i t f},\qquad g_t=\int_{-1/(2\Delta)}^{1/(2\Delta)} G(f)\,e^{2\pi i t f}\,df.$$
<p>Trait essentiel : $G$ est <strong>périodique</strong>, $G(f)=G(f+k/\Delta)$. Elle est donc entièrement déterminée sur une seule période de longueur $1/\Delta$ (c'est juste une série de Fourier, les rôles des domaines échangés).</p>
<p><strong>Données finies (finite-data FT).</strong> Avec $n$ observations aux temps $T=\{0,\Delta,\dots,(n-1)\Delta\}$,</p>
$$G_n(f)=\sum_{t\in T} g_t\,e^{-2\pi i t f}.$$
<p>C'est ce qu'on calcule réellement. Évaluée aux $n$ <strong>fréquences de Fourier</strong> $f_k=\dfrac{k}{\Delta n}$ (avec $-\tfrac{n}{2}\le k\le\tfrac{n-1}{2}$, soit $f_k=k/n$ quand $\Delta=1$), la FFT la calcule en $O(n\log n)$ au lieu de $O(n^2)$ par diviser-pour-régner (indices pairs/impairs, $\log_2 n$ niveaux).</p>`},
    {h: String.raw`Le théorème de convolution : le couteau suisse`, body: String.raw`<p>La <strong>convolution</strong> (convolution) de $g,h\in L^1$ est $u=g*h$, $u(t)=\int_{-\infty}^{\infty} g(t-u)\,h(u)\,du$ : une <em>moyenne pondérée</em> d'une fonction par l'autre, centrée en $t$.</p>
<p><strong>Théorème de convolution (convolution theorem).</strong> Multiplier dans un domaine $=$ convoler dans l'autre. Pour $g,h\in L^1$ :</p>
$$u=g*h \;\longleftrightarrow\; U=G\cdot H,\qquad v=g\cdot h \;\longleftrightarrow\; V=G*H \;(\text{si }G,H\in L^1).$$
<p>En temps discret, les deux paires tiennent aussi : $h*g\leftrightarrow H\cdot G$ et $h\cdot g\leftrightarrow H*G$.</p>
<p><em>Idée de preuve :</em> on substitue l'intégrale de convolution dans la définition de $U$, on échange l'ordre d'intégration (Fubini, légitime car $\iint\lvert g(x-y)h(y)\rvert\,dx\,dy=\lVert g\rVert_1\lVert h\rVert_1<\infty$), puis le changement $s=x-y$ fait apparaître le facteur $e^{-2\pi i s f}$ qui produit $G(f)$.</p>
<p><strong>Pourquoi c'est central :</strong> une opération coûteuse (la convolution) devient une simple <strong>multiplication</strong>. C'est pourquoi on passe en fréquentiel pour filtrer, et c'est l'identité qui relie la transformée sur données finies à la vraie transformée (voir la section sur le flou).</p>`},
    {h: String.raw`Aliasing et fréquence de Nyquist`, body: String.raw`<p>Échantillonner <strong>replie</strong> tout le contenu fréquentiel sur une seule période. Pour une fonction continue $g\in L^1$ de transformée $G$, et $G$ la transformée de la suite échantillonnée $\{g(t)\}_{t\in\Delta\mathbb{Z}}$ (sous les hypothèses de sommabilité) :</p>
$$G(f)=\sum_{k\in\mathbb{Z}} G\!\left(f+\tfrac{k}{\Delta}\right).$$
<p>La <strong>fréquence de Nyquist</strong> (Nyquist frequency) est $1/(2\Delta)$ (soit $\tfrac12$ quand $\Delta=1$) : au-delà, le contenu n'est <strong>pas</strong> récupérable.</p>
<p><em>Idée de preuve :</em> écrire $g(t)$ aux temps $t\in\Delta\mathbb{Z}$ par les deux formules d'inversion ; découper $\mathbb{R}$ en blocs de longueur $1/\Delta$ centrés en $k/\Delta$ ; décaler chaque bloc (le facteur $e^{2\pi i t k/\Delta}=1$ car $t=z\Delta$, $z\in\mathbb{Z}$) ; échanger somme et intégrale (sommabilité) ; identifier les coefficients de Fourier.</p>
<p><strong>Intuition.</strong> Une sinusoïde de <em>haute</em> fréquence échantillonnée trop lentement ressemble <em>exactement</em> à une sinusoïde de basse fréquence — l'effet « roue de chariot » au cinéma. Les fréquences $f$ et $f+k/\Delta$ deviennent indiscernables : ce sont des « alias ». Remède : échantillonner finement (petit $\Delta$, grand Nyquist) ou filtrer en passe-bas <em>avant</em> d'échantillonner. Et : en temps discret tout est périodique de période $1/\Delta$, donc on ne travaille jamais que sur une période.</p>`},
    {h: String.raw`Fenêtre finie = vision floue : le noyau de Dirichlet`, body: String.raw`<p>On n'observe jamais la suite entière, seulement $n$ points. Mathématiquement, <strong>observer = multiplier par un indicateur</strong> de fenêtre. La transformée sur données finies $G_n$ est donc la transformée complète multipliée par l'indicateur $d_t=\tfrac1\Delta\mathbf{1}_T(t)$, dont la propre transformée est le <strong>noyau de Dirichlet</strong> (Dirichlet kernel) :</p>
$$\mathcal{D}_T(f)=\sum_{t\in T}e^{-2\pi i f t}=\frac{\sin(n\pi f\Delta)}{\sin(\pi f\Delta)}\,e^{-\pi i(n-1)f\Delta}.$$
<p>Par le théorème de convolution, multiplier par l'indicateur en temps revient à <strong>convoler</strong> en fréquence avec $\mathcal{D}_T$ :</p>
$$G_n(f)=(\mathcal{D}_T * G)(f)=\int_{-1/(2\Delta)}^{1/(2\Delta)}\mathcal{D}_T(f-f')\,G(f')\,df'.$$
<p><strong>Conséquence (blurring).</strong> Une fenêtre finie <strong>floute</strong> la vraie transformée : les pics sont étalés et de l'énergie « fuit » vers les fréquences voisines. Plus $n$ est grand, plus $\mathcal{D}_T$ est concentré autour de $0$, moins ça floute. La manière propre de « tronquer » est de fenêtrer le spectre, pas la suite brute.</p>`},
    {h: String.raw`Les 4 propriétés de base et l'inversion`, body: String.raw`<p>Mêmes formes en temps continu et discret (preuves d'une ligne par changement de variable ou insertion de phase) :</p>
$$\overline{g(t)} \longleftrightarrow \overline{G(-f)},\qquad g(\alpha t) \longleftrightarrow \tfrac{1}{\lvert\alpha\rvert}G(f/\alpha),$$
$$g(t+\tau) \longleftrightarrow G(f)\,e^{2\pi i \tau f},\qquad \alpha g(t)+h(t) \longleftrightarrow \alpha G(f)+H(f).$$
<p>Lecture : conjuguer <strong>reflète</strong> ; dilater le temps <strong>comprime</strong> la fréquence ; décaler le temps multiplie par une <strong>phase</strong> (donc $\lvert G\rvert$ inchangé : déplacer un son dans le temps ne change pas quelles fréquences il contient) ; la transformée est <strong>linéaire</strong>.</p>
<p><strong>Théorème d'inversion de Fourier.</strong> Si $g,G\in L^1$ (continu) ou $\{g_t\}\in\ell^1$ (discret), l'inverse reconstruit $g$. <em>Idée :</em> réinjecter la transformée directe et utiliser l'orthogonalité $\int e^{2\pi i f(t-s)}\,df$ qui agit comme un Dirac. C'est ce qui fait de $(g,G)$ une vraie paire et fonde toute la dualité temps$\leftrightarrow$fréquence.</p>
<p><em>Cap suivant :</em> cette machinerie servira à définir la densité spectrale (spectral density) $S(f)=\sum_\tau\gamma_\tau e^{-2\pi i f\tau}$ — la transformée de l'ACVS.</p>`}
  ],
  checks: [
    {q: String.raw`Pourquoi le théorème de convolution est-il « le couteau suisse » de Fourier ?`, a: String.raw`Parce que convolution dans un domaine $\leftrightarrow$ produit dans l'autre : une convolution coûteuse devient une simple multiplication. $u=g*h\leftrightarrow U=G\cdot H$ (et la paire duale $g\cdot h\leftrightarrow G*H$). C'est l'outil du filtrage et du lien $G_n=\mathcal{D}_T*G$.`},
    {q: String.raw`Qu'est-ce que l'aliasing et quelle est la fréquence de Nyquist ?`, a: String.raw`L'échantillonnage replie le spectre : $G(f)=\sum_{k}G(f+k/\Delta)$, donc $f$ et $f+k/\Delta$ deviennent indiscernables (« alias »). La fréquence de Nyquist est $1/(2\Delta)$ ($=\tfrac12$ si $\Delta=1$) : au-delà l'information est perdue.`},
    {q: String.raw`Pourquoi une fenêtre finie « floute » la transformée ?`, a: String.raw`Observer = multiplier par un indicateur en temps, donc (théorème de convolution) convoler en fréquence par le noyau de Dirichlet $\mathcal{D}_T$ : $G_n=\mathcal{D}_T*G$. Les pics sont étalés, l'énergie fuit. Plus $n$ grand, plus $\mathcal{D}_T$ est concentré, moins ça floute.`},
    {q: String.raw`Quelle propriété rend la transformée en temps discret « périodique », et sur quel intervalle travaille-t-on ?`, a: String.raw`$G(f)=G(f+k/\Delta)$ pour tout $k\in\mathbb{Z}$ : $G$ est périodique de période $1/\Delta$. Il suffit de la connaître sur une période, p.ex. $[-\tfrac1{2\Delta},\tfrac1{2\Delta}]$.`},
    {q: String.raw`Comment un décalage temporel $g(t+\tau)$ modifie-t-il la transformée, et l'amplitude $\lvert G\rvert$ ?`, a: String.raw`$g(t+\tau)\leftrightarrow G(f)\,e^{2\pi i\tau f}$ : seule la phase change, multipliée par $e^{2\pi i\tau f}$. Le module $\lvert G(f)\rvert$ est inchangé — le contenu en fréquences est le même.`}
  ],
  test: [
    {type:'open', q: String.raw`(Propriétés de la transformée — Série 6, Ex. 6.1.) Soit $g\in L^1$ de transformée $G$, et $H$ la transformée de $h$. Démontrer : (1) si $h(t)=\overline{g(t)}$ alors $H(f)=\overline{G(-f)}$ ; (2) si $h(t)=g(\alpha t)$ avec $\alpha\ne0$ alors $H(f)=G(f/\alpha)/\lvert\alpha\rvert$ ; (3) si $h(t)=g(t+\tau)$ alors $H(f)=G(f)\,e^{2\pi i f\tau}$.`,
     answer: String.raw`<div class="step"><strong>(1) Conjugaison.</strong> On sort le conjugué de l'intégrale, ce qui change le signe de l'exposant : $H(f)=\int_{-\infty}^{\infty}\overline{g(t)}\,e^{-2\pi i t f}\,dt=\overline{\int_{-\infty}^{\infty} g(t)\,e^{2\pi i t f}\,dt}=\overline{G(-f)}$, car $\int g(t)e^{2\pi i t f}dt=G(-f)$.</div>
<div class="step"><strong>(2) Dilatation.</strong> Substitution $t'=\alpha t$, $dt=dt'/\lvert\alpha\rvert$ (le $\lvert\alpha\rvert$ vient de l'inversion des bornes si $\alpha<0$) : $H(f)=\int_{-\infty}^{\infty} g(\alpha t)\,e^{-2\pi i t f}\,dt=\dfrac{1}{\lvert\alpha\rvert}\int_{-\infty}^{\infty} g(t')\,e^{-2\pi i (f/\alpha)t'}\,dt'=\dfrac{1}{\lvert\alpha\rvert}\,G(f/\alpha).$</div>
<div class="step"><strong>(3) Décalage.</strong> On insère $1=e^{-2\pi i f\tau}e^{2\pi i f\tau}$ : $H(f)=\int_{-\infty}^{\infty} g(t+\tau)\,e^{-2\pi i f t}\,dt=\Big(\int_{-\infty}^{\infty} g(t+\tau)\,e^{-2\pi i f(t+\tau)}\,dt\Big)\,e^{2\pi i f\tau}=G(f)\,e^{2\pi i f\tau}$ (poser $s=t+\tau$ dans la parenthèse donne $G(f)$).</div>
<div class="step"><strong>Conséquence.</strong> Pour (3), $\lvert H(f)\rvert=\lvert G(f)\rvert$ : un décalage ne change que la phase, pas l'amplitude.</div>`, pts: 4},
    {type:'open', q: String.raw`(Théorème de convolution en temps continu — Série 6, Ex. 6.2.) Soient $g,h\in L^1$ et $u=g*h$, c.-à-d. $u(x)=\int_{-\infty}^{\infty} g(x-y)h(y)\,dy$. Démontrer que $U=G\cdot H$, en justifiant l'interversion des intégrales.`,
     answer: String.raw`<div class="step">Par définition de la transformée et de la convolution : $U(f)=\int_{-\infty}^{\infty} u(x)\,e^{-2\pi i x f}\,dx=\int_{-\infty}^{\infty}\Big(\int_{-\infty}^{\infty} g(x-y)h(y)\,dy\Big)e^{-2\pi i x f}\,dx.$</div>
<div class="step"><strong>Fubini.</strong> On échange l'ordre : $U(f)=\int_{-\infty}^{\infty}\Big(\int_{-\infty}^{\infty} g(x-y)\,e^{-2\pi i x f}\,dx\Big)h(y)\,dy.$</div>
<div class="step"><strong>Changement de variable</strong> $s=x-y$ (donc $x=s+y$, $e^{-2\pi i x f}=e^{-2\pi i s f}e^{-2\pi i y f}$) : $U(f)=\int_{-\infty}^{\infty}\Big(\int_{-\infty}^{\infty} g(s)\,e^{-2\pi i s f}\,ds\Big)e^{-2\pi i y f}\,h(y)\,dy=G(f)\int_{-\infty}^{\infty} h(y)\,e^{-2\pi i y f}\,dy=G(f)\,H(f).$</div>
<div class="step"><strong>Justification de Fubini.</strong> $\displaystyle\iint\lvert g(x-y)h(y)\rvert\,dx\,dy=\Big(\int\lvert g(s)\rvert\,ds\Big)\Big(\int\lvert h(y)\rvert\,dy\Big)=\lVert g\rVert_1\,\lVert h\rVert_1<\infty$ car $g,h\in L^1$ ; l'interversion est donc licite. D'où $U=G\cdot H$.</div>`, pts: 4},
    {type:'open', q: String.raw`(Aliasing — Série 6, Ex. 6.3.) Soit $g\in L^1$ continue, $G$ sa transformée (temps continu) et $G$ la transformée de la suite échantillonnée $\{g(t)\}_{t\in\Delta\mathbb{Z}}$ (avec $G\in L^1$, $\{g(t)\}\in\ell^1$ et $\{G(f+k/\Delta)\}_k\in\ell^1$). Démontrer $G(f)=\sum_{k\in\mathbb{Z}} G(f+k/\Delta)$. Énoncer ensuite ce qu'est la fréquence de Nyquist.`,
     answer: String.raw`<div class="step"><strong>Deux inversions.</strong> Pour tout $t\in\Delta\mathbb{Z}$, on dispose des deux formules d'inversion : $g(t)=\int_{-\infty}^{\infty} G(f)\,e^{2\pi i f t}\,df$ (continu) et $g(t)=\int_{-1/(2\Delta)}^{1/(2\Delta)} G(f)\,e^{2\pi i f t}\,df$ (discret).</div>
<div class="step"><strong>Découpage en blocs de période</strong> $1/\Delta$, puis décalage $f\mapsto f+k/\Delta$ : $g(t)=\sum_{k\in\mathbb{Z}}\int_{k/\Delta-1/(2\Delta)}^{k/\Delta+1/(2\Delta)} G(f)\,e^{2\pi i f t}\,df=\sum_{k\in\mathbb{Z}}\int_{-1/(2\Delta)}^{1/(2\Delta)} G(f+k/\Delta)\,e^{2\pi i f t}\,e^{2\pi i t k/\Delta}\,df.$</div>
<div class="step"><strong>La phase disparaît.</strong> Comme $t=z\Delta$ pour un $z\in\mathbb{Z}$, on a $e^{2\pi i t k/\Delta}=e^{2\pi i z k}=1$. Par la sommabilité $\sum_k\int\lvert G(f+k/\Delta)\rvert\,df<\infty$ on échange somme et intégrale : $g(t)=\int_{-1/(2\Delta)}^{1/(2\Delta)}\Big(\sum_{k\in\mathbb{Z}} G(f+k/\Delta)\Big)e^{2\pi i f t}\,df.$</div>
<div class="step"><strong>Identification.</strong> Cette intégrale égale aussi $\int_{-1/(2\Delta)}^{1/(2\Delta)} G(f)\,e^{2\pi i f t}\,df$ pour tout $t\in\Delta\mathbb{Z}$ : les coefficients de Fourier coïncident, donc $\sum_k G(f+k/\Delta)=G(f)$ pour presque tout $f$. Les deux membres étant continus ($\ell^1$/sommabilité), l'égalité vaut pour tout $f$.</div>
<div class="step"><strong>Nyquist.</strong> Les fréquences $f+k/\Delta$ se replient sur $f$ : elles sont indiscernables (alias). La fréquence de Nyquist est $1/(2\Delta)$ ($=\tfrac12$ si $\Delta=1$) ; au-delà le contenu fréquentiel n'est pas récupérable.</div>`, pts: 4},
    {type:'open', q: String.raw`(Noyau de Dirichlet et flou.) Pour des données finies aux temps $T=\{0,1,\dots,n-1\}$ ($\Delta=1$), on pose $\mathcal{D}_T(f)=\sum_{t=0}^{n-1} e^{-2\pi i f t}$. (a) Donner sa forme close. (b) Calculer $\mathcal{D}_T(0)$ et sa valeur aux fréquences de Fourier non nulles $f_k=k/n$, $k\ne0$. (c) Expliquer le lien $G_n=\mathcal{D}_T*G$ et pourquoi il y a « flou ».`,
     answer: String.raw`<div class="step"><strong>(a) Somme géométrique</strong> de raison $r=e^{-2\pi i f}$ : $\mathcal{D}_T(f)=\sum_{t=0}^{n-1} r^t=\dfrac{1-e^{-2\pi i f n}}{1-e^{-2\pi i f}}$. On factorise le demi-angle au numérateur $e^{-\pi i f n}(e^{\pi i f n}-e^{-\pi i f n})=e^{-\pi i f n}\,2i\sin(\pi f n)$ et au dénominateur $e^{-\pi i f}\,2i\sin(\pi f)$, d'où $\mathcal{D}_T(f)=\dfrac{\sin(n\pi f)}{\sin(\pi f)}\,e^{-\pi i (n-1)f}.$</div>
<div class="step"><strong>(b) En $f=0$ :</strong> la somme vaut directement $\sum_{t=0}^{n-1}1=n$ (limite : $\sin(n\pi f)/\sin(\pi f)\to n$). Aux fréquences de Fourier $f_k=k/n$ avec $k\ne0$ : $\sin(n\pi f_k)=\sin(k\pi)=0$ tandis que $\sin(\pi f_k)\ne0$, donc $\mathcal{D}_T(f_k)=0$. Le noyau s'annule donc exactement aux fréquences de Fourier non nulles.</div>
<div class="step"><strong>(c) Lien.</strong> Observer une fenêtre finie revient à multiplier la suite par l'indicateur $d_t=\mathbf{1}_T(t)$ (ici $\Delta=1$), dont la transformée est $\mathcal{D}_T$. Par le théorème de convolution, un produit en temps devient une convolution en fréquence : $G_n=\mathcal{D}_T*G$, soit $G_n(f)=\int_{-1/2}^{1/2}\mathcal{D}_T(f-f')\,G(f')\,df'.$</div>
<div class="step"><strong>Flou (blurring).</strong> $G_n$ est la vraie transformée $G$ convolée avec $\mathcal{D}_T$ : un pic net de $G$ est étalé par le lobe principal de $\mathcal{D}_T$ et de l'énergie fuit dans les lobes latéraux. Comme la largeur du lobe principal est $\sim 1/n$, plus $n$ est grand, plus $\mathcal{D}_T$ est concentré et moins le flou est important.</div>`, pts: 4},
    {type:'open', q: String.raw`(Transformée en temps discret d'une suite géométrique.) Soit $g_t=a^t$ pour $t\ge0$ et $g_t=0$ pour $t<0$, avec $a\in\mathbb{R}$, $\lvert a\rvert<1$, et $\Delta=1$. (a) Calculer $G(f)=\sum_{t\in\mathbb{Z}} g_t\,e^{-2\pi i t f}$. (b) Vérifier la périodicité $G(f)=G(f+1)$. (c) Calculer $\lvert G(f)\rvert^2$.`,
     answer: String.raw`<div class="step"><strong>(a)</strong> Seuls les $t\ge0$ contribuent ; c'est une série géométrique de raison $r=a\,e^{-2\pi i f}$ avec $\lvert r\rvert=\lvert a\rvert<1$ : $G(f)=\sum_{t=0}^{\infty}\big(a\,e^{-2\pi i f}\big)^t=\dfrac{1}{1-a\,e^{-2\pi i f}}.$</div>
<div class="step"><strong>(b) Périodicité.</strong> $e^{-2\pi i (f+1)}=e^{-2\pi i f}e^{-2\pi i}=e^{-2\pi i f}$, donc $G(f+1)=\dfrac{1}{1-a\,e^{-2\pi i (f+1)}}=\dfrac{1}{1-a\,e^{-2\pi i f}}=G(f)$ : période $1$ (cohérent avec $1/\Delta=1$).</div>
<div class="step"><strong>(c) Module au carré.</strong> $\lvert G(f)\rvert^2=\dfrac{1}{\lvert 1-a\,e^{-2\pi i f}\rvert^2}$. On développe $\lvert 1-a\,e^{-2\pi i f}\rvert^2=(1-a\,e^{-2\pi i f})(1-a\,e^{2\pi i f})=1-a(e^{-2\pi i f}+e^{2\pi i f})+a^2=1-2a\cos(2\pi f)+a^2$, d'où $\lvert G(f)\rvert^2=\dfrac{1}{1-2a\cos(2\pi f)+a^2}.$</div>
<div class="step"><strong>Vérification.</strong> Réel, pair (dépend de $\cos$), positif ($1-2a\cos+a^2\ge(1-\lvert a\rvert)^2>0$). Pour $a>0$ le maximum est en $f=0$ (spectre « rouge », basse fréquence) ; pour $a<0$ il est en $f=\tfrac12$. C'est exactement la forme de la densité spectrale d'un AR(1) de paramètre $a$.</div>`, pts: 4},
    {type:'open', q: String.raw`(Repliement d'un spectre par échantillonnage.) Un processus en temps continu a une « densité » $G(f)=e^{-\lvert f\rvert}$ sur $\mathbb{R}$. On échantillonne avec $\Delta=1$. (a) Donner la formule d'aliasing pour le spectre échantillonné $G(f)$ sur $[0,\tfrac12]$. (b) En déduire une forme close de $G(f)$ pour $f\in[0,\tfrac12]$. (c) Que vaut $G(0)$ et $G(\tfrac12)$ ?`,
     answer: String.raw`<div class="step"><strong>(a)</strong> Par le théorème d'aliasing (Nyquist $=1/(2\Delta)=\tfrac12$), $G(f)=\sum_{k\in\mathbb{Z}} G(f+k)=\sum_{k\in\mathbb{Z}} e^{-\lvert f+k\rvert}$ pour tout $f$.</div>
<div class="step"><strong>(b)</strong> Pour $f\in[0,\tfrac12]$ : les termes $k\ge0$ donnent $f+k\ge0$, soit $\lvert f+k\rvert=f+k$ ; les termes $k\le-1$ donnent $f+k<0$, soit $\lvert f+k\rvert=-(f+k)$. On sépare : $\sum_{k\ge0} e^{-(f+k)}=e^{-f}\sum_{k\ge0}e^{-k}=\dfrac{e^{-f}}{1-e^{-1}}$ et $\sum_{k\le-1} e^{f+k}=e^{f}\sum_{m\ge1}e^{-m}=\dfrac{e^{f}e^{-1}}{1-e^{-1}}=\dfrac{e^{-(1-f)}}{1-e^{-1}}$.</div>
<div class="step"><strong>Forme close :</strong> $G(f)=\dfrac{e^{-f}+e^{-(1-f)}}{1-e^{-1}},\qquad f\in[0,\tfrac12].$</div>
<div class="step"><strong>(c)</strong> En $f=0$ : $G(0)=\dfrac{1+e^{-1}}{1-e^{-1}}\approx 2.0746$. En $f=\tfrac12$ : les deux exponentielles valent $e^{-1/2}$, donc $G(\tfrac12)=\dfrac{2e^{-1/2}}{1-e^{-1}}\approx 1.9190$. Le spectre échantillonné est plus « plat » que le continu : tout le contenu au-delà de Nyquist s'est replié et additionné — c'est l'aliasing.</div>`, pts: 4}
  ]
},
