{cat: "Estimation (YW, MCO)", recto: String.raw`Définir les **estimateurs de Yule–Walker** pour un AR($p$) centré causal observé en $X_1,\dots,X_n$ : que valent $\hat{\boldsymbol\phi}_p$ et $\hat\sigma_\varepsilon^2$ ?`, verso: String.raw`Méthode des moments (method-of-moments). À partir de l'ACVS empirique on forme le vecteur $\hat{\boldsymbol\gamma}_p=(\hat\gamma_1,\dots,\hat\gamma_p)^{\top}$ et la matrice Toeplitz symétrique $\hat\Gamma_p=(\hat\gamma_{i-j})_{i,j=1}^p$, puis
$$\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p,\qquad \hat\sigma_\varepsilon^2=\hat\gamma_0-\sum_{j=1}^p\hat\phi_j\hat\gamma_j.$$
**Idée** : ce sont les analogues empiriques des identités de population $\boldsymbol\gamma=\Gamma\boldsymbol\phi$ et $\gamma_0=\sum_j\phi_j\gamma_j+\sigma_\varepsilon^2$. **Usage** : un seul système linéaire à résoudre ; l'ajustement obtenu est toujours stationnaire.`, src: "U04-D1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner l'estimateur empirique de l'**autocovariance** (ACVS) utilisé dans Yule–Walker pour une série centrée (mean-zero) de longueur $n$.`, verso: String.raw`Estimateur « diviseur $n$ » (divide-by-$n$) :
$$\hat\gamma_\tau=\frac1n\sum_{t=1}^{n-\lvert\tau\rvert}X_tX_{t+\lvert\tau\rvert}.$$
**Quand** : la moyenne est supposée nulle (sinon centrer d'abord la série). **Remarque** : on divise par $n$ (et non par $n-\lvert\tau\rvert$), ce qui garantit que la matrice $\hat\Gamma_p$ est semi-définie positive.`, src: "U04-D2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Décrire la matrice $\hat\Gamma_p$ et le vecteur $\hat{\boldsymbol\gamma}_p$ du système de Yule–Walker (structure et entrées).`, verso: String.raw`$\hat\Gamma_p$ est la matrice **Toeplitz symétrique** $p\times p$ d'entrées $(\hat\Gamma_p)_{i,j}=\hat\gamma_{i-j}$, soit $\hat\gamma_0$ sur la diagonale :
$$\hat\Gamma_p=\begin{pmatrix}\hat\gamma_0 & \hat\gamma_1 & \cdots & \hat\gamma_{p-1}\\ \hat\gamma_1 & \hat\gamma_0 & \cdots & \hat\gamma_{p-2}\\ \vdots & \vdots & \ddots & \vdots\\ \hat\gamma_{p-1} & \hat\gamma_{p-2} & \cdots & \hat\gamma_0\end{pmatrix}.$$
Le second membre est $\hat{\boldsymbol\gamma}_p=(\hat\gamma_1,\dots,\hat\gamma_p)^{\top}$. **Attention** : $\hat\gamma_0$ n'apparaît PAS dans le vecteur de droite. La symétrie Toeplitz est ce qu'exploite Levinson–Durbin.`, src: "U04-D3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Définir l'**estimateur des moindres carrés avant** (forward least squares) d'un AR($p$) : modèle linéaire et critère minimisé.`, verso: String.raw`On écrit les équations AR pour les instants observables $t=p+1,\dots,n$ sous forme du modèle linéaire $\mathbf X_F=F\boldsymbol\phi+\boldsymbol\varepsilon$, et on minimise
$$\mathrm{SS}_F(\boldsymbol\phi)=\lVert\mathbf X_F-F\boldsymbol\phi\rVert^2=\sum_{t=p+1}^n\Big(X_t-\sum_{k=1}^p\phi_kX_{t-k}\Big)^2.$$
**Idée** : on prédit chaque point à partir de son passé ; c'est une régression linéaire ordinaire (OLS). **Usage** : les $p$ premières observations $X_1,\dots,X_p$ servent de valeurs de conditionnement et sont écartées.`, src: "U04-D4"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la matrice de plan (design) $F$ et le vecteur réponse $\mathbf X_F$ des moindres carrés avant (forward LS) pour un AR($p$).`, verso: String.raw`Réponse : $\mathbf X_F=(X_{p+1},\dots,X_n)^{\top}$ (les $p$ premières observations sont écartées). Matrice $(n-p)\times p$ de lags passés :
$$F=\begin{pmatrix}X_p & X_{p-1} & \cdots & X_1\\ X_{p+1} & X_p & \cdots & X_2\\ \vdots & \vdots & & \vdots\\ X_{n-1} & X_{n-2} & \cdots & X_{n-p}\end{pmatrix}.$$
**Lecture** : la ligne $t$ contient $(X_{t-1},\dots,X_{t-p})$, les $p$ retards qui prédisent $X_t$.`, src: "U04-D5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Définir l'**estimateur des moindres carrés arrière** (backward least squares) d'un AR($p$) : que régresse-t-on et quel critère minimise-t-on ?`, verso: String.raw`On exploite la réversibilité temporelle du AR gaussien : on régresse les $n-p$ **premières** valeurs sur leurs retards **futurs**, $X_t=\sum_{j=1}^p\phi_jX_{t+j}+\nu_t$ pour $t=1,\dots,n-p$, soit $\mathbf X_B=B\boldsymbol\phi+\boldsymbol\nu$. On minimise
$$\mathrm{SS}_B(\boldsymbol\phi)=\lVert\mathbf X_B-B\boldsymbol\phi\rVert^2=\sum_{t=1}^{n-p}\Big(X_t-\sum_{k=1}^p\phi_kX_{t+k}\Big)^2.$$
**Clé** : ce sont les **mêmes** paramètres $\boldsymbol\phi$ qu'en avant, car $Y_t=X_{-t}$ est un AR($p$) de coefficients identiques.`, src: "U04-D6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la matrice de plan (design) $B$ et le vecteur réponse $\mathbf X_B$ des moindres carrés arrière (backward LS) pour un AR($p$).`, verso: String.raw`Réponse : $\mathbf X_B=(X_1,\dots,X_{n-p})^{\top}$. Matrice $(n-p)\times p$ de lags futurs :
$$B=\begin{pmatrix}X_2 & X_3 & \cdots & X_{p+1}\\ X_3 & X_4 & \cdots & X_{p+2}\\ \vdots & \vdots & & \vdots\\ X_{n-p+1} & X_{n-p+2} & \cdots & X_n\end{pmatrix}.$$
**Lecture** : la ligne $t$ contient $(X_{t+1},\dots,X_{t+p})$, les $p$ retards futurs servant à prédire $X_t$.`, src: "U04-D7"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Définir l'**estimateur des moindres carrés avant-arrière** (forward–backward LS) $\hat{\boldsymbol\phi}_{FB}$.`, verso: String.raw`C'est le minimiseur du critère **combiné**
$$\hat{\boldsymbol\phi}_{FB}=\arg\min_{\boldsymbol\phi}\ \mathrm{SS}_F(\boldsymbol\phi)+\mathrm{SS}_B(\boldsymbol\phi).$$
**Équivalent** : OLS du système empilé obtenu en superposant $\mathbf X_F,\mathbf X_B$ et $F,B$. **Idée** : on utilise les deux directions du temps à la fois, doublant approximativement les données effectives et stabilisant l'estimation près de la frontière de stationnarité. Les études de simulation montrent qu'il bat en général le seul avant ou le seul arrière.`, src: "U04-D8"},
{cat: "Estimation (YW, MCO)", recto: String.raw`En quoi consiste l'**estimateur des moindres carrés pour un ARMA général** via reconstruction des résidus ?`, verso: String.raw`Pour $\Phi(B)X_t=\Theta(B)\varepsilon_t$ les innovations $\{\varepsilon_t\}$ sont latentes. On choisit les paramètres minimisant
$$S(\boldsymbol\phi,\boldsymbol\theta)=\sum_t\hat\varepsilon_t^{\,2},$$
où, pour chaque valeur candidate, les résidus sont **reconstruits récursivement** à partir de l'équation du modèle, après avoir fixé à zéro les $q$ innovations pré-échantillon (et les données pré-échantillon) : $\varepsilon_0=\varepsilon_{-1}=\cdots=0$. **Remarque** : la minimisation est non linéaire (pas de forme close), sauf dans le cas AR pur où elle se réduit aux moindres carrés avant linéaires.`, src: "U04-D9"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Énoncer les **équations de Yule–Walker** pour un AR($p$) centré causal d'ACVS $\gamma_\tau$ (avec hypothèses).`, verso: String.raw`**Hypothèses** : $\{X_t\}$ AR($p$) centré (mean-zero) et **causal**. Alors pour tout $k\ge1$
$$\gamma_k=\sum_{j=1}^p\phi_j\,\gamma_{k-j}.$$
En détaillant pour $k=1,\dots,p$ et en utilisant la symétrie $\gamma_{-\tau}=\gamma_\tau$, on obtient $p$ équations dans les $p$ inconnues $\phi_1,\dots,\phi_p$. **Usage** : exprime les coefficients AR à partir des seules autocovariances $\gamma_0,\dots,\gamma_p$ ; remplacer $\gamma$ par $\hat\gamma$ donne l'estimateur YW.`, src: "U04-P1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire la **forme matricielle** des équations de Yule–Walker.`, verso: String.raw`$$\boldsymbol\gamma=\Gamma\boldsymbol\phi,\qquad \boldsymbol\gamma=(\gamma_1,\dots,\gamma_p)^{\top},\quad \Gamma=(\gamma_{i-j})_{i,j=1}^p.$$
La matrice $\Gamma$ est Toeplitz symétrique (diagonale $\gamma_0$). On en tire $\boldsymbol\phi=\Gamma^{-1}\boldsymbol\gamma$. **Attention indexation** : le second membre est $(\gamma_1,\dots,\gamma_p)$, on n'y met pas $\gamma_0$.`, src: "U04-P2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner l'**identité de variance** reliant $\gamma_0$, les $\phi_j$ et $\sigma_\varepsilon^2$ pour un AR($p$) causal centré, et son origine.`, verso: String.raw`$$\gamma_0=\sum_{j=1}^p\phi_j\,\gamma_j+\sigma_\varepsilon^2.$$
**Idée de preuve** : multiplier l'équation AR par $X_t$ et prendre l'espérance ; le terme croisé vaut $\mathbb{E}[\varepsilon_tX_t]=\mathbb{E}[\varepsilon_t(\sum_j\phi_jX_{t-j}+\varepsilon_t)]=\sigma_\varepsilon^2$ (tous les $\mathbb{E}[\varepsilon_tX_{t-j}]=0$, $j\ge1$, par causalité). **Usage** : fournit $\hat\sigma_\varepsilon^2=\hat\gamma_0-\sum_j\hat\phi_j\hat\gamma_j$ une fois $\hat{\boldsymbol\phi}$ trouvé.`, src: "U04-P3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Montrer que **minimiser l'erreur quadratique de prédiction** d'ordre un d'un processus centré stationnaire $\{Y_t\}$ donne les équations de Yule–Walker.`, verso: String.raw`**Hypothèses** : $\{Y_t\}$ centré (mean-zero) stationnaire d'ACVS $\gamma$. Les $\phi_1,\dots,\phi_k$ minimisant $\mathbb{E}\big[(Y_t-\sum_{i=1}^k\phi_iY_{t-i})^2\big]$ satisfont $\gamma_j=\sum_{i=1}^k\phi_i\gamma_{j-i}$, $j=1,\dots,k$.
**Idée de preuve** : comme $Y_t$ est centré, l'objectif égale la variance $\gamma_0-2\sum_i\phi_i\gamma_i+\sum_{i,j}\phi_i\phi_j\gamma_{i-j}$, quadratique définie positive. $\partial/\partial\phi_i=0$ donne $-2\gamma_i+2\sum_j\phi_j\gamma_{i-j}=0$, soit les équations YW.
**Portée** : YW = **meilleur prédicteur linéaire** (best linear predictor), d'où l'accord asymptotique YW $\approx$ MCO pour les AR.`, src: "U04-P4,U04-E2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quelle est la forme des **minimiseurs des moindres carrés avant et arrière** (forward / backward LS) d'un AR($p$) ?`, verso: String.raw`Ce sont les solutions OLS habituelles :
$$\hat{\boldsymbol\phi}_F=(F^{\top}F)^{-1}F^{\top}\mathbf X_F,\qquad \hat{\boldsymbol\phi}_B=(B^{\top}B)^{-1}B^{\top}\mathbf X_B.$$
**Idée de preuve** : chaque critère est un $\lVert\mathbf y-A\boldsymbol\phi\rVert^2$ ; les équations normales $A^{\top}A\,\boldsymbol\phi=A^{\top}\mathbf y$ donnent la solution. **Usage** : place l'estimation AR dans le cadre OLS standard (existence/unicité si $A^{\top}A$ inversible).`, src: "U04-P5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Énoncer la **réversibilité temporelle** (time reversibility) d'un AR($p$) gaussien stationnaire (avec hypothèses).`, verso: String.raw`**Hypothèses** : $\{X_t\}$ AR($p$) **gaussien** stationnaire, coefficients $\phi_1,\dots,\phi_p$, variance $\sigma_\varepsilon^2$. Alors le processus retourné $Y_t=X_{-t}$ est un AR($p$) de **mêmes** coefficients et même variance d'innovation :
$$Y_t=\sum_{j=1}^p\phi_jY_{t-j}+\tilde\nu_t,\quad \tilde\nu_t\ \text{de même loi que}\ \varepsilon_t,$$
ce qui équivaut à $X_t=\sum_{j=1}^p\phi_jX_{t+j}+\nu_t$ avec $\nu_t=\tilde\nu_{-t}$.
**Idée de preuve** : un processus gaussien stationnaire est déterminé par son ACVS, qui est symétrique ($\gamma_{-\tau}=\gamma_\tau$) ; processus avant et retourné ont donc même structure d'ordre 2 et même loi. **Usage** : justifie la régression arrière (backward LS) et l'estimateur avant-arrière.`, src: "U04-P6,U04-H3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Que fait l'algorithme de **Levinson–Durbin** et quel est son coût comparé à l'inversion naïve ?`, verso: String.raw`Il résout le système de Yule–Walker $\hat\Gamma_p\hat{\boldsymbol\phi}_p=\hat{\boldsymbol\gamma}_p$ en exploitant la structure **Toeplitz symétrique** de $\hat\Gamma_p$, de façon récursive en $k=1,\dots,p$, pour un coût $O(p^2)$ au lieu de $O(p^3)$ pour une inversion naïve. **Usage** : standard pour les AR d'ordre élevé, l'estimation spectrale, ou des systèmes emboîtés.`, src: "U04-P7"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quels **sous-produits** Levinson–Durbin fournit-il en plus des coefficients AR ?`, verso: String.raw`Il produit gratuitement, à chaque ordre $k=1,\dots,p$ :
- les **autocorrélations partielles** (PACF) $\hat\alpha_k=\hat\phi_{k,k}$, dites coefficients de réflexion (reflection coefficients) ;
- les **variances d'erreur de prédiction** à chaque ordre.
**Usage** : la PACF gratuite sert à la sélection d'ordre d'un AR (un AR($p$) a une PACF nulle au-delà du lag $p$).`, src: "U04-P8"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Les ajustements par moindres carrés (avant / arrière / avant-arrière) d'un AR sont-ils garantis **stationnaires** ? Et Yule–Walker ?`, verso: String.raw`**Non** pour les MCO : $\hat{\boldsymbol\phi}_F,\hat{\boldsymbol\phi}_B,\hat{\boldsymbol\phi}_{FB}$ ne sont pas contraints à donner un modèle stationnaire (causal) ; le polynôme $\hat\Phi(z)$ peut avoir des racines dans le disque unité. L'objectif OLS ne contraint pas le module des racines.
**Oui** pour Yule–Walker : YW donne toujours un ajustement stationnaire.
**Conséquence** : une estimation non stationnaire est gênante pour la **prédiction** mais acceptable pour l'**estimation spectrale** (densité spectrale toujours valide).`, src: "U04-P9,U04-K5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Pourquoi Yule–Walker et moindres carrés **coïncident-ils asymptotiquement** pour un AR ?`, verso: String.raw`Pour $n$ grand, les équations de score des moindres carrés se réduisent, au premier ordre, à la méthode des moments :
$$\hat\mu\approx\bar Y,\qquad \hat\phi\approx\hat\rho_1.$$
**Idée** : YW est le meilleur prédicteur linéaire et MCO minimise les erreurs de prédiction empiriques ; les deux convergent vers les mêmes poids optimaux. **Différences pratiques** : YW est un unique solve linéaire et toujours stationnaire ; MCO s'étend proprement à ARMA et à un modèle avec moyenne, mais peut sortir de la région stationnaire.`, src: "U04-P10"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **formule des coefficients de Yule–Walker** (4.3).`, verso: String.raw`$$\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p.$$
avec $\hat\Gamma_p=(\hat\gamma_{i-j})$ (Toeplitz symétrique, diagonale $\hat\gamma_0$) et $\hat{\boldsymbol\gamma}_p=(\hat\gamma_1,\dots,\hat\gamma_p)^{\top}$. **Usage** : à résoudre à la main pour $p\le3$, sinon Levinson–Durbin.`, src: "U04-F1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **formule de la variance d'innovation Yule–Walker** (4.4).`, verso: String.raw`$$\hat\sigma_\varepsilon^2=\hat\gamma_0-\sum_{j=1}^p\hat\phi_j\,\hat\gamma_j.$$
**Quand** : après avoir résolu $\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p$. **Origine** : version empirique de $\gamma_0=\sum_j\phi_j\gamma_j+\sigma_\varepsilon^2$.`, src: "U04-F2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **formule du coefficient des moindres carrés avant** $\hat{\boldsymbol\phi}_F$ (4.6).`, verso: String.raw`$$\hat{\boldsymbol\phi}_F=(F^{\top}F)^{-1}F^{\top}\mathbf X_F.$$
C'est l'estimateur OLS standard avec réponse $\mathbf X_F=(X_{p+1},\dots,X_n)^{\top}$ et matrice $F$ des lags passés. **Existence/unicité** : nécessite $F^{\top}F$ inversible.`, src: "U04-F3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **formule de la variance résiduelle des moindres carrés avant** $\hat\sigma_F^2$ (4.7) et le diviseur correct.`, verso: String.raw`$$\hat\sigma_F^2=\frac{\lVert\mathbf X_F-F\hat{\boldsymbol\phi}_F\rVert^2}{\,n-2p\,}.$$
**Diviseur** : $n-2p$ et non $n$ — il y a $n-p$ résidus et $p$ coefficients ajustés, donc $(n-p)-p=n-2p$ degrés de liberté.`, src: "U04-F4,U04-K2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner les **formules des moindres carrés arrière** : coefficient $\hat{\boldsymbol\phi}_B$ (4.10) et variance $\hat\sigma_B^2$ (4.11).`, verso: String.raw`$$\hat{\boldsymbol\phi}_B=(B^{\top}B)^{-1}B^{\top}\mathbf X_B.$$
$$\hat\sigma_B^2=\frac{\lVert\mathbf X_B-B\hat{\boldsymbol\phi}_B\rVert^2}{\,n-2p\,}.$$
avec $\mathbf X_B=(X_1,\dots,X_{n-p})^{\top}$ et $B$ la matrice des lags futurs. Mêmes degrés de liberté $n-2p$ qu'en avant.`, src: "U04-F5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire l'**objectif des moindres carrés avant** $\mathrm{SS}_F(\boldsymbol\phi)$ sous ses trois formes.`, verso: String.raw`$$\mathrm{SS}_F(\boldsymbol\phi)=\lVert\mathbf X_F-F\boldsymbol\phi\rVert^2=\sum_{t=p+1}^n\Big(X_t-\sum_{k=1}^p\phi_kX_{t-k}\Big)^2=\sum_{t=p+1}^n\varepsilon_t^2.$$
**Lecture** : somme des carrés des $n-p$ erreurs de prédiction à un pas, à partir du passé. Sa minimisation donne $\hat{\boldsymbol\phi}_F$.`, src: "U04-F6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire l'**objectif des moindres carrés arrière** $\mathrm{SS}_B(\boldsymbol\phi)$.`, verso: String.raw`$$\mathrm{SS}_B(\boldsymbol\phi)=\lVert\mathbf X_B-B\boldsymbol\phi\rVert^2=\sum_{t=1}^{n-p}\Big(X_t-\sum_{k=1}^p\phi_kX_{t+k}\Big)^2.$$
**Lecture** : somme des carrés des $n-p$ erreurs de prédiction des premiers points à partir de leurs lags **futurs**.`, src: "U04-F7"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire l'**objectif des moindres carrés avant-arrière** (4.12).`, verso: String.raw`$$\mathrm{SS}_F(\boldsymbol\phi)+\mathrm{SS}_B(\boldsymbol\phi).$$
On minimise la **somme** des deux critères ; le minimiseur $\hat{\boldsymbol\phi}_{FB}$ est l'OLS du système empilé (avant + arrière). Tend à se placer entre les estimations avant et arrière, avec une variance légèrement plus faible.`, src: "U04-F8"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner le **raccourci ACF** pour résoudre Yule–Walker quand on ne dispose que des autocorrélations $\hat\rho_\tau$.`, verso: String.raw`On divise tout le système par $\hat\gamma_0$ : avec $\bar\Gamma_p=(\hat\rho_{i-j})$ (utilise $\hat\rho_0=1$) et $\hat{\boldsymbol\rho}_p=(\hat\rho_1,\dots,\hat\rho_p)^{\top}$,
$$\hat{\boldsymbol\phi}_p=\bar\Gamma_p^{-1}\hat{\boldsymbol\rho}_p.$$
**Idée** : en posant $V=\hat\gamma_0^{-1}I$, $\hat{\boldsymbol\gamma}_p=\hat\Gamma_p\hat{\boldsymbol\phi}_p$ devient $V\hat{\boldsymbol\gamma}_p=V\hat\Gamma_p\hat{\boldsymbol\phi}_p$ : le même solve marche avec matrice et vecteur de corrélations, $\hat\gamma_0$ se simplifie. Il n'intervient plus que pour $\hat\sigma_\varepsilon^2$.`, src: "U04-F9,U04-M3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **variance d'innovation Yule–Walker exprimée via l'ACF** (raccourci corrélation).`, verso: String.raw`$$\hat\sigma_\varepsilon^2=\hat\gamma_0\Big(1-\sum_{j=1}^p\hat\phi_j\,\hat\rho_j\Big).$$
**Usage** : après avoir trouvé $\hat{\boldsymbol\phi}$ par le raccourci ACF ($\hat{\boldsymbol\phi}=\bar\Gamma_p^{-1}\hat{\boldsymbol\rho}_p$), seul $\hat\gamma_0$ reste nécessaire ici pour récupérer la variance.`, src: "U04-F10"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Cas particulier AR(1) : que vaut l'estimateur de Yule–Walker $\hat\phi$ ?`, verso: String.raw`Pour $p=1$ le système YW se réduit à l'équation scalaire $\hat\gamma_1=\hat\phi\,\hat\gamma_0$, donc
$$\hat\phi=\frac{\hat\gamma_1}{\hat\gamma_0}=\hat\rho_1.$$
**Mémo** : pour un AR(1), l'estimateur YW est simplement l'**autocorrélation empirique de lag 1**. Exemple : $\hat\gamma_0=4{,}0$, $\hat\gamma_1=2{,}4$ donnent $\hat\phi=0{,}6$.`, src: "U04-F11,U04-E6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner l'**identité de cohérence AR(1)** reliant $\gamma_0$, $\sigma_\varepsilon^2$ et $\phi$, et sa version empirique.`, verso: String.raw`Population : $\gamma_0=\dfrac{\sigma_\varepsilon^2}{1-\phi^2}$, équivalemment
$$\hat\sigma_\varepsilon^2=\hat\gamma_0\,(1-\hat\phi^2).$$
**Vérification (exemple)** : avec $\hat\gamma_0=4{,}0$ et $\hat\phi=0{,}6$, $\hat\sigma_\varepsilon^2=4{,}0(1-0{,}36)=2{,}56$, ce qui coïncide bien avec $\hat\gamma_0-\hat\phi\hat\gamma_1=4{,}0-0{,}6\times2{,}4=2{,}56$.`, src: "U04-F12"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **mise à jour du coefficient de réflexion** $\hat\phi_{k,k}$ de Levinson–Durbin.`, verso: String.raw`$$\hat\phi_{k,k}=\frac{\hat\gamma_k-\sum_{j=1}^{k-1}\hat\phi_{k-1,j}\,\hat\gamma_{k-j}}{v_{k-1}},$$
où $v_{k-1}$ est la variance d'erreur de prédiction courante (running error variance). **Rôle** : $\hat\phi_{k,k}$ est l'autocorrélation partielle (PACF) d'ordre $k$ ; c'est le coefficient de réflexion qui pilote la mise à jour rang-un de l'ordre $k-1$ à l'ordre $k$.`, src: "U04-F13"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **mise à jour des coefficients** $\hat\phi_{k,j}$ (pour $j<k$) de Levinson–Durbin.`, verso: String.raw`$$\hat\phi_{k,j}=\hat\phi_{k-1,j}-\hat\phi_{k,k}\,\hat\phi_{k-1,k-j},\qquad j=1,\dots,k-1.$$
**Lecture** : une fois le coefficient de réflexion $\hat\phi_{k,k}$ calculé, les autres coefficients de l'ordre $k$ se déduisent de ceux de l'ordre $k-1$ par cette correction rang-un, d'où le coût $O(p^2)$.`, src: "U04-F14"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire la **récursion des résidus pour un MA(1)** $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$ utilisée en moindres carrés.`, verso: String.raw`On résout l'équation du modèle pour l'innovation courante :
$$\varepsilon_t=X_t+\theta\,\varepsilon_{t-1}.$$
**Initialisation** : $\varepsilon_0=0$. On récurse ensuite vers l'avant ($\hat\varepsilon_1=X_1$, $\hat\varepsilon_2=X_2+\theta\hat\varepsilon_1$, …). **Pourquoi** : les $\varepsilon_t$ ne sont pas observés, il faut les reconstruire pour former $S(\theta)=\sum_t\hat\varepsilon_t^2$.`, src: "U04-F15"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Écrire la **récursion des résidus pour un ARMA(1,1)** $X_t=\phi X_{t-1}+\varepsilon_t-\theta\varepsilon_{t-1}$.`, verso: String.raw`On résout pour l'innovation courante :
$$\varepsilon_t=X_t-\phi X_{t-1}+\theta\,\varepsilon_{t-1}.$$
**Initialisation** : $X_0=0$ et $\varepsilon_0=0$ (données et innovation pré-échantillon nulles). On récurse vers l'avant pour obtenir $\hat\varepsilon_1,\dots,\hat\varepsilon_n$, chacun fonction de $(\phi,\theta)$, puis on minimise $S(\phi,\theta)=\sum_t\hat\varepsilon_t^2$.`, src: "U04-F16"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner le **résidu MA(1) déroulé** (unrolled) $\hat\varepsilon_t$ en fonction des données et de $\theta$ (avec $\hat\varepsilon_0=0$).`, verso: String.raw`En déroulant $\hat\varepsilon_t=X_t+\theta\hat\varepsilon_{t-1}$ avec $\hat\varepsilon_0=0$ :
$$\hat\varepsilon_t=\sum_{k=0}^{t-1}\theta^{\,k}X_{t-k}=X_t+\theta X_{t-1}+\theta^2X_{t-2}+\cdots+\theta^{\,t-1}X_1.$$
**Conséquence** : $\hat\varepsilon_t$ est un **polynôme de degré $t-1$** en $\theta$, donc $S(\theta)=\sum_t\hat\varepsilon_t^2$ est de degré $2(n-1)$ : en général optimisation numérique nécessaire.`, src: "U04-F17"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner les **solutions des équations de score** des moindres carrés pour un AR(1) **avec moyenne** $Y_t=\mu+\phi(Y_{t-1}-\mu)+\varepsilon_t$.`, verso: String.raw`On minimise $S(\mu,\phi)=\sum_{t=2}^n(Y_t-\mu-\phi(Y_{t-1}-\mu))^2$ ; en annulant les dérivées partielles on obtient les formes closes
$$\hat\mu=\frac{1}{(n-1)(1-\hat\phi)}\Big(\sum_{t=2}^nY_t-\hat\phi\sum_{t=2}^nY_{t-1}\Big),$$
$$\hat\phi=\frac{\sum_{t=2}^n\{Y_{t-1}-\hat\mu\}\{Y_t-\hat\mu\}}{\sum_{t=1}^{n-1}\{Y_t-\hat\mu\}^2}.$$
**Remarque** : il existe aussi la solution $\phi=1$ qu'il faut **rejeter** (non stationnaire). Pour $n$ grand, $\hat\mu\approx\bar Y$ et $\hat\phi\approx\hat\rho_1$.`, src: "U04-F18,U04-M9"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner la **recette d'ajustement par Yule–Walker** (les étapes pour fitter un AR($p$)).`, verso: String.raw`1. **Estimer l'ACVS** $\hat\gamma_0,\dots,\hat\gamma_p$ (estimateur diviseur $n$ sur la série centrée).
2. **Construire** la matrice Toeplitz $\hat\Gamma_p=(\hat\gamma_{i-j})$ et le vecteur $\hat{\boldsymbol\gamma}_p=(\hat\gamma_1,\dots,\hat\gamma_p)^{\top}$.
3. **Résoudre** $\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p$ (à la main si $p\le3$, sinon Levinson–Durbin).
4. **Variance** : $\hat\sigma_\varepsilon^2=\hat\gamma_0-\sum_{j=1}^p\hat\phi_j\hat\gamma_j$.
**Astuce** : si seules les autocorrélations sont fournies, diviser par $\hat\gamma_0$ et travailler avec $\bar\Gamma_p$ et $\hat{\boldsymbol\rho}_p$.`, src: "U04-M1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Décrire la **recette de dérivation des équations de Yule–Walker** (comment les obtenir).`, verso: String.raw`1. Multiplier l'équation AR $X_t=\sum_i\phi_iX_{t-i}+\varepsilon_t$ par $X_{t-k}$ (et séparément par $X_t$ pour la variance).
2. Prendre l'**espérance** des deux membres.
3. Utiliser la **causalité** : $\mathbb{E}[\varepsilon_tX_{t-k}]=0$ pour $k>0$ (le terme de bruit s'annule), et la **moyenne nulle** : $\mathbb{E}[X_{t-j}X_{t-k}]=\gamma_{k-j}$.
On obtient $\gamma_k=\sum_j\phi_j\gamma_{k-j}$ ($k\ge1$) et $\gamma_0=\sum_j\phi_j\gamma_j+\sigma_\varepsilon^2$ (terme croisé $\mathbb{E}[\varepsilon_tX_t]=\sigma_\varepsilon^2$).`, src: "U04-M2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Décrire la **reconstruction récursive des innovations** pour les moindres carrés MA / ARMA.`, verso: String.raw`Pour évaluer $S(\cdot)=\sum_t\hat\varepsilon_t^2$ à une valeur candidate :
1. **Résoudre l'équation du modèle pour $\varepsilon_t$** : MA(1) $\Rightarrow\varepsilon_t=X_t+\theta\varepsilon_{t-1}$ ; ARMA(1,1) $\Rightarrow\varepsilon_t=X_t-\phi X_{t-1}+\theta\varepsilon_{t-1}$.
2. **Initialiser** les $q$ innovations pré-échantillon (et données pré-échantillon) à zéro : $\varepsilon_0=0$ (et $X_0=0$ pour ARMA).
3. **Récurser vers l'avant** $t=1,\dots,n$ pour obtenir $\hat\varepsilon_t(\text{paramètres})$.
4. **Former $S$ et minimiser** (forme close seulement si $S$ est quadratique, sinon numériquement).`, src: "U04-M4"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Comment construire les **matrices de plan avant et arrière** pour un AR(2) (template) et calculer l'estimateur ?`, verso: String.raw`Avant : $\mathbf X_F=(X_3,\dots,X_n)^{\top}$, $F$ a pour lignes $(X_{t-1},X_{t-2})$. Arrière : $\mathbf X_B=(X_1,\dots,X_{n-2})^{\top}$, $B$ a pour lignes $(X_{t+1},X_{t+2})$.
$$F=\begin{pmatrix}X_2 & X_1\\ X_3 & X_2\\ \vdots & \vdots\\ X_{n-1}&X_{n-2}\end{pmatrix},\qquad B=\begin{pmatrix}X_2 & X_3\\ X_3 & X_4\\ \vdots & \vdots\\ X_{n-1}&X_n\end{pmatrix}.$$
Puis $\hat{\boldsymbol\phi}=(A^{\top}A)^{-1}A^{\top}\mathbf X$ avec $A=F$ ou $A=B$. **Préalable** : retirer la moyenne empirique si elle est significativement non nulle.`, src: "U04-M5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Décrire la **recette de preuve « MSE de prédiction $\to$ Yule–Walker »**.`, verso: String.raw`1. Écrire l'objectif $\mathbb{E}[(Y_t-\sum_i\phi_iY_{t-i})^2]$ comme une **forme quadratique positive** en $\boldsymbol\phi$ : pour $Y_t$ centré, il vaut $\gamma_0-2\sum_i\phi_i\gamma_i+\sum_{i,j}\phi_i\phi_j\gamma_{i-j}$.
2. **Dériver** par rapport à $\phi_i$ et annuler : $-2\gamma_i+2\sum_j\phi_j\gamma_{i-j}=0$.
3. Réarranger : $\gamma_i=\sum_j\phi_j\gamma_{i-j}$ = équations YW.
**Clé** : la forme étant définie positive, le point stationnaire est l'unique minimum global.`, src: "U04-M6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Donner l'**astuce d'inversion d'une matrice $2\times2$ symétrique** $\begin{pmatrix}a&b\\ b&a\end{pmatrix}$ (utile pour AR(2) YW).`, verso: String.raw`$$\begin{pmatrix}a&b\\ b&a\end{pmatrix}^{-1}=\frac{1}{a^2-b^2}\begin{pmatrix}a&-b\\ -b&a\end{pmatrix}.$$
**Usage** : pour AR(2) YW, $a=\hat\gamma_0$, $b=\hat\gamma_1$ et le déterminant est $\hat\gamma_0^2-\hat\gamma_1^2$. Exemple sunspot : $a=1382{,}185$, $b=1114{,}378$, $a^2-b^2\approx6{,}686\times10^5$, d'où $\hat{\boldsymbol\phi}\approx(1{,}3175,\ -0{,}6341)$.`, src: "U04-M7"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Comment **vérifier la stationnarité/causalité** d'un ajustement AR ?`, verso: String.raw`Calculer les **racines** du polynôme $\hat\Phi(z)$ et vérifier que leur **module est $>1$** (racines hors du disque unité).
**Exemple AR(1)** : $\hat\Phi(z)=1-0{,}6z$ a pour racine $z=1/0{,}6\approx1{,}667$, module $>1$ : fit causal.
**Exemple AR(2) sunspot** : racines de $1-1{,}3175z+0{,}6341z^2$ complexes, module $1/\sqrt{0{,}6341}\approx1{,}256>1$ : fit causal.`, src: "U04-M8"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quelle est l'**hypothèse de causalité** et son rôle exact dans la dérivation de Yule–Walker ?`, verso: String.raw`**Causalité** : les racines de $\Phi(z)$ sont hors du disque unité, donc $X_{t-k}$ ne dépend que de $\varepsilon_{t-k},\varepsilon_{t-k-1},\dots$ (innovations strictement antérieures à $\varepsilon_t$). Le bruit blanc non corrélé annule alors le terme croisé :
$$\mathbb{E}[\varepsilon_tX_{t-k}]=0\quad\text{pour }k>0.$$
**Rôle** : c'est le **seul fait** qui fait marcher toute la dérivation YW (le système linéaire en autocovariances). Sans causalité, le bruit « fuit » dans le passé et les équations YW ne tiennent plus.`, src: "U04-H1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quelle est l'**hypothèse de moyenne nulle** dans Yule–Walker / MCO, et que faire si la moyenne n'est pas nulle ?`, verso: String.raw`Moyenne nulle ⇒ $\mathbb{E}[X_{t-j}X_{t-k}]=\gamma_{k-j}$ (les produits espérés sont directement des autocovariances). C'est ce qui permet d'identifier les moments aux $\gamma$.
**Pratique** : si la moyenne est significativement non nulle, **centrer la série d'abord** ($x_t\mapsto x_t-\bar x$) avant d'estimer (cas des sunspots, moyenne clairement non nulle).`, src: "U04-H2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quelle **initialisation** est requise pour la récursion des résidus en MCO MA / ARMA ?`, verso: String.raw`Il faut fixer à **zéro** les $q$ innovations pré-échantillon (et toute donnée pré-échantillon) avant de récurser : par ex. $\varepsilon_0=0$ pour MA(1) ; $X_0=0$ **et** $\varepsilon_0=0$ pour ARMA(1,1).
**Pourquoi** : la récursion $\varepsilon_t=X_t+\theta\varepsilon_{t-1}$ (ou ARMA) a besoin d'une amorce, sinon $\hat\varepsilon_1$ est indéfini. C'est une convention standard pour tout ARMA($p,q$).`, src: "U04-H4,U04-K3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Quelle condition d'**inversibilité** garantit l'existence et l'unicité de la solution OLS (resp. YW) ?`, verso: String.raw`Il faut que $A^{\top}A$ soit inversible (resp. que $\hat\Gamma_p$ soit inversible) :
- OLS avant/arrière : $F^{\top}F$ (resp. $B^{\top}B$) inversible ⇒ $\hat{\boldsymbol\phi}=(A^{\top}A)^{-1}A^{\top}\mathbf X$ unique ;
- YW : $\hat\Gamma_p$ inversible ⇒ $\hat{\boldsymbol\phi}_p=\hat\Gamma_p^{-1}\hat{\boldsymbol\gamma}_p$ unique.
**Lecture** : c'est la condition de rang plein des équations normales.`, src: "U04-H5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Contre-exemple : montrer qu'une estimation **MCO peut sortir de la région stationnaire** (sunspot AR(2)).`, verso: String.raw`Pour l'AR(2) sunspot, les MCO avant donnent $\hat{\boldsymbol\phi}_F\approx(1{,}4046,\ -0{,}7113)$ ($\hat\sigma_F^2\approx232{,}26$) et arrière $\hat{\boldsymbol\phi}_B\approx(1{,}4061,\ -0{,}7076)$ ($\hat\sigma_B^2\approx231{,}03$), différents des valeurs YW $(1{,}3175,\ -0{,}6341)$.
**Leçon** : les MCO ne sont **pas contraints causaux** ; les deux méthodes ne coïncident qu'asymptotiquement. La quasi-égalité avant $\approx$ arrière illustre directement la réversibilité temporelle.`, src: "U04-X1,U04-E5"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Contre-exemple : quelle solution **inadmissible** apparaît dans les équations de score MCO d'un AR(1) avec moyenne ?`, verso: String.raw`Les équations de score de $S(\mu,\phi)=\sum_{t=2}^n(Y_t-\mu-\phi(Y_{t-1}-\mu))^2$ admettent la solution $\phi=1$, qui est **non stationnaire** et doit être **rejetée**.
**Leçon** : la minimisation peut produire des points stationnaires inadmissibles ; il faut écarter ceux qui violent la condition de stationnarité ($\lvert\phi\rvert<1$ pour un AR(1)).`, src: "U04-X2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Contre-exemple : pourquoi le problème MA(1) jouet ($X_1=0$) donne-t-il un $S(\theta)$ **quadratique** propre, alors que ce n'est pas le cas en général ?`, verso: String.raw`Données $X_1=0,X_2=1,X_3=0{,}5$ avec $\varepsilon_0=0$ : $\hat\varepsilon_1=0$, $\hat\varepsilon_2=1$ (libres de $\theta$), $\hat\varepsilon_3=0{,}5+\theta$ (linéaire). Donc $S(\theta)=1+(0{,}5+\theta)^2$ est **exactement quadratique**, minimiseur $\hat\theta=-0{,}5$.
**Artefact** : $X_1=0$ force $\hat\varepsilon_1=0$ et bloque la propagation. En général $\hat\varepsilon_t=\sum_{k=0}^{t-1}\theta^kX_{t-k}$ est de degré $t-1$, donc $S(\theta)$ est de degré $2(n-1)$ et nécessite une optimisation numérique.`, src: "U04-X3,U04-E8"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Piège d'**indexation Toeplitz** : où placer $\gamma_0$ dans le système de Yule–Walker ?`, verso: String.raw`$\Gamma_p$ utilise $\gamma_{i-j}$ avec $\gamma_0$ sur la **diagonale**, et le **second membre** est $(\gamma_1,\dots,\gamma_p)$.
**Erreur fréquente** : NE PAS mettre $\gamma_0$ dans le vecteur de droite. La diagonale (et seulement elle) porte $\gamma_0$.`, src: "U04-K1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Piège des **degrés de liberté** : par quoi divise-t-on la variance résiduelle en MCO d'un AR($p$) ?`, verso: String.raw`Par $n-2p$, **pas** par $n$ :
$$\hat\sigma^2=\frac{\lVert\text{résidus}\rVert^2}{n-2p}.$$
**Justification** : il y a $n-p$ résidus (les $p$ premières observations conditionnent) et $p$ coefficients ajustés, soit $(n-p)-p=n-2p$ degrés de liberté.`, src: "U04-K2"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Piège : pourquoi les MCO d'un ARMA/MA sont-ils généralement **non linéaires** (pas de forme close) ?`, verso: String.raw`À cause de la rétroaction $\theta\hat\varepsilon_{t-1}$ dans la récursion : $\hat\varepsilon_t$ dépend non linéairement de $\theta$ (polynôme de degré $t-1$), donc $S=\sum_t\hat\varepsilon_t^2$ n'est pas quadratique et n'a pas de solution explicite.
**Conséquence** : il faut **minimiser numériquement** (sauf cas AR pur, qui se réduit à une régression linéaire).`, src: "U04-K4"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Piège : la **longueur $n$** de la série influence-t-elle les estimations ponctuelles YW à partir d'une ACF donnée ?`, verso: String.raw`**Non** : seules les valeurs de l'ACF (ou ACVS) déterminent $\hat{\boldsymbol\phi}$. La longueur $n$ n'entre pas dans le calcul du point estimé YW.
**Exemple** : AR(3) avec $\hat\rho_1=0{,}8,\hat\rho_2=0{,}5,\hat\rho_3=0{,}4$ et $n=100$ donne $\hat{\boldsymbol\phi}=(1{,}309,-0{,}955,0{,}509)$ — le $n=100$ ne sert pas. (Il interviendrait pour les écarts-types, pas pour le point estimé.)`, src: "U04-K6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Piège : les MCO **arrière** estiment-ils des $\phi$ négatifs/inversés par rapport aux MCO avant ?`, verso: String.raw`**Non** : les moindres carrés arrière estiment **exactement les mêmes** paramètres $\boldsymbol\phi$ que l'avant, ni niés ni inversés.
**Raison** : $Y_t=X_{-t}$ est le **même** AR($p$) (réversibilité temporelle du AR gaussien), de coefficients identiques. Les petites différences avant/arrière observées sont du bruit d'échantillonnage (résidus différents).`, src: "U04-K7"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Schéma d'exercice : **ajuster un AR(2) par Yule–Walker** à partir d'une ACVS donnée (sunspot, $2\times2$ Toeplitz).`, verso: String.raw`Données : $\hat\gamma_0=1382{,}185$, $\hat\gamma_1=1114{,}378$, $\hat\gamma_2=591{,}721$. Résoudre
$$\begin{pmatrix}1382{,}185 & 1114{,}378\\ 1114{,}378 & 1382{,}185\end{pmatrix}\begin{pmatrix}\hat\phi_1\\ \hat\phi_2\end{pmatrix}=\begin{pmatrix}1114{,}378\\ 591{,}721\end{pmatrix}.$$
Par l'astuce d'inversion $2\times2$ : $\hat{\boldsymbol\phi}\approx(1{,}3175,\ -0{,}6341)$, puis $\hat\sigma_\varepsilon^2=\hat\gamma_0-\hat\phi_1\hat\gamma_1-\hat\phi_2\hat\gamma_2\approx289{,}21$. **Vérif causalité** : racines de $1-1{,}3175z+0{,}6341z^2$ de module $\approx1{,}256>1$.`, src: "U04-E1"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Schéma d'exercice : **estimer $\theta$ d'un MA(1) par moindres carrés récursifs** à partir de quelques points ($\varepsilon_0=0$).`, verso: String.raw`MA(1) $X_t=\varepsilon_t-\theta\varepsilon_{t-1}$, données $X_1=0,X_2=1,X_3=0{,}5$. Reconstruire via $\varepsilon_t=X_t+\theta\varepsilon_{t-1}$, $\varepsilon_0=0$ :
$$\varepsilon_1=0,\quad \varepsilon_2=1,\quad \varepsilon_3=0{,}5+\theta.$$
Critère $S(\theta)=0^2+1^2+(0{,}5+\theta)^2=1+(0{,}5+\theta)^2$, minimisé en $\hat\theta=-0{,}5$ (et $\lvert\hat\theta\rvert<1$, fit inversible).`, src: "U04-E3"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Schéma d'exercice : **AR(3) par Yule–Walker à partir d'une ACF** (raccourci corrélation, solve $3\times3$).`, verso: String.raw`ACF $\hat\rho_1=0{,}8,\hat\rho_2=0{,}5,\hat\rho_3=0{,}4$. Raccourci : $\hat{\boldsymbol\phi}=\bar\Gamma_3^{-1}\hat{\boldsymbol\rho}_3$ avec $\hat\rho_0=1$ :
$$\begin{pmatrix}1 & 0{,}8 & 0{,}5\\ 0{,}8 & 1 & 0{,}8\\ 0{,}5 & 0{,}8 & 1\end{pmatrix}\begin{pmatrix}\hat\phi_1\\ \hat\phi_2\\ \hat\phi_3\end{pmatrix}=\begin{pmatrix}0{,}8\\ 0{,}5\\ 0{,}4\end{pmatrix}.$$
Solution (élimination de Gauss) : $\hat{\boldsymbol\phi}\approx(1{,}309,\ -0{,}955,\ 0{,}509)$. La longueur $n=100$ n'entre pas dans le point estimé.`, src: "U04-E4"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Schéma d'exercice : **AR(1) par Yule–Walker à la main** ($\hat\phi$, $\hat\sigma_\varepsilon^2$, test de stationnarité).`, verso: String.raw`AR(1) centré, $n=200$, $\hat\gamma_0=4{,}0$, $\hat\gamma_1=2{,}4$. Système scalaire $\hat\gamma_1=\hat\phi\hat\gamma_0$ :
$$\hat\phi=\frac{2{,}4}{4{,}0}=0{,}6=\hat\rho_1,\qquad \hat\sigma_\varepsilon^2=\hat\gamma_0-\hat\phi\hat\gamma_1=4{,}0-1{,}44=2{,}56.$$
Cohérent avec $\hat\gamma_0(1-\hat\phi^2)=4{,}0(1-0{,}36)=2{,}56$. **Stationnarité** : $\Phi(z)=1-0{,}6z$, racine $z\approx1{,}667$, module $>1$, fit causal.`, src: "U04-E6"},
{cat: "Estimation (YW, MCO)", recto: String.raw`Schéma d'exercice : écrire la **récursion des résidus ARMA(1,1)** $\hat\varepsilon_1,\dots,\hat\varepsilon_4$ comme fonctions de $(\phi,\theta)$ et l'objectif MCO.`, verso: String.raw`Récursion $\varepsilon_t=X_t-\phi X_{t-1}+\theta\varepsilon_{t-1}$, init $X_0=\varepsilon_0=0$ :
$$\hat\varepsilon_1=X_1,\quad \hat\varepsilon_2=X_2-\phi X_1+\theta X_1,$$
$$\hat\varepsilon_3=X_3-\phi X_2+\theta(X_2-\phi X_1+\theta X_1),\quad \hat\varepsilon_4=X_4-\phi X_3+\theta\hat\varepsilon_3.$$
Objectif $S(\phi,\theta)=\sum_{t=1}^4\hat\varepsilon_t^2$ ; à cause de la rétroaction $\theta\hat\varepsilon_{t-1}$, il n'est **pas** quadratique en $\theta$ et se minimise numériquement.`, src: "U04-E7"},
